### ISSUE TITLE
The network connection was lost. (Code: 100, Version: 1.14.2)

### ISSUE THREAD

**Issue by mikeCalvir** [ParsePlatform/Parse-SDK-iOS-OSX#1017]
I have started a project with a simple initial connection, and so far can't get past this problem.

I can run a curl query just fine, so the networking from my computer to the back4app server seems fine. Yet running in the simulator I can never get results back.

Here is my setup code (truncated to obscure the keys):
<img width="456" alt="screen shot 2016-08-26 at 17 16 48" src="https://cloud.githubusercontent.com/assets/340607/18010569/5ae25022-6bb1-11e6-96c9-c70e2897eee7.png">

And here is my calling code, currently living in -viewWillAppear.
<img width="527" alt="screen shot 2016-08-26 at 17 17 06" src="https://cloud.githubusercontent.com/assets/340607/18010591/72e49202-6bb1-11e6-86bc-792552aaa37c.png">

Here's the result:
2016-08-26 17:14:32.186 Freddy[59485:824909] [Error]: The network connection was lost. (Code: 100, Version: 1.14.2)
2016-08-26 17:14:32.187 Freddy[59485:824909] [Error]: Network connection failed. Making attempt 1 after sleeping for 1.258213 seconds.

Any suggestions as to what might be wrong would be very much appreciated.

**Comment by mikeCalvir** [comment]
Ok I'm on a different network now, and I don't know why but this problem has gone away :/

**Comment by amsalt18** [comment]
So did you find a real fix, or just changing the network did it?

**Comment by mikeCalvir** [comment]
Pretty sure it was either my fault or changing network, by chance I've not touched this project since then so I've forgotten about it now. I know it annoyed me for a good hour late in the day, and then it disappeared quickly in the morning, as can so often be the way :)
