### ISSUE TITLE
error: Bolts/BFTask.h file not found 

### ISSUE THREAD

**Issue by devKC** [ParsePlatform/Parse-SDK-iOS-OSX#1024]
I've been running a Parse Server app with no problem for awhile. However, after I updated Cocoapods, I am getting the error message: "Bolts/BFTask.h file not found" and this message is being triggered on the #import <Bolts/BFTask.h> line in the PFAnalytics.h file. Because of this error, Xcode can't build Parse module and my project won't build. Has anyone seen on issue like this? Any pointers would be greatly appreciated.

**Comment by devKC** [comment]
Perform "Clean Build Folder"

**Comment by Bergasms** [comment]
Failing the above, delete your entire derived data folder under 

Library > Developer > Xcode > DerivedData > YourProjectName  

This worked for me.

**Comment by azermann** [comment]
none of them work for me

**Comment by arunprasathsivasamy** [comment]
none of them work for me also

**Comment by flovilmart** [comment]
@arunprasathsivasamy what version of the SDK are you using? we're using in production the latest version and are not impacted by this issue.
