### ISSUE TITLE
PFFacebookUtils.logInInBackground  on Swfit 3

### ISSUE THREAD

**Issue by notiles** [ParsePlatform/Parse-SDK-iOS-OSX#1047]
Hello, 

I got an issue on Facebook Login with swift 3 after the migration

Cannot convert value of type '(PFUser?, NSError?) -> Void' to expected argument type 'PFUserResultBlock?'

PFFacebookUtils.logInInBackground(withReadPermissions: permissions, block: {
                (user: PFUser?, error: NSError?) -> Void in
                statement...
})

Any idea?

**Comment by notiles** [comment]
Oups error due to another...

**Comment by lfarah** [comment]
How did you fix it, @notiles?
