### ISSUE TITLE
PFObject fetchInBackgroundWithBlock returns nil for fetched object

### ISSUE THREAD

**Issue by iosdev-republicofapps** [ParsePlatform/Parse-SDK-iOS-OSX#105]
I used to have code like the following that worked perfectly, without fail, in Parse OS X SDK version 1.6.3, but now fails every single time in Parse OS X SDK version 1.8.1:

```
PFObject object = ...; // Some object from the cloud

// Make some local changes to object ...

[object saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
  if (succeeded) {
    [object fetchInBackgroundWithBlock:^(PFObject *fetched, NSError *error) {
       // In Parse OS X SDK version 1.6.3 fetched was always non-nil.
       // In Parse OS X SDK version 1.8.1 fetched is always nil.
    }
  }
}];
```

So fetchInBackgroundWithBlock now always returns nil for an object that originally came from the cloud and definitely exists.  Why is it returning nil all of a sudden now?  None of my code has changed ... This is definitely a new bug in the Parse OS X SDK.

This is a blocking bug for me.

**Comment by nlutsenko** [comment]
Hey @iosdev-republicofapps, I've seen this happening yesterday and there was a #104 that fixes the similar problem to what you are describing.
Workaround: Keep the pointer to an object for the entire lifetime of it, since the bug was with evicting the object from memory too early.

I am going to close out this issue, feel free to reopen though if #104 didn't help or if you think there is something else here missing.

**Comment by iosdev-republicofapps** [comment]
Thanks @nlutsenko I appreciate your rapid response!  :-)

What do you mean "keep the pointer to an object for the entire lifetime of it"?  The problem is, when I create an object client side and save it to the Parse cloud, I have cloud code that adds extra fields (server side, for security) so I need to immediately fetch the saved object.

For example:
```
PFObject *object = [PFObject objectWithClassName:@"Foo"];
object[@"bar"] = @"baz";

[object saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
  if (succeeded) {
    // object was created in cloud, and cloud beforeSave added some extra fields
    // cloud-side for security, so we need to retrieve the just-created object again here
    [object fetchInBackgroundWithBlock:^(PFObject *fetched, NSError *error) {
       // In Parse OS X SDK version 1.6.3 fetched was always non-nil.
       // In Parse OS X SDK version 1.8.1 fetched is always nil.
    }
  }
}];
```

I don't understand how your proposed fix would work - the problem is not that `object` is nil, the problem is that `fetched` is nil, so I never get a chance to store a pointer to `fetched`.

How about this fix:
```
PFObject *object = [PFObject objectWithClassName:@"Foo"];
object[@"bar"] = @"baz";

[object saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
  if (succeeded) {
    // object was created in cloud, and cloud beforeSave added some extra fields
    // cloud-side for security, so we need to retrieve the just-created object again here
    PFQuery *query = [PFQuery queryWithClassName:@"Foo"];
    [query getObjectInBackgroundWithId:object.objectId block:^(PFObject *queryFetched, NSError *error)  {
        // Will queryFetched be non-nil here?
    }
  }
}];
```
Would this approach? Trying to query for the refreshed object by id?  Maybe `queryFetched` won't be nil?

Also, when will your fix #104 make it into a release?  :-)

Thanks and please advise!

Best,

Joel

**Comment by nlutsenko** [comment]
That approach would work. Or something like this should also work:
```objc
PFObject *object = [PFObject objectWithClassName:@"Foo"];
object[@"bar"] = @"baz";

[object saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
  if (succeeded) {
    // object was created in cloud, and cloud beforeSave added some extra fields
    // cloud-side for security, so we need to retrieve the just-created object again here
    [object fetchInBackgroundWithBlock:^(PFObject *fetched, NSError *error) {
       // In Parse OS X SDK version 1.6.3 fetched was always non-nil.
       // In Parse OS X SDK version 1.8.1 fetched is always nil.

    }
  }
}];


#104 is already merged - feel

**Comment by nlutsenko** [comment]
That approach would work. Or something like this should also work:
```objc
PFObject *object = [PFObject objectWithClassName:@"Foo"];
object[@"bar"] = @"baz";

[object saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
  if (succeeded) {
    // object was created in cloud, and cloud beforeSave added some extra fields
    // cloud-side for security, so we need to retrieve the just-created object again here
    [object fetchInBackgroundWithBlock:^(PFObject *fetched, NSError *error) {
       // In Parse OS X SDK version 1.6.3 fetched was always non-nil.
       // In Parse OS X SDK version 1.8.1 fetched is always nil.
       // Use an `object` here somewhere.
       object;
    }
  }
}];
```
Since #104 is already merged - you can use it via Cocoapods by adding:
`pod 'Parse', :git => 'https://github.com/ParsePlatform/Parse-SDK-iOS-OSX.git'`
Or even building the framework for yourself from source using instructions on README.

**Comment by iosdev-republicofapps** [comment]
Thanks again @nlutsenko .

But in your example above, inside the completion block supplied to `fetchInBackgroundWithBlock`, will object be the updated version (i.e. `[object isEqual:fetched]`) or will object be the original version before I saved it?  I need the updated version from the server since cloud code added some fields in beforeSave.

Will your trick prevent `fetched` from becoming nil somehow?

Also, if I go back to using CocoaPods now, will code signing work?  I had previously tried using the OS X SDK through CocoaPods but the code signing failed so I had to drop the frameworks in as embedded binaries.  Or will code signing just work now because now the pod compiles from source whereas before the pod included pre-compiled libs?

Thanks again and best wishes!  :-)

**Comment by iosdev-republicofapps** [comment]
Are you planning to do another release with this bug fix?

Thanks!

**Comment by nlutsenko** [comment]
Yup, soon after this weekend and a holiday (it's Labor Day holiday here in US).

**Comment by iosdev-republicofapps** [comment]
Thanks @nlutsenko , that sounds great!  Have a good long weekend.  :-)
