### ISSUE TITLE
iOS 10 Xcode 8 : Error with 100% CPU, both Simulator & Device

### ISSUE THREAD

**Issue by cyring** [ParsePlatform/Parse-SDK-iOS-OSX#1066]
Hello,

Since I have upgraded Xcode to version 8, my app locks in iOS 10 as soon as any Parse-SDK-iOS v1.14.2 network functions are called.
However with iOS 9.3 the app is still running fine.
The code is using legacy Swift 2

Dump of errors:
`objc[5322]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11b577998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11b39cd38). One of the two will be used. Which one is undefined.
2016-10-31 13:52:31.400555 app[5322:105275] [] nw_host_stats_add_src recv too small, received 24, expected 28
2016-10-31 13:52:31.416065 app[5322:105275] [] ____nwlog_simulate_crash_inner_block_invoke dlopen CrashReporterSupport failed
2016-10-31 13:52:31.416978 app[5322:105275] [] __nwlog_err_simulate_crash simulate crash failed "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
2016-10-31 13:52:31.418207 app[5322:105275] [] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
        [x86_64] libnetcore-856.20.4
    0   libsystem_network.dylib             0x00000001114db682 __nw_create_backtrace_string + 123
    1   libnetwork.dylib                    0x0000000111748932 nw_socket_add_input_handler + 3100
    2   libnetwork.dylib                    0x00000001117264f4 nw_endpoint_flow_attach_protocols + 3768
    3   libnetwork.dylib                    0x0000000111725511 nw_endpoint_flow_setup_socket + 563
    4   libnetwork.dylib                    0x0000000111724270 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
    5   libnetwork.dylib                    0x000000011173f44d nw_endpoint_handler_path_change + 1261
    6   libnetwork.dylib                    0x000000011173ee7c nw_endpoint_handler_start + 570
    7   libnetwork.dylib                    0x0000000111756ae5 nw_endpoint_resolver_start_next_child + 2240
    8   libdispatch.dylib                   0x0000000111258980 _dispatch_call_block_and_release + 12
    9   libdispatch.dylib                   0x00000001112820cd _dispatch_client_callout + 8
    10  libdispatch.dylib                   0x000000011125fe6b _dispatch_queue_serial_drain + 236
    11  libdispatch.dylib                   0x0000000111260b9f _dispatch_queue_invoke + 1073
    12  libdispatch.dylib                   0x00000001112633b7 _dispatch_root_queue_drain + 720
    13  libdispatch.dylib                   0x000000011126308b _dispatch_worker_thread3 + 123
    14  libsystem_pthread.dylib             0x000000011170e4de _pthread_wqthread + 1129
    15  libsystem_pthread.dylib             0x000000011170c341 start_wqthread + 13
`

The app does the following algorithm:

- Initialization   
```
    let configuration = ParseClientConfiguration {
        $0.applicationId	= "xxx"
        $0.clientKey		= "xxx"
        $0.server			= "https://xxx/parse"
    }

    Parse.initializeWithConfiguration(configuration)   
```
- Configuration   
```
PFConfig.getConfigInBackgroundWithBlock { (config: PFConfig?, error: NSError?)
```   
1. Reconnection   
 ```
let dbUser = PFUser.currentUser()
```   
_OR_   
2. Connection   
```
PFUser.logInWithUsernameInBackground(...)
```

**Comment by cyring** [comment]
Does anybody has crossed this issue ?

**Comment by fadylateef** [comment]
Crying : yes the same here , may we need to upgrade to macOS Sierra !!! 
actually idk

**Comment by cyring** [comment]
Solved : nothing relative to the Parse SDK

_Issue belongs to an InputField whom width is smaller than the inputs chars : 96px vs (4 * 28px)
This leads to a 100% CPU and it is fixed when width is set to 128px_

Sorry guys for this annoyment

**Comment by scorpionking2k5** [comment]
@cyring  - I'm getting the exact same error. How did you find out that the issue was with the InputField?
I have input fields set inside tablecells, but the crash happens on the next screen.

**Comment by cyring** [comment]
I have filled a report @ Apple and it looks fixed in last iOS.

Previously, during debug I noticed that the inputfield width matters with password black circles : a field too short against the entered chars and it locks the cpu (into a spinlock)

Using last iOS, you will also notice that the circles are getting progressively smallers to fit the width : sounds like a workaround into UIkit !

To conclude, it seems not being retroactively fixed to first 10.x versions, so enlarge your field enough.

**Comment by demopix** [comment]
same problem with JSONSerialization

**Comment by demopix** [comment]
i find this right now work for me Edit Scheme
Run(Environment Variables)  add variables, NS_ACTIVITY_MODE-disable
but it would be leads to next problem:

**Comment by cyring** [comment]
demopix : you may create another issue, because mine was an UIKit issue with a cpu locked side effect.

**Comment by demopix** [comment]
sorry its not NS_ACTIVITY_MODE the correct is OS_ACTIVITY_MODE and look you SDK processor if is Arm type intel
