### ISSUE TITLE
Can't install the 1.14.3

### ISSUE THREAD

**Issue by jeremypiednoel** [ParsePlatform/Parse-SDK-iOS-OSX#1113]
Hi there,
I wonder why i can't install the last version through cocoapods

The version on cocoapods is still on `1.14.2` https://cocoapods.org/pods/Parse
And can't install this version https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/tag/1.14.3

Thanks.

**Comment by flovilmart** [comment]
Because it hasn't been released to cocoa pods yet.

**Comment by jeremypiednoel** [comment]
Ok thanks do you have a ETA ?

**Comment by flovilmart** [comment]
ASA I get the credentials/approval to push on CocoaPods

**Comment by jeremypiednoel** [comment]
Thanks
