### ISSUE TITLE
registerAuthenticationDelegate dealloc issue

### ISSUE THREAD

**Issue by ranhsd** [ParsePlatform/Parse-SDK-iOS-OSX#1116]
Hi , 
When i am use the following function: 
`[PFUser registerAuthenticationDelegate:self forAuthType:@"myAuthProvider"];`
my class is not released (dealloc is not called) and the reason is that the PFUser holds a **strong** reference to my class. 

I noticed that there is another method with name **_unregisterAuthenticationDelegateForAuthType** but this method is private so i cannot really use it in my code. What i did in order to test if this method can help is to expose this method as a public method and then i call this method from my code and then dealloc was triggered and my class was released. 

What do you think we should do with it? do we need to expose this method as public method and handle it in the code? or maybe we need to hold a **weak** reference instead of strong one.

Another solution is to register it in AppDelegate or in some singleton and then you can make sure that it will work because this instance will always be in memory. But i really don't like this solution because usually i love that my code is clean and that i should instantiate and objects only when i really need to use them.

Thanks.

**Comment by flovilmart** [comment]
I believe the original intent / design around that object (authenticationDelegate) is a singleton/single instance per authType. With the single responsibility of starting a login flow in any context (not bound to any login controller etc...) 

Internally, the FBLogin and Twitter login are registered as such, probably looking into the code would provide a good example how it is managed with those two providers

**Comment by ranhsd** [comment]
Ok, that's what i did .. Personally i am not a big fan of singleton design patterns in iOS but what i did is i initiate it in AppDelegate and now it works.

**Comment by flovilmart** [comment]
> Personally i am not a big fan of singleton design patterns 

Yeah but in that case, as we bind them on the PFUser class, we don't really have a choice.
