### ISSUE TITLE
[Error]: A server with the specified hostname could not be found. (Code: 100, Version: 1.14.2)

### ISSUE THREAD

**Issue by partikles** [ParsePlatform/Parse-SDK-iOS-OSX#1117]
Suddenly getting debug message as

  [Error]: A server with the specified hostname could not be found. (Code: 100, Version: 1.14.2)

**Comment by flovilmart** [comment]
Without more informations that will be hard to debug.

**Comment by partikles** [comment]
I have no clue, why it is happening.

 I have enabled email verification in parse server and added ParseUI in the iOS client. 

I have disabled ParseUI and tried. Still the same. 

Even though it is showing error, I can still able to update to the server.

**Comment by partikles** [comment]
It is my error. My existing code uses PFFile for ProfileImage which is pointing to URL, which is not available now. 

Since I got the generic error message, I cannot figure it out properly.

**Comment by wdcurry** [comment]
This can result from *already* stored PFFIle fields pointing to (for example) files on parse.com, which no longer exists. I banged my head for a few days on this issue, assuming my code was somehow messed up. Nope, just resetting those particular PFFIles did the trick.
