### ISSUE TITLE
PFSubclassing Issues w/ Swift 3

### ISSUE THREAD

**Issue by ZacharyKhan** [ParsePlatform/Parse-SDK-iOS-OSX#1118]
I have been trying to create a subclass of **PFObject**, **_Range_**, but when doing so it seems to affect any queries against the **_Range_** subclass. 

### Range.swift
```swift
final class Range: PFObject, PFSubclassing {
    
    @NSManaged var title : String?
    @NSManaged var location : PFGeoPoint?
    @NSManaged var rating : NSNumber?
    @NSManaged var imageFile : PFFile?
    
    init(title : String, location : PFGeoPoint, rating : NSNumber, imageFile: PFFile) {
        super.init()
        self.title = title
        self.location = location
        self.rating = rating
        self.imageFile = imageFile
    }
    
    override init() {
        super.init()
    }
    
    public class func parseClassName() -> String {
        return "Ranges"
    }
    
    override class func query() -> PFQuery<PFObject> {
        let query = PFQuery(className: Range.parseClassName())
        query.order(byDescending: "createdAt")
        query.cachePolicy = .networkOnly
        return query
    }

}
```

### Calling Range.query()
```swift
let query = Range.query()
     query.findObjectsInBackground(block: {
         (objects, error) in
         if error == nil {
             print(objects!) // Prints nil
         } else {
             print(error!.localizedDescription)
     }
})
```

According to release [**1.14.0**](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/tag/1.14.0), there is no longer a need to implement `registerSubclass()` in the AppDelegate as it is done automatically, therefore I do no call `registerSubclass()` at all.

When I include `PFSubclassing` in **Range.swift**, the `query()` function returns nil. If I remove `PFSubclassing`, the `query()` function returns the correct objects from the database, but fails to recognize the returned objects as a `Range` object. Rather, it recognizes the returned objects as `PFObjects`.

**Comment by dorjeozer** [comment]
Dunno how you're making the other query, but could the problem be with your parseClassName as it's called 'Ranges'?

**Comment by ZacharyKhan** [comment]
@dorjeozer I don't understand the problem with naming the `parseClassName()` 'Ranges'.

I will add the code snippet to show how I am calling the query on `Range()` objects.

**Comment by ZacharyKhan** [comment]
I just tried it once more  and it worked, I didn't do anything differently. hmm..
