### ISSUE TITLE
Can't get 1.14.3 from CocoaPods

### ISSUE THREAD

**Issue by claesjacobsson** [ParsePlatform/Parse-SDK-iOS-OSX#1126]
I'm not able to update to 1.14.3 using CocoaPods. Says 1.14.2 is the latest release. What am I missing?

**Comment by flovilmart** [comment]
1.14.3 is not released on cocoapods due to an issue related to the ownership of the module in CP.
you can use the git reference:

pod 'Parse', git: "https://github.com/ParsePlatform/Parse-SDK-iOS-OSX", tag: "1.14.3"

**Comment by claesjacobsson** [comment]
Ah, I see. Thanks a lot!

Claes

**Comment by flovilmart** [comment]
no problemo!
