### ISSUE TITLE
Scheduled Jobs on Cloud Coding is not executing

### ISSUE THREAD

**Issue by MatheusBeckerP** [ParsePlatform/Parse-SDK-iOS-OSX#114]
Hi,

I'm trying to execute a cloud code job that repeats every day at a determined time, but after I've set it up the job is never executed.

I've tested the Run Now option and it was working fine, as well as the option to repeat every X mins every day after determined time.

In other words, only the option to repeat "Every day at XXXX" is not working.

Thanks in advance.

**Comment by nlutsenko** [comment]
This one does indeed look like product usage question, sorry...
I suspect 2 things:
- either we have a backend bug - which we still use FB Developers Bug Tool to track. Please file a report via https://parse.com/help
- there is something weird about your configuration
