### ISSUE TITLE
Randomly getting Error 100 when calling cloud code methods using iOS SDK

### ISSUE THREAD

**Issue by anoopnimkar** [ParsePlatform/Parse-SDK-iOS-OSX#118]
I am intermittently getting an error while making Parse cloud calls using iOS SDK, (calls our cloud code method implemented on parse)

Its either this error,
The network connection was lost. (Code: 100, Version: 1.7.5)
or
failed with error message: Request timed out (Code: 141, Version: 1.7.5)

We have Android client making same requests but it doesn't throw these errors. Also, I confirmed the internet connectivity and tried on different networks to confirm the issue.

We tried following approaches to reproduce the issue,
A1 - iOS Client calls cloud code methods using Parse SDK (** Issue reproduced)
A2 - iOS Client calls cloud code methods using REST API call with NSURLConnection (** Issue reproduced)
A3 - iOS Client fetches data by using REST API query with NSURLConnection (** Issue NOT reproduced)

Any inputs on debugging this issue would be very helpful.

**Comment by nlutsenko** [comment]
Hey @anoopnimkar, I suggest you try with the latest SDK - 1.8.1.
We've changed quite a bit of networking infrastructure behind the scenes when since 1.8.0.

**Comment by anoopnimkar** [comment]
Thanks @nlutsenko I will try 1.8.1

If we keep making cloud calls periodically, the issue is easy to reproduce. Example code can be found below,


    [PFCloud callFunctionInBackground:@"some-cloud-call-method" withParameters:@{} block:^(NSDictionary *responseDict, NSError *error) {
        if (!error) {
            NSLog(@"cloud-call complete");
            [NSTimer scheduledTimerWithTimeInterval:7.0/*refresh-interval*/ target:self selector:@selector(call-same-cloud-method) userInfo:nil repeats:NO];
        } else {
          NSLog(@"\n%@", error.description);
        }
    }
