### ISSUE TITLE
Performance issue when using subclass of ParseObject

### ISSUE THREAD

**Issue by innopage** [ParsePlatform/Parse-SDK-iOS-OSX#125]
A bit of background:

It is a Financial mobile app that calculates the value of a portfolio of transactions.

"Portfolio", "Transaction", "Stock" are all PFObject subclass
each "Transaction" has a column that is a pointer to "Portfolio", another pointer to "Stock"
Events:
1. PFQuery the "Portfolio" from Parse
2. PFQuery all the "Transactions" that has a pointer to this "Portfolio", in this case where I can reliably 100% lock it up, there are around 800 "Transactions", this PFQuery has "include" on "Stock" object
3. Fetch prices of each "Stock" from my own servers (not Parse related)
4. Loop through all 800 "Transactions", accessing its properties (of type string, number) frequently to do calculations.
5. Repeat 3&4 every 10 seconds.

Prior in 1.7.5 , step 4 takes around 0.2 seconds to compute, now in 1.8.2, it takes around 5 seconds to compute, so effectively locking up my app half the time.

If I reduce the number of objects I receive in the PFQuery to less than 100 "Transactions", the lock up becomes less noticeable. So I think it is related quickly accessing lots of PFObjects?

I spent sometime, and managed to create a useful XCode project that can demonstrate running the exact same code on Parse SDK 1.7.5 takes around 0.1 seconds,  and on Parse SDK 1.8.2 takes around 3 seconds.

(The calculation code is complicated and taken from my real app, I wish not to reveal the source code to the public, there used to be a way to mark submitted content "confidential" before you guys moved to GitHub, is there still this option now?  Otherwise, I need to mess up the code to make it worthless....)

**Comment by innopage** [comment]
I ripped apart the code and made a project that is not confidential, but still useful for demonstrating this bug: https://dl.dropboxusercontent.com/u/1874024/ParseSDK-iOS-Issue125-ReproducibleProject.zip

Two projects in the zip, one with SDK 1.7.5, the other with SDK 1.8.2., with exact same code otherwise.  Running on my iPhone 6 Plus iOS 8.4, the 1.7.5 version takes around 0.03 seconds, the 1.8.2 takes 10 to 20 times longer, around 0.70 seconds.

Note: the real algorithm involves a lot more calculation, for demonstration purposes, I extract some of the lines that accessed the ParseObject subclass's getters.  It seems that in SDK 1.8.2, accessing these getter's values is significantly slower than SDK 1.7.5

**Comment by nlutsenko** [comment]
Thanks for the repro project!
I'll post the results of the investigation here.

**Comment by innopage** [comment]
Thanks for the super fast response guys, looking at your fix commit explains why it killed performance.  I shall wait for 1.8.3 to be released and hopefully see this completely resolved in my full production app.

Thanks again guys.

**Comment by nlutsenko** [comment]
:grin:

**Comment by richardjrossiii** [comment]
If you'd like to verify that the fix works, feel free to update your podpsec (temporary, don't use this in production) to point to master:

    pod 'Parse', :git => 'https://github.com/parseplatform/parse-sdk-ios-osx.git'

Let me know if you have any more issues!

**Comment by innopage** [comment]
Hi @nlutsenko @richardjrossiii 

So, I finally had time to update my real app from Parse SDK 1.7.5 to Parse SDK 1.8.5 in my production app and it seems the performance issue is not "completely" fixed.  I'm still getting CPU 100% fro way longer than 1.7.5

Just like last time, I made a repo project that somewhat approximate my production app's code, capable demonstrating this performance issue: 

https://www.dropbox.com/s/anp64wrr0yewmfr/ParseSDK-iOS-Issue125-ReproducibleProject-UpdatedFor1.8.5.zip?dl=0

Three projects in the zip, one with SDK 1.7.5, 1.8.2 and 1.8.5, with exact same code otherwise. Running on my iPhone 6 Plus iOS 8.4, the 1.7.5 version takes around 0.03 seconds, the 1.8.2 takes around 20 times longer, around 0.70 seconds.  the 1.8.5 takes around 10 times longer, around 0.30 seconds.  

I'm thinking there are more than 1 place where you have bugs and you haven't caught them all yet?

**Comment by nlutsenko** [comment]
Let's reopen this for a follow up then.

**Comment by richardjrossiii** [comment]
There's no bug here. We changed the way that properties are dynamically resolved in 1.8.0, to make it more robust in the future. The old implementation was faster, but relied upon a bunch of undefined behavior, the code was extremely tightly coupled to `PFObject`, and overall just didn't work.

So, in 1.8.0, we switched the implementation to use `NSInvocation` objects instead of crazy `imp_impelementationWithBlock` hacks, as `imp_implementationWithBlock`, especially on systems where you cannot copy a page with execute permissions (e.g. iOS, where `mprotect` always fails for execute), can easily run out of block trampolines.

It is true that the `NSInvocation` method is significantly slower, but it's also true that it's the best cross-platform and non-architecture specific (important as we being targeting bitcode and archs like ARMv7k) to have a more stable solution.

I know this doesn't solve your performance issues, but unless you know of a way to do JIT inside of an application, there's not that much we can do, sadly.

**Comment by richardjrossiii** [comment]
As a workaround, you could make the properties of your model objects non-dynamic, e.g.:
 
```
@interface foo : PFObject<PFSubclassing>

@property int bar;

@end

@implementation foo

- (int)bar {
    return [self[@"bar"] intValue];
}

- (void)setBar:(int)newBar {
    self[@"bar"] = @(newBar);
}

@end
```

It's a little bit more code, but it will be faster than going through the dynamic message forwarding dispatch, which is what most of the time overhead you're seeing is.

**Comment by innopage** [comment]
Thanks for the workaround, I can confirm the work around solves my performance issues.  

I do agree with you, proper code is always better than having hack.   Good programmers write proper code once aiming for it to work for years and years rather hacks that is gonna keep popping up with issues.

Thanks again for the help.
