### ISSUE TITLE
CocoaPods Issue + missing PFTwitterUtils

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/Parse-SDK-iOS-OSX#128]
After installing Parse through cocoa pods when I do 
import Parse 

It tells me no such module. 

What are other steps necessary for this to work? 

Fixed this by importing Parse to bridging header. Missing PFTwitterUtils class.

**Comment by talkaboutdesign** [comment]
I tried downloading parse library from the website to add PFTwitterUtils. 
Dropped it into the project and got the following error when trying to import it: 
<img width="697" alt="screenshot 2015-08-28 13 41 06" src="https://cloud.githubusercontent.com/assets/2926534/9553043/757d7768-4d8a-11e5-8f99-ad591a6457a4.png">

**Comment by nlutsenko** [comment]
Hey @talkaboutdesign, ParseTwitterUtils live inside ParseTwitterUtils.framework, which is available in the same package (https://parse.com/docs/downloads)

I've just verified the package there and as soon as I add `Bolts.framework`, `Parse.framework` and `ParseTwitterUtils.framework` to the project - everything works great.

**Comment by nlutsenko** [comment]
This noted, using Cocoapods should help you to set it up easier.
Official pod names (as you might have guessed) are `Parse` and `ParseTwitterUtils`.

**Comment by talkaboutdesign** [comment]
Nice!

**Comment by nlutsenko** [comment]
Looks like it helped, great!
Closing this one then.
