### ISSUE TITLE
BOOL <-> Number iOS Parse 1.8.0

### ISSUE THREAD

**Issue by emonster** [ParsePlatform/Parse-SDK-iOS-OSX#13]
Interesting issue: This was working ok on 1.7.5 before updating to 1.8.0
I have a subclass of PFUser with a BOOL property isActive and a NSNumber property hibernating
-- init as isActive = NO;
-- init hibernating = [NSNumber numberWithBool:NO];
once the first PFUser is created the isActive is a number not a BOOL and the hibernating NSNumber becomes a BOOL not a number!!!! 
Something is very wrong here, this was working correctly before.
Has anyone else seeing this problem?

**Comment by nlutsenko** [comment]
Sounds weird, any chance you can add a repro to this issue? It would be a tremendous help in identifying the root cause of this.

**Comment by m-revetria** [comment]
Similar issue for me with Parse 1.8.0 installed using cocoapods.

I have a subclass of PFObject<PFSubclassing> with a BOOL property defined as `@property (nonatomic) BOOL isTaken`. When I try to save an instance of my class to Parse I got the error:

    [Error]: invalid type for key isTaken, expected boolean, but got number (Code: 111, Version: 1.8.0)

Debugging my iOS code, before call [pfobject save] the type for isTaken is __NSCFBoolean 

    NSLog(@"%@", [[pfobject valueForKey:@"isTaken"] class])

It will print __NSCFBoolean on the console. Parse 1.7.5 is working fine

**Comment by richardjrossiii** [comment]
I have successfully reproduced the bug, tracked down the issue, and am working on a fix now. As a temporary workaround, you can declare your properties using either the C++11 `bool` type, or the C11 `_Bool` type. Anyone interested in the details can look at [PFObjectSubclassingController.m](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/Internal/Object/Subclassing/PFObjectSubclassingController.m#L43-L66) for the relevant lines of code. This got reworked before the 1.8.0 release, and we missed this use case. Sorry!

**Comment by richardjrossiii** [comment]
I have just realized that the `_Bool` type will not work either. The current suggested work around is to use object subscripting and `@YES` instead of dot syntax. PR with a fix coming shortly.

**Comment by emonster** [comment]
Thank you for fixing this issue!!
Where do I get the fix? Can I get it by pod? or where can I download the new Parse.framework?
