### ISSUE TITLE
Screens wont reload properly

### ISSUE THREAD

**Issue by SkoThere** [ParsePlatform/Parse-SDK-iOS-OSX#130]
My app's homescreen/ browse often times doesn't load and I have to close out of the app and restart in order to get it working properly. It's a 5s iphone and my friend in a total different state testing the app has the same issue. 
![image](https://cloud.githubusercontent.com/assets/11668427/9555563/d2fec8cc-4d9b-11e5-9f2c-ba0ce37f68d6.jpg)

**Comment by richardjrossiii** [comment]
Are you experiencing any parse-specific issues? 

Can you provide us with API calls that fail? As it stands right now there's not much action I can take from this report. If there is a problem with the Parse SDK we're glad to help, we just need a bit more information.

If this is a back-end bug and is reproducible through the REST API, please report it at http://parse.com/help.

**Comment by SkoThere** [comment]
The issue is not with API but the issue is with the Parse server response. It is intermittent and is with all calls to Parse.

**Comment by richardjrossiii** [comment]
It sounds like this could be a network problem. Can you try using the [REST API](https://www.parse.com/docs/rest) to see if this is a bug with the back-end, please?

When did this start happening? Have you had any difficulties with your internet connection in the past with other websites?

**Comment by SkoThere** [comment]
No problem with anything else as weird as this one. It's just bizzare the
screen won't load at random times when the requests are so low (2-3% max)
so it's not a "busy" issue. I am having my developer check on the reset API
to see, but it's been a consistent glitch for a while.

Kendra


On Fri, Aug 28, 2015 at 9:04 PM, Richard Ross <notifications@github.com>
wrote:

> It sounds like this could be a network problem. Can you try using the REST
> API <https://www.parse.com/docs/rest> to see if this is a bug with the
> back-end, please?
>
> When did this start happening? Have you had any difficulties with your
> internet connection in the past with other websites?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/130#issuecomment-135924035>
> .
>



-- 

*​​Kendra Ratliff*
*Founder *
*www.skothere.com* <http://www.skothere.com/>
*​IG: skothere*
*Twitter: @skothere​*
*502-592-6525*

**Comment by SkoThere** [comment]
My dev. said, "Also you can tell them that the none of the call worked. It
was failing on Parse call. And then it suddenly started working. So
definitely there was an issue at Parse end."

Thoughts?

On Mon, Aug 31, 2015 at 10:09 AM, Kendra Ratliff <kendra@skothere.com>
wrote:

> No problem with anything else as weird as this one. It's just bizzare the
> screen won't load at random times when the requests are so low (2-3% max)
> so it's not a "busy" issue. I am having my developer check on the reset API
> to see, but it's been a consistent glitch for a while.
>
> Kendra
>
>
> On Fri, Aug 28, 2015 at 9:04 PM, Richard Ross <notifications@github.com>
> wrote:
>
>> It sounds like this could be a network problem. Can you try using the REST
>> API <https://www.parse.com/docs/rest> to see if this is a bug with the
>> back-end, please?
>>
>> When did this start happening? Have you had any difficulties with your
>> internet connection in the past with other websites?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/130#issuecomment-135924035>
>> .
>>
>
>
>
> --
>
> *​​Kendra Ratliff*
> *Founder *
> *www.skothere.com* <http://www.skothere.com/>
> *​IG: skothere*
> *Twitter: @skothere​*
> *502-592-6525*
>



-- 

*​​Kendra Ratliff*
*Founder *
*www.skothere.com* <http://www.skothere.com/>
*​IG: skothere*
*Twitter: @skothere​*
*502-592-6525*

**Comment by richardjrossiii** [comment]
Definitely sounds like a backend issue. Follow the steps that will be posted by the bot here to file an issue with our backend team. Thanks for the report.

**Comment by SkoThere** [comment]
I did this but it takes me to github which is not helpful!

On Tue, Sep 1, 2015 at 4:51 PM, Richard Ross <notifications@github.com>
wrote:

> Closed #130
> <https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/130>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/130#event-398269702>
> .
>



-- 

*​​Kendra Ratliff*
*Founder *
*www.skothere.com* <http://www.skothere.com/>
*​IG: skothere*
*Twitter: @skothere​*
*502-592-6525*
