### ISSUE TITLE
Issue with Facebook Login - Data couldn't be read because it isn't in the right format

### ISSUE THREAD

**Issue by duffek** [ParsePlatform/Parse-SDK-iOS-OSX#1345]
Looks like there are some issues with both:

`PFFacebookUtils.logInInBackground(withReadPermissions:` 
And:
`PFFacebookUtils.logInInBackground(with: accessToken`

Both functions return: 
`The data couldn’t be read because it isn’t in the correct format.`

Examples of code that should be working:
func signUpSignInWithFacebook() {

```
        PFFacebookUtils.logInInBackground(withReadPermissions: ["public_profile", "email"]) { (user, error) in
            if error == nil {
                if let user = user {
                    if user.isNew {
                        print("New User found!")
                    } else {
                        print("Returning user found!")
                    }
                } else {
                    print("returned but user is nil?")
                }
            } else {
                    print("there was an error! : \(error!.localizedDescription)")
            }
        }
    }

```
Result: `The data couldn’t be read because it isn’t in the correct format.`

Could this be due to an update to Facebook's SDK? Any ideas on where to go with this?

I am focused on a deadline and will investigate further if any Parse FBSDK functions are working.

Wanted to mark this here so I can loop back to it and get the feedback from everyone.

*Note:* I'm not seeing anything on the server that shows an error so might be coming back from the FB call not my parse server?

**Comment by AlexPestre** [comment]
Got the same issue.

**Comment by duffek** [comment]
Any ideas how to fix? Or what needs to be done in parse to fix it?

**Comment by flovilmart** [comment]
Feel free to investigate. At this time i don’t have the bandwidth to dedicate to this issue

**Comment by AyoPrez** [comment]
I'm having a similar issue. I don't see that message but this code from the ApplicationDelegate is not working properly. 

 `func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        return FBSDKApplicationDelegate.sharedInstance().application(app, open: url, options: options)
    }`

The url value is not empty or nil, but nothing else happen in the app

**Comment by jordaneckhardt** [comment]
Was there a resolution to this issue?

**Comment by jordaneckhardt** [comment]
@duffek @AlexPestre @flovilmart
