### ISSUE TITLE
Update Parse via pods to v. 1.8.2, twitter don't work anymore

### ISSUE THREAD

**Issue by telip007** [ParsePlatform/Parse-SDK-iOS-OSX#138]
I've updated the Parse framework via pods, now my Twitter login doesn't work anymore. 
<p>Do I have to download the Twitter utils manually now like the Facebook utils ?</p>
These are the errors I get: 
<img width="203" alt="bildschirmfoto 2015-08-29 um 23 35 49" src="https://cloud.githubusercontent.com/assets/8666886/9564407/b5ea3e40-4ea6-11e5-9dd7-1e131c30d1f2.png">

**Comment by nlutsenko** [comment]
Yup, Since `1.8.0` ParseTwitterUtils is a separate framework, or i nyour case a separate pod `ParseTwitterUtils`.

**Comment by telip007** [comment]
Oh, ok. Thank you for your fast respond.

**Comment by telip007** [comment]
@nlutsenko I have 1 Question left.
In the previous Parse Pod i used for example:         
<p>let screenName = PFTwitterUtils.twitter()?.screenName!</p>
to get the twitter screen name of the user who signedUp, so what do I need to call now?

**Comment by nlutsenko** [comment]
The APIs didn't change at all, it was just split into a separate framework, so that code should still work like a charm. The only potential difference is that you need to `import ParseTwitterUtils` when you want to use it in addition to importing Parse.

**Comment by telip007** [comment]
@nlutsenko nope, I imported it but now I get the message 'PFTwitterUtils.Type does not have a member named 'twitter'.

**Comment by nlutsenko** [comment]
Hmm... It definitely is there, can you try cleaning Xcode DerivedData to make sure you don't have outdated cache?

**Comment by telip007** [comment]
Yes I cleaned the DerivedData but still get the errors...

**Comment by telip007** [comment]
@nlutsenko

**Comment by nlutsenko** [comment]
Can you share your podfile here with me, so I can try to reproduce the problem.

**Comment by telip007** [comment]
Of course, wait a minute.

**Comment by telip007** [comment]
Here is the Link, just download it :D
https://www.dropbox.com/s/syhyihsz2usqpe7/Podfile?dl=0

**Comment by telip007** [comment]
* @nlutsenko

**Comment by nlutsenko** [comment]
I see... Since you are using pods as static libraries and your project is in Swift - is there a chance you have a ObjC->Swift Bridging Header that includes imports for all the libraries?

**Comment by telip007** [comment]
I use the objective c bridging header already 'cause if I import Parse in swift, I get the no such module... error. So this can't be the solution :D

**Comment by nlutsenko** [comment]
:D Can you try adding `#import <ParseTwitterUtils/ParseTwitterUtils.h` into that bridging header?
Also, if you add `use_frameworks!` to your Podfile and your target deployment is higher than iOS 8 - that makes everything easier, and you don't need the bridging header :D

**Comment by telip007** [comment]
I did the first one already soooo... but I try it with the second in hope that this one make it done :D

**Comment by telip007** [comment]
Where do I need to write the use_frameworks! statement?

**Comment by nlutsenko** [comment]
On top of your Podfile will work.

**Comment by nlutsenko** [comment]
<img width="935" alt="screen shot 2015-08-29 at 3 25 24 pm" src="https://cloud.githubusercontent.com/assets/606991/9564628/335745de-4e62-11e5-8b3d-2599d4937740.png">
I just created a simple blank project in Xcode and imported both Parse and ParseTwitterUtils - that line of Swift code works like a charm.

**Comment by telip007** [comment]
Hmm ok, something is wrong with my Xcode then :D

**Comment by telip007** [comment]
You're the man, works like a charm and without bridging header! :+1: @nlutsenko

**Comment by nlutsenko** [comment]
Perfect! Let me know if I can help you with anything else!

**Comment by telip007** [comment]
@nlutsenko I have another issue :D So when I try to run the App on my Device I get the error, shown below. 
My Bitcode was off so I turn it back on but the error still appears...
<img width="1050" alt="bildschirmfoto 2015-08-31 um 00 12 13" src="https://cloud.githubusercontent.com/assets/8666886/9569783/7b940cd8-4f75-11e5-886a-479b9c980ee1.png">

**Comment by nlutsenko** [comment]
`ParseFacebookUtilsV4`/`ParseFacebookUtilsV3`/`ParseTwitterUtils` don't quite support Bitcode yet, since they are not opensource (they are going to be very very soon).
Since you can't ship Bitcode-enabled apps to App Store, as well as the only gain you get from Bitcode is ability to run on watchOS2 (where Facebook or Twitter modules might not be that much relevant) - I suggest you disable `Enable Bitcode` flag for your project.
We are using #75 to track bitcode support for the SDK and any module (Twitter/Facebook).

**Comment by telip007** [comment]
So but I get the error if I disable Bitcode, too?

**Comment by nlutsenko** [comment]
Hmm... Is it the same error?
Try cleaning your project. Bitcode should only be required if you have it explicitly enabled.
For using via Cocoapods - you can also go into those targets and disable bitcode there if you are getting an error when pods are being built, compared to when your app is being built.

**Comment by telip007** [comment]
Oh ok, I forgot to turn off Bitcode in the FacebookUtils and TwitterUtils pod, ok solved it. Thank you! :+1:  :D
