### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by joshbeal** [ParsePlatform/Parse-SDK-iOS-OSX#140]
Not sure if backend issue or SDK issue, but I can't log in as an existing user with username and password. I'm getting error code 0 which is not documented.

[Error]: {
} (Code: 0, Version: 1.8.2)
Printing description of error:
Error Domain=Parse Code=0 "{
}" UserInfo={my user object data, omitted for brevity here}}

**Comment by joshbeal** [comment]
This only happens for older users. I've tried logging in with an older account (created over a year ago) with an app running the latest iOS SDK and it doesn't work, while a newer account works fine. The App Store version of my app handles both fine because it is running an older version of the Parse SDK (older than 1.8).

**Comment by nlutsenko** [comment]
Hey @joshbeal, this looks like a backend issue, since some users can log in, some can't.
I would suggest trying to reproduce an issue using REST API and curl, and if it does - file a bug using https://parse.com/help (we are still using FB Bug Tool for tracking backend issues).

**Comment by joshbeal** [comment]
It appears this is not a backend issue. I filed an issue via the FB Bug Tool, and it was closed, and I was sent back here. I took the steps they recommended and it looks like I can login fine via the REST API. 

The problem is that the authenticated user object seems to be returned in the userInfo dictionary of the error (which has error code 0, not listed). Please contact me (josh [at] reveal [dot] me) if necessary and I can send you the confidential data needed to reproduce the issue.

**Comment by nlutsenko** [comment]
Contacted. Thanks for following through with this.

**Comment by nlutsenko** [comment]
@joshbeal, just confirmed locally. Indeed a valid bug.
It's crazy, but `error` field on that user object makes it an error, where actually no error happened.
Going to send a pull request in a bit to fix this problem.

**Comment by nlutsenko** [comment]
Fixready, #147 fully solves the problem (just tested locally)
