### ISSUE TITLE
PFKeyValueCache causing app to be killed because out of memory.

### ISSUE THREAD

**Issue by ghugues** [ParsePlatform/Parse-SDK-iOS-OSX#141]
If many cached queries are made, my app spends an incredible amount of time in `-[PFKeyValueCache _compactDiskCache]`. Sometimes between 30s and 1min, and during that time the cpu is running at 100% (out of the 200% available with the 2 cores).

Also memory usage grows really fast during that time (I have yet to determine what is the cause of this). I just ran a test on an iphone 5 with iOS 7, the app quickly reaches about 600Mb and then gets killed by the system (after receiving several memory warnings).

I will look into it more deeply and provide more details and hopefully a way to reproduce. It might take few days since I will be working on an other project this week, but I wanted to report this as soon a possible.

**Comment by nlutsenko** [comment]
Hey @ghugues, thanks for reporting. We'll take a loot at the code to investigate if anything looks fishy or smelly, but waiting for the repro case.

**Comment by ghugues** [comment]
Yes I will try to be a little more precise as soon as I can. I reported it as is in case you had changed something around this method recently.
I just checked memory allocations : most of it is allocated inside `-[PFKeyValueCache _compactDiskCache]`, so it seems to be the the problem.

**Comment by ghugues** [comment]
So wrapping the content of `-[PFKeyValueCache _compactDiskCache]` inside an autorelease pool solves the memory problem completely.

Setting `PFKeyValueCacheDefaultDiskCacheRecords` to `100` reduces the cpu problem (obviously...), but doesn't solve it. This is strange because I'm pretty sure I didn't have this problem with earlier versions of the SDK.

I'll try to get a report case tomorrow.

**Comment by ghugues** [comment]
Here is the repro case : https://github.com/ghugues/KeyValueCache

Here is what I have found :
 - Under iOS 7, this causes enormous amounts of memory to be allocated and not released. Something to do with the autorelease pool of the dispatch queue not being drained probably. Strangely enough, the Allocations instrument reports this memory as freed but when looking at the overall amount of memory used by the process it's clear that it's not.
 - Under iOS 8, the memory is eventually released, but this creates big spikes (up to 300Mb).
 - In both cases wrapping `-[PFKeyValueCache _compactDiskCache]` in an autorelease pool solves the problem. I suggest looking into this more deeply, there my be other cases where dispatch queues do not drain their autorelease pool correctly or often enough.
 - Even with the memory problem solved, the time spent in `-[PFKeyValueCache _compactDiskCache]` and it's cpu usage is still a real problem. Cache queries cant take up to 1 minute to complete because of this.
 - The sample project will show you in more details what is happening (try running it multiple times to see the effect of the disk cache filling up). I suggest calling `-[PFKeyValueCache _compactDiskCache]` less often, I don't think this is necessary to execute it on every cache write. Maybe run it only when you hit 1100 cache entries and remove 100 in one batch.
 - I'm using the 1.8.2 SDK. None of these problems happen when using the 1.7.5 SDK (I haven't tried with 1.8.0 and 1.8.1).

**Comment by richardjrossiii** [comment]
Thanks for the repro case. I'll investigate it later today. I think I have a fairly good idea as to what's going on. Not sure about a ETA on a fix though.

**Comment by ghugues** [comment]
Great to see that you fixed it quickly !
I would like to update my app as soon as possible, do you have an ETA on the 1.8.3 release ? Or is it safe to use the master branch and not wait for a release ?

**Comment by nlutsenko** [comment]
Master is safe to use at this point (current state), so feel free to simply use that.
We are aiming for 1.8.3 release very soon.

**Comment by ghugues** [comment]
Ok thanks !
