### ISSUE TITLE
Wrong answer to request.

### ISSUE THREAD

**Issue by nikitabelosludtcev** [ParsePlatform/Parse-SDK-iOS-OSX#143]
You can see our data base on the screenshot:
![2015-08-31 12 36 52](https://cloud.githubusercontent.com/assets/1511214/9575187/2ad216d0-4fd6-11e5-806c-aeb5a949d393.png)
We send request in which we want to get all objects that have field "name" equal to "qwerty" (but we don't have objects like this in out DB)
![2015-08-31 12 36 12](https://cloud.githubusercontent.com/assets/1511214/9575225/8c427040-4fd6-11e5-9620-1940390fa4ad.png)
In result we got object with ID = «ofj6Atxe1z»

Can you tell me what's the problem?

**Comment by nlutsenko** [comment]
This looks to be a server-side issue, since the server is replying with the wrong data.
We are still using FB Bug Tool to track those down, please file an issue on https://parse.com/help
