### ISSUE TITLE
Local Database Latency Issues

### ISSUE THREAD

**Issue by awareads** [ParsePlatform/Parse-SDK-iOS-OSX#149]
Accessing larger amounts of data within the database with reads and writes can take in upwards of 2-3 minutes. The read and writes into the single JSON file is causing the main issue that we are experiencing with our implementation on a mobile iOS application. Is it possible that this can be converted to an SQL database? The current load times could be drastically reduced to seconds.

**Comment by richardjrossiii** [comment]
Duplicate of #32
