### ISSUE TITLE
Probably unused file PFBlockRetryer

### ISSUE THREAD

**Issue by nskboy** [ParsePlatform/Parse-SDK-iOS-OSX#15]
I've been investigating how Parse for iOS does retrying upon `-saveEventually` and found `PFBlockRetryer` class which is not included anywhere but tests. Is this file no longer used? Can I rely on this class in the future or it will be deleted?

**Comment by nlutsenko** [comment]
Hey @nskboy , good find. It in indeed unused and we should remove it to keep the ask free of dead code.

**Comment by nlutsenko** [comment]
The logic for retrying on `saveEventually` calls actually lives in [PFEventuallyQueue](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/Internal/PFEventuallyQueue.m#L262)

Another piece of retrying logic that we have lives in [PFURLSessionCommandRunner](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/Internal/Commands/CommandRunner/URLSession/PFURLSessionCommandRunner.m#L164), but that is used rather for `saveInBackground` or any other network request.

**Comment by nskboy** [comment]
Thanks for providing more details about retrying!
