### ISSUE TITLE
saveEventually and pinning while offline creates inconsistent objects on backend

### ISSUE THREAD

**Issue by RickDT** [ParsePlatform/Parse-SDK-iOS-OSX#150]
I have created a simple sample project and video to help reproduce this bug as of 1.8.2:
https://github.com/RickDT/parse-localdatastore-saveeventually-bug

Steps to reproduce:

1. Go offline
2. Create object, set its properties, call saveEventually on it, and pin it in background.
3. Update a property on that object, call saveEventually, and pin it in background.
4. Come back online

Expected result: Object on backend matches local object with all expected properties defined.

Actual results: Object on backend only has updated (dirty) properties saved to the backend. Local object is defined as expected.

**Comment by nlutsenko** [comment]
Hey @RickDT, thanks for building a repro project.
Will take a look and update here shortly.

**Comment by RickDT** [comment]
Hi @nlutsenko. Was this addressed in 1.8.4? I noticed this in the changeling, which sounds similar: `Fixed an issue with Local Datastore losing information on PFObjects that were pending to be eventually saved/deleted.`

**Comment by nlutsenko** [comment]
Wow, completely missed this issue... It might have, you are absolutely right.
Any chance you can retest on the latest SDK? (1.8.5)

**Comment by RickDT** [comment]
Our test repo now passes! I looks like this was fixed in 1.8.4. I also checked in 1.9.0 and it's good there too. Thanks to whoever fixed it :)

**Comment by nlutsenko** [comment]
Glad it's fixed!
