### ISSUE TITLE
Swift v2 Error Handling

### ISSUE THREAD

**Issue by adonoho** [ParsePlatform/Parse-SDK-iOS-OSX#152]
Gentlefolk,
 
The Swift v2 try-catch mechanism maps onto Objective-C quite well. Except when there is a shadowing problem.
 
For example:
 
    - (BOOL)pinWithName:(NSString *)name error:(NSError **)error;

 
which automatically maps into Swift v2 in [redacted] v7b6 headers as:
 
    public func pinWithName(name: String, error: ()) throws
 
It should probably map as:

    public func pinWithName(name: String) throws

The Objective-C method Is also commonly paired with this shortened form:
 
    - (BOOL)pinWithName:(NSString *)name;
 
Which maps as: 

    public func pinWithName(name: String) -> Bool

This short method, I suspect, just calls the main one with a NULL for the NSError**. The signature for the short method is remarkably similar to the Swift throwing method. If I leave the short method in my Objective-C header, then errors ensue:

    do { try location.pinWithName(kLocationPin)
        updatePinnedLocations() // Add the locations to the user in the cloud.
    }
    catch let e as NSError { log.error("Local location save error: \(e)") }

Results in the following compile time warning.

    warning: no calls to throwing functions occur within 'try' expression
           do { try location.pinWithName(kLocationPin)
                ^
 
Obviously, the compiler has chosen the wrong signature. In my own code, where I express a similar pattern, I comment out the short method, then the app compiles just fine.

What is the right way to fix the public API? In most things Swift, the answer would be to get rid of the short Objective-C method.
 
Or is there a workaround to the above problem? In my own code, I have tried using the NS_SWIFT_NOTHROWS annotation on the long method signature. It allows me to retain my Swift v1.2 error handling code mostly without change.

What would be the right solution for the Parse API?

Anon,
Andrew

**Comment by richardjrossiii** [comment]
Thanks for the report. I don't have any concrete ideas at this time as to how we should handle this, other than perhaps this is a language issue. Seeing as we do not yet have a GM of the [redacted] beta, maybe this aspect of Swift will change before the official release.

**Comment by adonoho** [comment]
Thanks for considering this issue.

While I haven't yet filed a radar with Apple, considering the footprint in the App Store represented by apps using Parse, you might get more attention if you filed with Apple first.

In the meantime, updating your headers to use `NS_SWIFT_NOTHROWS` is the least invasive change to make to your APIs.

BTW, a trifle more documentation on your build system would be helpful. On my OS X Yosemite box, `bundle` is not installed. Where would I get it?

**Comment by nlutsenko** [comment]
Bundler is a simple rubygem - you can run `gem install bundler` to start using it (it might require sudo to install it first).

**Comment by adonoho** [comment]
Thank you.

Bundler is now installed.

I have commented out `- (BOOL)pinWithName:(NSString *)name;` in `PFObject.h`. As expected, the warning disappears.

**Comment by nlutsenko** [comment]
Ok, great... I'll look into NS_SWIFT_NOTHROWS for methods that don't have an error, so we can fully support Swift 2.
Since Apple is yet to release Swift 2 with Xcode 7 GM - you can probably expect it by the time iOS 9 GM appears (some rumors suggest Sept 9 as the date).

**Comment by adonoho** [comment]
This is really Apple's problem. They are either choosing the wrong signature in their warnings processor or are doing worse job. I don't trust their warning. You really should not have to do anything.

**Comment by nlutsenko** [comment]
I absolutely agree with you, but since error handling in Swift 2 - I think there is not really a need to export the method with no error pointer, since that one is pretty useless and when translated into Swift 2 - both of those will have the same method signature. :grin:

**Comment by adonoho** [comment]
From an Apple forum, the following appears to be the correct solution:

    do { try location.pinWithName(kLocationPin, error: ())

It calls the long method and not the short one. The clue was in the auto generated method signature in my OP.

It is ugly beyond words...

**Comment by nlutsenko** [comment]
I think I found a good solution for it - simply adding `NS_SWIFT_UNAVAILABLE("")` attribute to methods make the error one have a proper `throws` annotation and skip `error: ()` behaving the same way as if you simply comment out the original method.

**Comment by nlutsenko** [comment]
Another awesome piece - that macro seems to be available only with in Xcode 7, meaning that method is still going to be available in Swift 1.2 if someone wants to use it. Seems like we have a plan to go here.

**Comment by adonoho** [comment]
That looks very promising. I am playing around with it and will report back tomorrow.

**Comment by adonoho** [comment]
You may also want to examine this macro:

    - (BOOL)canEvaluatePolicy:(LAPolicy)policy error:(NSError * __autoreleasing *)error __attribute__((swift_error(none)));

**Comment by adonoho** [comment]
Rebuilding the Parse framework results in:

    Compiling PFCommandURLRequestConstructor.m

    ⌦  /Users/awd/Projects/Libraries/Parse-SDK-iOS-OSX/Parse/PFObject.h:870:12: expected ';' after method prototype

    - (BOOL)pin NS_SWIFT_UNAVAILABLE("Breaks try-catch");
               ^

**Comment by nlutsenko** [comment]
Xcode 6.4 or 7?
Looks like NS_SWIFT_UNAVAILABLE is not available on 6.4

**Comment by adonoho** [comment]
Xcode 7b6

**Comment by nlutsenko** [comment]
Wow, ok... I'll look into it in a bit, should be available though.

**Comment by adonoho** [comment]
Do this on your schedule. I am happy commenting out the shadow methods I use until you have a good answer. I also stand ready to help you test your preferred solution.

**Comment by nlutsenko** [comment]
:) Thanks for all the help, I'll reach out when I have something set up. (say a branch for testing)

**Comment by adonoho** [comment]
Actually, my command line tools were using Xcode 6.4
After lunch, I'll try again with Xcode 7 tools.

**Comment by nlutsenko** [comment]
:grin:

**Comment by adonoho** [comment]
Everything compiles with Xcode tools v7b6 using the `NS_SWIFT_UNAVAILABLE` macro. Some methods are not being mapped properly.

    - (void)fetchFromLocalDatastore NS_SWIFT_UNAVAILABLE("Breaks try-catch");
    - (void)fetchFromLocalDatastore:(NSError **)error;

I suspect the problem is the void return value. To fit the Cocoa/Swift error handling pattern, you probably need to return the object itself or a BOOL.

**Comment by nlutsenko** [comment]
Those methods already have a return type. Are you sure you are using the latest code from master?

**Comment by adonoho** [comment]
- (void)fetchFromLocalDatastore:(NSError **)error;

Looks like a void return type to me ... ;-)


Yes, technically that is a return type. It just returns nothing for the try-catch mechanism to use. It needs, I believe, either a BOOL or a nullable returned object.

I made a branch off of `master` tagged `v1.8.2`. In general, I try to avoid stepping into new code when researching a problem.

**Comment by nlutsenko** [comment]
:) It already is an `instancetype` on master, so in the PR attached - everything should just work for that method.
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/PFObject.h#L734
