### ISSUE TITLE
Memory leaks when use PFCloud callFunction

### ISSUE THREAD

**Issue by maksimgrachev** [ParsePlatform/Parse-SDK-iOS-OSX#158]
Each 30 sec I to call cloud function, which return more 300 PFObjects, and every time increase in the application memory on several KB, but sometimes on 5-7 MB. 
As a result, the app crashes.

**Comment by nlutsenko** [comment]
Hey @maksimgrachev, thanks for the report.
Any chance you can attach a simple repro project, it would help tremendously with debugging issues like this.

Also, please note - releasing objects doesn't guarantee to deallocate immediately.
