### ISSUE TITLE
Exception when [Parse setApplicationId:clientKey:] is called twice

### ISSUE THREAD

**Issue by wzs** [ParsePlatform/Parse-SDK-iOS-OSX#159]
Recently I've found in our codebase that `+[Parse setApplicationId:clientKey:]` was called twice during app initialization (with same params). 

It was obviously mistake, but by the way I've found that in that case SDK throws exceptions, ie:
during call to `-[PFCommandURLRequestConstructor _URLRequestHeadersForCommand]`, `dataSource` became `nil` (it's a weak reference to `ParseManager`).

It'd be nice to have an assertion preventing from changing applicationId/clientKey after it's set already or cancel all ongoing operations started from the old instance of ParseManager.

**Comment by nlutsenko** [comment]
Hey @wzs, thanks for report.
Setting applicationId and clientKey more than once is definitely not supported use case, let me put this as an enhancement and add assertion there.

`PFCommandURLRequestConstructor` use case is super interesting though - we should do something smarter there.

**Comment by nlutsenko** [comment]
Implemented in #874
