### ISSUE TITLE
Parse for iOS v1.8.0 breaks localization

### ISSUE THREAD

**Issue by joshblour** [ParsePlatform/Parse-SDK-iOS-OSX#16]
After updating from parse v1.7.5.3 to v1.8.0 via cocoapods, my localizations stopped working.

I'm guessing it's because v1.8.0 now has it's own Localizable.strings file, which overrides the one my app was previously using.

Rolling back to v1.7.5.3 and cleaning my build folder restored my localizations.

**Comment by nlutsenko** [comment]
Hey @joshblour could you confirm whether you are usIng frameworks or static libraries for your Cocoapods?
I think what happens is that we are preparing our Localizations.strings for framework deployment, but if it's being used as a static library - Cocoapods overwrites the localizations in your project.

**Comment by natanrolnik** [comment]
I'm experiencing this as well with 1.8.0. I'm glad I saw this before I needed to start looking for the reason.

**Comment by alistra** [comment]
Experiencing the same thing, using static libraries because other vendors not yet support framworks.

Please rename the file so it won't collide.

**Comment by ghugues** [comment]
Experiencing this as well (using static library). Adding the following Run Script Phase, solves the problem :
# Remove Localizable.strings added by Parse
rm -rf "$TARGET_BUILD_DIR/$FULL_PRODUCT_NAME/Localizable.strings"

**Comment by umekun123** [comment]
I am also having this issue after updating..

**Comment by nlutsenko** [comment]
Hey everyone,

The fix is already checked into master and will be available with the next version of the SDK (1.8.1).
If you want to use it right now - you can simply change your Podfile to reference master by adding:
`pod 'Parse', :git => 'https://github.com/ParsePlatform/Parse-SDK-iOS-OSX.git'

**Comment by wouterds** [comment]
Localization still doesn't work for me though (tested with 1.8.1).

![image](https://up.kibakoapp.com/5kOodC8Dbs!#direct)
![image 2](https://up.kibakoapp.com/gTRBXuTQWW!#direct)

The only thing that did work for me until now is what @ghugues suggested by adding a build phase run script `rm -rf "$TARGET_BUILD_DIR/$FULL_PRODUCT_NAME/Localizable.strings"`

**Comment by nlutsenko** [comment]
Hmm... I am actually amazed by this, since I've tested it locally, as well as it should work since there are no more Localizable.strings in Parse pod.

I suggest trying cleaning pod cache in your project directory as well as maybe running `pod update`

**Comment by ghugues** [comment]
Might be a cache problem indeed. Xcode doesn't remove the previous build in the cache directory when making a new one. The consequence is that new files are added but old files are never removed.
Try removing the DerivedData directory (first thing to try when you have problems with Xcode...) :
`rm -rf ~/Library/Developer/Xcode/DerivedData`

**Comment by wouterds** [comment]
Aha, `rm -rf ~/Library/Developer/Xcode/DerivedData` fixed it. Thanks!
