### ISSUE TITLE
Unable to Invoke PFCloud.callFunctionInBackground in Swift 2.0

### ISSUE THREAD

**Issue by om23** [ParsePlatform/Parse-SDK-iOS-OSX#164]
Example Code: 

PFCloud.callFunctionInBackground("whereAmI", withParameters: ["location": geoPoint], block: {(
                    result: AnyObject, error: NSErrorPointer) in
                    let Zones = result as? NSObject
                    NSLog("-----tacos-----")
                    NSLog(Zones)
                })

**Comment by nlutsenko** [comment]
I think there is a syntax mistake in how you resolved the method signature.
Here is a fixed example using the last release of the SDK (as well as current master), which actually seems to properly work on both Swift 1.2 and 2.0.
```swift
        PFCloud.callFunctionInBackground("whereAmI", withParameters: ["location" : geopoint]) { (result: AnyObject?, error: NSError?) in
            let Zones = result as? NSObject
            print("-----tacos-----")
            print(Zones)
        }
```
Hope this helps. Let us know if there is anything else we can help you with.

**Comment by om23** [comment]
I updated to the last release of the SDK and even with your suggested fix I still get the error: 


Cannot invoke 'callFunctionInBackground' with an argument list of type '(String, withParameters: [String : PFGeoPoint?], (AnyObject?, NSError?) -> _)'

**Comment by nlutsenko** [comment]
It looks like it thinks that `geoPoint` in your case is an optional (`[String: PFGeoPoint?]`), can you try unwrapping it and see if it produces the same error?

**Comment by om23** [comment]
Unwrapping it worked. Thanks!

**Comment by nlutsenko** [comment]
:+1:
