### ISSUE TITLE
Value for field changing without any cause

### ISSUE THREAD

**Issue by jaredMermey** [ParsePlatform/Parse-SDK-iOS-OSX#165]
Values for a field are randomly changing in the background. Though it refers to a UserID from my User class, the field itself is being stored as a String. The issue arises that sometimes the field changes from a String to an array of objects that stores as:

[object object]

It appears to be fairly random as to when it stores one way vs. the other...and I do not know how or why it changes. When my app calls for that field and the array is returned, my app breaks. 

Is this a bug or shortcoming of Parse?

**Comment by nlutsenko** [comment]
Hey @jaredMermey, this sounds very strange.
Can you attach a small repro piece of code or a repro project to help diagnose the problem?
It would help tremendously to discover and address the issue faster.

**Comment by jaredMermey** [comment]
Sure. 

Class Creation: 
1) The second class that holds this fields is called "Relationship."
2) I both created the Relationship class and populated it manually. The class store relationships and their types. 
3) The two fields that hold the two people involved in the relationship are called "doer" and "recipient." Each stores a User ObjectID as a String (not using pointers or relationships).

I've written codes to get the recipientId in two ways -- once as a map function and once as a for loop. Either way, I grab all the recipientIds from the objects where the currentUser is the "doer." I wrote it a second time because at first I thought it was a client side issue. I then noticed the following returns:

FOR SUCCESS (70% of time...just a string): recipient = KE2ceJkZgQ;
FOR FAILURE (an array): recipient = "<pfuser: 0x7fc612df77b0,="" objectid:="" ke2cejkzgq="">";

I then went to the Core interface and noticed the String in the cell which caused the error turned into [object object]. I refreshed the page and it returned back to the alphanumeric String. Whenever I checked the core after a FAILURE, there was a higher frequency of seeing [object object].

**Comment by nlutsenko** [comment]
This looks like a backend or data browser issue to me, since after refreshing the page you can see the proper result. 
Since we are still using FB Bug Tool for those - could you file a bug under https://parse.com/help

**Comment by nlutsenko** [comment]
Feel free to reopen and or provide more details here if you think it's related to the client.

**Comment by jaredMermey** [comment]
Do I do that on the developer forum? That seems to be public. Sorry but I
am new to this.

**Comment by nlutsenko** [comment]
The `file a bug` piece is on https://parse.com/help
