### ISSUE TITLE
Build failure with 'framework not found FBSDKCoreKit for architecture x86_64'

### ISSUE THREAD

**Issue by apersaud** [ParsePlatform/Parse-SDK-iOS-OSX#17]
When trying to build an application, using Cocoapods that also includes ParseFacebookUtilsV4 with the latest Facebook SDK, we get a linker error:
![screen shot 2015-08-14 at 9 08 20 am](https://cloud.githubusercontent.com/assets/127068/9278198/08e1c1ee-4264-11e5-8d8f-146c493d5520.png)
```
ld: framework not found FBSDKCoreKit for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have provided a sample project that makes it reproducible: https://dl.dropboxusercontent.com/u/119336/ParseLinkerErrorSample.zip 

Podfile:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
link_with 'ParseSample'
inhibit_all_warnings!

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Parse'
pod 'ParseFacebookUtilsV4'
```

**Comment by nlutsenko** [comment]
Hey @apersaud, thanks for the report.
Will take a look and fix it for you shortly.

**Comment by CraigSiemens** [comment]
I'm running across the same issue except with Parse

```
ld: framework not found Parse for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nlutsenko** [comment]
Hey guys,

I've just updated our pods for `ParseFacebookUtils`, `ParseFacebookUtilsV4`, `ParseTwitterUtils` and `ParseCrashReporting` to `1.8.0.1`. This fully resolves the issue with using Cocoapods as static libraries and those pods. It doesn't contain any other changes.

Let me know guys if you run into any more problems.

**Comment by smitjb45** [comment]
Hello, I'm getting a similar kind of error...

ld: framework not found ParseTwitterUtils
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm using v1.8.5

**Comment by nlutsenko** [comment]
That means that you probably didn't add ParseTwitterUtils to linked binaries list.
ParseTwitterUtils is available from the SDK download package [here](https://parse.com/docs/downloads) or I would also suggest starting to use Cocoapods for all your dependency management, since it simplifies the process.

**Comment by smitjb45** [comment]
Okay, thanks. Ill try it. sorry, I opened a new issue... I'm new to git and Parse.

**Comment by nlutsenko** [comment]
Sure, let's take this discussion off to that issue, since it's not related to this one.
