### ISSUE TITLE
PFUser logInWithUsernameInBackground not returning the latest User record data

### ISSUE THREAD

**Issue by henry-tappd** [ParsePlatform/Parse-SDK-iOS-OSX#172]
PFUser logInWithUsernameInBackground is not returning the current PFUser data consistently sometimes.

```
[PFUser logInWithUsernameInBackground:email password:password block:^(PFUser *user, NSError *error) {
            if (!error) {
                resolve(user);
            } else {
                resolve(error);
            }
        }];
```

I have a column "userStatus" to store the user status. When I changed it in Parse Browser and login again. Sometimes it still shows the old data. Does Parse always return the current User record in the block callback? 

It was working quite well in the last 9 months until recently on Tuesday 1st Sept, we saw some unusual behaviours in the Parse. We have to ask our new signup users to delete the app and download it again from AppStore in order to get the new changes in User table.

Is anything changed recently in the backend?

Thanks in advance !

**Comment by nlutsenko** [comment]
Hmm. This sounds very strange. To the best of my knowledge - nothing changed. I suggest filing a FB Bug Tool issue on https://parse.com/help since we are continuing to use it for tracking backend issues.
