### ISSUE TITLE
Error when trying to use Parse in watchOS2 App 

### ISSUE THREAD

**Issue by mahmoud-khalifa** [ParsePlatform/Parse-SDK-iOS-OSX#177]
I have tried to add Parse using cocoa pods to a watchOS2 App here is the pod file 
> target 'OS2Test WatchKit Extension' do
    pod 'Parse',                    '~> 1.8.2'
end

When I compile I get the following error:
>In file included from ~/Xcode_Projects/OS2Test/OS2Test WatchKit Extension/InterfaceController.m:10:
In file included from ~/Xcode_Projects/OS2Test/Pods/Headers/Public/Parse/Parse.h:36:
~/Xcode_Projects/OS2Test/Pods/Headers/Public/Parse/PFPurchase.h:11:9: fatal error: 'StoreKit/StoreKit.h' file not found
#import <StoreKit/StoreKit.h>
        ^
1 error generated.

It seems that StoreKit framework can not be added to the app, so is there  is a parse version that supports watchOS2?? or what?

**Comment by nlutsenko** [comment]
Hey @mahmoud-khalifa, since you can't quite ship watchOS 2 apps yet, we are still working on getting there. Pull Requests would be very helpful.
In the meantime - you can use precompiled framework from the releases page and simply delete PFPurchase.h in order to get this working.

**Comment by nlutsenko** [comment]
I've just created an issue to track watchOS 2 support #179. Closing this one out.
