### ISSUE TITLE
PFAnalytics not tracking push opens

### ISSUE THREAD

**Issue by arielelkin** [ParsePlatform/Parse-SDK-iOS-OSX#184]
Hey all,

I have an issue with PFAnalytics not tracking push opens on iOS, despite the app correctly receiving pushes and PFAnalytics being set up as instructed. 

I've set up my app to receive push notifications sent from Parse, following all the steps in Parse's documentation:

https://www.parse.com/docs/ios/guide#push-notifications

When running on my mobile devices, the app receives every single push notification I send to it from Parse, but push opens are not being tracked. This is what I see on the dashboard: 

![][1]

Given that [`PFAnalytics.trackAppOpenedWithLaunchOptions` and `PFAnalytics.trackAppOpenedWithRemoteNotificationPayload`](https://parse.com/docs/osx/api/Classes/PFAnalytics.html) are [`BFTasks`](http://boltsframework.github.io/docs/ios/Classes/BFTask.html), I've added a completion block for them as follows:

In `application:didReceiveRemoteNotification`:

```
PFAnalytics.trackAppOpenedWithRemoteNotificationPayload(userInfo).continueWithBlock({ (task) -> AnyObject! in

        assert(task.completed, "task should have completed")

        assert(!task.cancelled, "task should not have been cancelled")

        assert(!task.faulted, "task should not complete due to error or exception")

        return task
    })
```

In `application:didFinishLaunchingWithOptions`:

```
PFAnalytics.trackAppOpenedWithLaunchOptions(launchOptions).continueWithBlock({ (task) -> AnyObject! in

        assert(task.completed, "task should have completed")

        assert(!task.cancelled, "task should not have been cancelled")

        assert(!task.faulted, "task should not complete due to error or exception")
        
        return task
    })
```

The continuations block do get called, but none of the `asserts` fail, so `PFAnalytics` is supposedly successfully sending the data to Parse Analytics. 

Why are my push opens and open rate still zero? 

[1]: http://i.stack.imgur.com/WunkF.png

Thanks

**Comment by nlutsenko** [comment]
Sounds pretty sad, thanks for the report. Asserts help a lot in identifying the root cause here, which in this case looks to be the backend. Since we are still using FB Bug Tool for those - could you file a bug on https://parse.com/help
P.S. For backend issues, tbh it's a much better tool, since we can instantly see the name of the app, for example.

**Comment by arielelkin** [comment]
thanks @nlutsenko 

Bug filed here: https://developers.facebook.com/bugs/119817525037600/

**Comment by LudaFuxPlaybuzz** [comment]
Is there any news?
