### ISSUE TITLE
Crashes don't appear in the dashboard

### ISSUE THREAD

**Issue by virt87** [ParsePlatform/Parse-SDK-iOS-OSX#185]
From yesterday the dashboard doesn't show any bug but using Charles i was able to see that bugs are sent to the api.parse.com after relaunching the app after a crash

**Comment by nlutsenko** [comment]
Hey @virt87, since crashes make it's way to the backend - seems there is something going wrong in that field. As we are still using FB Bug Tool to track these, could you please file a bug at https://parse.com/help

Let me know if there is anything I can help you with.
