### ISSUE TITLE
PFObject removeObject:forKey: crash

### ISSUE THREAD

**Issue by joshbeal** [ParsePlatform/Parse-SDK-iOS-OSX#186]
I've experienced a crash related to removing an object from channel array on PFInstallation. Relevant stack frame and exception: 

Fatal Exception: NSInternalInconsistencyException
Operation is invalid after previous operation.

PFFieldOperation.m line 354
-[PFRemoveOperation mergeWithPrevious:]

I can share confidential details (code snippet and full crash report) over email if needed.

**Comment by nlutsenko** [comment]
Hey @joshbeal, thanks for the report. I believe you are doing something else before this, maybe adding an object for key and saving it eventually?
Would love to hear from you about the use case that you are running in to better support it.
Feel free to post a stack trace or more details here or send it to `nlutsenko@fb.com`.

**Comment by joshbeal** [comment]
@nlutsenko just wanted to follow up, I shared details over email

**Comment by joshbeal** [comment]
^ still waiting for feedback on my previous report

**Comment by paolorau** [comment]
Hi!
I had the same problem and I found that is caused because you are (probably) deleting and adding channels at the same time. You must wait until saveEventually finish and then run the other saveEventually, look at this code :

```javascript
[currentInstallation
 removeObjectsInArray:toDelete
 forKey:@"channels"];

[currentInstallation saveEventually:^(BOOL succeeded, NSError * _Nullable error) {
    if (succeeded){
        for (NSString *channel in toAdd) {
            if (![[currentInstallation channels]  containsObject:channel]){
                [currentInstallation addUniqueObject:channel forKey:@"channels"];
                [currentInstallation saveEventually];
            }
        }
    }
}];
```

**Comment by funkenstrahlen** [comment]
I currently have the same issue. I see this crash:

![screen shot 2018-04-18 at 10 54 01](https://user-images.githubusercontent.com/144173/38921783-d7a1c76e-42f6-11e8-8867-70eaee6300d0.png)

It crashes because of calling `removeObject` in this method:

```objectivec
- (BFTask *)unsubscribeFromChannelAsyncWithName:(nonnull NSString *)name {
    return [[self _getCurrentObjectAsync] continueWithSuccessBlock:^id(BFTask *task) {
        PFInstallation *installation = task.result;
        if (name.length != 0 &&
            ![installation.channels containsObject:name] &&
            ![installation isDirtyForKey:PFInstallationKeyChannels]) {
            return @YES;
        }
        [installation removeObject:name forKey:PFInstallationKeyChannels];
        return [installation saveInBackground];
    }];
}
```

@joshbeal Have you found a solution for your problem?

**Comment by Skyb0rg** [comment]
Still have the same Problem ... when having bad coverage and user removes and adds a Channel to fast it crashes.
