### ISSUE TITLE
Deploying app with Parse SDK behind firewall

### ISSUE THREAD

**Issue by nskboy** [ParsePlatform/Parse-SDK-iOS-OSX#191]
My app uses Parse SDK but it is deployed behind corporate firewall which denies all Internet access. So in order to use Parse I need to tell which hosts, ports and protocols will be used by SDK to the information security department. Could you please provide this information? Is there a way to be notified of this information change?

**Comment by nlutsenko** [comment]
As of right now (not taking into account ParseTwitterUtils and ParseFacebookUtils which talk to generic FB/Twitter endpoint), we have roughly 2 possible domains that could be hit:
- api.parse.com (all SDK communication with Parse)
- files.parsetfss.com (PFFile downloads)

All communication happens over HTTPS with a possibility to fallback to HTTP.
To the best of my knowledge, iOS starting from 4.0 (or even earlier?) will use TLS 1.2 for SSL connections. 

Whilst there is no guarantee that these end points aren't going to change, doing so would break a lot of apps, thus it is something we would want to avoid at all costs, so they are pretty much fixed and not going to change. 

Let me know if there is anything else I can help you with. 
P.S. I feel bad for you guys. Hope it helps.

**Comment by nskboy** [comment]
Thank you for making my life a bit easier!
