### ISSUE TITLE
Not able to compile the code after taking pod update

### ISSUE THREAD

**Issue by sabby3861** [ParsePlatform/Parse-SDK-iOS-OSX#193]
![screen shot 2015-09-09 at 12 50 29 am](https://cloud.githubusercontent.com/assets/532928/9745005/d9b9737a-568c-11e5-95b1-933f641c082e.png)
Hi

I am not able to compile and run the code after taking the pod update. There are showing 8 errors.
1 error in PFEncoder and 7 errors in PFPushInternalUtils class.
The error are of type, expected a type or unknown type say for NS_ASSUME_NONNULL_BEGIN.
Please help and update

Thanks
Sanjay

**Comment by nlutsenko** [comment]
Hey @sabby3861, these are not available in Xcode < 6.3.
Two suggestions to fix these:
- Update your Xcode to the latest (6.4)
- Use precompiled frameworks from the releases page

Let me know if there is anything else I can help you with.
