### ISSUE TITLE
Combine podspecs, using platform-specific settings

### ISSUE THREAD

**Issue by segiddins** [ParsePlatform/Parse-SDK-iOS-OSX#2]
i.e., in `Parse.podspec`, you could do

```ruby
s.ios.source_files = ...
s.osx.source_files = ...
```

That way, you wont need two separate specs.

**Comment by nlutsenko** [comment]
Hey @segiddins, welcome... :D
Our OS X framework name is `ParseOSX`, and as Cocoapods doesn't support `s.osx.module_name` - we decided to leave it as is for this release, but will merge both of them together for the next one.

**Comment by segiddins** [comment]
:+1: awesome -- you could just make `ParseOSX` depend on `Parse` and deprecate it
