### ISSUE TITLE
error repeat header table in qweb report

### ISSUE THREAD

**Issue by Anhlq87** [ParsePlatform/Parse-SDK-iOS-OSX#203]
Hi guys

I print sale orders report in root sale module. I enter many product to it split 2 page. In the page 2 it show not good. Everybody help me solve it. please see bellow image:
![error](https://cloud.githubusercontent.com/assets/9975164/9752620/b2d2740a-56dc-11e5-97ab-dc4197245322.png)

**Comment by nlutsenko** [comment]
Hmm... Not sure how we can help.
Few questions first, are you sure this is something related to Parse SDK for iOS/OSX?
Looks related to web and/or printing?

**Comment by Anhlq87** [comment]
sorry, I'm mistake
