### ISSUE TITLE
Add fields to PFAnonymousUtils BEFORE logInWithBlock?

### ISSUE THREAD

**Issue by Natelegreat1** [ParsePlatform/Parse-SDK-iOS-OSX#204]
I want to create an anonymous user on Parse. I would like that anonymous user to have a field for 'language' which will save the device's default language. My PFUser object has a field 'language'.

Is there a way to save `[PFUser current][@"language"]` BEFORE calling `logInWithBlock`??
Or do I have to wait for the completion block and then save a second time...

I posted the same question here:
[StackOverflow](http://stackoverflow.com/questions/32470431/add-fields-to-pfanonymousutils-before-loginwithblock)

**Comment by nlutsenko** [comment]
You can definitely do it, using something like this:
- Enable automatic users by calling `PFUser.enableAutomaticUser()`
This will make `currentUser` always return a user that could be still unsaved
- Call into `PFAnonymousUtils.logInWithBlock()` or even `PFUser.save()`
- ???
- Profit

The other piece to note here - current device locale together with language is already persisted as `localeIdentifier` on a `PFInstallation` automatically for you. This actually helps address an issue where your user might have couple of devices and they would want to have different language settings on every one of them, so `currentUser["language"]` might not be accurate and not covering all the devices.

Hope this helps.

**Comment by Natelegreat1** [comment]
I was wondering about PFUser.enableAutomaticUser() !
My understanding is that if I allow that, they will have a 'valid' PFUser even though it may only persist locally (until I explicitly call save() or signUp() at some point)?

I saw the addition of localeIdentifier on PFInstallation the other day! Great stuff! I had been saving it for ages. I want to keep it on the User too -- just in case they don't allow Push Notifications, it's great for analytics! Maybe it'll be added to Parse v1.8.3.

Thanks!

**Comment by Natelegreat1** [comment]
PFUser.enableAutomaticUser() is doing exactly what I wanted it to do...! 
Not sure why I had given up on it a few weeks back.

THANK YOU!
