### ISSUE TITLE
Parse push status: pending

### ISSUE THREAD

**Issue by Dridia1** [ParsePlatform/Parse-SDK-iOS-OSX#215]
Hi,

Sending push-notifications has always worked out great for me.
But last week on Thursday it stopped working. All the pushes that is sent from the app gets the status: pending.  When i'm sending the push notification from the website everything works great. i get the push-notifications on all the phones that i target.

**Comment by nlutsenko** [comment]
Hey @Dridia1, the `pending` notifications are being sent from the push console on `parse.com` or in any different way?

Not sure why they are constantly in `pending` status, but it might be related to APNS Certificates problem.

**Comment by Dridia1** [comment]
The Pending notifications were being sent from the actual app it self. Now for some reason they are working. I haven't done any changes.

**Comment by nlutsenko** [comment]
If you see anything like this again - I suggest filing a bug report on https://parse.com/help since this appears to purely be a backend issue.
