### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by dailenspencer** [ParsePlatform/Parse-SDK-iOS-OSX#216]
Im here because i have tried everything under the sun to try and get my parse push notifications working for my ios devices. I originally had them functioning well for development puposes, and then had them working for production. Now they dont work at all and i have fallen back to development and cant even get them to work for my development purposes. I went back and completely erased all of my provisioning profiles and revoked all of my certificates and restarted. Nothing works. The notifications appear in the log of parse but they are not received by the devices. When i view the delivery report, the count is 0 for each issue. Any advice? Thanks

**Comment by nlutsenko** [comment]
Hey @dailenspencer, the only thing that comes to my mind is probably installations not being saved from the client to the server. Or push notifications registration with Apple not being implemented/not working.
