### ISSUE TITLE
Custom Events PFAnalytics not showing in Explorer

### ISSUE THREAD

**Issue by Maxrencoret** [ParsePlatform/Parse-SDK-iOS-OSX#217]
When calling 

PFAnalytics.trackEventInBackground("myAnalyticsName", block: {
         (success: Bool, error: NSError?) -> Void in
            if (success){
                println("Correctly registered")
            } else {
                println("Not registered")
            }
        })

I'm not seeing anything in Explorer although I get "Correctly registered".
How long does it take for the analytic to appear in the Explorer? Does Parse store every analytic the device sends or only some of them?

I'm also trying

        let dimensions = [
            "category" : "landing"
        ]
        PFAnalytics.trackEventInBackground("myAnalyticsName", dimensions: dimensions, block: {
            (success: Bool, error: NSError?) -> Void in
            if (success){
                println("Correctly registered")
            } else {
                println("Not registered")
            }
        })

And also get "Correctly Registered" but event does not appear in Explorer "Custom Events"
Thanks

**Comment by nlutsenko** [comment]
Hey @Maxrencoret, since the client side piece appears to work - I suspect this is purely a backend issue.
We are still using FB Bug Tool to track those - could you file a report at https://parse.com/help

Let me know if there is anything else I can help you with.
