### ISSUE TITLE
PFThreadsafetySafeDispatchSync Crash on PFThreadsafety.m:28

### ISSUE THREAD

**Issue by maxbryan** [ParsePlatform/Parse-SDK-iOS-OSX#234]
Getting a crash while trying to get an image file's data. Calling getDataInBackgroundWithBlock on the main thread. The crashing code is called from PFFile downloadAsyncWithProgressBlock.

        image.getDataInBackgroundWithBlock {
            (data, error) -> Void in
            
            if let data = data {
                
                if let image = UIImage(data: data) {
                    
                    self.imageView.image = image
                }
            }
        }

<img width="613" alt="screen shot 2015-09-10 at 9 04 02 pm" src="https://cloud.githubusercontent.com/assets/3952680/9805692/cadbd85e-5801-11e5-9c03-d21fd0fcfa06.png">
<img width="823" alt="screen shot 2015-09-10 at 9 03 49 pm" src="https://cloud.githubusercontent.com/assets/3952680/9805691/cadacf5e-5801-11e5-884d-ebf7f13293d1.png">
crash source: 0 dispatch_queue_get_specific
<img width="613" alt="screen shot 2015-09-10 at 9 22 34 pm" src="https://cloud.githubusercontent.com/assets/3952680/9805724/13d2533a-5802-11e5-9c34-44298dd17d5a.png">

**Comment by maxbryan** [comment]
Looks like this happened when trying to get data from a nil PFFile

**Comment by richardjrossiii** [comment]
This should never happen when a `PFFile` is `nil`, as messages sent to nil should always be a no-op. Can we get a full stack trace? (type `thread backtrace all` in the LLDB console).

**Comment by maxbryan** [comment]
Here's a full trace. Thanks again for your help
<img width="2405" alt="screen shot 2015-09-16 at 1 23 17 pm" src="https://cloud.githubusercontent.com/assets/3952680/9914183/34401cce-5c76-11e5-9858-9b22bb534912.png">

**Comment by richardjrossiii** [comment]
Thanks for the stack trace... What version of the SDK are you using? That stack trace indicates that the crash is on line 298 of `PFFile`, though in the latest version of the SDK line 298 is doing something completely different.

**Comment by maxbryan** [comment]
Looks like 1.7.5

**Comment by richardjrossiii** [comment]
Parse 1.7.5 was released in almost 3 months ago, and is no longer supported. Please try using the latest version of Parse, which is 1.8.4. If the problem still persists, post a stack trace with the current version of the SDK so that we can help you better.

**Comment by maxbryan** [comment]
Problem still exists with the newest SDK. 
<img width="2336" alt="screen shot 2015-09-17 at 1 00 27 pm" src="https://cloud.githubusercontent.com/assets/3952680/9941629/292a6cd8-5d3c-11e5-9bce-c028e5236ab6.png">

**Comment by richardjrossiii** [comment]
Are you ever creating a `PFFile` via a method other than `-[PFFile fileWith...]`? What appears to be happening is that the files internal dispatch queue is NULL, which should only ever happen if the file was not created through one of our dedicated constructors.

**Comment by maxbryan** [comment]
I'm initializing a variable with PFFile() at the header of my swift document then getting the file from the server then assigning it to that variable. I recently changed it so that if the image doesn't exist on the server, I assign nil to it and it seems to be working correctly now.

**Comment by nlutsenko** [comment]
Yup, sounds like we didn't mark that method as unavailable...
Going to fix in a bit.
