### ISSUE TITLE
timezone field getting updated on Installation object?

### ISSUE THREAD

**Issue by SolomonRajput1** [ParsePlatform/Parse-SDK-iOS-OSX#246]
I'm building an iOS app with Parse 1.6.2. 

The documentation says that when certain fields for the Installation object change, like time zone or app version number, the installation object will be updated. These are read-only properties so we can't set them ourselves. 

However, I'm changing the app version number and the time zone on my app and the installation isn't being updated, even when I specifically save the installation object.

Does anyone have any idea about how we can update the installation?

**Comment by nlutsenko** [comment]
Hey @SolomonRajput1, thanks for the report.
iOS SDK 1.6.2 was released on Jan 23 this year.
The latest as of right now is 1.8.3 - any chance you can try the same using that version?

**Comment by SolomonRajput1** [comment]
Hi Nikita,

Thanks for the suggestion-- if I use the latest SDK do you think that will
solve the problem? I don't want to have to perform an update and risk
messing up some parts of my project if it won't be all that helpful.

Thanks so much!
Salman

**Comment by nlutsenko** [comment]
Hey @SolomonRajput1, we don't foresee any problems with upgrading from 1.6.2 to the latest version of the SDK, so I would recommend you give it a try.
