### ISSUE TITLE
Could not build Objective-C module 'Parse'

### ISSUE THREAD

**Issue by sandyleo26** [ParsePlatform/Parse-SDK-iOS-OSX#247]
Just downloaded the zip file a new project selecting ios/swift/data, the project builds fine but it shows the following error at `import Parse`. Code completion for Parse objects don't work either. Test could pass in Parse website though. I'm using Xcode 7 beta 3.

`/Users/jjjjjjjj/Desktop/parse-starter-project-1.8.3/ParseStarterProject-Swift/ParseStarterProject/ViewController.swift:11:8: Could not build Objective-C module 'Parse'`

I tried the bridge header method which could remove the error but code completion still doesn't work.

**Comment by sandyleo26** [comment]
the zip file I downloaded is parse-starter-project-1.8.3.zip

**Comment by nlutsenko** [comment]
Hey @sandyleo26, Xcode 7 beta 3 is quite old.
Any chance you can try the same using latest Xcode 7 GM?

This sounds to me like an Xcode bug.

**Comment by sandyleo26** [comment]
Hi Nikita,

Thanks. I've tried the Xcode 7 Beta 7 and now the problem is gone. Please
close it.

On Mon, Sep 14, 2015 at 5:28 PM, Nikita Lutsenko <notifications@github.com>
wrote:

> Hey @sandyleo26 <https://github.com/sandyleo26>, Xcode 7 beta 3 is quite
> old.
> Any chance you can try the same using latest Xcode 7 GM?
>
> This sounds to me like an Xcode bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/247#issuecomment-139983993>
> .
>



-- 
Best Regards,
Sam
