### ISSUE TITLE
Could not find member 'subscript' (v1.8.3 Swift Compiler Error)

### ISSUE THREAD

**Issue by efremidze** [ParsePlatform/Parse-SDK-iOS-OSX#248]
v1.8.3 has a compiler error. I'm getting an error with the subscript in the line below. Not getting the error on v1.8.2.
`categories.map({ $0["name"] })`

**Comment by nlutsenko** [comment]
Hey @efremidze, thanks for the report. Which version of Xcode are you using? I've just tested with the latest stable aka Xcode 7 GM and the issue doesn't reproduce for me.

**Comment by efremidze** [comment]
I'm using Xcode 6 and swift 1.2. v1.8.3 must require swift 2.0. Thanks for swift response.
