### ISSUE TITLE
Calling deleteAll:error: on an empty array causes a crash

### ISSUE THREAD

**Issue by ghugues** [ParsePlatform/Parse-SDK-iOS-OSX#253]
This will cause a crash :
```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
	[PFObject deleteAll:@[] error:nil];
});
```
This is because `deleteAllInBackground:` returns a task whose result is not a boolean wrapped in an `NSNumber` when the array is empty.

**Comment by nlutsenko** [comment]
Indeed. Fixing in a bit.
