### ISSUE TITLE
Xcode 7 iOS 9 Migration issue Parse(PFACL.o)' does not contain bitcode

### ISSUE THREAD

**Issue by coolagrwal** [ParsePlatform/Parse-SDK-iOS-OSX#254]
While Migrating app from iOS 8.4 to 9.1 i am getting below exception on 1.8.3 Parse SDK. 

Does anybody have workaround from this.

Parse.framework/Parse(PFACL.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by nlutsenko** [comment]
This sounds very strange, since `1.8.3` is definitely compiled with Bitcode support and there are not warnings on Xcode 7 GM.
Are you using Xcode 7 GM or 7.1 beta?

Bitcode seems to be incompatible between different versions of Xcode, and 9.1 is not available yet, and you can't quite submit apps with support for it.

The issue also is going to be resolved if you are using Cocoapods.

**Comment by coolagrwal** [comment]
here is the screen shot with SDK & Xcode Build details.


![2015-09-14_16-38-55](https://cloud.githubusercontent.com/assets/13136559/9863710/9ca14252-5aff-11e5-9a3b-cd0a6a798d49.png)

**Comment by nlutsenko** [comment]
Hey @coolagrwal, you are running Xcode 7.0 beta 6, any chance you can upgrade to the latest Xcode 7 GM and let us know if it works?

**Comment by coolagrwal** [comment]
Good call, i will update to 7 GM and get back.

**Comment by coolagrwal** [comment]
@nlutsenko thanks for your help, it is not an issue in 7 GM, but it sucks overall iOS 9.0 & Xcode 7.0

**Comment by the-scott-davis** [comment]
@nlutsenko this is still an issue with Xcode 7 official release running against iOS 9 base SDK.... still throwing the enable bitcode message @coolagrwal Does anyone have a solution for this?

**Comment by nlutsenko** [comment]
@the-scott-davis can you attach a repro piece, I can't seem to reproduce an issue at all with the 1.8.4 release.

**Comment by nlutsenko** [comment]
@the-scott-davis I would suggest trying to clean your Xcode DerivedData.
If that still doesn't work - any chance you can try including the errors that you are getting here?

**Comment by coolagrwal** [comment]
Hi scott, have u download new sdk, and replaced old in ur build folder??

it worked for me on 7 gm

**Comment by the-scott-davis** [comment]
@nlutsenko and @coolagrwal i did a clean on the derived data and it fixed the problem. Thanks!

**Comment by nlutsenko** [comment]
Glad it helped!
Let us know if there is anything else we can help you with!

**Comment by pocketdeveloper** [comment]
@nlutsenko thanks for the help, but I still get a very similar issue on Xcode 7.0.1 and the latest Parse SDK.
Apparently PFPrimaryButton.o was built without full bitcode.

<img width="706" alt="screen shot 2015-10-08 at 10 36 42 pm" src="https://cloud.githubusercontent.com/assets/7883203/10385356/23598f50-6e0d-11e5-9358-50094ce2ab54.png">

**Comment by nlutsenko** [comment]
Hmm... Very strange. @pocketdeveloper any chance you can try using Cocoapods? That will get you building from source which should support bitcode from get-go.

Will look into it, though. Thanks!

**Comment by nlutsenko** [comment]
Yup, this indeed doesn't work on ParseUI 1.1.6.
Going to create an issue there, will link back in a moment.

**Comment by nlutsenko** [comment]
Apparently, there is one... https://github.com/ParsePlatform/ParseUI-iOS/issues/169
@pocketdeveloper, let's discuss it over there. Thanks!

**Comment by man00604** [comment]
Hi all,

I still have the same issue with the bit code and the same error as the originally post.

My Xcode version is 7.2.1 (7C1002) and the SDK bundle version is 1.12.0. I clear out the DerivedData and still have the problem. Can anyone help please?

/Parse(PFACL.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

Thanks

Terence
