### ISSUE TITLE
Adding a property named `state` to a PFObject causes a crash

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/Parse-SDK-iOS-OSX#26]
As I originally posted [here in the Google Forum] (https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/parse-developers/J28hap2qouQ/G6Xr3eRaAwAJ), if you have a `PFObject` subclass, where one of the property is named `state`, Parse will cause a crash, related to `PFObjectState` trying to set an object that is not a `PFObjectState` instance.

It was introduced, I guess, in version 1.7 or around that - as it wasn't crashing for me. To fix it temporarily, I needed to replace my property with `geographicState` instead of `state`.

To reproduce it, is very simple. One just needs to create a subclass of `PFObject`, add a property named `state` (in my case, it was a string), assign it and save.

I hope it's enough information. If not, I can try to reproduce and attach a stack strike.

If this behaviour is expected, that's ok - but it should be documented (maybe I didn't find this in the docs?). But it seems that I'm not the only one, according to the replies in the Google Forum.

**Comment by richardjrossiii** [comment]
This was an oversight when we refactored PFObject's state, and was fixed in 1.8.0.

**Comment by natanrolnik** [comment]
Ooops I just noticed while updating my pod.
I'm sorry!!
