### ISSUE TITLE
PFInstallation specific properties not set when calling [PFObject saveAllInBackground block]

### ISSUE THREAD

**Issue by claesjacobsson** [ParsePlatform/Parse-SDK-iOS-OSX#261]
My app sometimes saves an array of objects to Parse using [PFObject saveAllInBackground:objectsToSave block:^(BOOL succeeded, NSError *error)

This has been working fine, but since maybe a week or two some of the PFInstallation specific properties are not set. appIdentifier, appName, appVersion, badge, parseVersion, timeZone, localeIdentifier are all 'undefined'. All other properties are saved as expected. 

I solved this by calling [[PFInstallation currentDevice] saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) and now it works.

But this seems to be a bug. I tried rolling back to older versions of Parse iOS SDK but no change. So, possibly this is an issue server-side.

Thanks! Keep up the great work you are doing over at Parse :-)

**Comment by nlutsenko** [comment]
Hey @claesjacobsson, thanks for the report.
Looks like a bug to me, any chance you can point us to a Parse app that you are seeing this for?
The name would be perfect.

**Comment by claesjacobsson** [comment]
Can I send it to you by email? If so, what is your email?

Thanks!
Claes

**Comment by nlutsenko** [comment]
nlutsenko@fb.com

**Comment by nlutsenko** [comment]
Indeed a valid bug, just reproduced the code path locally. Fixing in a bit.

**Comment by claesjacobsson** [comment]
Great, thanks!

Claes
