### ISSUE TITLE
Pushes have not sent

### ISSUE THREAD

**Issue by kasnitski** [ParsePlatform/Parse-SDK-iOS-OSX#263]
Hi, guys.
The push notifications no more works for me.
I have more than 30 thousands users, but only some push notifications.
Please, fix this issue.

Thanks.

![screenshot 2015-09-15 13 13 12](https://cloud.githubusercontent.com/assets/849638/9874148/0c43de82-5bad-11e5-8fe6-0d3f26823f2c.png)

**Comment by nlutsenko** [comment]
Hey @kasnitski, thanks for the report.
It looks like a backend or configuration issue. Since we are using FB Bug Tool for those - could you file a bug at https://parse.com/help
