### ISSUE TITLE
Parse SDK crasheson 'ok'-click on versions higher than 1.8.2

### ISSUE THREAD

**Issue by enapos** [ParsePlatform/Parse-SDK-iOS-OSX#269]
When using Parse SDK 1.8.3 or higher the app crashes when pressing "ok" on the alertView.

The method showAlertWithTitle:message:etc. crashes because of a nil value as the 'completion' argument.

**Comment by richardjrossiii** [comment]
Valid bug. Thanks for reporting, submitting a PR shortly.
