### ISSUE TITLE
PFFacebookUtils (V4) initializeFacebookWithApplicationLaunchOptions crashes on 1.8.4

### ISSUE THREAD

**Issue by alonahar** [ParsePlatform/Parse-SDK-iOS-OSX#276]
When calling initializeFacebookWithApplicationLaunchOptions, the app crashes with the following issue: 
'+[PFUser registerAuthenticationProvider:]: unrecognized selector sent to class 0x1007d70f8'

Seems to be related to the following change made in the last SDK version:

Restructure authentication provider APIs on PFUser to be able to publicly support them. #136 

Please assist since version 1.8.3 is not available on Parse.com anymore.
Thanks.

**Comment by richardjrossiii** [comment]
What version is your ParseFacebookUtilsV4? If you're still using an old version of that, then yes, that will be broken, as we changed the authentication APIs in 1.8.4. Try updating ParseFacebookUtilsV4 to 1.8.4.

**Comment by alonahar** [comment]
Hi Richard, thanks for the reply.
As mentioned, I'm using version 1.8.4 via frameworks (and not via cocoa pods). 
The code I'm using in "application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?)" has not changed and worked so far. 
When I replaced the following framework files on my project, the app started crashing as described:

Bolts.framework (version 1.8.4)
Parse.framework (version 1.8.4)
ParseCrashReporting.framework (version 1.8.4)
ParseFacebookUtilsV4.framework (version 1.8.4)
ParseUI.framework (version 1.8.4)

The code is as follows:
ParseCrashReporting.enable()
Parse.setApplicationId(<applicationId>, clientKey: <clientKey>)
PFFacebookUtils.initializeFacebookWithApplicationLaunchOptions(launchOptions) --> CRASHED

As mentioned, this code has worked perfectly until upgrading to version 1.8.4
Kindly advise.

Thanks again.

**Comment by richardjrossiii** [comment]
I would strongly suggest clearing your Xcode's derived data, and checking your framework search paths, because I just tested ParseFacebookUtilsV4 both from the downloads page and from cocoa pods, and both work great with version 1.8.4.

My best guess is that Xcode is still linking to an old version of ParseFacebookUtilsV4, due to caching.

**Comment by alonahar** [comment]
Hey,
It did turn out to be a severe Xcode caching issue.

Thanks again for the assistance.

**Comment by nlutsenko** [comment]
:+1: Glad it worked!
 Let us know if there is anything we can help you with.
