### ISSUE TITLE
Issues with countObjects query with Xcode 7.0 and Parse 1.8.4

### ISSUE THREAD

**Issue by plv2002** [ParsePlatform/Parse-SDK-iOS-OSX#277]
I am trying to query data and when I try and use the nameOfMyQuery.countObjectsInBackgroundWithBlock I get the below error

'(Int, NSError?) -> Void' is not convertible to 'PFIntegerResultBlock?'

here is the snippet of code where i get the error.

let lookForAccountsQuery = PFQuery(className: "Accounts")
lookForAccountsQuery.whereKey("User", equalTo: (PFUser.currentUser()!.username)!)
        
        lookForAccountsQuery.countObjectsInBackgroundWithBlock {
            (count: Int, error: NSError?) -> Void in
            if error == nil {
                print("\(PFUser.currentUser()?.username) has \(count) accounts")
            }
        }

**Comment by richardjrossiii** [comment]
This is because `count` should be of type `Int32`, not `Int`.

**Comment by plv2002** [comment]
Awesome, that worked.  Didn't think to change that.  I had copied the documentation code and changed to match my query.

**Comment by richardjrossiii** [comment]
Hmm, I'll go take a look at the docs and make sure they get updated. Thanks for reporting.
