### ISSUE TITLE
PFQuery.findObjectsInBackgroundWithBlock causing Segmentation Fault: 11 in Swift 2

### ISSUE THREAD

**Issue by craiggrummitt** [ParsePlatform/Parse-SDK-iOS-OSX#280]
Title pretty much says it all. When migrating to Swift 2, I was getting a "Segmentation Fault: 11" error. After pulling apart my code line by line(grr!), I narrowed it down to a line containing the PFQuery method `findObjectsInBackgroundWithBlock`. I hence downloaded the sample Parse project, and pasted in the sample Swift code in the documentation under the title 'Basic Queries':

```
var query = PFQuery(className:"GameScore")
query.whereKey("playerName", equalTo:"Sean Plott")
query.findObjectsInBackgroundWithBlock {
  (objects: [AnyObject]?, error: NSError?) -> Void in

  if error == nil {
    // The find succeeded.
    println("Successfully retrieved \(objects!.count) scores.")
    // Do something with the found objects
    if let objects = objects as? [PFObject] {
      for object in objects {
        println(object.objectId)
      }
    }
  } else {
    // Log details of the failure
    println("Error: \(error!) \(error!.userInfo!)")
  }
}
```

Again, this causes the same error: "Segmentation Fault: 11"

You can find a project demonstrating the bug here:
https://github.com/craiggrummitt/ParseQueryBug

**Comment by nlutsenko** [comment]
Hey @craiggrummitt, the method signature had improved in Swift 2 with SDK 1.8.3.
It's `findObjectsInBackgroundWithBlock { (objects: [PFObject]?, error: NSError?) -> Void) in ... }` now.
aka replace `AnyObject` with `PFObject`.

The crash here is extremely sad and happens due to a bug in Xcode.
Let me know if it works.

**Comment by craiggrummitt** [comment]
Extraordinary that that causes the compiler to crash! Thanks, that's been driving me crazy for hours.

Not sure if you intend to update the docs to Swift 2 now(I assume that would be the plan), but this was my updated code for the example I quoted:

```
let query = PFQuery(className:"GameScore")
query.whereKey("playerName", equalTo:"Sean Plott")
query.findObjectsInBackgroundWithBlock {
    (objects:[PFObject]?, error:NSError?) -> Void in
    if error == nil {
        // The find succeeded.
        print("Successfully retrieved \(objects!.count) scores.")
        // Do something with the found objects
        if let objects = objects {
            for object in objects {
                print(object.objectId)
            }
        }
    } else {
        // Log details of the failure
        print("Error: \(error!) \(error!.userInfo)")
    }
}
```

**Comment by nlutsenko** [comment]
Right... We did update docs, but looks like few pieces were left out, will fix in more places.
Thanks!

**Comment by massoud12345** [comment]
Thanks a lot Craig for asking the question and posting your corrected code. Thank you nlutsenko as well. 
Spent a few hours on this bug.

**Comment by BrinkmanM** [comment]
Hi nlutsenko,

Im using xcode 7.0.1 and changed the code from [Anyobject]? to [PFObject]? but still receiving the same error.

**Comment by nlutsenko** [comment]
@BrinkmanM There should be something else then... Look for vague types, like AnyObject or [AnyObject] when you are using PFQuery.

**Comment by damtsnkff** [comment]
@craiggrummitt Thank you for asking and posting your code, I was in the exact same situation. I can now move forward. Thanks !

**Comment by alechoward** [comment]
@nlutsenko I'm also on swift 7.0. Still receiving the error after changing from Anyobject to PFObject. Did you find a solution

**Comment by nlutsenko** [comment]
Unfortunately, these swift compiler crashes are very hard to track down and I wish we could have fixed them from our end, but it's a compiler crash after all, so not really feasible.

From what I've seen so far - these are likely caused by generic type mismatch on object collections.
I would look for all usages of our SDK where there is an Array or Dictionary set as argument/return type. Then try taking out piece by piece (just commenting out), until you have non crashing compiler, then add half of these back and try again, then take another half and so on (comments + binary search + compile).

If anyone finds a common source of these - please comment here as it would be helpful for everyone.

**Comment by andreacannella** [comment]
let query = PFQuery(className:"GameScore")

            query.whereKey("playerName", equalTo:"Sean Plott")

            query.findObjectsInBackgroundWithBlock {

                (objects:[AnyObject]?, error:NSError?) -> Void in

                if error == nil {

                    // The find succeeded.

                    print("Successfully retrieved \(objects!.count) scores.")

                    // Do something with the found objects

                    print(objects)

                    if let objects = objects {

                        for object in objects {

                            print(object.objectId)

                        }

                    }

                } else {

                    // Log details of the failure

                    print("Error: \(error!) \(error!.userInfo)")

                }

            }

Try this! It works!

**Comment by andreacannella** [comment]
let query = PFQuery(className:"GameScore")

            query.whereKey("playerName", equalTo:"Sean Plott")

            query.findObjectsInBackgroundWithBlock {

                (objects:[AnyObject]?, error:NSError?) -> Void in

                if error == nil {

                    // The find succeeded.

                    print("Successfully retrieved \(objects!.count) scores.")

                    // Do something with the found objects

                    print(objects)

                    if let objects = objects {

                        for object in objects {

                            print(object.objectId)

                        }

                    }

                } else {

                    // Log details of the failure

                    print("Error: \(error!) \(error!.userInfo)")

                }

            }

Try this! It works!

**Comment by alechoward** [comment]
Hey @nlutsenko! It looks like the compiler was crashing. I ended up doing a fresh install of Swift 2.1 and deleting all cached installs. Runs perfectly. Thanks.

**Comment by nlutsenko** [comment]
@alechoward Glad you found the solution. :+1:

**Comment by polis80cy** [comment]
Really? I have to uninstall / reinstall XCode all together for this to work?

XCode 7 keeps giving me the segmentation fault for both objects:[AnyObject]? and objects:[PFObject]?

@alechoward Did you end up having to reinstall XCode for this to work?
