### ISSUE TITLE
Facebook Authorization dialog opens in Portrait mode instead of Landscape (iOS 9)

### ISSUE THREAD

**Issue by santiagopf** [ParsePlatform/Parse-SDK-iOS-OSX#282]
![capture](https://cloud.githubusercontent.com/assets/14338445/9967133/1fb16874-5e17-11e5-9faa-3276700d4adb.png)

Repro Steps:

1. Set the Application to support only Landscape Mode. 
My Configuration file:
     ` <key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>` 
2. Make sure that the User has already authorized the app
3. Make sure that there is no previous login session
4. Make sure that the device does not have Facebook App installed
5. Login using PFFacebookUtils logInInBackgroundWithReadPermissions
6. The Facebook Login Authorization dialog appears (Safari ViewController)

Expected Result:
The Facebook Login Authorization dialog is presented in Landscape mode instead of Portrait

Current Result:
The Facebook Login Authorization dialog is presented in Portrait mode, therefore the dialog buttons (OK and CANCEL) are out of the bounds of the screen. This happens due to the application running in Landscape mode.

FB SDK Version: 4.6.0
Parse SDK Version: 1.8.4
iOS Version: 9.0
Tested with iPad Air

Update: attached screenshot of the result in landscape mode

**Comment by nlutsenko** [comment]
Hey @santiagopf, this is a great report, thanks for the repro steps.
Any chance you can paste your view controller hierarchy when this happens?

Behind the scenes FBSDK is trying to present safari view controller on top of the front most view controller on the key window, thus presentation would be affected by the view controller hierarchy and how those behave.

**Comment by santiagopf** [comment]
We are currently using only one ViewController that handles the animations when the orientation of the device is changed from UIInterfaceOrientationLandscapeLeft to UIInterfaceOrientationLandscapeRight and vice versa.
The application itself is using a GLView to draw in fullscreen mode.

**Comment by nlutsenko** [comment]
I suppose that if you try to present bare empty SFSafariViewController on top of your front most view controller (not via FB/Parse), it will properly handle rotation?

**Comment by santiagopf** [comment]
Thats correct I created my own SFSafariViewController (code below) and it handles rotation properly.
`NSURL *url = [[NSURL alloc] initWithString:@"https://www.google.com.ar"];
SFSafariViewController *sfcontroller = [[SFSafariViewController alloc] initWithURL:url];
UIViewController *root_controller = [UIApplication     sharedApplication].keyWindow.rootViewController;
[root_controller presentViewController:sfcontroller animated:NO completion:nil];`

**Comment by nlutsenko** [comment]
The code that we are using to present this would be identical to:
```objc
NSURL *url = [[NSURL alloc] initWithString:@"https://www.google.com"];
SFSafariViewController *sfcontroller = [[SFSafariViewController alloc] initWithURL:url];
UIViewController *viewController = [UIApplication sharedApplication].keyWindow.rootViewController;
while (viewController.presentedViewController) {
  viewController = viewController.presentedViewController;
}
[viewController presentViewController:sfcontroller animated:NO completion:nil];
```
Any chance you can test this behavior?

**Comment by santiagopf** [comment]
I tested that behavior and the ViewController its working as expected, it opens in Landscape mode.

**Comment by nlutsenko** [comment]
Super strange... Any chance you can test behavior of FBSDK? The presentation happens outside of our code, so something like this would work and test the behavior.

```objc
    [[PFFacebookUtils facebookLoginManager] logInWithReadPermissions:@[ @"public_profile" ] fromViewController:nil handler:^(FBSDKLoginManagerLoginResult *result, NSError *error) {
        NSLog(@"%@ %@", result, error);
    }];
```
(also I would suggest retesting by passing a view controller from the method that you got above)

**Comment by santiagopf** [comment]
Hello, I tried with the ViewController being nil and using SFSafariViewController with the same result. The authorization dialog is shown in Portrait mode.
Should I assume that the issue is related to FBSDK then ?

**Comment by nlutsenko** [comment]
Yup. Seems like it.
Also - I believe the rotation is being inherited in most cases, meaning that I would double check the presented view controller in your code for potential issues.
