### ISSUE TITLE
Parse SDK (1.8.1) clould calls hangs (freezes) the App indefinitely

### ISSUE THREAD

**Issue by anoopnimkar** [ParsePlatform/Parse-SDK-iOS-OSX#283]
- We are using Parse iOS SDK 1.8.1 in our App and most of our Parse cloud interaction is through "PFCloud callFunctionInBackground:" API.
- After upgrading to 1.8.1, we have noticed that on some iOS devices app freezes(hangs) indefinitely. After app hangs, there's no user interaction possible till user dismisses the app and restarts. 
- Is this because of changes related with NSURLSession? Kindly give us some inputs on how we can fix this.

**Comment by nlutsenko** [comment]
Hey @anoopnimkar, thanks for the report.
We moved to use NSURLSession since 1.8.0, as well as it shouldn't matter in this case.

Any chance you can provide a stack trace for all threads when the application freezes? Unfortunately, since it's the first report of this sort, it's not really actionable for us since without a stack trace or a reproducible project/test/code snippet...

**Comment by nlutsenko** [comment]
Also, I tempted to suggest trying out the latest version of the SDK, which is 1.8.5 at this point.

**Comment by anoopnimkar** [comment]
Wow, thanks for quick response :+1:  This was reported by couple of our users, I'll try to get a stack-trace for this. Sure, will upgrade to 1.8.5 and try it out.
I had seen one issue before where app hangs when NSURLSession returns nil. Do you think that might be happening internally in Parse SDK?

**Comment by nlutsenko** [comment]
I am not sure if that is the case, as I've never seen it happening for us, both in unit as well as integration tests. There probably is something different going on here...

**Comment by anoopnimkar** [comment]
Upgrading to 1.8.5 seem to have resolved this issue. But we are still trying to understand what was going wrong as there was no stack trace and app just becomes unresponsive. I see that there's one more issue  reported for App Freezing, do you think its similar to ours? I mean something related to deadlocks. We are not using Facebook login though.

**Comment by nlutsenko** [comment]
Amount of changes between 1.8.1 and 1.8.5 is quite extensive, so I am not sure which commit specifically fixed the issue you were running into. Glad it is fixed for you guys!
