### ISSUE TITLE
Cannot find protocol declaration for 'PFVoid'

### ISSUE THREAD

**Issue by jacob-israel-turner** [ParsePlatform/Parse-SDK-iOS-OSX#285]
I'm trying to include the iOS SDK in my React Native app for push notifications.  I installed using CocoaPods and I get this error when trying to build:

<img width="256" alt="screen shot 2015-09-18 at 12 46 44" src="https://cloud.githubusercontent.com/assets/8698364/9958580/5e547d5a-5e03-11e5-9352-cbba89f2884f.png">

<img width="768" alt="screen shot 2015-09-18 at 12 44 34" src="https://cloud.githubusercontent.com/assets/8698364/9958570/479a24f2-5e03-11e5-99e0-d5c65ecc31bc.png">

The line above states that the code is used for testing.  If I comment it out, it builds just fine.

Any help would be appreciated.  Thanks.

**Comment by DmitryPashinskiy** [comment]
Me to

**Comment by jacob-israel-turner** [comment]
Looks like this was introduced in v1.8.5.  Rolling back to v1.8.4 fixes it.

**Comment by kincade71** [comment]
+1

**Comment by arielelkin** [comment]
:+1:

**Comment by nlutsenko** [comment]
Any chance you guys are using non Xcode 7, but 6.4?
should not be a problem on Xcode 7, since we have Travis running on every commit.

**Comment by jacob-israel-turner** [comment]
Turns out I'm on 6.4.  I'll upgrade and see if that fixes the issue.

**Comment by arielelkin** [comment]
We're on Xcode 6.4, but upgrading to 7 is not a good option at this stage because we're close to launch and don't have much time to migrate all our code base to Swift 2.0...

1.8.5 is therefore not backwards compatible with 1.8.4, so consider revising the tag, as it breaks the semantic versioning that pods are supposed to adhere to.

**Comment by nlutsenko** [comment]
@arielelkin @jacob-israel-turner @DmitryPashinskiy @kincade71
The fix was landed I updated the tag on the releases page, please update your Pods once again.

**Comment by andreykorolenko** [comment]
i still have this issue. Xcode 6.4, Parse 1.8.5

**Comment by arielelkin** [comment]
@andreykorolenko how are you including Parse in your Podfile? Does the issue go away for you if you modify your Podfile to include Parse like this:

`pod 'Parse' , :head`
