### ISSUE TITLE
PFDateFormatter seems to break another framework in my project

### ISSUE THREAD

**Issue by chadkouse** [ParsePlatform/Parse-SDK-iOS-OSX#287]
I'm using the latest parse SDK and the "entourage" framework from gracenote

Everything works fine until I login a user on parse.  From that point on the gracenote audio service won't initialize.

I've tracked it down to the sqlite connection opening here:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/61f68e9333206f0eebf15d5adab076a0ae7c4b71/Parse/Internal/PFDateFormatter.m#L49-L54

If I comment those lines out and then just return `[NSDate date]` from `dateFromString:` here:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/61f68e9333206f0eebf15d5adab076a0ae7c4b71/Parse/Internal/PFDateFormatter.m#L94

Then everything works (except of course my dates are wrong)

Interestingly enough if I return `[NSDate date]` from `dateFromString:` but I **don't** comment out the sqlite connection it still doesn't work.

Sadly I can't dig into the entourage framework as it's compiled code so I am asking you guys if you have any idea what might be happening here?

**Comment by richardjrossiii** [comment]
That's very strange. It should not break anything, as according to the sqlite documentation for memory database (https://www.sqlite.org/inmemorydb.html), every one opened should be a completely separate sqlite database.

The reason we use a sqlite database over `NSDateFormatter` there is actually performance, as sqlite is the fastest way to convert a date to a string that we know of. For your case, you could definitely replace it with a normal `NSDateFormatter`, and hopefully things are less broken.

I would definitely reach out to the devs of the entourage framework, and see what they have to say. If there's any issues that we caused, we'd very much like to know to prevent something like this from happening in the future.

**Comment by chadkouse** [comment]
@richardjrossiii Yeah I actually went and read that sqlite doc earlier today too and also tried changing it to a file db and a temp file db.. no luck... I have since made a fork and replaced it with your guys already available `preciseDateFormatter` since that seems to be the format my date objects are coming through as...  Thanks for getting back to me but yeah, it's a stumper...
