### ISSUE TITLE
Parse iOS SDK 1.8.5 - App freezes on iOS 9, Swift 2, CollectionView and TableView

### ISSUE THREAD

**Issue by fvimagination** [ParsePlatform/Parse-SDK-iOS-OSX#295]
Hi there,
we're experiencing a wired issue on the iOS SDK 1.8.4, everything works fine in the Home screen of our app, classes and data get loaded from a query and all records are shown in a CollectionView, but when we tap on it to push an new controller the app freezes and there are NO error messages in the XCode 7 console... the app just freezes.

We have tried to log the PFObject store in the CollectionView's cell and it returns well, here are the methods we're using (please note that they were working prfectly on iOS 8.4):

func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
    let cell = collectionView.dequeueReusableCellWithReuseIdentifier("PropertyCell", forIndexPath: indexPath) as! PropertyCell
    
    var propClass = PFObject(className: PROP_CLASS_NAME)
    propClass = self.recentArray[indexPath.row] as! PFObject
    
    // Get details
    let imageFile = propClass[PROP_IMAGE] as? PFFile
    imageFile?.getDataInBackgroundWithBlock { (imageData, error) -> Void in
        if error == nil {
            if let imageData = imageData {
                cell.pImage.image = UIImage(data:imageData)
    } } }

    if propClass[PROP_TITLE] != nil { cell.pTitle.text = "\(propClass[PROP_TITLE]!)"
    } else { cell.pTitle.text = "N/A"  }
    
    cell.layer.cornerRadius = 8

return cell
}
 
func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {
    var propClass = PFObject(className: PROP_CLASS_NAME)
    propClass = recentArray[indexPath.row] as! PFObject
 
    let pdVC =  storyboard!.instantiateViewControllerWithIdentifier("PropertyDetails") as! PropertyDetails
    pdVC.propObj = propClass
    navigationController?.pushViewController(pdVC, animated: true)
}

Accordingly to the App Transport Security policy, here's how we've updated the Info.plist file:
   <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
        <key>NSExceptionDomains</key>
        <dict>
            <key>files.parsetfss.com</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSExceptionMinimumTLSVersion</key>
                <string>TLSv1.1</string>
            </dict>
        </dict>
    </dict>

Anyway, even without such update in the Info.plist file, we were still getting data from our Parse database in the Home screen, all collectionView's cells look right, the only thing we cannot understand is why the app freezes when we tap on a cell to push a new controller (which stored an empry PFObject like this):

import Parse
class PropertyDetails: UIViewController {
...
    var propObj = PFObject(className: PROP_CLASS_NAME)
...

Hope somebody can help,
thanks!

**Comment by nlutsenko** [comment]
Hey @fvimagination, thanks for the report!
Any chance you can post a stack trace when the app freezes or attach a repro project?
It would help tremendously to identify and fix the exact issue you are running into...

**Comment by fvimagination** [comment]
We have installed the latest Parse iOS SDK version (1.8.5), and that's where we get the issue on XCode 7. 
How can we attach a repro project? Do you mean an XCode project?

**Comment by nlutsenko** [comment]
Yup. Something that we can run to see the problem for ourselves and be able to debug it.

**Comment by fvimagination** [comment]
All right, we'll pack a demo app soon and share a download link with you

**Comment by fvimagination** [comment]
Hi Nikita, here's a download link to a sample app, the Home controller loads smoothly some data from our Parse database and if you scroll down to the horizontal CollectionView you can see such data. 
Tap on a cell and the app will freeze: https://www.dropbox.com/s/pimc2jz2bs76lts/demo_Parse_issue_%20%23295.zip?dl=0

Thanks for your support!

**Comment by fvimagination** [comment]
Hi there @nlutsenko
had a chance to try the demo app mentioned in the above comment?
Thanks so much!

**Comment by fvimagination** [comment]
Hi there, just an update: we've updated XCode to 7.0.1 version, still using Parse SDK 1.8.5, same issue, and there's no stack trace in XCode, it just freezes again :(
Here'ìs the link to download a demo app that clearly presents this issue on CollectionViews: https://www.dropbox.com/s/pimc2jz2bs76lts/demo_Parse_issue_%20%23295.zip?dl=0
Hope you can help!

**Comment by nlutsenko** [comment]
Will take a look one of the first things tomorrow morning (it's about 3AM here in PST).
Thanks for bearing with us.

**Comment by fvimagination** [comment]
Thanks so much!

**Comment by nlutsenko** [comment]
Just looked into it...
Completely unrelated to Parse, but it's not the point.
Looks like a crazy Apple bug with storyboards and localization.
Deadlock due to inability to find a localized string for `detailsTxt` text view inside your Storyboards PropertyDetails.

Changing text to some other value (I used `dfljghsjdfkhgldsfgklsh`) or even removing text from that text view completely resolves the problem at it's entirety.

I might be wrong, but this specific change seems to resolve the whole thing, I suggest filing a bug report against Apple [here](https://bugreport.apple.com).

P.S. Here is a stack trace that hinted me where to look for this stuff:
```
#0	0x000000011032781c in objc_msgSend ()
#1	0x000000010e6e837a in -[NSString isEqualToString:] ()
#2	0x000000010e6e8344 in -[NSString isEqual:] ()
#3	0x000000010e22b73b in CFEqual ()
#4	0x000000010e3a6dd7 in CFBundleCopyLocalizedStringForLocalization ()
#5	0x000000010e6fa91d in -[NSBundle localizedStringForKey:value:table:] ()
#6	0x000000010e7464a7 in -[NSLocalizableString awakeAfterUsingCoder:] ()
#7	0x000000010f387d39 in UINibDecoderDecodeObjectForValue ()
#8	0x000000010f3879f4 in -[UINibDecoder decodeObjectForKey:] ()
#9	0x000000010e7467e3 in _NSReadMutableAttributedStringWithCoder ()
#10	0x000000010e7465fd in -[NSAttributedString initWithCoder:] ()
#11	0x000000010f387cbe in UINibDecoderDecodeObjectForValue ()
#12	0x000000010f3879f4 in -[UINibDecoder decodeObjectForKey:] ()
#13	0x000000010f772e6d in -[UITextView initWithCoder:] ()
#14	0x000000010f387cbe in UINibDecoderDecodeObjectForValue ()
#15	0x000000010f387e7f in UINibDecoderDecodeObjectForValue ()
#16	0x000000010f3879f4 in -[UINibDecoder decodeObjectForKey:] ()
#17	0x000000010eeae6f2 in -[UIView initWithCoder:] ()
#18	0x000000010f387cbe in UINibDecoderDecodeObjectForValue ()
#19	0x000000010f387e7f in UINibDecoderDecodeObjectForValue ()
#20	0x000000010f3879f4 in -[UINibDecoder decodeObjectForKey:] ()
#21	0x000000010eeae6f2 in -[UIView initWithCoder:] ()
#22	0x000000010eede2cf in -[UIScrollView initWithCoder:] ()
#23	0x000000010f387cbe in UINibDecoderDecodeObjectForValue ()
#24	0x000000010f3879f4 in -[UINibDecoder decodeObjectForKey:] ()
#25	0x000000010f1c3e93 in -[UIRuntimeConnection initWithCoder:] ()
#26	0x000000010f387cbe in UINibDecoderDecodeObjectForValue ()
#27	0x000000010f387e7f in UINibDecoderDecodeObjectForValue ()
#28	0x000000010f3879f4 in -[UINibDecoder decodeObjectForKey:] ()
#29	0x000000010f1c30a5 in -[UINib instantiateWithOwner:options:] ()
#30	0x000000010efae84d in -[UIViewController _loadViewFromNibNamed:bundle:] ()
#31	0x000000010efaf179 in -[UIViewController loadView] ()
#32	0x000000010efaf47c in -[UIViewController loadViewIfRequired] ()
#33	0x000000010efb5923 in -[UIViewController __viewWillAppear:] ()
#34	0x000000010efe518a in -[UINavigationController _startCustomTransition:] ()
#35	0x000000010eff47c7 in -[UINavigationController _startDeferredTransitionIfNeeded:] ()
#36	0x000000010eff567d in -[UINavigationController __viewWillLayoutSubviews] ()
#37	0x000000010f18d63d in -[UILayoutContainerView layoutSubviews] ()
#38	0x000000010eed511c in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
#39	0x000000010d48336a in -[CALayer layoutSublayers] ()
#40	0x000000010d477bd0 in CA::Layer::layout_if_needed(CA::Transaction*) ()
#41	0x000000010d477a4e in CA::Layer::layout_and_display_if_needed(CA::Transaction*) ()
#42	0x000000010d46c1d5 in CA::Context::commit_transaction(CA::Transaction*) ()
#43	0x000000010d4999f0 in CA::Transaction::commit() ()
#44	0x000000010ee1f1b6 in _UIApplicationHandleEventQueue ()
#45	0x000000010e2820a1 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#46	0x000000010e277fcc in __CFRunLoopDoSources0 ()
#47	0x000000010e277483 in __CFRunLoopRun ()
#48	0x000000010e276e98 in CFRunLoopRunSpecific ()
#49	0x0000000112a30ad2 in GSEventRunModal ()
#50	0x000000010ee24676 in UIApplicationMain ()
#51	0x000000010c1f3cdd in main at /Users/soul/Downloads/demo_Parse_issue_ #295/iResidence/AppDelegate.swift:13
#52	0x0000000110e6292d in start ()
#53	0x0000000110e6292d in start ()
```

**Comment by fvimagination** [comment]
perfect, thanks so much for your help!
