### ISSUE TITLE
Where can I download the *.framework binary for ParseFacebookUtils 1.8.5?

### ISSUE THREAD

**Issue by istx25** [ParsePlatform/Parse-SDK-iOS-OSX#296]
Where can I download the *.framework binary for ParseFacebookUtils 1.8.5? I have ran into some issues since running my app on iOS 9 and I am hoping upgrading from 1.7.1 will fix them. Thank you!

**Comment by istx25** [comment]
Specifically ParseFacebookUtilsV4. https://cocoapods.org/pods/ParseFacebookUtilsV4. I don't want to use CocoaPods though. I have an old version of the framework but I don't remember where I got it from.

**Comment by istx25** [comment]
found it. thanks for the help.

**Comment by nlutsenko** [comment]
;)

**Comment by istx25** [comment]
We are having some issues with the other framework though.

**Comment by istx25** [comment]
Could you help me @nlutsenko?

**Comment by istx25** [comment]
We're trying to use the new versions of the SDK and for iOS 9 it's saying that we need to do:

*** Terminating app due to uncaught exception 'InvalidOperationException', reason: 'fbauth2 is missing from your Info.plist under LSApplicationQueriesSchemes and is required for iOS 9.0’

We've already added:

<img width="468" alt="messages image 116037873" src="https://cloud.githubusercontent.com/assets/6799989/9977587/6d90cc6e-5ec2-11e5-95d2-a49ca3dd1487.png">

but we still get the same crash.

**Comment by istx25** [comment]
Not specifically related to Parse, but I can't figure it out. https://developers.facebook.com/docs/ios/ios9

**Comment by nlutsenko** [comment]
I would suggest cleaning derived data for your project as well as maybe editing the info.plist as source code (aka open in any text editor) to verify that the keys were added properly.

**Comment by istx25** [comment]
We've tried both. :/

**Comment by istx25** [comment]
Interestingly enough. We just fixed it.

**Comment by zsll** [comment]
Hi istx25, can you please share how your fixed this issue please? I am having the same issue now. Thanks.

**Comment by falsalloum** [comment]
Can you please share how you did it?

**Comment by RayanSaeed** [comment]
Can you please tell us the solution? How did you overcome this problem?

**Comment by istx25** [comment]
One of my friends had a copy of the framework binary. She also didn't know where she originally downloaded it from. Either way, here is a link to a zip with the framework: https://dl.dropboxusercontent.com/u/162794740/Source%20Code/ParseFacebookUtilsV4.framework.zip. Cheers!

**Comment by nlutsenko** [comment]
https://parse.com/downloads/ios/parse-library/latest - this is the official download package link.

**Comment by istx25** [comment]
There you have it. ¯\_(ツ)_/¯

**Comment by istx25** [comment]
Thanks @nlutsenko.

**Comment by horseshoe7** [comment]
surely this can't be the solution.  ditch cocoapods and use this framework binary?  is there another way?

**Comment by horseshoe7** [comment]
see here, section 3, whitelisting.   https://developers.facebook.com/docs/ios/ios9  Gotta add some stuff to the Info.plist

**Comment by phyominthu** [comment]
@nlutsenko Thanks for the link. But turns out it's not giving me the latest Parse version `1.14.2` right now. Instead it's giving me Parse `1.12.0` and the `ParseFacebookUtilsV4.framework` included in the ZIP is `1.11.0`.
