### ISSUE TITLE
PFUser does not have a member named subscript

### ISSUE THREAD

**Issue by dailenspencer** [ParsePlatform/Parse-SDK-iOS-OSX#298]
Hello, 

I seem to just be having an awful time when it comes to errors and parse. So today i was cleaning out my downloads folder and i deleted the parse ios sdk unzipped folder. This in turn, caused some errors in my xcode project. I redownloaded the sdk and added it back to my xcode project which shouldve solved it but now i have like 50+ errors. Each error says "PFUser does not have a member named subscript". My whole project was running perfectly yesterday so i know its not just the syntax or anything like that. The only help ive seen onine is to change the syntax but thats a pain to do it for 50 lines of code. It might be helpful to note that when i try to move the parse frameworks into my frameworks folder, all the frameworks turn red. But when they are sitting outside the frameworks folder everything is fine. Any advice? It sucks because my app is already on the app store and i have some important updates i want to make and i cant do anything because the build fails every time.

**Comment by dailenspencer** [comment]
Ended up solving the issue by rewriting the syntax for each error. Took a while but everything seems to be working fine

**Comment by nlutsenko** [comment]
Just for reference, the issue surfaces only if you are using Xcode 6.4. Since Xcode 7 was already released and available - I would strongly recommend updating to the latest Xcode.
