### ISSUE TITLE
PFFile TLS support - leftover servers?

### ISSUE THREAD

**Issue by Xotic1** [ParsePlatform/Parse-SDK-iOS-OSX#300]
Hello,

Is it possible that there are still some left-over servers in your farm that don't have the new support enabled?

I have a strange issue: in my "User" table I have some accounts that have been created over a year ago and some that are relatively new.  Each User record has a field called ProfileImage of type PFFile (essentially this is the thumbnail of the user's default profile image).

In the following code I load two users as a test case (old and new), and for each of them I attempt to get the profile image by doing something like this:

```
// here, self refers to the view controller
PFUser *user = (PFUser *)[self->activeUsers objectAtIndex:indexPath.row];
UIImage *image = nil;
PFFile *userPhoto = (PFFile *)[user objectForKey:kUserProfileImageKey];
if(userPhoto != nil)
    image = [UIImage imageWithData:[userPhoto getData]];
else
    image = [UIImage  imageNamed:@"imagePlaceholder"];
```

Strange thing is that for the "new" user record, [userPhoto getData] goes through just fine, but for the "old" user record, it crashes with the now infamous message: "App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure..."

Here is a link to a file that gives the error: http://files.parse.com/54efae95-2887-49ab-8d17-06975b7a897b/46870079-b8c0-4d57-88e2-abfefae550bf-Thumbnail.jpg

Thank you.

**Comment by nlutsenko** [comment]
Hey @xotic1, this sounds about right
`files.parse.com` domain name is not used anymore for new file uploads for quite a long time at this point.
There are 2 workaround that we have for this:
- reupload all files that are hosted at `files.parse.com`, so they are using the new domain/links
- add `files.parse.com` to the domain names that are exempt from [app transport security](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/)
aka add `NSExceptionAllowsInsecureHTTPLoads` for `files.parse.com` to `NSExceptionDomains` in your Info.plist (let me know if you want more help on this, as it could be quite misleading).

We can make files.parse.com domain available through https but that would require slightly more time to make this happen (let us know if you really want this and neither of the workarounds are an option).

**Comment by Xotic1** [comment]
Thank you for the quick response. As I understand now, only ```http://files.parsetfss.com/``` (aka "new" domain) is enabled, right?

Since there aren't that many old accounts in my app (most are new), I'll just ask the users to re-upload.  So, please don't worry about the old links. I'll just go ahead and implement the exception.  I saw some sample ```.plist``` entries on the web, but none that are conclusive (you'd read a statement work in some cases and not in others).  If you happen to have the correct version that works consistently, I'd very much appreciate you sharing it with me (and the rest of the community reading this).

One last question, what I've been also reading is that Apple may reject the app if one has this exception implemented.  Do you know if that's true?

Thank you in advance.

**Comment by nlutsenko** [comment]
files.parsetfss.com is indeed implemented to work through https with Parse SDK 1.8.3+
Here is a piece that you need to add to your info.plist (if it doesn't work, please paste your full info.plist here, so we can fix the full one):
```plist
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>facebook.com</key>
    <dict>
      <key>NSIncludesSubdomains</key>
      <true/>                
      <key>NSExceptionAllowsInsecureHTTPLoads</key>
      <true/>
    </dict>
  </dict>
</dict>
```

Apple rejections - this is case by case basis, but I don't foresee any problems with this, simply due to the fact that this is purely one domain, as well as it's quite well known.

**Comment by nlutsenko** [comment]
I am going to close this issue, but feel free to reopen if the problem remains unsolved or there is anything else I can help you with.

**Comment by Xotic1** [comment]
Thank you for the help!  You've been awesome!
