### ISSUE TITLE
Verify the Email when sign up App.

### ISSUE THREAD

**Issue by nhu2000** [ParsePlatform/Parse-SDK-iOS-OSX#304]
I have created the Parse Account 2 months ago.
For this server, Email Verification works well.
BTW, I have created the new Parse Account 2 days ago and tried the Email Verification.
Of course, I set the "Verify user Emails" term to "YES" on Setting.
BTW, this function does not work on new Parse Account.
What's up?
I need your help as soon as possible.

Thank you.

**Comment by nlutsenko** [comment]
Hey @nhu2000, since email verification happens on the backend (we are not sending anything from the client), could you file a bug report at the link mentioned above?

I am going to close down this issue, but feel free to reopen for any help/follow-up.
