### ISSUE TITLE
Parse SDK 1.8.5 Terminating app due to uncaught exception 

### ISSUE THREAD

**Issue by patpawasantanon** [ParsePlatform/Parse-SDK-iOS-OSX#307]
I got this error message in appDelegate

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PFUserAuthenticationController authenticationProviderForAuthType:]: unrecognized selector sent to instance 0x7fec8ac245f0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106bb8f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000106606deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106bc158d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000106b0ef7a ___forwarding___ + 970
	4   CoreFoundation                      0x0000000106b0eb28 _CF_forwarding_prep_0 + 120
	5   MyApp                               0x000000010158417a +[PFFacebookUtils initializeFacebookWithUrlShemeSuffix:] + 223
	6   MyApp                               0x00000001013e7782 _TFC5MyApp11AppDelegate11applicationfS0_FTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVSs10DictionaryCSo8NSObjectPSs9AnyObject____Sb + 1314
	7   MyApp                               0x00000001013eabd3 _TToFC5MyApp11AppDelegate11applicationfS0_FTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVSs10DictionaryCSo8NSObjectPSs9AnyObject____Sb + 179
	8   UIKit                               0x0000000104db74ca -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 272
	9   UIKit                               0x0000000104db8670 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3415
	10  UIKit                               0x0000000104dbee15 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1755
	11  UIKit                               0x0000000104dbbff0 -[UIApplication workspaceDidEndTransaction:] + 188
	12  FrontBoardServices                  0x00000001083ce7ac -[FBSSerialQueue _performNext] + 192
	13  FrontBoardServices                  0x00000001083ceb1a -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	14  CoreFoundation                      0x0000000106ae50a1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	15  CoreFoundation                      0x0000000106adafcc __CFRunLoopDoSources0 + 556
	16  CoreFoundation                      0x0000000106ada483 __CFRunLoopRun + 867
	17  CoreFoundation                      0x0000000106ad9e98 CFRunLoopRunSpecific + 488
	18  UIKit                               0x0000000104dbb98d -[UIApplication _run] + 402
	19  UIKit                               0x0000000104dc0676 UIApplicationMain + 171
	20  MyApp                               0x00000001013ecb0d main + 109
	21  libdyld.dylib                       0x0000000107d6c92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any suggestion?

**Comment by nlutsenko** [comment]
Looks like you are using an old ParseFaceboolUtils with the latest SDK.
Can you try updating it to the latest and run through this once again?

**Comment by patpawasantanon** [comment]
I use ParseFaceboolUtils 1.8.3 is that latest?

**Comment by nlutsenko** [comment]
The latest would be 1.8.5 aka the same version as the main SDK.

**Comment by patpawasantanon** [comment]
Fixed. Thanks

**Comment by math-miki** [comment]
I got almost same error massage, too.
Could you tell me how to solve it?
I am using ParseSDK1.8.5 and XCode7.0

**Comment by nlutsenko** [comment]
Use latest versions of both Parse and ParseFacebookUtils.
