### ISSUE TITLE
Array of PFObjects from cloud code may have trouble processing dates?

### ISSUE THREAD

**Issue by doffing81** [ParsePlatform/Parse-SDK-iOS-OSX#309]
iOS:
``` objective-c
[PFCloud callFunctionInBackground:@"updateWeekly" withParameters:@{} block:^(NSArray *objects, NSError *error) {
            if (!error) {
                NSLog(@"objects %@", objects);
            } else {
                NSLog(@"error");
            }
        }];
```

Cloud Code:
``` javascript
Parse.Cloud.define("updateWeekly", function(request, response) {
	var dateToday = new Date();
	var query = new Parse.Query("Future_Sweeps");
	query.ascending("endDate");
	query.greaterThanOrEqualTo("endDate", dateToday);
	query.find({
    success: function(results) {
      response.success(results);
    },
    error: function() {
      response.error("ERROR!!!???!!!");
    }
  });
});
```

LOG:
2015-09-23 08:00:12.456 Inline-Sweeps[31248:4386372] -[__NSDate UTF8String]: unrecognized selector sent to instance 0x7fb21a5d4920
2015-09-23 08:00:12.574 Inline-Sweeps[31248:4386372] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDate UTF8String]: unrecognized selector sent to instance 0x7fb21a5d4920'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109cf7c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000109990bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000109cff0ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000109c5513c ___forwarding___ + 988
	4   CoreFoundation                      0x0000000109c54cd8 _CF_forwarding_prep_0 + 120
	5   Inline-Sweeps                       0x0000000108357678 __34-[PFDateFormatter dateFromString:]_block_invoke + 38
	6   libdispatch.dylib                   0x000000010be86614 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x000000010be6c002 _dispatch_barrier_sync_f_invoke + 365
	8   Inline-Sweeps                       0x0000000108357587 -[PFDateFormatter dateFromString:] + 244
	9   Inline-Sweeps                       0x000000010830b3a2 -[PFObjectState setUpdatedAtFromString:] + 87
	10  Inline-Sweeps                       0x000000010832cd64 -[PFMutableObjectState setUpdatedAtFromString:] + 39
	11  Inline-Sweeps                       0x0000000108317580 __69-[PFObject(Private) _mergeFromServerWithResult:decoder:completeData:]_block_invoke + 181
	12  CoreFoundation                      0x0000000109c37656 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 102
	13  CoreFoundation                      0x0000000109c3755c -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 204
	14  Inline-Sweeps                       0x000000010831737d -[PFObject(Private) _mergeFromServerWithResult:decoder:completeData:] + 281
	15  Inline-Sweeps                       0x0000000108316e48 -[PFObject(Private) _mergeAfterFetchWithResult:decoder:completeData:] + 115
	16  Inline-Sweeps                       0x0000000108313edc +[PFObject(Private) _objectFromDictionary:defaultClassName:completeData:decoder:] + 248
	17  Inline-Sweeps                       0x000000010836d15e -[PFDecoder decodeDictionary:] + 1355
	18  Inline-Sweeps                       0x000000010836d5a5 -[PFDecoder decodeObject:] + 130
	19  Inline-Sweeps                       0x000000010836d474 -[PFDecoder decodeArray:] + 271
	20  Inline-Sweeps                       0x000000010836d5a5 -[PFDecoder decodeObject:] + 130
	21  Inline-Sweeps                       0x0000000108367c6a __80-[PFCloudCodeController callCloudCodeFunctionAsync:withParameters:sessionToken:]_block_invoke_2 + 126
	22  Inline-Sweeps                       0x000000010838c24c __62-[BFTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 83
	23  Inline-Sweeps                       0x000000010838bae9 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 86
	24  Inline-Sweeps                       0x000000010838ca4c __29+[BFExecutor defaultExecutor]_block_invoke_2 + 331
	25  Inline-Sweeps                       0x000000010838cf73 -[BFExecutor execute:] + 65
	26  Inline-Sweeps                       0x000000010838ba69 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 138
	27  Inline-Sweeps                       0x000000010838b67c -[BFTask runContinuations] + 396
	28  Inline-Sweeps                       0x000000010838af32 -[BFTask trySetResult:] + 151
	29  Inline-Sweeps                       0x000000010838ae6d -[BFTask setResult:] + 17
	

Inline-Sweeps`__62-[BFTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke:
    0x10838c1f9 <+0>:   pushq  %rbp
    0x10838c1fa <+1>:   movq   %rsp, %rbp
    0x10838c1fd <+4>:   pushq  %r14
    0x10838c1ff <+6>:   pushq  %rbx
    0x10838c200 <+7>:   movq   %rdi, %r14
    0x10838c203 <+10>:  movq   %rsi, %rdi
    0x10838c206 <+13>:  callq  *0x2bf9c(%rip)            ; (void *)0x00000001099a4930: objc_retain
    0x10838c20c <+19>:  movq   %rax, %rbx
    0x10838c20f <+22>:  movq   0x63dc2(%rip), %rsi       ; "isFaulted"
    0x10838c216 <+29>:  movq   %rbx, %rdi
    0x10838c219 <+32>:  callq  *0x2bf79(%rip)            ; (void *)0x00000001099a7000: objc_msgSend
    0x10838c21f <+38>:  testb  %al, %al
    0x10838c221 <+40>:  jne    0x10838c237               ; <+62> at BFTask.m:406
    0x10838c223 <+42>:  movq   0x616ce(%rip), %rsi       ; "isCancelled"
    0x10838c22a <+49>:  movq   %rbx, %rdi
    0x10838c22d <+52>:  callq  *0x2bf65(%rip)            ; (void *)0x00000001099a7000: objc_msgSend
    0x10838c233 <+58>:  testb  %al, %al
    0x10838c235 <+60>:  je     0x10838c242               ; <+73> at BFTask.m:408
    0x10838c237 <+62>:  movq   %rbx, %rdi
    0x10838c23a <+65>:  callq  *0x2bf68(%rip)            ; (void *)0x00000001099a4930: objc_retain
    0x10838c240 <+71>:  jmp    0x10838c254               ; <+91> at BFTask.m:408
    0x10838c242 <+73>:  movq   0x20(%r14), %rdi
    0x10838c246 <+77>:  movq   %rbx, %rsi
    0x10838c249 <+80>:  callq  *0x10(%rdi)
    0x10838c24c <+83>:  movq   %rax, %rdi                           // PROBLEM LINE
    0x10838c24f <+86>:  callq  0x10838d2ca               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10838c254 <+91>:  movq   %rax, %r14
    0x10838c257 <+94>:  movq   %rbx, %rdi
    0x10838c25a <+97>:  callq  *0x2bf40(%rip)            ; (void *)0x00000001099a49b0: objc_release
    0x10838c260 <+103>: movq   %r14, %rdi
    0x10838c263 <+106>: popq   %rbx
    0x10838c264 <+107>: popq   %r14
    0x10838c266 <+109>: popq   %rbp
    0x10838c267 <+110>: jmp    0x10838d24c               ; symbol stub for: objc_autoreleaseReturnValue

**Comment by doffing81** [comment]
Updated SDK... all good

**Comment by nlutsenko** [comment]
Woohoo!
