### ISSUE TITLE
Parse SDK 1.8.5 crash  Terminating app due to uncaught exception 

### ISSUE THREAD

**Issue by mohitngm** [ParsePlatform/Parse-SDK-iOS-OSX#310]
i got this crash when internet is off

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: error)'

PFURLSessionJSONDataTaskDelegate' s in 

- (void)_taskDidFinish {
      .................
        errorDictionary[@"error"] = [self.error localizedDescription]; 
      // it crashes here  as [self.error localizedDescription] is nil
     
}

it can be reproduced by turn off internet  
Error object: 

Error Domain=NSURLErrorDomain Code=-1001 "(null)" UserInfo=0x14ed5580 {NSErrorFailingURLKey=https://api.parse.com/1/classes/_Installation/****, NSErrorFailingURLStringKey=https://api.parse.com/1/classes/_Installation/***, NSUnderlyingError=Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)"}

**Comment by nlutsenko** [comment]
Hey @mohitngm, thanks for the report.
Will look into it, thanks.

**Comment by nlutsenko** [comment]
Valid potential problem, pull request is coming.
