### ISSUE TITLE
iOS beforeSave issue

### ISSUE THREAD

**Issue by avagarwal** [ParsePlatform/Parse-SDK-iOS-OSX#311]
The beforeSave trigger seems to be giving an issue when I update the table it from iOS, it is working perfectly in Android (java). The code is show below. What could be the issue?

obj[@"commentText"]=self.textField.text;
obj[@"userId"] = [DataHolder DataHolderSharedInstance].userObject;
obj[@"yakId"] = self.objPost;
obj[@"likes"] = [NSArray array];
obj[@"dislikes"] = [NSArray array];
obj[@"imageId"] = [NSNumber numberWithInt:-1];

__block DetailsViewController *weakSelf = self;

[obj saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {

}];

==================================================================

Parse.Cloud.beforeSave("comment", function (request, response) {

    var imageId = request.object.get("imageId");

    if (imageId <= 0)        //image id set to max
    {
        //do some processing
         request.object.set("imageId", newid + 1);
         response.success();
    }
    else
    {
        response.success();
    }
}

======= Log Entry ================================================

I2015-09-23T10:22:15.255Z]v10 before_save triggered for comment for user TIS8ZZWw13:
  Input: {"original":null,"update":{"ACL":{"*":{"read":true,"write":true},"TIS8ZZWw13":{"read":true,"write":true}},"commentText":"test comment from ipad","dislikes":[],"imageId":-1,"likes":[],"userId":{"__type":"Pointer","className":"user","objectId":"IUdeepHERj"},"yakId":{"__type":"Pointer","className":"yak","objectId":"MRV35i24Bc"}}}
  Result: Update changed to {}

**Comment by samwarfield** [comment]
I started getting this issue if I updated past JS SDK 1.5.0... What version are you using?

**Comment by avagarwal** [comment]
Using the latest version

**Comment by nlutsenko** [comment]
Hey guys, try using previous version of the JS SDK aka 1.5, and let us know if it works for you.
We are tracking few of these across the board, and I am not sure we have a problem in iOS/OSX SDK, since we didn't change any logic that might be related to `beforeSave` hooks.

**Comment by samwarfield** [comment]
1.5.0 is working for me… I tried every version after and it would create a new empty object instead of updating the original.

**Comment by avagarwal** [comment]
Will try 1.5.0. Not sure why such an issue would slip through so many
versions.

**Comment by nlutsenko** [comment]
@avagarwal, did 1.5 work good for it?
Since JS SDK is open source and the issue seems to be not on iOS specifically - I would suggest filing an issue on the Parse JS SDK repo [here](https://github.com/ParsePlatform/Parse-SDK-JS)

Let me know if there is anything I can help you with though.
