### ISSUE TITLE
iOS: Object Pinning takes too much time 

### ISSUE THREAD

**Issue by PSIPhone** [ParsePlatform/Parse-SDK-iOS-OSX#318]
Below is the simple code i have, after few hundreds of pinned objects, new object take more than 12 seconds to pin. 

-(void)saveToparse{
    PFQuery *query= [PFQuery queryWithClassName:@"cashregister"];
    [query fromPinWithName:self.registerId];
    [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
        if (objects.count==1) {
            PFObject *object = [objects objectAtIndex:0];
            [self setvalue:object];
            [object saveEventually];
            [object pinInBackgroundWithName:self.registerId];
        }
        else{
            PFObject* object = [PFObject objectWithClassName:@"cashregister"];
            [self setvalue:object];
            [object saveEventually];
            [object pinInBackgroundWithName:self.registerId];
        }
    }
     ];
}

-(void)setvalue:(PFObject *)object{
    [object setObject:self.registerId forKey:@"register_id"];
    [object setObject:[NSNumber numberWithFloat:self.amountIn] forKey:@"amount_in"];
    [object setObject:[NSNumber numberWithFloat:self.amountOut] forKey:@"amount_out"];
    [object setObject:[NSNumber numberWithInt:self.transactionType] forKey:@"transactiontype"];
    [object setObject:[NSNumber numberWithFloat:self.total] forKey:@"total"];
    [object setObject:self.date forKey:@"date"];
    [object setObject:self.username forKey:@"username"];
}

**Comment by nlutsenko** [comment]
Hey @PSIPhone, this sounds about right.
A general recommendation - use smaller pins, since there is no limit on the total pin count.

We are also tracking overall LDS (local datastore) performance improvements in #32, and there is some information there around this.

**Comment by PSIPhone** [comment]
Ohh, so if my rows in a table is 10k then will it increase time to pin an object?

**Comment by nlutsenko** [comment]
Yup. We have a somewhat linear dependency on number of objects in a pin, so yes - 10k objects will slow things down.

**Comment by PSIPhone** [comment]
How much time it will take to pin an object if i have 10k rows in a customer table with 2 pointers and 5 string fields?

**Comment by PSIPhone** [comment]
Hope this fixes in 1.9.0 else i will have to drop parse.
