### ISSUE TITLE
PFObject.state causes crash

### ISSUE THREAD

**Issue by craiggrummitt** [ParsePlatform/Parse-SDK-iOS-OSX#33]
If a PFObject contains a variable called 'state' saving this object causes a crash.
You can find a sample bare bones project based on Parse Starter Project(v1.8) illustrating the bug here:
https://github.com/craiggrummitt/ParseStateBug

Error in console:
NSInvalidArgumentException', reason: '-[Swift._NSContiguousString isDeleted]: unrecognized selector sent to instance ...'

**Comment by nlutsenko** [comment]
Hey @craiggrummitt thanks for reporting this with a repro.
Will investigate further and let you know what I find.

**Comment by richardjrossiii** [comment]
Stack trace, for easier debugging:

<pre>
(
	0   CoreFoundation                      0x00000001015869b5 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000103303deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010158efdd -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00000001014dc9fa ___forwarding___ + 970
	4   CoreFoundation                      0x00000001014dc5a8 _CF_forwarding_prep_0 + 120
	5   ParseStarterProject-Swift           0x0000000100c0215b -[PFObject(Private) isDirty:] + 111
	6   ParseStarterProject-Swift           0x0000000100c0767a __31-[PFObject(Private) saveAsync:]_block_invoke598 + 91
	7   ParseStarterProject-Swift           0x0000000100c78da9 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 86
	8   ParseStarterProject-Swift           0x0000000100c79d0c __29+[BFExecutor defaultExecutor]_block_invoke_2 + 331
	9   ParseStarterProject-Swift           0x0000000100c7a233 -[BFExecutor execute:] + 65
	10  ParseStarterProject-Swift           0x0000000100c78d29 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 138
	11  ParseStarterProject-Swift           0x0000000100c7893c -[BFTask runContinuations] + 396
	12  ParseStarterProject-Swift           0x0000000100c781f2 -[BFTask trySetResult:] + 151
	13  ParseStarterProject-Swift           0x0000000100c7812d -[BFTask setResult:] + 17
	14  ParseStarterProject-Swift           0x0000000100c76276 -[BFTaskCompletionSource setResult:] + 79
	15  ParseStarterProject-Swift           0x0000000100c79071 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_3 + 306
	16  ParseStarterProject-Swift           0x0000000100c78da9 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 86
	17  ParseStarterProject-Swift           0x0000000100c79d0c __29+[BFExecutor defaultExecutor]_block_invoke_2 + 331
	18  ParseStarterProject-Swift           0x0000000100c7a233 -[BFExecutor execute:] + 65
	19  ParseStarterProject-Swift           0x0000000100c78d29 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 138
	20  ParseStarterProject-Swift           0x0000000100c7893c -[BFTask runContinuations] + 396
	21  ParseStarterProject-Swift           0x0000000100c781f2 -[BFTask trySetResult:] + 151
	22  ParseStarterProject-Swift           0x0000000100c7812d -[BFTask setResult:] + 17
	23  ParseStarterProject-Swift           0x0000000100c76276 -[BFTaskCompletionSource setResult:] + 79
	24  ParseStarterProject-Swift           0x0000000100c78e7c __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 297
	25  ParseStarterProject-Swift           0x0000000100c79d0c __29+[BFExecutor defaultExecutor]_block_invoke_2 + 331
	26  ParseStarterProject-Swift           0x0000000100c7a233 -[BFExecutor execute:] + 65
	27  ParseStarterProject-Swift           0x0000000100c78d29 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 138
	28  ParseStarterProject-Swift           0x0000000100c7893c -[BFTask runContinuations] + 396
	29  ParseStarterProject-Swift           0x0000000100c784f6 -[BFTask trySetException:] + 178
	30  ParseStarterProject-Swift           0x0000000100c78416 -[BFTask setException:] + 17
	31  ParseStarterProject-Swift           0x0000000100c7635a -[BFTaskCompletionSource setException:] + 79
	32  ParseStarterProject-Swift           0x0000000100c78f13 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 448
	33  ParseStarterProject-Swift           0x0000000100c79d0c __29+[BFExecutor defaultExecutor]_block_invoke_2 + 331
	34  ParseStarterProject-Swift           0x0000000100c7a233 -[BFExecutor execute:] + 65
	35  ParseStarterProject-Swift           0x0000000100c78d29 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 138
	36  ParseStarterProject-Swift           0x0000000100c7893c -[BFTask runContinuations] + 396
	37  ParseStarterProject-Swift           0x0000000100c781f2 -[BFTask trySetResult:] + 151
	38  ParseStarterProject-Swift           0x0000000100c76409 -[BFTaskCompletionSource trySetResult:] + 79
	39  ParseStarterProject-Swift           0x0000000100c0fd82 __56-[PFSQLiteDatabaseController openDatabaseWithNameAsync:]_block_invoke_2 + 162
	40  ParseStarterProject-Swift           0x0000000100c78da9 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 86
	41  ParseStarterProject-Swift           0x0000000100c79d0c __29+[BFExecutor defaultExecutor]_block_invoke_2 + 331
	42  ParseStarterProject-Swift           0x0000000100c7a233 -[BFExecutor execute:] + 65
	43  ParseStarterProject-Swift           0x0000000100c78d29 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 138
	44  ParseStarterProject-Swift           0x0000000100c7893c -[BFTask runContinuations] + 396
	45  ParseStarterProject-Swift           0x0000000100c781f2 -[BFTask trySetResult:] + 151
	46  ParseStarterProject-Swift           0x0000000100c7812d -[BFTask setResult:] + 17
	47  ParseStarterProject-Swift           0x0000000100c76276 -[BFTaskCompletionSource setResult:] + 79
	48  ParseStarterProject-Swift           0x0000000100c79071 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_3 + 306
	49  ParseStarterProject-Swift           0x0000000100c78e66 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 275
	50  libdispatch.dylib                   0x0000000103e4bfad _dispatch_call_block_and_release + 12
	51  libdispatch.dylib                   0x0000000103e6c4bb _dispatch_client_callout + 8
	52  libdispatch.dylib                   0x0000000103e52a3c _dispatch_queue_drain + 2215
	53  libdispatch.dylib                   0x0000000103e51f5d _dispatch_queue_invoke + 601
	54  libdispatch.dylib                   0x0000000103e54ba6 _dispatch_root_queue_drain + 1420
	55  libdispatch.dylib                   0x0000000103e54615 _dispatch_worker_thread3 + 111
	56  libsystem_pthread.dylib             0x00000001041b472f _pthread_wqthread + 1129
	57  libsystem_pthread.dylib             0x00000001041b2409 start_wqthread + 13
)
</pre>

**Comment by richardjrossiii** [comment]
Found the issue. It is related to our automatic inferring of instance variables for subclassed objects. For some backwards compatibility reason, if you have an instance variable on your `PFObject` subclass with the same name (or the name + underscore) as one of your properties, we make the `@dynamic` implementation of that property set the iVar, not the PFObject dictionary.

Now, normally this isn't an issue. It works in 99% of all cases. However, in the case of state, we have an iVar on `PFObject` named `_state`, which causes our method resolution (found in `PFObjectSubclassingController`) to write to the `_state` iVar instead of the object dictionary. PR with a fix incoming shortly.

**Comment by richardjrossiii** [comment]
Should be fixed in #35.
