### ISSUE TITLE
PFTwitterUtils logInWithBlock crashes if twitter not setup on iphone

### ISSUE THREAD

**Issue by 3bodar** [ParsePlatform/Parse-SDK-iOS-OSX#330]
[xcode 7, yosemite, ios 9]

I have a problem similar to [issue 153](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/153) but that solution does not work for me. My twitter app has a callback url and if I call PFTwitterUtils.logInWithBlock, using parse sdk 1.7.1, everything works ok. 1.8.5 however results in a crash (as does 1.8.2 used by the poster of issue 153).

To reproduce:

* get the sdk [parse-library-1.8.5.zip](https://parse.com/downloads/ios/parse-library/1.8.5) and the blank project [parse-starter-project-1.8.5.zip](https://parse.com/downloads/ios/parse-starter-project/1.8.5)
* open `ParseStarterProject-Swift/ParseStarterProject-Swift.xcodeproj` and add to the project's 'Linked Frameworks and Libraries': `ParseTwitterUtils.framework` (from the the sdk zip), `Accounts.framework`, `Social.framework`
* `import ParseTwitterUtils` into `AppDelegate.swift` and `ViewController.swift`
* in `AppDelegate.swift` uncomment the line
```
    Parse.setApplicationId("..." , clientKey: "...")
```
and add right after it:
```
 PFTwitterUtils.initializeWithConsumerKey("...", consumerSecret: "...")
```
* in `ViewController.swift` `viewDidLoad()` add 
```
PFTwitterUtils.logInWithBlock ({ (user: PFUser?, error: NSError?) -> Void in
    print("twitter callback")
})
```
* if necessary, `Simulator -> Reset Content and Settings...` , to make sure twitter is not set up
* run

Result: 
```
2015-09-26 04:45:49.783 ParseStarterProject-Swift[3047:2008114] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107b5cf65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000109b8edeb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107a5ff5e -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 318
	3   CoreFoundation                      0x0000000107a722ab +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	4   ParseStarterProject-Swift           0x0000000107013d99 -[PF_Twitter _showWebViewDialogAsync:requestSecret:] + 206
	5   ParseStarterProject-Swift           0x00000001070159ed __38-[PF_Twitter _performWebViewAuthAsync]_block_invoke_2 + 232
	6   libdispatch.dylib                   0x000000010edf1ef9 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000010ee1249b _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010edfa34b _dispatch_main_queue_callback_4CF + 1738
	9   CoreFoundation                      0x0000000107abd3e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	10  CoreFoundation                      0x0000000107a7e939 __CFRunLoopRun + 2073
	11  CoreFoundation                      0x0000000107a7de98 CFRunLoopRunSpecific + 488
	12  GraphicsServices                    0x000000010ae88ad2 GSEventRunModal + 161
	13  UIKit                               0x0000000108717676 UIApplicationMain + 171
	14  ParseStarterProject-Swift           0x000000010700f68d main + 109
	15  libdyld.dylib                       0x000000010ee4692d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by nlutsenko** [comment]
Just tested with the latest SDK in [ParseUI](https://github.com/parseplatform/parseui-ios) demo project.
It seems to work great...
Any chance you don't have a valid URL set in `callback url` field of your twitter app settings?

**Comment by 3bodar** [comment]
@nlutsenko , thanks for looking into it, just figured out what it is - being new to twitter apps, I had decided to do as 'recommended' (screenshot), so I had checked the 'Enable Callback Locking ...' checkbox, thus shooting myself in the foot.

![screen shot 2015-09-26 at 10 47 08](https://cloud.githubusercontent.com/assets/14845480/10116913/343d0a20-643c-11e5-898b-9bb9e10fbdc9.png)

As soon as a clear that checkbox (and save the settings) everything's ok, as soon as I check it - crash.

I'd be happy to fix this and submit a patch when the PFTwitterUtils gets open-sourced...

**Comment by nlutsenko** [comment]
Great, glad you found the source of the problem.
PFTwitterUtils is coming to open source very very shortly (heads down working on making it happen right now).

Let me know if there is anything else I can help you in the meantime.

**Comment by rinyfo4** [comment]
I'm having a similar issue. I downloaded both files that @3bodar posted and in my ParseStarterProject I added the 'import ParseTwitterUtils' in both the AppDelegate.swift and the ViewController.swift. 

I added the libraries mentiond by @3bodar. Now there's an error that says: "No such module 'ParseTwitterUtils' in both the AppDelegate and ViewController. 

I have also tried to adding a bridging header by importing     '#import <ParseTwitterUtils/PFTwitterUtils.h>' and  ' #import <ParseTwitterUtils/PF_Twitter.h>' and the error that appears is this: 

    CompileSwift normal x86_64 /Users/luka/Downloads/parse-starter-project-1/ParseStarterProject-    Swift/ParseStarterProject/ViewController.swift
    cd /Users/luka/Downloads/parse-starter-project-1/ParseStarterProject-Swift
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/luka/Downloads/parse-starter-project-1/ParseStarterProject-Swift/ParseStarterProject/ViewController.swift /Users/luka/Downloads/parse-starter-project-1/ParseStarterProject-Swift/ParseStarterProject/AppDelegate.swift -target x86_64-apple-ios7.0 -enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -I /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Products/Debug-iphonesimulator -F /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Products/Debug-iphonesimulator -F /Users/luka/Downloads/parse-starter-project-1/ParseStarterProject-Swift -g -import-objc-header /Users/luka/Downloads/parse-starter-project-1/ParseStarterProject-Swift/ParseStarterProject/ParseStarterProject-Swift-Bridging-Header.h -module-cache-path /Users/luka/Library/Developer/Xcode/DerivedData/ModuleCache -serialize-debugging-options -Xcc -I/Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/ParseStarterProject-Swift-generated-files.hmap -Xcc -I/Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/ParseStarterProject-Swift-own-target-headers.hmap -Xcc -I/Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/ParseStarterProject-Swift-all-target-headers.hmap -Xcc -iquote -Xcc /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/ParseStarterProject-Swift-project-headers.hmap -Xcc -I/Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/DerivedSources/x86_64 -Xcc -I/Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -working-directory/Users/luka/Downloads/parse-starter-project-1/ParseStarterProject-Swift -emit-module-doc-path /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/Objects-normal/x86_64/ViewController~partial.swiftdoc -Onone -module-name ParseStarterProject_Swift -emit-module-path /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/Objects-normal/x86_64/ViewController~partial.swiftmodule -serialize-diagnostics-path /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/Objects-normal/x86_64/ViewController.dia -emit-dependencies-path /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/Objects-normal/x86_64/ViewController.d -emit-reference-dependencies-path /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/Objects-normal/x86_64/ViewController.swiftdeps -o /Users/luka/Library/Developer/Xcode/DerivedData/ParseStarterProject-Swift-gfncswdkcddmjuakcgurnhowymud/Build/Intermediates/ParseStarterProject-Swift.build/Debug-iphonesimulator/ParseStarterProject-Swift.build/Objects-normal/x86_64/ViewController.o

/Users/luka/Downloads/parse-starter-project-1/ParseStarterProject-Swift/ParseStarterProject/ParseStarterProject-Swift-Bridging-Header.h:5:9: error: 'ParseTwitterUtils/PFTwitterUtils.h' file not found
#import <ParseTwitterUtils/PFTwitterUtils.h>
        ^
<unknown>:0: error: failed to import bridging header '/Users/luka/Downloads/parse-starter-project-1/ParseStarterProject-Swift/ParseStarterProject/ParseStarterProject-Swift-Bridging-Header.h'

**Comment by hyd00** [comment]
Thanks @3bodar , I had the same issue, figured out my CallBack URL was empty.. Filled it and now Twitter login works like a charm.

**Comment by kvenkatesh-nyros** [comment]
2016-02-11 11:39:59.964 Iosloginpage[3917:93856] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x04655a94 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x040aee02 objc_exception_throw + 50
	2   CoreFoundation                      0x04544682 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 386
	3   CoreFoundation                      0x045588db +[NSDictionary dictionaryWithObjects:forKeys:count:] + 75
	4   Iosloginpage                        0x0005e6c5 -[PF_Twitter _showWebViewDialogAsync:requestSecret:] + 197
	5   Iosloginpage                        0x00060663 __38-[PF_Twitter _performWebViewAuthAsync]_block_invoke_2 + 266
	6   libdispatch.dylib                   0x087c93ff _dispatch_call_block_and_release + 15
	7   libdispatch.dylib                   0x087ec9cd _dispatch_client_callout + 14
	8   libdispatch.dylib                   0x087d2018 _dispatch_main_queue_callback_4CF + 910
	9   CoreFoundation                      0x045a770e __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	10  CoreFoundation                      0x04565454 __CFRunLoopRun + 2356
	11  CoreFoundation                      0x04564866 CFRunLoopRunSpecific + 470
	12  CoreFoundation                      0x0456467b CFRunLoopRunInMode + 123
	13  GraphicsServices                    0x05840664 GSEventRunModal + 192
	14  GraphicsServices                    0x058404a1 GSEventRun + 104
	15  UIKit                               0x010adcc1 UIApplicationMain + 160
	16  Iosloginpage                        0x00022e1c main + 140
	17  libdyld.dylib                       0x08817a21 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
sir i can't undestand what is the error while twitter login button clicked..
please tell me sir
