### ISSUE TITLE
PFFile.getData() stop working with Swift 2

### ISSUE THREAD

**Issue by kjelljisaksen** [ParsePlatform/Parse-SDK-iOS-OSX#331]
After converting to swift 2 /XCode 7 the .getData() only returns nil.  Please advice.
PS! This is my first issue post, so please advice on format or further information needed...

                if let imageFile = currGjerning["gIkonType"] as? PFFile {
                    if let dBilde = imageFile.getData() {
                        if let imgData = UIImage(data:dBilde) {
                            self.ivValgtType.image = imgData
                        }
                    } else {
                        regLogg("Gjerning", strTittel: "Bilde", strBeskrivelse: "Mangler bilde for \(strBildeNavn)",strKategori: "OBS")
                    }
                } else {
                    regLogg("Gjerning", strTittel: "Bilde", strBeskrivelse: "Mangler bilde for \(strBildeNavn)",strKategori: "OBS")
                }

**Comment by nlutsenko** [comment]
Hey @kjelljisaksen, thanks for the report.
This is super strange, any chance you can test the same behavior say in ObjC compared to Swift 2?
Just trying to isolate the issue to whether it's some Swift 2 magic (which I doubt), or we have an issue across all supported languages.

**Comment by kjelljisaksen** [comment]
Thank you for your reply.

I have never used Objective C so it may be a long struggle to test this in
Objective C.

It did work perfectly before I converted to Swift 2 / Xcode 7.

Are you able to try with a simple test to read a simple image with swift 2?

PS! It seems to be the same problem with getDataInBackgroundWithBlock.


Regards
Kjell J. Isaksen

2015-09-26 21:45 GMT+02:00 Nikita Lutsenko <notifications@github.com>:

**Comment by nlutsenko** [comment]
Yup, just tried it - works perfectly.
Tested against ParseUIDemo, written in Swift 2 from [this](https://github.com/parseplatform/parseui-ios) repo.

**Comment by kjelljisaksen** [comment]
When using getDataInBackgroundWithBlock I get this error :
*Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded
because the App Transport Security policy requires the use of a secure
connection." UserInfo={NSUnderlyingError=0x7fc51c53b5d0 {Error
Domain=kCFErrorDomainCFNetwork Code=-1022 "The resource could not be loaded
because the App Transport Security policy requires the use of a secure
connection."
UserInfo={NSErrorFailingURLStringKey=http://files.parsetfss.com/9ae17342-2d5c-467e-937c-967f281450c9/tfss-d4c6f673-c3b6-4c94-9041-a1a174e2700d-ikonVASKE%20OG%20RYDDE.png
<http://files.parsetfss.com/9ae17342-2d5c-467e-937c-967f281450c9/tfss-d4c6f673-c3b6-4c94-9041-a1a174e2700d-ikonVASKE%20OG%20RYDDE.png>,
NSLocalizedDescription=The resource could not be loaded because the App
Transport Security policy requires the use of a secure connection.,
NSErrorFailingURLKey=http://files.parsetfss.com/9ae17342-2d5c-467e-937c-967f281450c9/tfss-d4c6f673-c3b6-4c94-9041-a1a174e2700d-ikonVASKE%20OG%20RYDDE.png}
<http://files.parsetfss.com/9ae17342-2d5c-467e-937c-967f281450c9/tfss-d4c6f673-c3b6-4c94-9041-a1a174e2700d-ikonVASKE%20OG%20RYDDE.png}>},
NSErrorFailingURLStringKey=http://files.parsetfss.com/9ae17342-2d5c-467e-937c-967f281450c9/tfss-d4c6f673-c3b6-4c94-9041-a1a174e2700d-ikonVASKE%20OG%20RYDDE.png
<http://files.parsetfss.com/9ae17342-2d5c-467e-937c-967f281450c9/tfss-d4c6f673-c3b6-4c94-9041-a1a174e2700d-ikonVASKE%20OG%20RYDDE.png>,
NSErrorFailingURLKey=http://files.parsetfss.com/9ae17342-2d5c-467e-937c-967f281450c9/tfss-d4c6f673-c3b6-4c94-9041-a1a174e2700d-ikonVASKE%20OG%20RYDDE.png
<http://files.parsetfss.com/9ae17342-2d5c-467e-937c-967f281450c9/tfss-d4c6f673-c3b6-4c94-9041-a1a174e2700d-ikonVASKE%20OG%20RYDDE.png>,
NSLocalizedDescription=The resource could not be loaded because the App
Transport Security policy requires the use of a secure connection.}*

Any suggestions?

Regards
Kjell Isaksen

2015-09-27 11:03 GMT+02:00 Nikita Lutsenko <notifications@github.com>:

**Comment by kjelljisaksen** [comment]
I had to update info.plist to ignore security (i think) using:

<dict>
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

But this does not seem right. Any suggestions to establish secure
connection to parse?

Regards
Kjell Isaksen

2015-09-27 14:46 GMT+02:00 Kjell J Isaksen <kjell.isaksen@mobitag.no>:

**Comment by nlutsenko** [comment]
This was updated and we are fully compliant with app transport security in the latest Parse SDK (1.8.5 at this time), looks like you are using an old version.
I would suggest updating to the latest version and removing `NSAppTransportSecurity` from Info.plist.

Glad you found the source of the problem.
Let me know if there is anything I can help you with.
