### ISSUE TITLE
Improve error messages when creating an invalid PFFile.

### ISSUE THREAD

**Issue by richardjrossiii** [ParsePlatform/Parse-SDK-iOS-OSX#338]
Currently, if you attempt to create a `PFFile` with a `nil` NSData parameter, you get a strange 'file not found' error when attempting to save it to Parse.

Let's make this either 

 - Throw an exception
 - Make the PFFile constructor return `nil`, when invalid data is passed in.

Somewhat relates to #6.

**Comment by nlutsenko** [comment]
Sounds great! Let's do it!
We have this method:
```objc
+ (instancetype)fileWithName:(PF_NULLABLE NSString *)name
                        data:(NSData *)data
                 contentType:(PF_NULLABLE NSString *)contentType
                       error:(NSError **)error;
```
Which returns `nil` and if there was an `error` - it will be populated.

What do you think if we take this approach:
- Check for `nil` on NSData (it's ok if it's empty probably, not ok if it's `nil`)
- Add more methods that accept pointer-to-a-pointer-to-an-error (nice name :grin:)
- Mark methods without an `error:` parameter as unavailable in Swift, so whoever uses Swift gets `throws` :)

**Comment by nlutsenko** [comment]
This is probably an example of the method signature that we are aiming for in Swift:
`public convenience init(name: String?, data: NSData, contentType: String?) throws`
Which is a result of this in ObjC:
```objc
+ (PF_NULLABLE instancetype)fileWithName:(PF_NULLABLE NSString *)name
                                    data:(NSData *)data
                             contentType:(PF_NULLABLE NSString *)contentType PF_SWIFT_UNAVAILABLE;

+ (PF_NULLABLE instancetype)fileWithName:(PF_NULLABLE NSString *)name
                                    data:(NSData *)data
                             contentType:(PF_NULLABLE NSString *)contentType
                                   error:(NSError **)error;
```
