### ISSUE TITLE
ParseTwitterUtils.h, 7 issues: error expected ')'

### ISSUE THREAD

**Issue by smitjb45** [ParsePlatform/Parse-SDK-iOS-OSX#339]
Hello, I'm still having a problem with ParseTwitterUtils. On line 32 in ParseTwitterUtils.h, its giving me an error expected ')' for + (PF_NULLABLE FBSession *)session;. I'm getting the same error on lines 101, 110, 409, and 426.

**Comment by nlutsenko** [comment]
ParseTwitterUtils doesn't seem to have any reference to FBSession.
Are you sure you are not talking about ParseFacebookUtils?

Could you post the exact error that it gives you here?

**Comment by smitjb45** [comment]
Oh sorry, my mistake ParseFacebookUtils:

CompileSwift normal x86_64 /Users/joshuasmith/Desktop/Rego1/Rego1/ParseLoginViewController.swift
    cd /Users/joshuasmith/Desktop/Rego1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/joshuasmith/Desktop/Rego1/Rego1/ParseLoginViewController.swift /Users/joshuasmith/Desktop/Rego1/Rego1/HealperMethods.swift /Users/joshuasmith/Desktop/Rego1/Rego1/SendPushViewController.swift /Users/joshuasmith/Desktop/Rego1/Rego1/SignUpViewController.swift /Users/joshuasmith/Desktop/Rego1/Rego1/LoginViewController.swift /Users/joshuasmith/Desktop/rego/rego/AppDelegate.swift -target x86_64-apple-ios9.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -I /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Products/Debug-iphonesimulator -F /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Products/Debug-iphonesimulator -F /Users/joshuasmith/Downloads/FacebookSDKs-iOS-20150910 -F /Users/joshuasmith/Desktop/rego -F /Users/joshuasmith/Desktop/google-plus-ios-sdk-1.7.1 -F /Users/joshuasmith/Downloads/parse-library-1 -enable-testing -g -import-objc-header /Users/joshuasmith/Desktop/Rego1/Bridging-Header.h -module-cache-path /Users/joshuasmith/Library/Developer/Xcode/DerivedData/ModuleCache -serialize-debugging-options -Xcc -I/Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Rego1-generated-files.hmap -Xcc -I/Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Rego1-own-target-headers.hmap -Xcc -I/Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Rego1-all-target-headers.hmap -Xcc -iquote -Xcc /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Rego1-project-headers.hmap -Xcc -I/Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/DerivedSources/x86_64 -Xcc -I/Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -working-directory/Users/joshuasmith/Desktop/Rego1 -emit-module-doc-path /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Objects-normal/x86_64/ParseLoginViewController~partial.swiftdoc -Onone -module-name Rego1 -emit-module-path /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Objects-normal/x86_64/ParseLoginViewController~partial.swiftmodule -serialize-diagnostics-path /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Objects-normal/x86_64/ParseLoginViewController.dia -emit-dependencies-path /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Objects-normal/x86_64/ParseLoginViewController.d -emit-reference-dependencies-path /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Objects-normal/x86_64/ParseLoginViewController.swiftdeps -o /Users/joshuasmith/Library/Developer/Xcode/DerivedData/Rego1-fhketmhplxmxdygkwryxpfdzczdc/Build/Intermediates/Rego1.build/Debug-iphonesimulator/Rego1.build/Objects-normal/x86_64/ParseLoginViewController.o

/Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:9: note: in file included from /Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:
#import <ParseFacebookUtils/PFFacebookUtils.h>
        ^
/Users/joshuasmith/Downloads/parse-library-1/ParseFacebookUtils.framework/Headers/PFFacebookUtils.h:32:16: error: expected ')'
+ (PF_NULLABLE FBSession *) session;
               ^
/Users/joshuasmith/Downloads/parse-library-1/ParseFacebookUtils.framework/Headers/PFFacebookUtils.h:32:3: note: to match this '('
+ (PF_NULLABLE FBSession *) session;
  ^
/Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:9: note: in file included from /Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:
#import <ParseFacebookUtils/PFFacebookUtils.h>
        ^
/Users/joshuasmith/Downloads/parse-library-1/ParseFacebookUtils.framework/Headers/PFFacebookUtils.h:101:35: error: expected a type
+ (void)setFacebookLoginBehavior:(FBSessionLoginBehavior)behavior;
                                  ^
/Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:9: note: in file included from /Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:
#import <ParseFacebookUtils/PFFacebookUtils.h>
        ^
/Users/joshuasmith/Downloads/parse-library-1/ParseFacebookUtils.framework/Headers/PFFacebookUtils.h:110:4: error: expected a type
+ (FBSessionLoginBehavior)facebookLoginBehavior;
   ^
/Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:9: note: in file included from /Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:
#import <ParseFacebookUtils/PFFacebookUtils.h>
        ^
/Users/joshuasmith/Downloads/parse-library-1/ParseFacebookUtils.framework/Headers/PFFacebookUtils.h:409:42: error: expected a type
                               audience:(FBSessionDefaultAudience)audience;
                                         ^
/Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:9: note: in file included from /Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:
#import <ParseFacebookUtils/PFFacebookUtils.h>
        ^
/Users/joshuasmith/Downloads/parse-library-1/ParseFacebookUtils.framework/Headers/PFFacebookUtils.h:426:26: error: expected a type
               audience:(FBSessionDefaultAudience)audience
                         ^
/Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:9: note: in file included from /Users/joshuasmith/Desktop/Rego1/Bridging-Header.h:14:
#import <ParseFacebookUtils/PFFacebookUtils.h>
        ^
/Users/joshuasmith/Downloads/parse-library-1/ParseFacebookUtils.framework/Headers/PFFacebookUtils.h:445:26: error: expected a type
               audience:(FBSessionDefaultAudience)audience
                         ^
<unknown>:0: error: failed to import bridging header '/Users/joshuasmith/Desktop/Rego1/Bridging-Header.h'

**Comment by nlutsenko** [comment]
Looks like you are missing Facebook SDK from linking.
Also, if you are using ParseFacebookUtilsV4 - there is no need to use ParseFacebookUtils, since they are mutually exclusive and the latter is built for FBSDKv3, the former - FBSDKv4.

**Comment by smitjb45** [comment]
Okay, that's strange. I have the Facebook SDK linked... I'm using the ParseFacebookUtils instead of V4 because it doesn't recognize V4 for some reason.

**Comment by nlutsenko** [comment]
ParseFacebookUtilsV4 requires FBSDKCoreKit/FBSDKLoginKit, which is the latest Facebook SDK available (v4). This is indeed strange, but all these errors mean that Xcode can't find references to Facebook SDK.

**Comment by smitjb45** [comment]
Okay, thanks. At least I know where the problem is... I tried relinking FB SDK and still having the same problem. Should I try re-downloading Xcode?

**Comment by nlutsenko** [comment]
I don't think so, no. If you have Xcode 7 (which looks like you do), it shouldn't be a problem.
Maybe convert your usage of Facebook SDK to use v4 according to the latest [docs](https://developers.facebook.com/docs/ios)?

**Comment by nlutsenko** [comment]
@smitjb45, hope the issue is resolved for you.
I am going to close out this issue, since it looks like it's fixed. 
Let me know if there is anything else I can help you with.
