### ISSUE TITLE
Facebook Auth is broken with 1.8

### ISSUE THREAD

**Issue by thefaj** [ParsePlatform/Parse-SDK-iOS-OSX#34]
Facebook auth doesn't work on iOS 9 — from the console it times out.
Might be related to this:
https://developers.facebook.com/docs/ios/ios9

Facebook's frustratingly opaque developer site points out how little they care about security.

**Comment by nlutsenko** [comment]
Hey @thefaj, yeah it is said that FB doesn't yet support SHA256. We do though with Parse.
Let me ask you few questions on this, first:
- Are you using native app auth (transition to FB.app and back to the app)
- Which version of FB SDK are you using, also, which version of ParseFacebookUtils are you using
An ideal scenario would be to get a repro project for this, it could be without keys and everything - just a piece of code that reproduces the problem.

From what I can see - I think it's related to an issue inside FB SDK, other than in Parse<->FB integration, as we don't do anything special on top other than using public APIs.

**Comment by thefaj** [comment]
Hi Nikita,

Thank you for getting back to me so quickly! It looks like the latest Parse 1.8.1 plus Facebook SDK frameworks (20150813) have authentication working again. I’m not sure what happened last week…but I updated all 12 Parse & Facebook libraries in the app, and I can login.

Thanks!
-Alex

**Comment by nlutsenko** [comment]
Ow, great! That's good news!
Let me know if you run into this again!
