### ISSUE TITLE
localstore queries slower than network

### ISSUE THREAD

**Issue by mungra** [ParsePlatform/Parse-SDK-iOS-OSX#341]
Hello,

When i query using "fromLocalDatastore" or "fromPinWithName", it's 10 - 15 sec slower than querying from the network (which is almost instant). is this a parse issue? using xcode 7 with swift.

**Comment by nlutsenko** [comment]
Hey @mungra, thanks for the report.
We are tracking Local Datastore performance improvements in #32.
I am going to merge this issue there...

There are couple of things planned there, including something for next release.
