### ISSUE TITLE
PFUser currentUser returns nil after restarting the app

### ISSUE THREAD

**Issue by henry-tappd** [ParsePlatform/Parse-SDK-iOS-OSX#347]
I was working at upgrading my App to use XCode 7 and iOS 9.

I found a behaviour change from Parse iOS SDK 1.8.0 to 1.8.5 in terms of the way PFUser.currentUser is cached in the device.

In 1.8.0, when the app has [Parse enableLocalDatastore] and the app is restarted, PFUser.currentUser can return the previously logged in PFUser without re-login.

In 1.8.5, when the app is killed and restarted, PFUser.currentUser returns nil. 
If I turned off local datastore, PFUser.currentUser works correctly and returns the cached PFUser after app is restarted.

I wonder if there is a bug in the way PFUser.currentUser is returned when Local DataStore is enabled.

Thanks !

**Comment by nlutsenko** [comment]
This sounds super strange, as it would mean we have a massive regression.
I've just retested this locally and it seems to work great.

Any chance there is something specific to the way you login?

A small repro project or even a code snippet would help tremendously to identify the problem.

**Comment by henry-tappd** [comment]
I will prepare a small repo project. In the mean time, following is the code snippet that may help.
It saves firstTimeLoginDate to PFUser after successful call and it uses PromiseKit.

```
- (AnyPromise*)loginWithEmail:(NSString*)email password:(NSString*)password{
    AnyPromise *promise = [AnyPromise promiseWithResolverBlock:^(PMKResolver resolve) {
        // clear currentUser object
        PFUser *currentUser = [PFUser currentUser];
        if (currentUser) {
            [PFUser logOut];
        }
        
        [PFUser logInWithUsernameInBackground:email password:password block:^(PFUser *user, NSError *error) {
            if (!error) {
                [self saveFirstTimeLoginDate:user];
                resolve(user);
            } else {
                resolve(error);
            }
        }];
    }];
    
    return promise;
}

- (void)saveFirstTimeLoginDate:(PFUser*)user {
        if (!user[@"firstTimeLoginDate"]) {
            user[@"firstTimeLoginDate"] = [NSDate new];
            [user saveEventually:^(BOOL succeeded, NSError *error) {
            }];
        }
}

```

**Comment by henry-tappd** [comment]
After some further investigation into the issue, I figured out the problem was caused by the Parse + Firebase iOS library. Parse iOS v1.8.5 doesn't play well with older version of Firebase. After I upgraded Firebase iOS to v2.4.1 which is more compatible with iOS 9, the problem is gone.

If anyone uses Parse and Firebase, use the latest version of both is highly recommended.

**Comment by nlutsenko** [comment]
Glad you found the solution! :grinning:
