### ISSUE TITLE
Exception in ParseTwitterUtils while using PFLogInViewController

### ISSUE THREAD

**Issue by grigorye** [ParsePlatform/Parse-SDK-iOS-OSX#348]
I'm trying to use PFLoginViewController with PFLogInFieldsTwitter. All works well (I can authenticate with Twitter and etc.) except for the following scenario:

1. Present PFLoginViewController
2. Tap Twitter button
3. In the popup asking for authorization with Twitter, select Cancel button.
4. On next page tap on "Return to <your app>" button.

At this point I get an exception thrown with the following stuff logged into the console:

```
objc[3123]: EXCEPTIONS: throwing 0x7b8a7b90 (object 0x7b889620, a NSException)
objc[3123]: EXCEPTIONS: searching through frame [ip=0xaa6288 sp=0xb0218610] for exception 0x7b8a7b70
objc[3123]: EXCEPTIONS: catch(NSException)
objc[3123]: EXCEPTIONS: unwinding through frame [ip=0xaa6288 sp=0xb0218610] for exception 0x7b8a7b70
objc[3123]: EXCEPTIONS: handling exception 0x7b8a7b70 at 0xaa63d9
objc[3123]: EXCEPTIONS: finishing handler
objc[3123]: EXCEPTIONS: releasing completed exception 0x7b8a7b90 (object 0x7b889620, a NSException)
[.] [23].0: [Error]: Caught "NSInvalidArgumentException" with reason "*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]":
(
	0   CoreFoundation                      0x06021a84 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x059d4e02 objc_exception_throw + 50
	2   CoreFoundation                      0x05f104f2 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 386
	3   CoreFoundation                      0x05f2477b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 75
	4   opas-awol                           0x0047786d -[PFTwitterAuthenticationProvider authDataWithTwitterId:screenName:authToken:secret:] + 318
	5   opas-awol                           0x00477ae0 __52-[PFTwitterAuthenticationProvider authenticateAsync]_block_invoke + 297
	6   opas-awol                           0x00aa70a8 __62-[BFTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke + 184
	7   opas-awol                           0x00aa6289 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 121
	8   opas-awol                           0x00aa19f9 __29+[BFExecutor defaultExecutor]_block_invoke_2 + 505
	9   opas-awol                           0x00aa248a -[BFExecutor execute:] + 106
	10  opas-awol                           0x00aa6199 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 217
	11  opas-awol                           0x00aa5a3f -[BFTask runContinuations] + 719
	12  opas-awol                           0x00aa4caa -[BFTask trySetResult:] + 282
	13  opas-awol                           0x00aa4b35 -[BFTask setResult:] + 85
	14  opas-awol                           0x00aa7ce7 -[BFTaskCompletionSource setResult:] + 119
	15  opas-awol                           0x00aa674b __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_3 + 539
	16  opas-awol                           0x00aa6289 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 121
	17  opas-awol                           0x00aa19f9 __29+[BFExecutor defaultExecutor]_block_invoke_2 + 505
	18  opas-awol                           0x00aa248a -[BFExecutor execute:] + 106
	19  opas-awol                           0x00aa6199 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke + 217
	20  opas-awol                           0x00aa5a3f -[BFTask runContinuations] + 719
	21  opas-awol                           0x00aa4caa -[BFTask trySetResult:] + 282
	22  opas-awol                           0x00aa4b35 -[BFTask setResult:] + 85
	23  opas-awol                           0x00aa7ce7 -[BFTaskCompletionSource setResult:] + 119
	24  opas-awol                           0x00479bfa __35-[PF_Twitter authorizeInBackground]_block_invoke_3 + 213
	25  opas-awol                           0x00aa6289 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 + 121
	26  libdispatch.dylib                   0x06b97377 _dispatch_call_block_and_release + 15
	27  libdispatch.dylib                   0x06bba9cd _dispatch_client_callout + 14
	28  libdispatch.dylib                   0x06ba0985 _dispatch_root_queue_drain + 1008
	29  libdispatch.dylib                   0x06ba058e _dispatch_worker_thread3 + 115
	30  libsystem_pthread.dylib             0x06ef3270 _pthread_wqthread + 1050
	31  libsystem_pthread.dylib             0x06ef0f82 start_wqthread + 34
).
```

And no methods on PFLoginViewController delegate are invoked, particularly neither -logInViewController:didFailToLogInWithError: nor -logInViewControllerDidCancelLogIn: (they are invoked in other scenarios).

As result the app is stuck on the intial screen with Twitter button and close button, and does not react to tap on any button. It's reproducible on both iOS 8 and iOS 9.

SDKs used:

- Parse (1.8.5)
- ParseTwitterUtils (1.8.5)

**Comment by nlutsenko** [comment]
Hey @grigorye, thanks for the report!
Awesome to see repro steps and a stack trace.

Will look into it and potentially fix the issue, as it looks like a valid bug.

**Comment by nlutsenko** [comment]
Just verified - indeed a bug. Will follow-up with a fi. Can't cross-link with a pull-request, since ParseTwitterUtils are not yet opensource (coming very very soon), but it is going to be released in the next version of the SDK

**Comment by nlutsenko** [comment]
Hey guys, ParseTwitterUtils is finally opensource and available [here](https://github.com/ParsePlatform/ParseTwitterUtils-iOS).
It also is the new version - `1.9.0` which should include the fix for this issue.
Let me know if this works, otherwise - feel free to open the issue in that repo.

**Comment by weiwarren** [comment]
I have recently upgraded to the Parse SDK 1.9.0 and tried creating a simple project in xcode 6 replicating the steps described by grigorye, and I received the following error:
<pre>
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: Invalid request token.)'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000111ae1c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000112637bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x00000001119e6af8 -[__NSDictionaryM setObject:forKey:] + 968
	3   testparse                           0x000000010f12f8de +[NSURL(OAuthAdditions) PF_ab_parseURLQueryString:] + 541
	4   testparse                           0x000000010f128bfc __65-[PF_Twitter _getAccessTokenForWebAuthAsync:requestSecret:token:]_block_invoke + 127
	5   CFNetwork                           0x0000000110b67beb __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 157
	6   Foundation                          0x000000011226f57f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	7   Foundation                          0x00000001121b00b2 -[NSBlockOperation main] + 98
	8   Foundation                          0x0000000112192774 -[__NSOperationInternal _start:] + 645
	9   Foundation                          0x0000000112192383 __NSOQSchedule_f + 184
	10  libdispatch.dylib                   0x00000001132c8614 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x00000001132af6a7 _dispatch_queue_drain + 2176
	12  libdispatch.dylib                   0x00000001132aecc0 _dispatch_queue_invoke + 235
	13  libdispatch.dylib                   0x00000001132b23b9 _dispatch_root_queue_drain + 1359
	14  libdispatch.dylib                   0x00000001132b3b17 _dispatch_worker_thread3 + 111
	15  libsystem_pthread.dylib             0x000000011364da9d _pthread_wqthread + 729
	16  libsystem_pthread.dylib             0x000000011364b3dd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
</pre>

**Comment by nlutsenko** [comment]
@weiwarren Can you please make sure that `callback URL` setting in your Twitter app settings is not empty?
According to our guide [here](https://parse.com/docs/ios/guide#users-twitter-users) it's a required step in setting up Twitter.

**Comment by weiwarren** [comment]
@nlutsenko, thanks for your quick response. I have double checked on twitter that the callback URL is definitely there in the twitter app as required. It is a valid random URL. 

I am able to login through parse twitter, the issue only occurs when I click cancel button, and return to the app. 

I had this issue in my app initially with Parse 1.8 and after upgrading to 1.9 the issue remains.

![image](https://cloud.githubusercontent.com/assets/6090759/11162274/ece4c4f4-8aee-11e5-98f5-ff2d1f4bfe0a.png)

**Comment by nlutsenko** [comment]
@weiwarren Could you create an issue on ParsePlatform/ParseTwitterUtils-iOS with as much information as you have, I'll look into it.

**Comment by weiwarren** [comment]
@nlutsenko New issue created at https://github.com/ParsePlatform/ParseTwitterUtils-iOS/issues/11

**Comment by ashish-naik** [comment]
@weiwarren were you able to solve this? I am also getting this exception. I also created an issue just now. 

https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1474
