### ISSUE TITLE
Anypic is broken on iOS

### ISSUE THREAD

**Issue by rabidrebeldog** [ParsePlatform/Parse-SDK-iOS-OSX#351]
I just downloaded the latest source code for Anypic on iOS.  I built and ran on both an iphone running iOS 9 and in the simulator running iOS 8.2, same result.
I am presented with a "log in with Facebook" button.
I select that and then I am taken to Safari where I log in.
I am returned to Anypic and I still see the "log in..." button.   
I can never get past that point.

**Comment by nlutsenko** [comment]
Super strange, as I've just tested and it works beautifully.
Please note that you need to create your own Facebook App and put the application identifier in these places:
- `[PFFacebookUtils initializeWithApplicationId:@"FBAPPID"];` in `AppDelegate.m`
- URL Types in Info.plist - update URL Scheme from `fbFACEBOOK_APP_ID` to `fbYOURID`

In addition to these, if you are running iOS 9 - you would need to add few extra pieces in Info.plist, according to [this guide](https://developers.facebook.com/docs/ios/ios9).

Let me know if this helps, I am going to send a quick update to AnyPic to incorporate the last bit there (iOS 9 things).

**Comment by nlutsenko** [comment]
Indeed, I can see the issue... Looking inside of it...

**Comment by nlutsenko** [comment]
Anypic was using the quite old Facebook SDK, I just upgrade it to use the latest one.
Feel free to checkout the branch attached to that pull request to be able to fully work on anypic.
