### ISSUE TITLE
unrecognized selector sent to instance

### ISSUE THREAD

**Issue by rahulShrestha89** [ParsePlatform/Parse-SDK-iOS-OSX#352]
I have been getting this error when implementing the latest parse update with latest facebook sdk for XCode 7.

ParseStarterProject-Swift[2841:107652] -[PFUserAuthenticationController authenticationDelegateForAuthType:]: unrecognized selector sent to instance 0x7fd0bbc34620
2015-09-30 00:56:33.960 ParseStarterProject-Swift[2841:107652] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PFUserAuthenticationController authenticationDelegateForAuthType:]: unrecognized selector sent to instance 0x7fd0bbc34620'

**Comment by nlutsenko** [comment]
It looks like you are using different versions of ParseFacebookUtils and Parse SDK.
Try getting the latest Parse SDK from releases page here or from [Parse Downloads Page](https://parse.com/docs/downloads) and replacing the current one - it should help.

Let me know if this works, or if there is anything else I can help you with.

**Comment by rahulShrestha89** [comment]
tried doing it more than 10 times, but the issue is same. i downloaded the latest parse sdk and facebook sdk. still cant work it out.

**Comment by nlutsenko** [comment]
Try cleaning your project?
Also - you can double check the version (they should match as of right now) in Info.plists of every framework.

**Comment by rahulShrestha89** [comment]
even though i added the latest parse sdk, i have the following on my ifo.plist. 
<img width="444" alt="screenshot 2015-09-30 21 25 09" src="https://cloud.githubusercontent.com/assets/7716938/10211548/dee1e704-67b9-11e5-8e91-3403e1acc714.png">

**Comment by nlutsenko** [comment]
Try deleting it first, then if you can still find it - delete it again, then add it back to your app.

On Sep 30, 2015, at 7:26 PM, Rahul Shrestha <notifications@github.com<mailto:notifications@github.com>> wrote:


even though i added the latest parse sdk, i have the following on my ifo.plist.
[screenshot 2015-09-30 21 25 09]<https://urldefense.proofpoint.com/v1/url?u=https://cloud.githubusercontent.com/assets/7716938/10211548/dee1e704-67b9-11e5-8e91-3403e1acc714.png&k=ZVNjlDMF0FElm4dQtryO4A%3D%3D%0A&r=zxFHBXEnKtFUPQxCGyQAqg%3D%3D%0A&m=jew6EOSQI882IT0MEINmLEt2vNhDHapSgnh0Exd2zT0%3D%0A&s=50b208654be5591c98b6089b35525feeab77d5f87e92f29999e387b1e4e7f472>

**Comment by rahulShrestha89** [comment]
tried everything, but no any luck. anyway , Thanks nlutsenko! (Y)

**Comment by nlutsenko** [comment]
The current latest is 1.8.5 - that's the one you are looking for.
