### ISSUE TITLE
Data from server not coming down for some tables

### ISSUE THREAD

**Issue by stephengazzard** [ParsePlatform/Parse-SDK-iOS-OSX#353]
We are not 100% convinced this is an iOS SDK rather than a server issue, as this started to happen just a couple days ago to our customers, who have been running the same version of the app for over 6 months. But Parse support sent us here... so here I am :)

Essentially, we have found that in some cases, our Parse requests have stopped returning objects that, as best as we can tell, clearly exist in the database.

In the first case, we were requesting the first instance of an object that matched this query:
```
PFObject *parseObject = [PFObject objectWithoutDataWithClassName:@"Tailboard" objectId:self.parseObjectId];
PFQuery *query = [PFQuery queryWithClassName:@"TailboardSnapshot"];
[query whereKey:@"tailboard" equalTo:parseObject];
[query orderByDescending:@"dateModified"];
[query getFirstObjectInBackgroundWithBlock:^(PFObject *object, NSError *error) {
```

We started getting error code 101 in response to this (101 = no object matches your query), even though making the same query in Parse or in our own dashboard web app that fetches from Parse was yielding the valid object.

This corrected itself after about 12 hours, but other objects related to this table failed to come down. Given this query:
```
/* Where relatedClassName could be: ConfinedSpace, LiftCalculationForm, TailboardLiveLine, AudioRecording, TailboardGroundingLocation, HazardAssessment, Hazard, Image, JobEmployee, TailboardLocation, Procedure, TailboardTagging, TailboardTask */
PFQuery *query = [PFQuery queryWithClassName:relatedClassName];
 /* Where parseObject is a tailboardSnapshot downloaded from parse */
[query whereKey:@"tailboardSnapshot" equalTo:parseObject];
[query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
```

We often get empty arrays, even though we have verified using the same methods above that the objects do exist in the back end. Again, this wasn't the case until two days ago.

Some of these objects have started to behave correctly, some of them still always return empty arrays. The current status is that 5 of our classes are coming down (it was originally 3, but two have come back online since we started tracking this), while 8 are not, which means over half of our related data is still missing.

The app was using an old version of the Parse pod but we have updated locally and are seeing identical results from the server from 1.8.5.

Any guidance on what might have changed?

**Comment by nlutsenko** [comment]
Taking into account that on the same version of the client SDK you are seeing weird behavior - I am almost 100% confident than it's weird behavior on the backend.
I would strongly encourage you guys to file a bug against the backend aka use FB Bugs tool, if you didn't do it before, or follow-up there, since we are focusing on the client SDK issues in this repo.

**Comment by stephengazzard** [comment]
Thanks @nlutsenko, will go back to their support team with this.
