### ISSUE TITLE
PFUser subclass not updating property after fiirst save, needed two to update.

### ISSUE THREAD

**Issue by dev-mush** [ParsePlatform/Parse-SDK-iOS-OSX#357]
In my PFUser subclass, I'm using a flag to track if a user has accepted my T&C. Latley I've noticed that, at least for anonymous users, the first time I save this property (defined ad an NSNumber) it won't get saved on parse, even if the callback returns success.
After the second save, the property get stored correctly on parse.

here's some sample code:

```
// .h file
@interface MyUser : PFUser <PFSubclassing>
.
. //other properties 
.
@property (nonatomic, strong) NSNumber *legalsAccepted;
. 
. //other properties 
.
@end

// .m file
@implementation MyUser 
. 
. 
.
@dynamic obtainedTickets;
. 
.  //code
.
@end


//code that I use to save the property
- (void) acceptLegals{
    [[MyUser currentUser] setLegalsAccepted: [NSNumber numberWithBool:YES]];
    [[MyUser currentUser] saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
            
         //callback says succeeded is true, no errors or logs in console
        
        dispatch_async(dispatch_get_main_queue(), ^{
            [self dismissViewControllerAnimated: YES completion:nil];
            if(self.delegate)
                [self.delegate userDidCompleteWithTermsAccepted: succeeded];
        });
    }];

```

my acceptLegals method has to be called twice to store the data correctly on parse, the property legalsAccepted is set back to no after method invocation. It has always worked, so unless I'm missing something very obvious, there might be a bug on parse.
The problem occurs for every class of property, the user is Anonymous.

**Comment by richardjrossiii** [comment]
Thanks for the report. I'm looking into it now....

**Comment by richardjrossiii** [comment]
I just ran the following test locally:

    [UserSubclass registerSubclass];
    [UserSubclass enableAutomaticUser];

    UserSubclass *anonymousUser = [UserSubclass currentUser];
    XCTAssertNotNil(anonymousUser);

    anonymousUser.foo = @10;

    XCTAssertEqualObjects(@10, anonymousUser[@"foo"]);

    XCTestExpectation *expectation = [self currentSelectorTestExpectation];
    [[anonymousUser saveInBackground] continueWithBlock:^id(BFTask<NSNumber *> *task) {
        NSString *objectId = anonymousUser.objectId;

        UserSubclass *fetchedUser = [UserSubclass objectWithoutDataWithClassName:[PFUser parseClassName] objectId:objectId];
        return [[fetchedUser fetchInBackground] continueWithBlock:^id(BFTask<__kindof PFObject *> *task) {
            XCTAssertEqualObjects([task.result foo], @10);
            [expectation fulfill];

            return nil;
        }];
    }];

    [self waitForTestExpectations];

It would appear to work flawlessly from my testing (tested with LDS both enabled and disabled), so I think that there's more to this  story. Which version of Parse are you using?

**Comment by dev-mush** [comment]
Will look into it and write a replicable test if I manage to ;)
