### ISSUE TITLE
Parse Facebook Login Error - Swift 2

### ISSUE THREAD

**Issue by sanergulec** [ParsePlatform/Parse-SDK-iOS-OSX#364]
I have created a login with facebook button using parse servers. However when the login button is clicked I am getting an error like:

2015-10-04 18:20:23.040 MyProject[352:91466] * Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString containsObject:]: unrecognized selector sent to instance 0x15615560' * First throw call stack: (0x22c9b86b 0x3464edff 0x22ca1035 0x22c9ec8f 0x22bce2b8 0x62e355 0x62e1f9 0x1c14dab 0x1c159c1 0x62d5a7 0x61a435 0x61a7f3 0x61a7b5 0x61968d 0x61956f 0x6d5cab 0x6d4e1f 0x6d4ccf 0x49cd08 0x49cf54 0x26de3cc9 0x26de3c55 0x26dcc95b 0x26de35a1 0x26de320f 0x26ddc2d7 0x26dada3d 0x26dac25f 0x22c5e827 0x22c5e417 0x22c5c77f 0x22baf1e9 0x22baefdd 0x2be53af9 0x26e1417d 0x616a74 0x34d79873) libc++abi.dylib: terminating with uncaught exception of type NSException
enter image description here

The function I am using is as bellow. I just used the same methods that is documented in parse website in swift. Why may I getting the error?

        @IBAction func button_clicked(sender: AnyObject) {

    let permissions = ["public_profile"]

    PFFacebookUtils.logInInBackgroundWithReadPermissions(permissions) {
        (user: PFUser?, error: NSError?) -> Void in
        if let user = user {
            if user.isNew {
                print("User signed up and logged in through Facebook!")
            } else {
                print("User logged in through Facebook!")
            }
        } else {
            print("Uh oh. The user cancelled the Facebook login.")
        }
    }

    }
I created a bridging header as

    #import <Parse/Parse.h>

    #import "KeychainWrapper.h"

      #import <FBSDKCoreKit/FBSDKCoreKit.h>

and added to info.plist

        <key>CFBundleURLTypes</key>
       <array>
        <dict>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>xxxxxxx</string>
        </array>
    </dict>
    </array>
    <key>FacebookAppID</key>
     <string>xxxxxxxxx</string>
    <key>FacebookDisplayName</key>
    <string>My App</string>
    <key>NSAppTransportSecurity</key>
    <dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>facebook.com</key>
        <dict>
            <key>NSIncludesSubdomains</key>
            <true/>
            <key>NSExceptionRequiresForwardSecrecy</key>
            <false/>
        </dict>
        <key>fbcdn.net</key>
        <dict>
            <key>NSIncludesSubdomains</key>
            <true/>
            <key>NSExceptionRequiresForwardSecrecy</key>
            <false/>
        </dict>
        <key>akamaihd.net</key>
        <dict>
            <key>NSIncludesSubdomains</key>
            <true/>
            <key>NSExceptionRequiresForwardSecrecy</key>
            <false/>
        </dict>
    </dict>
    </dict>

    <key>LSApplicationQueriesSchemes</key>
    <string>fbauth2</string>

my appDelegate is:

     import UIKit
     import FBSDKCoreKit
     import ParseFacebookUtilsV4

    @UIApplicationMain
    class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject:      AnyObject]?) -> Bool {
    // Override point for customization after application launch.

     Parse.setApplicationId("xxxxxxxxx", clientKey: "xxxxxxxxxxxx")
    PFFacebookUtils.initializeFacebookWithApplicationLaunchOptions(launchOptions)

    UIApplication.sharedApplication().setStatusBarStyle(UIStatusBarStyle.LightContent, animated: true)

    return true
     }

     func applicationWillResignActive(application: UIApplication) {
    // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
    // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
    }

     func applicationDidEnterBackground(application: UIApplication) {
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

     func applicationWillEnterForeground(application: UIApplication) {
    // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
   }

    func applicationDidBecomeActive(application: UIApplication) {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    FBSDKAppEvents.activateApp()
   }

    func applicationWillTerminate(application: UIApplication) {
    // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
   }

    func application(application: UIApplication,
    openURL url: NSURL,
    sourceApplication: String?,
    annotation: AnyObject) -> Bool {
        return FBSDKApplicationDelegate.sharedInstance().application(application,
            openURL: url,
            sourceApplication: sourceApplication,
            annotation: annotation)
   }
   }

**Comment by nlutsenko** [comment]
Sounds super strange.
Any chance you can post a full stack trace from the exception?
The piece I am trying to figure out here is where this exception is coming from, or rather - what triggers the exception.

**Comment by sanergulec** [comment]
My previous code for facebook permissions in info.plist was as string, however it needed to be as array.

it was:

  <key>LSApplicationQueriesSchemes</key>
   <string>
    <string>fbauth2</string>
   </string>
I updated it as:

 <key>LSApplicationQueriesSchemes</key>
   <array>
    <string>fbapi</string>
    <string>fbapi20130214</string>
    <string>fbapi20130410</string>
    <string>fbapi20130702</string>
    <string>fbapi20131010</string>
    <string>fbapi20131219</string>
    <string>fbapi20140410</string>
    <string>fbapi20140116</string>
    <string>fbapi20150313</string>
    <string>fbapi20150629</string>
    <string>fbauth</string>
    <string>fbauth2</string>
    <string>fb-messenger-api20140430</string>
   </array>

**Comment by nlutsenko** [comment]
Glad you found the solution!
