### ISSUE TITLE
Update Parse - Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by kjelljisaksen** [ParsePlatform/Parse-SDK-iOS-OSX#365]
After installing the latest Parse.framework as well as Bolts.framework my app will not link. It gives the error "Command failed due to signal: Segmentation fault: 11". If I roll back to the last frameworks I used I am able to run (after fixing som casting issues that seems to be handled differently).

I thought it was that I had the wrong version of libz.dylib and libsqlite3.dylib as these where colored red, so I removed them and added them once more (ending up with lib.1.dylib but I guess that is ok). This did however not help.

Part of the attack dump that may help:
-------------------------------------------------------
1.	While type-checking 'viewDidLoad' at /Users/kjell/Documents/MOBITAG/MobitagUtvikling/Dragehjelperen/Dragehjelperen/vcGjerning.swift:207:14
2.	While type-checking expression at [/Users/kjell/Documents/MOBITAG/MobitagUtvikling/Dragehjelperen/Dragehjelperen/vcGjerning.swift:225:9 - line:256:9] RangeText="queryGjerningType.findObjectsInBackgroundWithBlock {
            (objects: [AnyObject]?, error: NSError?) -> Void in
            if error == nil {
                if let objects = objects as? [PFObject] {
                    var strGjernigTypeNavn = ""
                    var imgData = UIImage()
                    //var imageFile : PFFile
                    for object in objects {
                        strGjernigTypeNavn = object["Navn"] as! String
                        let imageFile = object["ikonType"] as! PFFile
                        let dBilde = imageFile.getData()
                        if dBilde != nil {
                            if let imgData = UIImage(data:dBilde!) {
                                //-----------------------------------------------------
                                // Kan ikke kjøre getDataInBackgroundWithBlock
                                // på ikonfilen da append må skje sammen !?!
                                // Kjører vel uansett i annen thread ? Selv om warning?
                                //-----------------------------------------------------
                                self.arrsTyperAvGjerninger.append(strGjernigTypeNavn)
                                self.arrikonTyperAvGjerninger.append(imgData)
                            }
                        } else {
                            regLogg("Gjerning", strTittel: "BILDE", strBeskrivelse: "Mangler bilde Gjerningtype \(strGjernigTypeNavn)",strKategori: "OBS")
                        }
                    }
                    self.tvVelgTypeGjerning.reloadData()
                }
            } else {
                // Log details of the failure
                regLogg("Gjerning", strTittel: "Gjerning type", strBeskrivelse: "Error==>\(error!)",strKategori: "OBS")
            }
        }"
--------------------------------------

Do I have to update any other frameworks?

Any other suggestions?

Regards

Kjell Isaksen

**Comment by nlutsenko** [comment]
Hey @kjelljisaksen, thanks for the report.
Looks like the compiler itself crashes, which is an Apple bug, that we reported already.
The problem arises from the different method signature for closure of `findObjectsInBackgroundWithBlock()`.
It changed from 
`(objects: [AnyObject]?, error: NSError?) -> Void`
to
`(objects: [PFObject]?, error: NSError?) -> Void`

Try updating the method signature, also from the code - it looks like it will help you remove some logic and cleanup code.

Let me know if this helps.

**Comment by kjelljisaksen** [comment]
Well, now more errors are appearing (which may be a good thing since they
are relevant), but I am such with a new error at this
findObjectsInBackgroundWithBlock


------------

        let queryRos = PFQuery(className:"Ros")

        queryRos.whereKey("bObjectId", equalTo: GlobalVars
.strCurrBarnObjectId)

        //queryRos.whereKey("fObjectId", equalTo:
GlobalVars.strCurrFamObjectId)

        queryRos.limit = 30 // limit to at most 10 results

        queryRos.orderByDescending("createdAt")

        queryRos.findObjectsInBackgroundWithBlock {

                (objects: [PFObject]?, error: NSError?) -> Void in

            if error == nil {

                if let arrRos = arrRos {

                    var sBeskrivelse: String = ""

                    var iAntKrystaller: Int = 0

-------------------


It spells : /Users/kjell/Documents/MOBITAG/MobitagUtvikling/Dragehjelperen/Dragehjelperen/vcDragenHoved.swift:906:51:
'([PFObject]?, NSError?) throws -> Void' is not convertible to
'PFQueryArrayResultBlock?'


Any suggestions?


Regards


Kjell Isaksen


2015-10-04 21:05 GMT+02:00 Nikita Lutsenko <notifications@github.com>:

**Comment by kjelljisaksen** [comment]
Sorry. Did go away after some more tries....


2015-10-04 21:46 GMT+02:00 Kjell J Isaksen <kjell.isaksen@mobitag.no>:

**Comment by kjelljisaksen** [comment]
Next issue is this:
---------------------------

        let queryVoksen = PFQuery(className:"Bruker")

        if let currVoksen =
queryVoksen.getObjectWithId(GlobalVars.strCurrBrukerObjectId)
{

            iAntLedige = currVoksen["bLedigeDiamanter"] as! Int

        }


-----------------------------
 Error: /Users/kjell/Documents/MOBITAG/MobitagUtvikling/Dragehjelperen/Dragehjelperen/vcGjerning.swift:2400:12:
Initializer for conditional binding must have Optional type, not 'PFObject'

Suggestions?

Regards

Kjell Isaksen



2015-10-04 21:51 GMT+02:00 Kjell J Isaksen <kjell.isaksen@mobitag.no>:

**Comment by nlutsenko** [comment]
Try replacing with this: `iAntLedige = currVoksen?["bLedigeDiamanter"] as! Int`
It might be different, but hard to grasp, since I don't know the exact type of `iAntLedige` (optional or not)

**Comment by kjelljisaksen** [comment]
It seemed only to need a do - catch statement....like many more places...

Save and rerun...

And I was finally able to run!

Thx for all the help.

Regards

Kjell Isaksen

2015-10-04 22:18 GMT+02:00 Nikita Lutsenko <notifications@github.com>:

**Comment by nlutsenko** [comment]
Glad to help!

**Comment by andreacannella** [comment]
let query = PFQuery(className:"GameScore")

            query.whereKey("playerName", equalTo:"Sean Plott")

            query.findObjectsInBackgroundWithBlock {

                (objects:[AnyObject]?, error:NSError?) -> Void in

                if error == nil {

                    // The find succeeded.

                    print("Successfully retrieved \(objects!.count) scores.")

                    // Do something with the found objects

                    print(objects)

                    if let objects = objects {

                        for object in objects {

                            print(object.objectId)

                        }

                    }

                } else {

                    // Log details of the failure

                    print("Error: \(error!) \(error!.userInfo)")

                }

            }

Try this! It works!
