### ISSUE TITLE
[PFAnalytics trackAppOpenedWithLaunchOptionsInBackground:block:] incorrectly causes network activity indicator to spin

### ISSUE THREAD

**Issue by chrisfuller** [ParsePlatform/Parse-SDK-iOS-OSX#366]
Hello,

After disabling `PFNetworkActivityIndicatorManager`, `trackAppOpenedWithLaunchOptionsInBackground` still causes the network activity indicator to spin.

Example code:

```swift
PFNetworkActivityIndicatorManager.sharedManager().enabled = false
PFAnalytics.trackAppOpenedWithLaunchOptionsInBackground(launchOptions, block: nil)
```

I believe this may be a bug. 

Please advise.

Thanks!

**Comment by nlutsenko** [comment]
Hey @chrisfuller, thanks for the report.
Is it the only method that triggers network activity indicator or any network call still continues to use network activity indicator?

**Comment by chrisfuller** [comment]
@nlutsenko I just tested a `PFUser` query and the network activity indicator was visible also. :( Note that I am calling `PFNetworkActivityIndicatorManager.sharedManager().enabled = false` in `didFinishLaunchingWithOptions`. I am happy to test more on my end to see if it's something unique with my configuration. Please let me know if there is anything else I should test.

**Comment by nlutsenko** [comment]
I wonder if our set to `enabled` is being triggered after this.
Can you try adding a symbolic breakpoint for `PFNetworkActivityIndicatorManager setEnabled:` and looking if it is triggered at any point after your call?

**Comment by chrisfuller** [comment]
Yup, that's correct. It's enabled in `+[PFInternalUtils initialize]` and that's getting called after it's disabled in `didFinishLaunchingWithOptions`.

**Comment by nlutsenko** [comment]
Yup. Looks like a bug. Will fix.

**Comment by chrisfuller** [comment]
@nlutsenko Thanks!

FYI, as a workaround for myself, and until you have the fix in place, I am now calling `+[PFInternalUtils parseServerURLString]` before disabling `PFNetworkActivityIndicatorManager`. Not to use the `parseServerURLString`, but simply so it triggers `+[PFInternalUtils initialize]`. And this hack does work, meaning the network activity indicator is no longer becoming visible. Thanks again for your help, and will look out for the fix.

**Comment by chrisfuller** [comment]
note: I used `NSClassFromString` and `performSelector` to call `parseServerURLString`.
