### ISSUE TITLE
Extreme Latency and delays

### ISSUE THREAD

**Issue by markwelsh** [ParsePlatform/Parse-SDK-iOS-OSX#371]
On our iOS and Android app Fantasy Life we have had many errors and latency tonight. We have not received any emails from Parse to make us aware of these issues like in the past. This is extremely worrisome to my company. Any information would be appreciated.

**Comment by nlutsenko** [comment]
Hey @markwelsh, thanks for the report.
I suggest you file a bug in FB Bug Tool, we are still using that one to track outages/backend issues.
Since we didn't have any outages or elevated error rates that would impact a significant percentage of apps - this looks to be very isolated.
