### ISSUE TITLE
Enhancement : Do not cache file downloads with errors

### ISSUE THREAD

**Issue by ghugues** [ParsePlatform/Parse-SDK-iOS-OSX#375]
If a PFFile download results in an error with a body then this body is cached in the PFFile cache and returned (forever) in subsequent file downloads.
Here is an example erroneous body found in the PFFileCache for what is supposed to be an image :
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront is currently experiencing problems with requesting objects from Amazon S3.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: wQTa-tBMCf16IShvTfla3aRfb9ntBBlLL6rfZYrJZRVtWAztTHI60w==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```
I suggest checking the HTTP response code and only caching successful downloads.

**Comment by nlutsenko** [comment]
We are actually checking status codes. This looks to be a transient CloudFront issue.
Will fix, but quite hard to reproduce.

**Comment by ghugues** [comment]
If you allow yourself to cheat a little it's actually easy to reproduce. Try this :

```
@interface PFFile (PrivateAdditions)
+ (instancetype)fileWithName:(NSString *)name url:(NSString *)url;
@end

PFFile *file = [PFFile fileWithName:@"file-that-does-not-exist" url:@"https://files.parsetfss.com/hi-can-i-get-a-403-please"];
[file getDataInBackgroundWithProgressBlock:nil completionBlock:^(NSData *data, NSError *error) {
	if (!data || error) {
		NSLog(@"Download failed with error : %@.", error);
	} else {
		NSLog(@"Download succeded with data : %@.", [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
	}
}];
```

Of course I have no real way of measuring how often this happens, I imagine Amazon S3 uptime is pretty good. The real problem is that the error will reproduce forever (or at least until the cache is cleared which can be a long time).
