### ISSUE TITLE
SDK 1.9.0 doesn't work under iOS 7

### ISSUE THREAD

**Issue by ghugues** [ParsePlatform/Parse-SDK-iOS-OSX#388]
This sounds too big to be true, but I've tried cleaning caches (same problem), using the Parse Starter Project (same problem) and going back to 1.8.5 (problem solved), it doesn't seem to be coming from my end so here it is (my apologies if I made a terrible mistake) :

When running iOS 7 (and Xcode 6.4), *all* requests made by the SDK fail with the following error :
```
Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (JSON text did not start with array or object and option to allow fragments not set.) UserInfo=0x7b6bb4c0 {NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
```

Digging a little shows that all requests to `api.parse.com` return a 404 response (which then causes the JSON decoding error) :
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.6.0</center>
</body>
</html>
```
It seems that all requests are made to / instead of the correct API path (e.g /1/classes/... )
Everything works fine on iOS 8 and 9.

**Comment by nlutsenko** [comment]
Does indeed sound extremely weird, since iOS 7/8/9 all use the same API and system frameworks to perform network requests.

Do you think there might be something else specific about the device/simulator you are testing this on?

**Comment by ghugues** [comment]
I'm still investigating, as I find that strange as well, but I've removed and re added all simulators, and things work fine if I use 1.8.5 (I'm using cocoapods)

**Comment by nlutsenko** [comment]
I am going to test from my end as well, let me know if you find anything in the meantime.

**Comment by ghugues** [comment]
I think I got it : PFURLConstructor.m line 24. Shouldn't you check for `path` and not `components.path` ?

**Comment by nlutsenko** [comment]
(－‸ლ) Yes! This probably works differently between iOS 7 and later!

**Comment by ghugues** [comment]
Yep, using path seems to solve the issue. I'm a little relieved, I really thought I was losing my mind !

**Comment by nlutsenko** [comment]
Yeah, what seems to be happening is that on iOS 8/9 - this reports an empty string instead of `nil`, whilst on iOS 7 - it is explicitly `nil`. Sending a PR in a second.
