### ISSUE TITLE
ParseFacebookUtils 1.9.0 does not compile

### ISSUE THREAD

**Issue by wimbledon** [ParsePlatform/Parse-SDK-iOS-OSX#389]
```
- (BOOL)restoreAuthenticationWithAuthData:(nullable NSDictionary<NSString *,NSString *> *)authData {
    if (!authData) {
        OSAtomicIncrement32(&_currentOperationId);
        self.tokenCache.facebookId = nil;
        self.tokenCache.expirationDate = nil;
        self.tokenCache.accessToken = nil;
        self.session = nil;
        return YES;
    }

```

**Comment by nlutsenko** [comment]
Looks like you are using Xcode 6.4? This define you looks like our mistake though of not being backward compatible with 6.4. Will fix it, but in the meantime - use Xcode 7, which is the current latest public release from Apple.

**Comment by nlutsenko** [comment]
I am going to close this here, since it's not related to the Parse SDK, but only to ParseFacebookUtils.
The pull request with the fix -> https://github.com/ParsePlatform/ParseFacebookUtils-iOS/pull/1
