### ISSUE TITLE
Push notifications to channels are working inconsistently

### ISSUE THREAD

**Issue by damianesteban** [ParsePlatform/Parse-SDK-iOS-OSX#394]
As of approximately one week ago it seems as though Parse is no longer reliably sending push notifications to channels.  Advanced targeting is working fine (we use both channels and advanced targeting in our application).

We have not modified any of the code (which was working one week ago) related to sending/receiving push notifications, which leads me to believe it is an issue with Parse's services.

Has anything related to push notifications changed recently?  Our application is currently in production and this is a major issue.

We have posted several times on the Parse Google Group and no one from Parse has responded.

Thank you

**Comment by nlutsenko** [comment]
Not aware of any change in terms of Push Notifications.
I would suggest filing a bug at `https://parse.com/help`, since we are still using FB Bugs Tool for backend related issues.
