### ISSUE TITLE
PFFile contentsAtPath fails after upgrading to Parse 1.9

### ISSUE THREAD

**Issue by natecraft1** [ParsePlatform/Parse-SDK-iOS-OSX#395]
This line:
let videoFile: PFFile = PFFile(name: "newMovie.mov", contentsAtPath: videoUrl.path!)
errors out on "Call can throw, but is not marked with 'try' and the error is not handled.

**Comment by richardjrossiii** [comment]
From the [release notes](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases):

> PFFile constructors now report errors instead of throwing exceptions. #345

Update your code to use the swift 2 style of do-try, and everything should work just fine.
