### ISSUE TITLE
Can't get ParseFacebookUtilsV4 working with cocoapods and Xcode 7

### ISSUE THREAD

**Issue by avdwerff** [ParsePlatform/Parse-SDK-iOS-OSX#400]
I have the following in my Podfile:

pod 'ParseFacebookUtilsV4'
pod 'Parse'
pod 'ParseUI'
pod 'ParseCrashReporting'

After pod update and build the project (xcode 7, swift 2) I get the following errors:

/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.h:21:9: Include of non-modular header inside framework module 'FBSDKLoginKit.FBSDKLoginButton'

/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginConstants.h:21:9: Include of non-modular header inside framework module 'FBSDKLoginKit.FBSDKLoginConstants'

/Pods/ParseFacebookUtilsV4/ParseFacebookUtils/Internal/PFFacebookAuthenticationProvider.h:12:9: Could not build module 'FBSDKLoginKit'

If I add this  to the Podfile:

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end

I get: 

/Pods/Headers/Private/FBSDKCoreKit/FBSDKGraphRequestConnection.h:325:1: Unknown type name 'FBSDK_EXTERN'

/Development/Fungry/App/iOS/I am Fungry/Pods/Headers/Private/FBSDKCoreKit/FBSDKGraphRequestConnection.h:325:1: Unknown type name 'FBSDK_EXTERN'

error: unknown type name 'FBSDK_EXTERN'
FBSDK_EXTERN NSString *const FBSDKLoggingBehaviorCacheErrors;
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

Any ideas?

**Comment by nlutsenko** [comment]
Hey @avdwerff, thanks for the report.
This is a known issue with FBSDKCoreKit+FBSDKLoginKit pod that impacts all pods that depend on those.
The workaround for it is to remove`use_frameworks!` from your Podfile.

We are tracking this issue in the appropriate repo, so I am going to close this one out.
https://github.com/ParsePlatform/ParseFacebookUtils-iOS/issues/2
