### ISSUE TITLE
I'm not receiving notifications that were sent while offline

### ISSUE THREAD

**Issue by joshbuddha** [ParsePlatform/Parse-SDK-iOS-OSX#402]
Currently i'm not seeing notifications that were sent while my device was online. I would expect the notification to arrive once the device came back online? 

I'm curious how to troubleshoot this issue further?

Thanks,
Josh

**Comment by nlutsenko** [comment]
Hey @joshbuddha, this is fairly how APNS (Apple Push Notification Service) works, according to [this](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html) guide Quality of Service action.

In practice - the device should usually receive the last notification.
We had few thoughts around guaranteeing delivery of notifications to device and potential ways of implementing this, but this is not yet available.

Let us know if there is anything we could help you with.
