### ISSUE TITLE
findObjectsInBackgroundWithBlock always returning 1 PFObject

### ISSUE THREAD

**Issue by santanu4ver** [ParsePlatform/Parse-SDK-iOS-OSX#41]
Last known working date: Unknown
Affected app: VoteYourSpider
Using Parse (1.7.5.3)
Using ParseUI (1.1.4)

```
query.whereKeyExists("name")
query.findObjectsInBackgroundWithBlock { (objects: [AnyObject]?, error: NSError?) -> Void in
            
     if error == nil
     {
                if let pfObjects = objects as? [PFObject]
                {
                    println(pfObjects)
                    completinHandler(pfObjects, true)
                    return
                }
            }
            
            // anything else
            completinHandler(nil, false)
}
```

The above query supposed to return all the records exists in my table, but always returning one PFObject.

**Comment by hramos** [comment]
@santanu4ver are you reusing the query object? If so, does this problem still happen if you use a new query object?

**Comment by santanu4ver** [comment]
Yah. I just tested by creating different instances of query class and that resolved the issue, as suggested in https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/40, too! Thanks! :smile:
