### ISSUE TITLE
Push abort?

### ISSUE THREAD

**Issue by doudou2012** [ParsePlatform/Parse-SDK-iOS-OSX#412]
please help ,
why has 101 push ? thanks!
app: iweekly-iphone

![screenshots](https://cloud.githubusercontent.com/assets/3632875/10479815/1138e966-7299-11e5-8f08-9b2f301927af.png)

**Comment by nlutsenko** [comment]
Hey @doudou2012, thanks for the report.

I would suggest filing a request on https://parse.com/help , since we are tracking backend/web console issues through FB Bug Tool.
