### ISSUE TITLE
Library not found?

### ISSUE THREAD

**Issue by haleyngonadi** [ParsePlatform/Parse-SDK-iOS-OSX#413]
I just updated my podfile, which contained the ParseFacebookUtilsV4 library. After the update, Terminal read: Installing ParseFacebookUtilsV4 1.9.0 (was 1.8.5)

Everything was working fine until the update. Now, the project won't upload because: 

>ld: library not found for -lParseFacebookUtilsV4Lib
>clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have checked and I see the library so I'm not sure what is causing this error?!

**Comment by nlutsenko** [comment]
Hey @haleyngonadi, sounds super strange.
I suggest trying to clear your targets `other linker flags` in build settings and re-running `pod install`, also maybe clean derived data?

**Comment by nlutsenko** [comment]
Let me know if it helps.
