### ISSUE TITLE
Localization is fucked since Parse 1.8

### ISSUE THREAD

**Issue by wouterds** [ParsePlatform/Parse-SDK-iOS-OSX#42]
What happened guys? Where are all the previous versions? What's the reason all the previous releases were deleted?? Who does that?

Because there's only 1.8 everyone upgraded to the latest version and everyone is fucked. This version is breaking Localization and there's no way to downgrade.

Good job!

Edit: sorry about all the rage, took some time to debug and find what the exact issue was.

**Comment by wouterds** [comment]
Apparently a duplicate of #16

**Comment by wouterds** [comment]
Never the less, still interested why older releases were deleted.

**Comment by wouterds** [comment]
Apparently because of license issues since the opensourcing of the SDK the previous versions are no longer available I just read somewhere.

Full story about the opensourcing of the SDKs: http://blog.parse.com/announcements/open-sourcing-our-sdks/

**Comment by nlutsenko** [comment]
Old versions of the SDK are still available through Cocoapods and website downloads.
Not aware about the licensing issues, but the answer to the question on why didn't we open source previous versions as well - because it's not really useful to use old things.
We are working hard to fix any issue in a matter of days if not hours, so rolling forward (using the latest) is preferred to rolling backward (using the previous).

**Comment by natanrolnik** [comment]
@wouterds I suggest you to read the [code of conduct] (https://code.facebook.com/pages/876921332402685/open-source-code-of-conduct) before posting issues this way. Even though Parse may be a paid service for some users, their developers aren't supposed to deal with comments like this. Please be more considerate next time.
Not only it was a duplicate of another issue, as you posted, you could use CocoaPods to point to the previous version.

**Comment by wouterds** [comment]
@natanrolnik: I was using Cocoapods and it didn't take any of the previous/older versions anymore, always picked 1.8 (in my Podfile I was using `pod 'Parse', '~> 1.7'`).

Updated original post with more info and removed all the unnecessary rage.

**Comment by natanrolnik** [comment]
@wouterds Hope it works for you now 👍🏻

**Comment by wouterds** [comment]
@natanrolnik It does after removing derived data & updating to 1.8.1 👌!
