### ISSUE TITLE
Parse SDK Fails FB Login With No Error Code

### ISSUE THREAD

**Issue by rcldesign** [ParsePlatform/Parse-SDK-iOS-OSX#420]
Using: 

Parse SDK 1.9.0
FB SDK 4.6

The following code snippit sometimes returns nil for both the user object and the error object. 

    NSArray* permissionArray = @[@"email", @"user_friends"];
    FBSDKLoginManager *login = [[FBSDKLoginManager alloc] init];
    [login logOut];
    
    
    [PFFacebookUtils logInInBackgroundWithReadPermissions:permissionArray block:^(PFUser *user, NSError *error)

This is attached to a custom button in our app. When the user taps the button, the FB SDK works as expected (launches a Safari view, authenticates user, etc.), but when the call returns, both objects are nil. 

We hypothesize that this is somehow related to this bug: https://developers.facebook.com/bugs/865668060184806/

However due to the fact that this problem seems to only affect users randomly, we're not sure and reliably duplicating this issue is more or less impossible. For example, on one device, we don't have problems logging in with a FB account, but on a different device, using the same FB account, the login will fail in this way.

**Comment by richardjrossiii** [comment]
Thanks for the report. This sounds really strange.

Firstly, to see if it's our issue and not FBDSKs, if you change to the `BFTask` version of the API, and continue on that, can you print out the description of the task that's returned? It will provide much more information than the block callback.

**Comment by rcldesign** [comment]
I'd bet dimes to doughnuts it is a FB SDK issue (we didn't have this issue specifically with 4.5.1 but there were other iOS 9 issues). We'll give your suggestion a try tonight and see if we can get the problem to occur.
