### ISSUE TITLE
PFTwitterUtils has  no member 'twitter' [Xcode 7.0.1 - Mac OSX El capitan]

### ISSUE THREAD

**Issue by jsanchezbcn** [ParsePlatform/Parse-SDK-iOS-OSX#421]
I've just created a new project from scratch to avoid any other interaction.

Added these pods to Podfile

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Parse'
pod 'ParseTwitterUtils'
pod 'ParseFacebookUtilsV4'

I'm not using use_frameworks! because it fails on the ParseFacebookUtilsV4, I think is a know issue.

Execute pod install, and write some test code:

Add #import <ParseTwitterUtils/PFTwitterUtils.h> to bridging header.

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        PFTwitterUtils.initializeWithConsumerKey("", consumerSecret: "") <--- It's ok
        PFTwitterUtils.twitter <-----PFTwitterUtils has  no member 'twitter'
        PFTwitterUtils.twitter() <------ PFTwitterUtils has  no member 'twitter'
        return true
    }

Apparently anything on PDTwitterUtils except the twitter property can be accessed.
<img width="732" alt="screenshot 2015-10-15 22 28 01" src="https://cloud.githubusercontent.com/assets/1147116/10526577/0c7e0868-738c-11e5-91c8-979e0639097c.png">

**Comment by nlutsenko** [comment]
This sounds super strange, as I've just tested this on a generic project installing everything from scratch and it works great. It definitely is `PFTwitterUtils.twitter()` and compiles without any problems.

Quick question - in your ObjC bridging header - do you have proper import for `ParseTwitterUtils` aka via it's umbrella header aka `#import <ParseTwitterUtils/ParseTwitterUtils.h>`.

Here is the repro project that I've used: 
http://cl.ly/dY6v

**Comment by jsanchezbcn** [comment]
I've checked what was different in your sample project than mine, and it was that the Podfile had a different format:

I've changed from:

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Parse'
  pod 'ParseTwitterUtils'
  pod 'ParseFacebookUtilsV4'

To:

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PodTest' do
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Parse'
  pod 'ParseTwitterUtils'
  pod 'ParseFacebookUtilsV4'
end


And now it works fine, I still have the issue on my production project but I will try to figure out why. Now at least I can access to the twitter member on the sample project, so I think is not an issue on the Parse library.

Thanks for the help. I close the issue

**Comment by aakash-copper** [comment]
I am having the same issue. Were you able to find what the problem was?

**Comment by jsanchezbcn** [comment]
aakash-copper, as I commented on the previous post, just adding the "target 'PodTest' do" fixed the issue, I just created a new podfile from scratch and added the needed pods
