### ISSUE TITLE
trackAppOpenedWithRemoteNotificationPayload not working

### ISSUE THREAD

**Issue by FreudGit** [ParsePlatform/Parse-SDK-iOS-OSX#423]
1.9.0

Receiving a push, I can see that trackAppOpenedWithRemoteNotificationPayload are called, BUT "PUSH OPENS" stay at zero on the push report.
Any Idea?

    func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject]) {
       
        PFPush.handlePush(userInfo)
        if application.applicationState == UIApplicationState.Inactive {
            PFAnalytics.trackAppOpenedWithRemoteNotificationPayload(userInfo)
        }
    }

**Comment by nlutsenko** [comment]
Does the push open stat changes in the Analytics console?
We've seen another report about this #411, where the analytics console is there, but the push opens in the push console is not.

Since both this one and #411 look to be purely backend issues - I would suggest filing a report at https://parse.com/help , since we are using that one for tracking backend/web frontend issues.

**Comment by juliengomes** [comment]
@nlutsenko I'm not sur it's a backend issue, I have the same issue, when I set a breakpoint on the call to ```trackAppOpenedWithRemoteNotificationPayload:``` it works fine, ie I can see 1 push open in the dashboard, but when I remove the breakpoint, there is 0 push open in the dashboard.

Here is how I call it 

```objc
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler {
    [PFAnalytics trackAppOpenedWithRemoteNotificationPayload:userInfo];
    [PFPush handlePush:userInfo];
    completionHandler(UIBackgroundFetchResultNewData);
}
```

**Comment by nlutsenko** [comment]
Ok, let's try debugging this then...

Could you try instrumenting your app with the network debug piece that we have outlined in https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool
And look into whether the request for tracking app opened is actually sent?
It's definetly super weird behavior that the breakpoint here causes this to send out...

Also, since the `PFAnalytics.trackAppOpenedWithRemoteNotificationPayload()` is returning a `BFTask`, could you chain on it and output the result/error inside?
Something like:
```objc
    [[PFAnalytics trackAppOpenedWithRemoteNotificationPayload:userInfo] continueWithBlock:^id _Nullable(BFTask<NSNumber *> * _Nonnull task) {
        NSLog(@"%@", task);
        NSLog(@"%@ %@ %d", task.result, task.error, task.cancelled);
        return nil;
    }];
```

**Comment by juliengomes** [comment]
Here is what I get when there is no breakpoint (still 0 push open in the dashboard) :

```
2015-11-20 23:55:35.830 Prunelle[8145:1340782] URL : https://api.parse.com/1/events/AppOpened
2015-11-20 23:55:35.830 Prunelle[8145:1340782] Method : POST
2015-11-20 23:55:35.837 Prunelle[8145:1340782] Headers : {
    "Content-Type" = "application/json; charset=utf-8";
    "X-Parse-Installation-Id" = "72c50fb7-94b7-443d-8420-e59e1d20c344";
}
2015-11-20 23:55:35.839 Prunelle[8145:1340782] Request Body : {"at":{"iso":"2015-11-20T22:55:35.802Z","__type":"Date"},"push_hash":"e1b923468d9cba4d7df454f56aca59f6"}
2015-11-20 23:55:35.965 Prunelle[8145:1340769] URL : https://api.parse.com/1/events/AppOpened
2015-11-20 23:55:35.977 Prunelle[8145:1340769] Status Code : 200
2015-11-20 23:55:35.978 Prunelle[8145:1340769] Headers : {
    "Access-Control-Allow-Methods" = "*";
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 3;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Fri, 20 Nov 2015 22:55:35 GMT";
    Server = "nginx/1.6.0";
    "X-Parse-Platform" = G1;
    "X-Runtime" = "0.011188";
}
2015-11-20 23:55:35.988 Prunelle[8145:1340769] Response Body : {}
2015-11-20 23:55:36.010 Prunelle[8145:1340767] <BFTask: 0x16ee7460; completed = YES; cancelled = NO; faulted = NO; result = 1>
2015-11-20 23:55:36.011 Prunelle[8145:1340767] 1 (null) 0
```

And here is what I get when I set the breakpoint before the call to ```trackAppOpenedWithRemoteNotificationPayload ``` (1 push open in the dashboard)

```
2015-11-21 00:05:19.441 Prunelle[8162:1342609] URL : https://api.parse.com/1/events/AppOpened
2015-11-21 00:05:19.442 Prunelle[8162:1342609] Method : POST
2015-11-21 00:05:19.443 Prunelle[8162:1342609] Headers : {
    "Content-Type" = "application/json; charset=utf-8";
    "X-Parse-Installation-Id" = "72c50fb7-94b7-443d-8420-e59e1d20c344";
}
2015-11-21 00:05:19.443 Prunelle[8162:1342609] Request Body : {"at":{"iso":"2015-11-20T23:05:19.418Z","__type":"Date"},"push_hash":"76debf9f9ecee7d91a616b3df657bee7"}
2015-11-21 00:05:20.005 Prunelle[8162:1342609] URL : https://api.parse.com/1/events/AppOpened
2015-11-21 00:05:20.006 Prunelle[8162:1342609] Status Code : 200
2015-11-21 00:05:20.009 Prunelle[8162:1342609] Headers : {
    "Access-Control-Allow-Methods" = "*";
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 3;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Fri, 20 Nov 2015 23:05:19 GMT";
    Server = "nginx/1.6.0";
    "X-Parse-Platform" = G1;
    "X-Runtime" = "0.014353";
}
2015-11-21 00:05:20.011 Prunelle[8162:1342609] Response Body : {}
2015-11-21 00:05:31.256 Prunelle[8162:1342678] <BFTask: 0x16c048b0; completed = YES; cancelled = NO; faulted = NO; result = 1>
2015-11-21 00:05:31.257 Prunelle[8162:1342678] 1 (null) 0
```

I really don't understand what's going, it seems like everything is well went, but I keep not seing push open when breakpoints are not set.
The tests run on an iPad 2 iOS 8.3

I make the test while the app is in the active state, I'm going to try on a blank project to check if I have the same results.

**Comment by nlutsenko** [comment]
Huh... There is a difference in push_hash there.
Are you using the same `user_info` for both scenarios?

**Comment by juliengomes** [comment]
Yes it's the exact same code portion (```didReceiveRemoteNotification:fetchCompletionHandler:```) I outputed, but I tried with two different push hence the hash difference (I think)

**Comment by nlutsenko** [comment]
Maybe that's the thing - try the same user info...

**Comment by juliengomes** [comment]
I made a temporary repo, I have the same issue with a blank project, you can check it there : https://github.com/juliengomes/ParseDebug

**Comment by nlutsenko** [comment]
@juliengomes I've checked out the repo and the code looks absolutely fine.
Will try to poke around few more times, but it looks like it's sending the network request every time, so no sure there is much we can do from the client end.

@juliengomes Could you file a bug report at https://parse.com/help against our backend team, since we are still using FB Bug Tool to track those.
