### ISSUE TITLE
can not set device token in ios7 device

### ISSUE THREAD

**Issue by keyhui-heha** [ParsePlatform/Parse-SDK-iOS-OSX#424]
ios8 & ios9 work fines , but ios7

some related posts
http://stackoverflow.com/questions/33160713/cocoa-error-3840-parse-code-ios7-only
http://stackoverflow.com/questions/33145043/parse-not-upload-devicetoken-for-ios7

**Comment by nlutsenko** [comment]
Hey @keyhui-heha, thanks for the report.
I think it was already addressed by #390.

That Pull Request addresses specific problem to iOS 7, which addresses network errors with exact same code.
One thing that might be useful to try - installing `master` via CocoaPods and running your app on iOS 7 device again (aka add `pod 'Parse', :branch => 'master'` to your Podfile).

Let me know how it goes, I will also keep this issue open until we have 1.9.1 released (coming very soon), which is going to have the same fix available for everyone.
