### ISSUE TITLE
request.user returns null in beforeSave function

### ISSUE THREAD

**Issue by inovotek** [ParsePlatform/Parse-SDK-iOS-OSX#425]
In a beforeSave callback, I want to get a reference to the requesting user by getting request.user, however it returns null. I am very sure that [PFUser currentUser] is not nil before making the saveInBackgroundCall, in fact there is an attribute in the object being saved that holds a pointer to the curent user. 

Using iOS SDK 1.9

**Comment by inovotek** [comment]
I have verified that this issue only occurs if the client is running on the iOS Simulator. In a real device, the requesting user is returned.

**Comment by nlutsenko** [comment]
Hey @inovotek thanks for the report.
Super weird, since it should be identical from our perspective.

Maybe you got the simulator in a weird state? Try resetting it by going into iOS Simulator -> **Simulator** in menu -> Reset Content and Settings.

**Comment by inovotek** [comment]
Hi @nlutsenko , thanks for the insight. Indeed it was the simulator causing the trouble. Reset Content and Settings fixed it.

**Comment by nlutsenko** [comment]
Glad it helped!
