### ISSUE TITLE
Parse Localizable.strings make app to ignore default Localizable.strings

### ISSUE THREAD

**Issue by robertodias180** [ParsePlatform/Parse-SDK-iOS-OSX#44]
The file "Localizable.strings" that is present in Parse is overriding the Localizable.strings that already existis as the default app string file. 

Using this name probably is not the best approach. Unless i am missing something. 

should i fix and send a pull request?

**Comment by tilowestermann** [comment]
Just discovered this issue, too  ... +1

**Comment by wouterds** [comment]
@robertodias180 @tilowestermann: see #42 & #16.

I am currently using the following Run Script Phase: `rm -rf "$TARGET_BUILD_DIR/$FULL_PRODUCT_NAME/Localizable.strings"`

**Comment by nlutsenko** [comment]
Hey guys, as specified in #16 - it's already fixed in master. Closing this one out as duplicate.
