### ISSUE TITLE
[query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) with iOS 7

### ISSUE THREAD

**Issue by marian19** [ParsePlatform/Parse-SDK-iOS-OSX#449]
when i try to use [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) with iOS 7 , it always returns this error " nserror * domain @ nscocoaerrordomain - code 3840"

**Comment by drewlarsen** [comment]
I think is probably a duplicate of the error I filed yesterday:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/448

**Comment by nlutsenko** [comment]
Duplicate of #448, indeed.
