### ISSUE TITLE
Revocable session is invalidated when anonymous user becomes registered

### ISSUE THREAD

**Issue by ako2009** [ParsePlatform/Parse-SDK-iOS-OSX#459]
To reproduce the issue just set "Require Revocable Sessions" to YES and then run the code below.

```
    [Parse setApplicationId:PARSE_APP_ID clientKey:PARSE_CLIENT_KEY];
    [PFUser enableAutomaticUser];
    
    [PFUser currentUser][@"name"] = @"unknown";
    [[PFUser currentUser] saveInBackgroundWithBlock:^(BOOL succeeded, NSError * _Nullable error) {
        
        // Revocable session is appeared on Parse, it's OK
        
        PFUser* user = [PFUser user];
        user.username = @"test@test.com";
        user.password = @"test";
        
        [user signUpInBackgroundWithBlock:^(BOOL succeeded, NSError* error) {
            
            // Revocable session is removed on Parse, it's FAIL
            // Session is removed in any case, if there is error or not
            
        }];
    }];
```

**Comment by ako2009** [comment]
There is also another issue connected with the process of anonymous user registering  - https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/393

**Comment by nlutsenko** [comment]
Hey @ako2009, thanks for the report.
Any chance you can specify the version of the SDK you are using?
We had a bugfix around this issue few versions of the SDK ago.

**Comment by ako2009** [comment]
I tested it using SDK v1.9.0. The last version is 1.9.1, but there are no changes for anonymous users.

**Comment by ako2009** [comment]
Hello,

I added a bug for the backend team -
https://developers.facebook.com/bugs/1045853882115643/

Thank you,
Andrew

**Comment by nlutsenko** [comment]
Looks like the issue on FB Bug Tool was closed out, so I am going to close this one as well.
Let me know if there is anything here that I've missed.
