### ISSUE TITLE
PFuser fetchInBackgroundWithBlock is not returning full object

### ISSUE THREAD

**Issue by russnettle** [ParsePlatform/Parse-SDK-iOS-OSX#460]
Summary of the bug:Sporadic but I have a PFUser pointer in my PFUser object called 'significantOther' I can see this contains a value in the parse data browser. However, if I call 
[pfuser fetchInBackgroundWithBlock...

the return object is missing the value to this completely. However if i call

    PFQuery *userQuery = [PFUser query];
    [userQuery whereKey:@"objectId" equalTo:[PFUser currentUser].objectId];
    [userQuery findObjectsInBackgroundWithBlock:^(NSArray *objects ,  NSError *error){

the object returned shows the correctfields

Steps to reproduce the bug: as above

Relevant code snippets from your implementation:
    [[PFUser currentUser]fetchInBackgroundWithBlock:^(PFObject *object, NSError *error) {
        if (object && !error) {
            if (object[@"significantOther"]) {
// returns nil

}
}
}];

    PFQuery *userQuery = [PFUser query];
    [userQuery whereKey:@"objectId" equalTo:[PFUser currentUser].objectId];
    [userQuery findObjectsInBackgroundWithBlock:^(NSArray *objects ,  NSError *error){
PFObject *object = [objects firstObject];
if (object[@"significantOther"]) {
//returns object

**Comment by russnettle** [comment]
![screen shot 2015-10-23 at 16 17 11](https://cloud.githubusercontent.com/assets/5123908/10698865/10f5ea9e-79ab-11e5-90d2-85abffb12e4c.png)

**Comment by nlutsenko** [comment]
Hey @russnettle, thanks for the report.
Any chance you can post your User object schema here?
I wonder what do the ACLs look like on both of these.

**Comment by russnettle** [comment]
Hey - @nlutsenko  - no Worries
Attached a screenshot of the acl and structure in the User class - ACL seems good

![screen shot 2015-10-26 at 10 00 19](https://cloud.githubusercontent.com/assets/5123908/10726097/71d90bce-7bc8-11e5-8543-43c863553fc5.png)

**Comment by nlutsenko** [comment]
@russnettle Could you attach or send a repro project/code snippet here that reproduces the issue?
(email: nlutsenko(at)fb.com)
This is super strange, since at least all pointers should be fetched.
