### ISSUE TITLE
Parse returns no users when login by email with existing in DB or just registered user

### ISSUE THREAD

**Issue by OlegPanfyorov** [ParsePlatform/Parse-SDK-iOS-OSX#461]
I`m trying to login by email with existing in parse account or with just registered user but Parse tells no user. Using Parse (1.9.0)

Code=3 "Please check the username or email and try again" UserInfo={NSLocalizedDescription=Please check the username or email and try again, NSLocalizedFailureReason=Unable to log in}

**Comment by nlutsenko** [comment]
Hey @OlegPanfyorov,

This looks super strange, can you add a little more info?
Specifically, specifying what does your row look like in User class in Data Browser and what values you are using on the client?

Please note - PFUser login requires username and password. You can use email as username for your users, but it's not the same as `email` field on the User class.
