### ISSUE TITLE
user creation through lazy loading (enableAutomaticUser) does not call a PFUser subclass +user method

### ISSUE THREAD

**Issue by hhanesand** [ParsePlatform/Parse-SDK-iOS-OSX#463]
If you register a `PFUser` subclass with parse, such as this : 

```objective-c
[ABConsumer registerSubclass];
```

and then call `[ABConsumer enableAutomaticUser]`, the `+user` method in the subclass is not called on user creation :
```objective-c
// user method in ABConsumer subclass
+ (instancetype)user {
    // Breakpoint never hit
    ABConsumer *user = (ABConsumer *)[super object];
    user.details = [ABUserDetails object];
    return user;
}
```

Is there another method I can hook into, or am I doing something wrong?

**Comment by richardjrossiii** [comment]
It should not. We do not guarantee that *any* initializer is called when subclassing PFObject. The current implementation, however, will always invoke `-init` on a created PFObject. But once again, this is an implementation detail and subject to change.

**Comment by hhanesand** [comment]
Ok, thanks for the info. How do you suggest I initialize default properties in user subclasses when using automatic users (preferably without cloud code)?
