### ISSUE TITLE
Parse 1.9.0 Doesn't Sync test Objects 

### ISSUE THREAD

**Issue by davidlong028** [ParsePlatform/Parse-SDK-iOS-OSX#464]
I am attempting to run the following : 
 
>let testObject = PFObject(className: "TestObject")
        testObject["foo"] = "bar"
        testObject.saveInBackgroundWithBlock { (succeeded, error) -> Void in
            print("Object has been saved.")
        }

in my ViewController file. I am doing this as a test, and its supposed to return an value to the Parse database for the test app, but it does not. 

I have also tried this code: 

>let user = PFUser()
user.username = "my name"
user.password = "my pass"
user.email = "email@example.com"
 // other fields can be set if you want to save more information
user["phone"] = "650-555-0000"
 user.signUpInBackgroundWithBlock { (success: Bool, error: NSError!) -> Void in
  if error == nil {
    // Hooray! Let them use the app now.
  } else {
    // Examine the error object and inform the user.
  }
}

to no avail. 

I have the api keys in my delegate file, the builds succeed, but parse receives no data. 

Any suggestions?

**Comment by hhanesand** [comment]
Are you getting any error messages in the console?

**Comment by davidlong028** [comment]
no, none whatsoever

**Comment by davidlong028** [comment]
?

**Comment by davidlong028** [comment]
I'm still having this issue. I am unable to start my app until this situation is resolved. I have tested other apps and know that this isn't an issue with the code, but there has to be an issue with Parse. Can someone help with this?

**Comment by richardjrossiii** [comment]
> I have tested other apps

What precisely do you mean by this? If you're saying that you have multiple apps on Parse.com, and all but this one works, then this is certainly a backend bug, which should be filed with the backend team, which still tracks bugs through https://parse.com/help.

Otherwise, I have tested that code, and it seems to be working for me, perhaps you could share a small project that reproduces this use-case?
