### ISSUE TITLE
Parse 1.9.0 not working under 7.1.1 device

### ISSUE THREAD

**Issue by Ricardo1980** [ParsePlatform/Parse-SDK-iOS-OSX#465]
I receive this message in my iPhone 7.1.1 when trying to login or call findObjectsInBackgroundWithBlock

Printing description of error:
Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (JSON text did not start with array or object and option to allow fragments not set.) UserInfo=0x17807eb40 {NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

However, in the simulator (ios 9.0), works perfectly.

Any idea?
Thanks.

**Comment by nlutsenko** [comment]
@Ricardo1980 this was fixed in 1.9.1 version of the SDK, which was released just yesterday.
Let me know if the latest version works for you.

**Comment by Ricardo1980** [comment]
Awesome! Now it works, thanks!
