### ISSUE TITLE
isLinkedWithAuthType returns true after failed account linking attempt

### ISSUE THREAD

**Issue by bybyron** [ParsePlatform/Parse-SDK-iOS-OSX#467]
After attempting to link to a Facebook/Twitter account that already exists, the correct error is returned:
"Another user is already linked to this facebook/twitter id"

using the "isLinkedWithUser" method returns the correct result, however when the application is closed and re-opened the "isLinkedWithUser" method returns true for the failed attempt

one is then able to retrieve information (friends list/email) etc for the account that failed to link

logging out and back in resets the behaviour back to normal.. I have spend hours attempting to debug this issue.. if it is something within my implementation then I need to address this further.. however if this is a bug with the SDK then it is a security flaw so I thought it was worth reporting, even if it turns out to be my implementation

**Comment by nlutsenko** [comment]
Hey @bybyron, thanks for the report.
Will take a look in-depth, but I guess it is indeed an issue.

**Comment by nlutsenko** [comment]
Valid bug, just reproduced with a test app. Fix is incoming...

Workaround: Try saving the user again - it will be persisted to disk at that point.

**Comment by bybyron** [comment]
thanks for the response, glad to have helped
