### ISSUE TITLE
PFObject thinks 'YES' and 'NO' in BOOL property is a 'number'

### ISSUE THREAD

**Issue by fatuhoku** [ParsePlatform/Parse-SDK-iOS-OSX#47]
I got an error on `saveEventually` about this when I updated to 1.8.0.

Say I have a custom subclass called `MyObject`. The following errors out:

```objc
MyObject *obj = [MyObject object];
obj.isAwesome = NO;
[obj save];
```

Just following syntax here: http://blog.parse.com/announcements/stay-classy-objective-c-introducing-native-subclasses-for-parse-objects/

The workaround for now is of course to set a bool value on the object:

```objc
...
obj[@"isAwesome"] = @NO;
...
```

**Comment by nlutsenko** [comment]
Hey @fatuhoku, looks like this is duplicate of #13 (BOOL vs NSNumber) and it was already fixed in master.

**Comment by fatuhoku** [comment]
@nlutsenko Fantastic!
