### ISSUE TITLE
iOS SDK 1.9.1 on iOS 9.1 on iPhone 6s PLUS is slow to make concurrent PFQuery calls

### ISSUE THREAD

**Issue by kross50** [ParsePlatform/Parse-SDK-iOS-OSX#474]
SDK 1.9.0 was fast so I'm going back to it.

**Comment by nlutsenko** [comment]
Not sure what happened here. 
Is it still slow for you? 
There is not much that changed in terms of query performance, so I am somewhat skeptical about this.

**Comment by kross50** [comment]
Ended up being an issue with my internet providers connection.  Thank you for the reach out :)

Sent from my iPhone

On Oct 26, 2015, at 6:45 PM, Nikita Lutsenko <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what happened here.
Is it still slow for you?
There is not much that changed in terms of query performance, so I am somewhat skeptical about this.

-
