### ISSUE TITLE
PFQuery key containedIn array of pointers. 

### ISSUE THREAD

**Issue by chlebta** [ParsePlatform/Parse-SDK-iOS-OSX#476]
Hello, 
I'm trying to run this query 
```
 PFQuery *query = [PFUser query];
    [query whereKey:@"objectId" notEqualTo:[PFUser currentUser].objectId];
    [query whereKey:@"objectId" containedIn:[[Global sharedInstance] currentUserDetails][@"following"]];
```
 But I get no objects always.
**[[Global sharedInstance] currentUserDetails][@"following"]** return an array of _UserPointers.

What's the problem what did I missed there ?

**Comment by nlutsenko** [comment]
`objectId` is not the same as an array of pointers.
Additionally, `_UserPointer` is different class from `_User` (the latter is the class name used for user pointers).

Try using this snippet:
```objc
 PFQuery *query = [PFUser query];
 [query whereKey:@"objectId" notEqualTo:[PFUser currentUser].objectId];
 [query whereKey:@"objectId" containedIn:[[[Global sharedInstance] currentUserDetails][@"following"] valueForKey:@"objectId"]];
```

**Comment by chlebta** [comment]
Thank's for the help and explenation

**Comment by nlutsenko** [comment]
Hope it helped.
Let me know if there is anything else.

**Comment by acegreen** [comment]
@nlutsenko a side question:
Can we have two containedIn, for two separate keys, in one query? query.containedIn("Key1", [2,3,4]); query.containedIn("Key2", [7,8,9]); ??

When I do that, I get no objects as well.

**Comment by chlebta** [comment]
@acegreen yes you can have multiple containedIn in same query. 
You get nothing because there's no row match your query.
