### ISSUE TITLE
Two different command cacheKey for same query.

### ISSUE THREAD

**Issue by marcinwalus** [ParsePlatform/Parse-SDK-iOS-OSX#478]
Referring to: cacheKey property in PFRESTCommand class

Using this code
```swift
let query = PFQuery(className: "Location")
query.whereKey("objectId", equalTo: "...id...")
query.includeKey("organization")
query.includeKey("city")
query.includeKey("city.country")
query.includeKey("city.country.language")
```
hash for parse command (base on parameters, like "order", "include") may not be the same.

In my example I'm getting two different cache keys depend on iPhone version (5 and earlier vs 5S and later):

iPhone 5 (simulator)
parametersCacheKey = {parameters:{include:"**city.country,organization,city,city.country.language**",where:{objectId:"...id...",},},}
iPhone 5S (simulator)
parametersCacheKey = {parameters:{include:"**organization,city.country.language,city.country,city**",where:{objectId:"...id...",},},}

And obviously hash for two different cache keys (strings) will be different too.

My workaround for now is to use this approach when making multiple includeKey calls
```swift
let query = PFQuery(className: "Location")
query.whereKey("objectId", equalTo: "...id...")
query.includeKey("organization,city,city.country,city.country.language")
```
When using this approach then I'm getting same cache key on both platforms:

iPhone 5 (simulator)
parametersCacheKey = {parameters:{include:"**organization,city,city.country,city.country.language**",where:{objectId:"...id...",},},}
iPhone 5S (simulator)
parametersCacheKey = {parameters:{include:"**organization,city,city.country,city.country.language**",where:{objectId:"...id...",},},}

But I think this is a bug in Parse framework. cacheKey property should return same value no matter platform.

**Comment by nlutsenko** [comment]
@marcinwalus, that sounds about right.
Do you notice if the keys change on the same device?

I wonder why does this matter, since the keys are used for query caching and aren't used anywhere outside of local device.

**Comment by marcinwalus** [comment]
@nlutsenko No, on same device it is always the same.

I think the reason for this is that according to documentation: 
> "NSSet.allObjects(): An array containing the set’s members, or an empty array if the set has no members. (read-only). **The order of the objects in the array is undefined.**" 

And thats why sometimes (in this case due to different platforms 32bit vs 64bit) we are getting parameters in different order. But it probably may happen even on the same platform.

Scenarios? I have two right now two in my mind. 
1. When you backup your phone in iTunes and restore it on different device (the question is: is Caches folder copied also? not sure right now - so this scenario is probably a poor example).
2. You "manually" backup parse cache folder, bundle it with your app and restore it on first launch (just to have some initial data in your app). In this case you won't see initial data on one of the platform (iPhone 5 or iPhone 5S, depends on which platform you created cache).

**Comment by nlutsenko** [comment]
I see...
Yup, those use cases are indeed valid.
(Caches are not backed up/copied though), but the second one makes sense.

Will address this with a PR.
