### ISSUE TITLE
fetch and fetchifneeded unavailable in Swift

### ISSUE THREAD

**Issue by AngeloGiurano** [ParsePlatform/Parse-SDK-iOS-OSX#479]
fetchIfNeeded and fetch are unavailable in Swift?

**Comment by nlutsenko** [comment]
They are, but only with 'throws' syntax. 
If you still fail to find them - can you paste the PFObjecy generated interface that you see?

**Comment by AngeloGiurano** [comment]
<img width="862" alt="screenshot 2015-10-27 19 36 01" src="https://cloud.githubusercontent.com/assets/6850571/10768550/0e500718-7ce2-11e5-9233-836242b465a4.png">

This are the methods I find, there are just fetch and fetchIfNeeded with throws can't find the ones which don't throw

**Comment by nlutsenko** [comment]
As I specified previously - the only ones available on Swift is the ones with throws syntax. 
It provides better compile-time guarantees in your code.

**Comment by AngeloGiurano** [comment]
Yes, I know exactly. The only problem was I had to downcast to PFObject
