### ISSUE TITLE
Pinned object has no createdAt

### ISSUE THREAD

**Issue by rossrossp** [ParsePlatform/Parse-SDK-iOS-OSX#483]
I have noticed that when I pin a newly created object, its createdAt value is null. I must save the object and then fetch it from the server again in order to see the createdAt value populated.
![screen shot 2015-10-27 at 22 37 23](https://cloud.githubusercontent.com/assets/6325131/10774799/59f30558-7cfb-11e5-967d-2ac8c5f5bac7.png)

**Comment by nlutsenko** [comment]
This is intended and by design.
`createdAt` designates a date when the object was created on the server.
If you need a client-side createdAt - I would suggest creating your own custom column.
