### ISSUE TITLE
PFFileCache does not get cleared out by iOS

### ISSUE THREAD

**Issue by MobileVet** [ParsePlatform/Parse-SDK-iOS-OSX#488]
We are finding that our application disk usage grows significantly due to the PFFileCache that is stored by Parse.  Our app uploads a log file to the server every 5 min.  There is also another image that is saved numerous times in the cache despite not changing at the client level.  After running for a couple months, the application can take up 8GB of space.

Has a method been provided for flushing this cache manually?  We are not finding iOS to clean it up as Parse says it should.  This is a huge issue for us as our devices run for ~15 hours a day, 7 days a week and they are arriving at a state where the app must be deleted and reinstalled to function again.

**Comment by nlutsenko** [comment]
No manual way to clear the cache, but we can easily add it.
~15h/day + 7d/week is probably why iOS is not clearing the cache for the application.
Generally - iOS manages Caches directory automatically and purges it when it pleases (specifically in low disk space conditions).

Will look into easy way to add an API to be able to clear cache for a file.

**Comment by MobileVet** [comment]
Interesting tid bit for you.  We were able to recover an iPad with 0kb free, as reported by MDM and the device itself in Settings.  We pulled the container and found 1.3gb of log files in the PFFileCache directory (which you expect iOS to clean up) and 9gb in the Private Documents/Parse/PFFileStaging directory.

We wanted to debug into the app, but figured we couldn't even install over the app with debug symbols as it would be larger so we deleted 2 small apps (SpeedTest and Chromecast).  Viola, the PFFileCache was cleared!  Interesting.

As for PFFIleStaging, we operate in really rough wifi locations.  Our theory is that Parse is attempting to upload files but failing.  Instead of clearing them out, it leaves them in the staging directory.  Regardless, this is pretty rough as we are filling iPads up and making them unresponsive.

Appreciate you reopening this issue.

**Comment by nlutsenko** [comment]
That's interesting... `PFFileStaging` piece should behave actually the same way as PFFileCache once you update the SDK to `1.11.0`, since we moved it (one good thing would also be to add some code to nuke it if you have old devices upgrading).

Otherwise - keep an eye open on this issue, we are going to add an enhancement here to let you manually control either cache size or let you evict items from cache.

**Comment by MobileVet** [comment]
We have definitely added code to nuke it ourselves.

Really appreciate you adding in this functionality, thank you.  A max cache size would be great, but obviously eviction is also helpful.
