### ISSUE TITLE
Bitcode problem

### ISSUE THREAD

**Issue by flamesoft** [ParsePlatform/Parse-SDK-iOS-OSX#494]
I have tried with both Parse frameworks for iOS v1.9.0 and v1.9.1 in XCode7.1. My project can compile but not archive. The error message is as follows:

ld: bitcode bundle could not be generated because '/Users/xx/Code/yyyy/ParseUI.framework/ParseUI(PFImageView.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have to update my app soon. Could you please fix the bitcode problem? Thanks!

**Comment by richardjrossiii** [comment]
This seems like an issue with ParseUI, would you mind re-opening the issue on that repo?

https://github.com/parseplatform/ParseUI-ios/issues
