### ISSUE TITLE
Please consider moving to Clang's libc++ instead of GNU's libstdc++6.

### ISSUE THREAD

**Issue by adonoho** [ParsePlatform/Parse-SDK-iOS-OSX#495]
Gentle Parse Folk,

As Xcode hasn't used the GNU compilers in several years, please consider moving to Clang's libc++ instead of GNU's libstdc++6. (Having to use the framework's version number in our builds is a good clue that this technology is being left behind.)

Anon,
Andrew

**Comment by richardjrossiii** [comment]
I agree, for any new project, using libstdc++ is probably a bad choice.

Unfortunately, we currently rely on a stable C++ ABI (which libc++ does not guarantee, nor is it backwards compatible with libstdc++) for the parts in the SDK where we do use C++ (as few as they are).

At some point in the future this may change, but for the immediate future, we still need to keep the older GNU library :(

**Comment by adonoho** [comment]
It sounds like you know this will hurt your framework eventually. The logic you use above pays more interest on your technical debt. I'm just a Parse developer but I will be asked to pay that debt some day with some odd interaction between Parse and my apps. I would rather it not be due to some little used downlevel library in your framework. Allow me to encourage you to finish the move to the modern toolchain.
