### ISSUE TITLE
Duplicate symbol is Parse 1.9.1

### ISSUE THREAD

**Issue by mrFranklin** [ParsePlatform/Parse-SDK-iOS-OSX#497]
I add Parse.framework and Bolts.framework to my project. My project is using the -ObjC linker flag and I had add all the framewoks(including Accounts.framewrok and Social.framework)
my develop environment is: xcode6.1, iOS7.0
when compling in arm64, it shows the link error below:

duplicate symbol l014 in:
/Users/franklin/Documents/git/Aonesdk/samples/ios/proj_parse2/Bolts.framework/Bolts(BFAppLinkReturnToRefererController.o)    /Users/franklin/Documents/git/Aonesdk/samples/ios/proj_parse2/Parse.framework/Parse(PFGeoPoint.o)
duplicate symbol l011 in:
/Users/franklin/Documents/git/Aonesdk/samples/ios/proj_parse2/Bolts.framework/Bolts(BFCancellationToken.o)
/Users/franklin/Documents/git/Aonesdk/samples/ios/proj_parse2/Parse.framework/Parse(PFNetworkActivityIndicatorManager.o)
ld: 308 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could you help me finding which wrong?

**Comment by nlutsenko** [comment]
Hey @mrFranklin, since Xcode 6.1 was released over a year ago (Oct 20, 2014), I would love to test on that version, but I am afraid it is not going to work.
Any chance you can update to at least Xcode 6.4 and retest the project?

**Comment by mrFranklin** [comment]
ok! 
I updated the OSX system and the Xcode version. The mistake was missing! 
thank you very much!

**Comment by nlutsenko** [comment]
Glad it worked!
