### ISSUE TITLE
[PFUser currentUsers] returns nil in nested loop

### ISSUE THREAD

**Issue by Xotic1** [ParsePlatform/Parse-SDK-iOS-OSX#500]
Hi,

I'm seeing a strange issue that's got me a bit puzzled.  I'm implementing the emailVerified feature, where upon login, I check to see if this property is set to true or false, and if it's false, I pop up an alert view (another Github project - PXAlertView), with two buttons:

"Ok" - just dismisses the popup and logs the user out
"Resend verification email" - send another email to the user with the confirmation link

Here is the code.  Essentially, what is happening is that when I obtain [PFUser currentUser] in the first block (logInWithUsernameInBackground call), the SDK returns a valid object and everything works fine.  However, if I show an alert view with a completion block that get's called after the user responds to the alert view, the exact same code doesn't work because for some odd reason now [PFUser currentUser] returns false and of course curUsers2.isAuthenticated is false as well (and an exception is thrown with message something like "cannot save object because user is not authenticated...")

How can this be? Am I doing something wrong?

Another strange thing: I tried to pass the outside curUser object to the inside block using __block and use curUser that for setting/saving values, but that didn't make a difference.  In the debugger, within the outside block curUser.isAuthenticated is true; however, when I get to the inside completion block, every property of curUser remains the same except curUser.isAuthenticated.

For now, I just dropped PXAlertView and went back to basic UIAlertView with a delegate, which works fine.

Thanks for all the help.

```
[PFUser logInWithUsernameInBackground:self.email.text password:self.password.text
                                    block:^(PFUser *user, NSError *error)
    {
        if (user)
        {
            // login is successful; check to see if the user's email has been verified
            if (![[user objectForKey:kUserEmailVerifiedKey] boolValue])
            {
                // for debugging only, the next 4 lines executed at this point work just fine
                __block PFUser *curUser1 = [PFUser currentUser];
                
                // here curUser1.isAuthenticated returns true
                
                [curUser1 setObject:@"no-reply@host.com" forKey:kUserEmailKey];
                [curUser1 save];
                [curUser1 setObject:self.email.text forKey:kUserEmailKey];
                [curUser1 save];
                
                // show the user a reminder to verify the email, plus and option to resend the email
                PXAlertView *alert = [PXAlertView showAlertWithTitle:@"Login Error"
                                                             message:[NSString stringWithFormat:@"This account has not been verified yet.  Please click on the confirmation link in the email sent to %@ to activate this account", self.email.text]
                                                         cancelTitle:@"Ok"
                                                          otherTitle:@"Resend verification email"
                                                  buttonsShouldStack:YES
                                                          completion:^(BOOL cancelled, NSInteger buttonIndex) {
                                                              if (!cancelled)
                                                              {
                                                                  // the user wants another email confirmation link sent;
                                                                  PFUser *curUser2 = [PFUser currentUser];

                                                                  // here curUser2 is nil and curUser2.isAuthenticated is false
                                                                  //<------------  Why? ------------>                                

                                                                  //<------------ the first save throws an exception ------------>
                                                                  curUser2[kUserEmailKey] = @"name@host.com";
                                                                  [curUser2 save];                                                                  
                                                                  [curUser2[kUserEmailKey]= self.email.text;
                                                                  [curUser2 save];
                                                              }
                                                          }];                
                // log out the user
                [PFUser logOut];
                               
                return;
            }            
        }
```

**Comment by Xotic1** [comment]
Literally few minutes after I posted it, I figured it out. I was explicitly loggin the user out, which was happening before the completion code could run (instead, the solution is to move the logout code to else part of if (!cancelled), so that the user is logged out when they simply dismiss the alert view.

**Comment by nlutsenko** [comment]
Glad you found the solution!
