### ISSUE TITLE
Parse Crash Reporting Not Working

### ISSUE THREAD

**Issue by pbush25** [ParsePlatform/Parse-SDK-iOS-OSX#501]
I am trying to add Parse crash reporting to my project. I have added the modules necessary for this to work in my existing project yet I never get any crash reports in my dashboard. So I started a blank project to see if this issue was local to my project and I came upon the same issue, with crash reports not ending up in my dashboard. I can provide a link on Dropbox for my sample project that doesn't add crash reports to my dashboard.

**Comment by nlutsenko** [comment]
Duplicate of #444
