### ISSUE TITLE
PFInternalUtils.m Crash !

### ISSUE THREAD

**Issue by modiodio** [ParsePlatform/Parse-SDK-iOS-OSX#504]
Hello,

I want to report a bug
I am using the the jsqmessagesviewcontroller and parse library 
When I swip to bottom to hide the keybord the application crash. It happend only when there are No messages in the UICollectionView.

LOG ERROR

0x1002d9828 <+344>: b 0x1002d9834 ; <+356> at PFInternalUtils.m:381
(lldb) !

Do you have an idea ?
Thanks for yout response

**Comment by richardjrossiii** [comment]
`PFInternalUtils` has never had 381 lines in its existence, so I think you're probably looking in the wrong place. Try doing `thread bt all` in the lldb console and post the output of that, and maybe we can help more.
