### ISSUE TITLE
Ability to revert all changes or a single field on `PFObject`.

### ISSUE THREAD

**Issue by nlutsenko** [ParsePlatform/Parse-SDK-iOS-OSX#52]
After changing a single field on `PFObject` - there is no functionality to revert it back to the server state, even though we have the server state available internally. This is implemented in dotNet SDK via `ParseObject.revert()` method which reverts any changes to an object that were done after last successful save/fetch.

Implementation would require:
- Add `PFObject.revert()` that would clear all operations in `operationSetQueue` and rebuild `estimatedData`
- Add `PFObject.revertObjectForKey(key: String)` that would remove all operations for that key in `operationSetQueue` as well as rebuild `estimatedData`.

**Comment by mykrr** [comment]
I am also facing the same issue as in #51. Please provide us quick fix for this.

**Comment by kashif** [comment]
so something like:

```objective-c
- (void)revert {
    @synchronized (lock) {
        [operationSetQueue removeAllObjects];
        [self rebuildEstimatedData];
    }
}

-(void)revertObjectForKey:(NSString *)key {
    @synchronized (lock) {
        NSUInteger index = [operationSetQueue indexOfObject:key];
        [operationSetQueue removeObjectAtIndex:index];
        [self rebuildEstimatedData];
    }
}
```

**Comment by nlutsenko** [comment]
@kashif pretty close, there are a little bit more things there - `availableKeys` would need to be adjusted as well as we need to `checkpointAllMutableContainers`.
Also - operationSetQueue contains PFOperationSet objects, not just keys.

**Comment by kashif** [comment]
thanks for the info @nlutsenko just about to send a pull request. At the moment I am thinking:

```objective-c
- (void)revert {
    @synchronized (lock) {
        [operationSetQueue removeAllObjects];
        [self rebuildEstimatedData];
        [self checkpointAllMutableContainers];
    }
}

-(void)revertObjectForKey:(NSString *)key {
    @synchronized (lock) {
        NSUInteger index = [operationSetQueue indexOfObject:key];
        [operationSetQueue removeObjectAtIndex:index];
        [_availableKeys removeObject:key];
        
        PFFieldOperation *changes = [[self unsavedChanges] objectForKey:key];
        index = [operationSetQueue indexOfObject:changes];
        [operationSetQueue removeObjectAtIndex:index];
        
        [self rebuildEstimatedData];
        [self checkpointAllMutableContainers];
    }
}
```

**Comment by grantland** [comment]
`- revert` looks good, I'm just a little worried about `- revertObjectForKey:`. It seems like the only reasonable thing we could do is revert the key as long as it's not part of an inflight operation. Is that something that won't confuse developers and something that we can document well enough?

If not, is creating `- revert` enough?

**Comment by grantland** [comment]
Also see https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseObject.java#L842

**Comment by kashif** [comment]
thanks @grantland having a look

**Comment by grantland** [comment]
Another optimization that Android should probably have is no-oping if we're not dirty or the key isn't dirty.

**Comment by nlutsenko** [comment]
Fully done. Thanks everyone.

**Comment by kashif** [comment]
thanks @nlutsenko for your help!

**Comment by arasu01** [comment]
This is not fully fixed for me. 
When use the 'revert' on the [PFUser currentUser], it restores to previous state when the already existing email is used.

But after killing the app and relaunching the app again and fetch the data from [PFUser currentUser] it doesn't shows up the revert data instead it shows the wrong data for which I opened the issue #51.
