### ISSUE TITLE
Parse getting Logout when application updated

### ISSUE THREAD

**Issue by NasirMalik** [ParsePlatform/Parse-SDK-iOS-OSX#527]
I am using latest Parse iOS SDK installed via cocoapods. Also my app have new revoke-able sessions activated by Default. When I update application to a newer version and download via TestFlight, on running application for first time application is logged out.

<img width="1067" alt="screen shot 2015-11-07 at 6 03 17 pm" src="https://cloud.githubusercontent.com/assets/3906649/11015376/ad1f8946-857e-11e5-947e-65750e7efa1d.png">

Users are forced to re-login thus giving a unusual and awkward experience. How this session is getting terminated?

**Comment by hilalh** [comment]
Same issue

**Comment by nlutsenko** [comment]
Do you guys experience this only with TestFlight and not say if you run your app via Xcode?
This sounds strange, but I am confident we are going to get to the source of this behavior.

**Comment by FreudGit** [comment]
Same

**Comment by NasirMalik** [comment]
Yes and this issue is reproducible. This one last time I have not got this. Otherwise every-time I am facing same issue.

**Comment by nlutsenko** [comment]
Does it happen on latest master or on 1.9.1?
Guys, can someone please attach a repro project or code snippet? I'll fix it right away then.

On Nov 8, 2015, at 5:48 PM, NasirMahmood <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes and this issue is reproducible. This one last time I have not got this. Otherwise every-time I am facing same issue.

**Comment by nlutsenko** [comment]
@FreudGit for you, the issue is only on TestFlight as well, right?

**Comment by FreudGit** [comment]
Maybe related:

Also, 

'PFUser *myUser= [PFUser currentUser];  / Was ok(not nil)
'     if ([FBSDKAccessToken currentAccessToken])   // was true


' bool bGranted_publish_actions=[[FBSDKAccessToken currentAccessToken] hasGranted:@"publish_actions"];  // report FALSE

After, I call this, and get the "Already autorized..." screen.
'  [PFFacebookUtils linkUserInBackground:[PFUser currentUser] withPublishPermissions:@[@"publish_actions"] block:^(BOOL succeeded, NSError *error) {

**Comment by FreudGit** [comment]
Yes, i'm using TestFlight and get this problem

**Comment by nlutsenko** [comment]
Does it reproduce if you use a debugger/via App Store or only via TestFlight?
I am trying to understand on the potential reasons this happens.

**Comment by nlutsenko** [comment]
In terms of code above - didn't quite get you, any chance you can highlight what you are trying to do and what is the end result?

**Comment by NasirMalik** [comment]
With debugger if I install a newer build number version it does-not happen. But if you run application with a larger build number on a TestFlight installed version for first time it happens. As per my assumption this thing has to do something with these new revokeable sessions but I am not sure.

**Comment by FreudGit** [comment]
In terms of code above - didn't quite get you, any chance you can highlight what you are trying to do and what is the end result?

== sorry, i've move previous code to the facebook side.  I don't want to mix things.

**Comment by nlutsenko** [comment]
Huh. Do you get the nil currentUser locally?
 Or simply every request reports unauthorized user.

**Comment by NasirMalik** [comment]
In my case if I intall application in  my RootViewController i check if ![PFUser currentUser] I move to login flow otherwise redirect application to Dashboard, every-time its getting to login glow. It means [PFUser currentUser] is nil. It doen't say anything like unauthorized user. At that time there is simply no current user.

**Comment by nlutsenko** [comment]
Ok, great. We are getting somewhere...
This means it's completely not related to revocable sessions, since revolution happens only on the server. 
@NasirMalik any chance you are using different app ids between TestFlight builds? The question about production and debug builds still stands.

**Comment by NasirMalik** [comment]
Yea. You got it. For me that is the issue.

**Comment by nlutsenko** [comment]
:( I am getting rusty here.
Can you be more explicit when you are referring to 'yes, this is the issue'?
:grin:

**Comment by NasirMalik** [comment]
I have a live version installed with production application. Then I created another application with debug keys and sent a test flight update. That logs me out. Next time I was all set for release so I again pushed a Production app. So this again happened. Same happened with my fellows thus reproductions make me feel sure that there is issue.

**Comment by NasirMalik** [comment]
For the record: If you use different apps for LIVE and TEST modes this issue will always occur when someone switch.

**Comment by nlutsenko** [comment]
Aha! Phew, I thought there is something bigger here.
The change of applicationId intentionally resets the contents of the local data folder.
The biggest reason - the data between different apps is not compatible, since objectIds are not the same, plus there is no way you can guarantee client-server data consistency between different Parse apps.
