### ISSUE TITLE
PFUser currentUser returns nil then non-nil without intervening login or logout

### ISSUE THREAD

**Issue by iosdev-republicofapps** [ParsePlatform/Parse-SDK-iOS-OSX#529]
Hi,

I have code that does something like the following
```
// currentUser is false on app startup even though user is actually logged in from last app run
// so isLoggedIn is NO
BOOL isLoggedIn = [PFUser currentUser] != nil;

// Set some UI code state based on isLoggedIn

// wait a second or so, without any login or logout actions
// Suddenly [PFUser currentUser] becomes non-nil
// so isLoggedIn is now YES
isLoggedIn = [PFUser currentUser] != nil;

// So now my UI is messed up because part of it shows the user as being logged in and part shows it as being logged out.
```

Any ideas why this is happening?

Note that between the two calls to `[PFUser currentUser]` I am not doing any kind of login or logout of any kind.  I don't have any odd automatic or lazy login or anonymous users.

Since `currentUser` is not a property, I can't even KVO it.  So I'm not sure how to handle this.  Why is this happening?

I look at the code for `currentUser` and it looks like its blocking and waiting to load the current user synchronously.

This is really causing issues for my app and has just started happening suddenly.

Any ideas?

Thanks!

**Comment by iosdev-republicofapps** [comment]
Note that the issue persists in the latest version 3.2.  I am on Mac OS X 10.10.5 using Xcode Version 7.1 (7B91b).

**Comment by richardjrossiii** [comment]
This doesn't sound possible (though I've seen stranger bugs before). Are you sure you don't have anonymous users anywhere?

I would strongly suggest placing a symbolic breakpoint in `-[PFCurrentUserController saveCurrentObjectAsync:]`, as that should always be called when `[PFUser currentUser]` is updated.

If this is reproducible, and you can extract the reproducible parts into a smaller project, that would be super helpful in trying to debug this, though my best guess is that you have a stray `loginAsync:` call that's being invoked somewhere.

**Comment by iosdev-republicofapps** [comment]
For future reference, what was happening was that I was initializing the state of my UI with data about the Parse user *before* I had set the Parse client id, key etc.  So Parse was not initialized yet.  This is because I was initializing Parse in `applicationDidFinishLaunching` but the UI was being initialized when the main NIB was loading, which is *before* `applicationDidFinishLaunching` gets called.

This was my error, sorry.  However, I think Parse should abort or log errors if Parse methods that require Parse to have been initialized are invoked before Parse has not been initialized.  That would have made this bug a lot easier to track down.

Would you be open to making that change?
