### ISSUE TITLE
appVersion in installation table for iOS is wrong

### ISSUE THREAD

**Issue by kengleong** [ParsePlatform/Parse-SDK-iOS-OSX#530]
where does parse get the appVersion value in the installation table?
Shouldn't it be from TARGETS > MyApp > General > Identity > Version ?

**Comment by nlutsenko** [comment]
The appVersion field on the client is populated from `CFBundleVersion` key in your Info.plist aka `General -> Identity -> Build`.
This is done, as "Version"(CFBundleShortVersionString) stands for user-visible version, whilst build number is usually used for debugging/analyzing. This is also inline with Apple guidelines for usage of these versions.

Example:
- You start developing version 1.0, so `CFBundleShortVersionString` is `1.0`
- Build -> Test -> Submit to TestFlight, where the version remains the same, but the build number increments.
- You release an app to the store with version `1.0`, but build is drastically different (incremented) from what you used for local development, or for TestFlight.

Hope this answers your question :wink:
