### ISSUE TITLE
[PFFile loadInBackground] leads to Parse Error Code 1

### ISSUE THREAD

**Issue by dtaitz** [ParsePlatform/Parse-SDK-iOS-OSX#536]
Hello,

I use PFFile throughout my app. Starting this morning, I started to receive the following error each and every time I called [PFFile loadInBackground];

Response status code was unacceptable: 400 (Code: 1, Version: 1.9.1)

This happens regardless of what iOS version I test. I am currently using Parse 1.9.1.

Please let me know what I can do to help resolve this issue.

Best,

David

**Comment by dtaitz** [comment]
After some further investigation, it seems that the problem does not occur when I run the command on iPhone 6 Plus but does on any other size phone.

**Comment by nlutsenko** [comment]
This sounds very weird, since `400` probably would come from S3/CloudFront, not Parse API server.
Could you extract the url from the file and trying to access it in your browser?

**Comment by dtaitz** [comment]
@nlutsenko here is the response I get with the file path:





<NSHTTPURLResponse: 0x12d847aa0> { URL: https://files.parsetfss.com/7eed937a-5c08-4bab-be98-c6208873fd24/tfss-e62126df-9023-4b2d-bc2b-88f341564f0c-hjcuGN7p6W-profile.png } { status code: 400, headers {

    Connection = close;

    "Content-Length" = 551;

    "Content-Type" = "text/html";

    Date = "Tue, 10 Nov 2015 22:20:03 GMT";

    Server = CloudFront;

    Via = "1.1 86ecaaad1bf09697690720df2c709cb6.cloudfront.net (CloudFront)";

    "X-Amz-Cf-Id" = "k8NYzMpkTAvDxkTYIfX2ZEmI8-GfwipM3rAJdsw9v3qU4f-mLTkxRw==";

    "X-Cache" = "Error from cloudfront";

} }

**Comment by nlutsenko** [comment]
Since this error comes from CloudFront - this is outside of the client code.
Can you file a backend issue at https://parse.com/help, as we are still using FB Bug Tool for tracking those.
