### ISSUE TITLE
[SKProductsRequest _handleReply:] crash

### ISSUE THREAD

**Issue by ChrisGrant** [ParsePlatform/Parse-SDK-iOS-OSX#537]
I'm getting the below crash report through crashlytics.

I'm using Parse through cocoapods. Here's the versions from my Podfile.lock.
- Parse (1.7.5.3):
  - Bolts/Tasks (>= 1.2.0)

All of the crashes are happening on iOS7.

StoreKit	
__34-[SKProductsRequest _handleReply:]_block_invoke + 540

  Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                6704609744 objc_msgSend + 16
1  StoreKit                       6552361264 __34-[SKProductsRequest _handleReply:]_block_invoke + 540
2  libdispatch.dylib              6710723616 _dispatch_call_block_and_release + 24
3  libdispatch.dylib              6710723552 _dispatch_client_callout + 16
4  libdispatch.dylib              6710736236 _dispatch_main_queue_callback_4CF + 344
5  CoreFoundation                 6503574884 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
6  CoreFoundation                 6503567524 __CFRunLoopRun + 1452
7  CoreFoundation                 6502783800 CFRunLoopRunSpecific + 452
8  GraphicsServices               6597310512 GSEventRunModal + 168
9  UIKit                          6553370856 UIApplicationMain + 1156
10 AppName                    4296173188 main (main.m:16)
11 libdyld.dylib                  6710835872 start + 4

**Comment by hhanesand** [comment]
How does this have anything to do with parse? The stack trace doesn't even touch any parse code.

**Comment by nlutsenko** [comment]
Yup. I would say - since it happens purely on iOS 7 this is an Apple StoreKit.framework bug.
If you have a good repro case - I would more than glad to investigate further and help you out.

**Comment by ChrisGrant** [comment]
I looked into this a bit further. A lot of people are seeing the same issue because the delegate is not being managed correctly.

Take a look here http://stackoverflow.com/questions/24675528/ios-crash-report-skproductsrequest and here, for example: http://stackoverflow.com/questions/3324596/storekit-skproductsrequest-crash.

Could you confirm that you are doing this in your framework?

**Comment by nlutsenko** [comment]
@ChrisGrant We are doing exactly that in https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/Internal/Product/ProductsRequestHandler/PFProductsRequestHandler.m#L58

Going to send out a Pull Request to make sure we extra safeguard everything here, hopefully it will resolve the problem.

**Comment by ChrisGrant** [comment]
Great thank you!
