### ISSUE TITLE
'+[PFUser registerAuthenticationProvider:]' - Crash when initializing PFFacebookUtils

### ISSUE THREAD

**Issue by sebyddd** [ParsePlatform/Parse-SDK-iOS-OSX#550]
Out of nowhere, the app started to crash on 

`    [PFFacebookUtils initializeFacebookWithApplicationLaunchOptions:launchOptions]; `

with the following: 

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[PFUser registerAuthenticationProvider:]: unrecognized selector sent to class.`

If I remove the initialization, I obviously cannot use PFFacebookUtils. 

Bellow are my imports in case it could help:

<img width="888" alt="screen shot 2015-11-12 at 10 21 23" src="https://cloud.githubusercontent.com/assets/5271150/11113642/278e6eda-8927-11e5-82e0-946ea97aa8c1.png">

Thanks a bunch!

**Comment by nlutsenko** [comment]
@sebyddd, looks like you are using different versions of Parse SDK and ParseFacebookUtils.
Please make sure that you are using either the same versions, or, the latest for both.

At the time of writing this - the latest is `1.9.1` for Parse SDK and `1.9.0` for ParseFacebookUtils.
