### ISSUE TITLE
How would i query 8000 objects from parse?

### ISSUE THREAD

**Issue by londonbridges13** [ParsePlatform/Parse-SDK-iOS-OSX#555]
I'm having trouble, please help.

**Comment by richardjrossiii** [comment]
This does not appear to be an actual issue with the client SDK. I would suggest asking such questions on the [google group](https://groups.google.com/forum/#!forum/parse-developers) or [stackoverflow](http://stackoverflow.com).

Though, to help you get started with your question, I would suggest looking at `limit` and `offset` of the PFQuery object.
