### ISSUE TITLE
I accidentally deleted all users in our Social High database last night.

### ISSUE THREAD

**Issue by marshsutherland** [ParsePlatform/Parse-SDK-iOS-OSX#568]
I accidentally deleted all users in our Social High database last night.

I thought I deleted one user "chems" in our Social High database hosted on Parse last night. I accidentally deleted all users.

We need our database restored ASAP!

There is no phone number for Parse so I am emailing you.

Can this please be done asap? 

My phone number is 617-999-9211. Ken's phone number is 509-922-5629.

Marsh Sutherland
COO | Co-Founder
WeedShare™
o: (844) WEEDSHARE Ext 3

**Comment by nlutsenko** [comment]
@marshsutherland Please reach out to our backend/support team via https://parse.com/help

**Comment by marshsutherland** [comment]
It's not clear how

On Monday, November 16, 2015, Nikita Lutsenko <notifications@github.com>
wrote:

> @marshsutherland <https://github.com/marshsutherland> Please reach out to
> our backend/support team via https://parse.com/help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/568#issuecomment-157132906>
> .
>


-- 
*Marsh Sutherland*
COO | Co-Founder
WeedShare™
*o: *(844) WEEDSHARE Ext 3
*e:* marsh@weedshare.net

**Comment by nlutsenko** [comment]
Go through the `report a bug` flow - this will take you to the FB Bug Tool, as we are using that one for backend issue tracking.
