### ISSUE TITLE
emailVerified is found nil on iPhone while is fine on Simulator

### ISSUE THREAD

**Issue by TruthDerek** [ParsePlatform/Parse-SDK-iOS-OSX#581]
When I try to call 'user.objectForKey("emailVerified")' on iPhone, an error 'unexpectedly found nil while unwrapping an Optional value' occurred. But everything is fine on Simulator which means it can return 'false'. Therefore, it has nothing to do with turning on 'Email Verification'. It seems like there is no 'emailVerified' field when it's running on iPhone.

**Comment by nlutsenko** [comment]
Hey @TruthDerek, thanks for the report!
What I think is happening is that `emailVerified` value is actually set to `nil` until the moment the email actually becomes verified. I would say - if you successfully logged in or signed up a user - you can treat a `nil` value for `emailVerified` field as `false`.

Are you logging in/signing up with the same email address on Simulator and Device? Or they are different?
A piece of code or a sample project that reproduces the issue would be super helpful for this.
