### ISSUE TITLE
PFUser.logInWithUsernameInBackground - block isn't called

### ISSUE THREAD

**Issue by robertvojta** [ParsePlatform/Parse-SDK-iOS-OSX#584]
**Setup**

* Xcode 7.1.1
* Parse 1.9.1
* Swift project

**Description**

Simple call to `PFUser.logInWithUsernameInBackground` doesn't lead to `block` callback. Nothing happens. So I decided to replace it with `do` & `catch` & `try PFUser.logInWithUsername(loginUsername, password: loginPassword)`. This calls Objective-C method `+ (instancetype)logInWithUsername:(NSString *)username password:(NSString *)password error:(NSError **)error` on `PFUser` class. Now my `catch` block is called and the error is `NilError`, to be more precise, it is `Foundation._GenericObjCError.NilError` with error code set to `0`. And it means that the Objective-C method:

* returned `nil`,
* and `error` wasn't set.

Under which circumstances can this happen? I would expect that the `PFUser` is returned or `error` is set. But neither of these two things happened and it probably explains why my `block` isn't called in `logInWithUsernameInBackground`.

I'm 100% sure that my user does exist. There's no problem with connection or any similar problem, because other Parse calls do work.

**Comment by nlutsenko** [comment]
@robertvojta Any chance you can attach a repro project or anything that might help us identify the issue?

I tested this 2 minutes ago on the latest SDK (1.10.0) with the following code snippet:
```swift
do {
            let user = try PFUser.logInWithUsername("nlutsenko", password: "yolo")
            print(user)
        } catch let error {
            print(error)
        }
        do {
            let user = try PFUser.logInWithUsername("nlutsenko", password: "1") // invalid password
            print(user)
        } catch let error {
            print(error)
        }
```

Works great and properly logs user first time, an error next time.
There probably is something else involved here.

**Comment by robertvojta** [comment]
@nlutsenko here's the gist with related code https://gist.github.com/robertvojta/5a08ff208e0067e54118#file-subscriptions-swift-L82

* highlighted line no. 82 is called
* next line no. 83 is not called

When I replace it with synchronous login then it throws NilError.

**Comment by nlutsenko** [comment]
Quick question: 
Is there a chance that Parse is not initialized at the moment you call `logInWithUsername()`?

I just extracted logic for lines 87 and 136 and it works the same way.
Could you share the small repro project with me, you can do it privately as well via nlutsenko(at)fb.com

**Comment by robertvojta** [comment]
@nlutsenko shame on me, you were right. I was refactoring my code, moved initialization code somewhere else and it wasn't called, ie. `logInWithUsername` was called before initialization.

Shouldn't be this kind of developer error propagated via `NSError` as well? Just to avoid future issues like this one.

**Comment by nlutsenko** [comment]
This should be a fatal error indeed, there are few places in tests that we rely on this (or might rely), so this is going to be converted into exception soon.
