### ISSUE TITLE
Cannot find version 1.10 in cocoapod

### ISSUE THREAD

**Issue by SwiftNextStep** [ParsePlatform/Parse-SDK-iOS-OSX#588]
Hi after fail to retrive the pod for Parse 1.10 i try this:

platform :ios, ‘9.1’
target 'SwiftNextStep' do
pod 'Parse', ‘< 2’
pod 'ParseUI', ‘< 2’
pod 'ParseCrashReporting', ‘< 2’
pod 'ParseFacebookUtilsV4', ‘< 2’
pod 'ParseTwitterUtils', ‘< 2’
end

However after I install the pods I get "Using Parse (1.9.1)"

Why can I not access the Parse v1.10?

**Comment by nlutsenko** [comment]
Hey @SwiftNextStep just found why this doesn't work.
`ParseCrashReporting` pod lists `~> 1.9.1` as it's dependency.
Fixing in a few minutes.

Side note: You can use `pod 'Parse', '~> 1.9'` instead of `< 2` as it's going to have the same behavior.

**Comment by nlutsenko** [comment]
Just pushed a new version of ParseCrashReporting that has this problem fixed.
Should fix the problem, try running `pod update` now. :)

**Comment by SwiftNextStep** [comment]
Thanks @nlutsenko I use "< 2" to try to find the highest available version, the original file was using "~>1.9 instead
