### ISSUE TITLE
Cannot build Parse with Xcode 7.1.1 and Swift 2.0

### ISSUE THREAD

**Issue by ethanneff** [ParsePlatform/Parse-SDK-iOS-OSX#594]
- New project. 
- Tried importing Parse SDK with CocoaPods, failed.
- Tried importing Parse SDK manually, failed.

Getting 'Parse' has no member errors. 

The rest of the Parse SDK is working (PFAnalytics, PFUser, PFACL, etc)

<img width="702" alt="screen shot 2015-11-22 at 10 41 51 am" src="https://cloud.githubusercontent.com/assets/2933593/11325556/ab6b9530-9105-11e5-811b-b570a21f14fb.png">

**Comment by ethanneff** [comment]
i'm an idiot... close this haha

**Comment by abramandis** [comment]
I am also an idiot... but I still haven't found the solution. =/

**Comment by ethanneff** [comment]
My problem was I created a Class Parse {} within my project which overwrote my Parse framework.
