### ISSUE TITLE
Problem with PFFacebookUtils isLinkedWithUser

### ISSUE THREAD

**Issue by alexvolchek** [ParsePlatform/Parse-SDK-iOS-OSX#596]
I have 2 Parse accounts, let's say X and Y. I've signed up them using 'signUpInBackgroundWithBlock' after setting username and pass. Then I login with X and link it with FB using 'PFFacebookUtils linkUserInBackground:[PFUser currentUser]'. After it I logout and login with user Y. I'm trying to connect to FB, and it returns error (Another user is already linked to this facebook id. (Code: 208, Version: 1.9.1)) as it should normally do. But after relaunching application, 'PFFacebookUtils isLinkedWithUser:[PFUser currentUser]' returns YES for user Y, although Parse.com shows that user X is connected to FB and Y is not. Only after relogging into Y, it shows that it's not connected to FB. 
Any chances you know what's the problem?
Thanks!

**Comment by nlutsenko** [comment]
Hey @alexvolchek, any chance you can put the version of the SDK you are using?
`1.10.0` from last week has a fix for exactly this issue.
Try it out and let me know how it goes.

**Comment by alexvolchek** [comment]
@nlutsenko I've updated to 1.10.0 and now it works fine, thanks!
