### ISSUE TITLE
Verify Email Link not being sent

### ISSUE THREAD

**Issue by davidohyer** [ParsePlatform/Parse-SDK-iOS-OSX#599]
I am requiring users to verify their email before they can log in to my app. Occasionally, the verification email never gets sent and there is nothing the user can do to fix it. Submitting the forgot password form doesn't resend the verification, changing the password from that link doesn't verify the email. There is currently no way to resend the verification, so the user ends up having to create a new account, but my accounts are based on email address, so they are now required to have two email addresses potentially. Any ideas on a workaround or why this is happening?

**Comment by nlutsenko** [comment]
Hey @davidohyer, this is very strange that the emails are not being sent for some users.
We currently do not provide a way to resend the verification email, unfortunately.

When email is verified - it will have `true` in `emailVerified` column on your user table. ([guide](https://parse.com/docs/rest/guide#users-verifying-emails))
The key part here is that you can change that field manually (my recommendation would be through CloudCode or via web hook and use a master key for it), so you can build your own email verification on top of the one built by Parse.

The other workaround - if the user asks to re-verify the email address and they can't proceed without it - the moment they are trying to sign up once again - delete the old user and create the new one with the same credentials (this requires some safety checking, but I am confident you can do it).

Let me know if either of these work for you, or if there is anything else here that I missed.
