### ISSUE TITLE
PFFile getData method silently fails sporadically

### ISSUE THREAD

**Issue by a-hitti** [ParsePlatform/Parse-SDK-iOS-OSX#601]
In my iOS app I need to pull the first image synchronously when the app is first opened. I use the [PFFile getData] method. Sometimes it fetches the image data, sometimes the request just hangs forever. I have also used "getData:(NSError **)error" and the error variable is always null. This never used to happen before this past week and timing is suspiciously related to our db growing in size in the same time period.

How can I make this method call reliable?

**Comment by nlutsenko** [comment]
Hey @a-hitti, have you seen this happen in the wild open on the same version of the SDK?
Also, there were few improvements around file downloads/uploads in the recent versions of the SDK, so if you are not using the latest one - I would recommend that.

All-in-all, this feels like a transient issue on the server and I would recommend simply adding a retry logic around getting the file data.

Let me know about the details on this and I'll try to help further.
