### ISSUE TITLE
Do not repeat cloud function call automatically

### ISSUE THREAD

**Issue by yaalaa** [ParsePlatform/Parse-SDK-iOS-OSX#602]
Platform: iOS 9.1
Parse SDK: 1.10.0

I face with an issue: repeated calls to the same cloud function with the same parameters, in short interval (100ms, 700ms). Cloud code executes successfully both calls (as per cloud log).

I've taken a look at SDK source and found the following:
```
        return [self.dataSource.commandRunner runCommandAsync:command withOptions:PFCommandRunningOptionRetryIfFailed];

```
I guess it means client could repeat function call in case of some client network issues.

**Comment by nlutsenko** [comment]
Hey @yaalaa, this sounds very strange, as it will repeat the call only in case if the cloud function returned an error.
Any chance you can look into the log on the client? (it will be logged automatically)

**Comment by yaalaa** [comment]
It seems there was a bug in my app. Sorry for inconvenience.
