### ISSUE TITLE
Follow Up Issue #563

### ISSUE THREAD

**Issue by valeIT** [ParsePlatform/Parse-SDK-iOS-OSX#604]
Seems like I can't reopen Issues... [Original #563 ]

Ok let's start from the beginning. My object models: [Forgot about the reference to PFUser.]

```
class MainModel: PFObject, PFSubclassing {
  @NSManaged var title: String
  @NSManaged var value: Int
  @NSManaged var createdAtLocally: NSDate
  @NSManaged var lastModifiedAtLocally: NSDate
  @NSManaged var goal: Goal
  @NSManaged var colors: ColorModel
  @NSManaged var user: PFUser //PFUser.currentUser()
}

class Goal: PFObject, PFSubclassing {
  @NSManaged var enabled: Bool
  @NSManaged var goal: Int
  @NSManaged var completed: Bool
}

class ColorModel: PFObject, PFSubclassing {
  @NSManaged var text: String
  @NSManaged var background: String
}

//ACL in AppDelegate
    PFACL.setDefaultACL(PFACL(), withAccessForCurrentUser:true)

```

I have a list of `MainModels` shown in a `PFTableViewController` subclass. 

Calling:

```
let query:PFQuery = PFQuery(className:self.parseClassName!)
      query.fromLocalDatastore()
      do{
        if let obj = try query.findObjects() as? [MainModel] {
//          try PFObject.unpinAllObjects()
          for each in obj {
            try each.unpin()
            each.deleteEventually()
            print(each)
          }
        }
      }catch let error as NSError {print(error.debugDescription); print(error.localizedDescription)} catch _ {print("error unpinning")}
    }
```

Or uncommenting`unpinAllObjects` and commenting the loop doesn't work, raises:

```
The operation couldn’t be completed.
Error Domain=Foundation._GenericObjCError Code=0 "(null)"
```
`unpinAllObjectsInBackgroundWithBlock` works when there is an internet connection though...

How they are pinned:
The only objects that get pinned are `MainModel` at creation or when downloaded from the server, nothing else.

**Comment by nlutsenko** [comment]
Any chance you can pinpoint on which line is the exception raised?
Going over code right now and having trouble finding the root of the issue here.

**Comment by valeIT** [comment]
Weird now it doesn't raise anything anymore,no matter what.

[This is done without internet connection.]

It gets the correct MainModel object to be deleted and than calls `- (BFTask *)unpinInBackgroundWithName:(NSString *)name`

And after:
```
- (id)waitForResult:(NSError **)error {
    return [self waitForResult:error withMainThreadWarning:YES];
}
```
error pointer: `error	NSError **	domain: class name = _TtC15App12MainModel - code: 140572037279856	0x00007fff54cc6678`

Containing:
`*error	NSError *	nil	0x0000000000000000`
`[1]	NSError *	nil	0x0000000000000000`
`[2]	App.MainModel *	domain: class name = NSObject - code: 140572037279632	0x00007fd97a58f070`
`[3]	App.MainModel *	domain: class name = NSObject - code: 140572037279632	0x00007fd97a58f070`
`[4]	NSError *	0x40007fd97a6755e0	0x40007fd97a6755e0` [Which contains nil]

In the end Error returns nil and result returns 1.

After though when I `print();' the MainModel object it prints it as it was still there (and it is). Even after reloading the tableView it still persists the model. Am I missing something?

**Comment by valeIT** [comment]
From my understanding the first 2 unpins should fail since there is a reference to them in self, but they don't. All the prints print: `error: nil nil nil | success: true`

```
func deleteAndSaveDataToCloud(completion:((success: Bool, error: NSError?) -> ())?){
    let colors = self.colors
    let goals = self.goals

    self.colors.unpinInBackgroundWithBlock { (success, error) -> Void in
      print("error: \(error) \(error?.localizedDescription) \(error?.debugDescription) | success: \(success)")
      if error == nil && success == true {

        self.goal.unpinInBackgroundWithBlock({ (success, error) -> Void in
          print("error: \(error) \(error?.localizedDescription) \(error?.debugDescription) | success: \(success)")
          if error == nil && success == true {
            
            self.unpinInBackgroundWithBlock { (success, error) -> Void in
              print("error: \(error) \(error?.localizedDescription) \(error?.debugDescription) | success: \(success)")
              if error == nil && success == true {
                colors.deleteEventually()//[Error]: Failed to run command eventually with error: Error Domain=Parse Code=101 "object not found for delete" UserInfo={code=101, temporary=0, error=object not found for delete, NSLocalizedDescription=object not found for delete}
                goal.deleteEventually()//[Error]: Failed to run command eventually with error: Error Domain=Parse Code=101 "object not found for delete" UserInfo={code=101, temporary=0, error=object not found for delete, NSLocalizedDescription=object not found for delete}
                
                self.deleteEventually()
                completion?(success: success, error: nil)
              } else if let error = error as NSError! {
                completion?(success: success, error: error)
              }}
            
          } else {
            print("1error")
            completion?(success: success, error: error)
          }
        })
      } else {
        print("error")
        completion?(success: success, error: error)
      }}}
  
}
```

When the tableView reloads though all dated objects pop back up.

**Comment by valeIT** [comment]
The issue is still present, as a workaround i've added a deleted property, but it's really bad since deleted objects will just pile up and up (to filter out queries). They're going to get deleted eventually when it comes back online but mah...

**Comment by nlutsenko** [comment]
Sorry, took a while to back to this one.
Taking into account that this heavily depends on where you pin the objects and anything else happening in the app at the same time - could you strip down a repro project that has the issue reproducible?
It would help me tremendously in addressing the issue, as it's quite hard to find it right now.

**Comment by nlutsenko** [comment]
I found a piece that is related to this issue - `unpinAllObjects` does indeed throw an error, where it indicates a success. Not sure on whether this is related to the original source issue here, but at least something :grin: 

Fixing the `unpinAllObjects` success, though it shows an error problem in a few seconds.


P.S. As a workaround for not showing objects that are pending deletion - you can use 2 separate pins for your objects, one which show all of them, and the other that will show only the ones that are not yet deleted. Will follow-up on the `deleteEventually` logic here, though...

**Comment by valeIT** [comment]
Nice, Thanks. Seems like it may be connected. 

I'm sorry, but I wasn't able to repro from a new Project..
