### ISSUE TITLE
Allow disabling retry logic

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/Parse-SDK-iOS-OSX#607]
Hey Parsers!

One issue that has been annoying me for months, when the SDK wasn't open source - but now it is so I remembered I can discuss it.

In some case in my app, there is no point where some calls should automatically retry to succeed. Simple example: In my login view controller, if the user mistakenly disabled wi-fi, I want to be able to show as soon as possible that the request failed. But right now, the SDK tries a few times before passing back the error calling the completion block.

Is it very complicated to give the developers some option to disable the retry logic?

**Comment by nlutsenko** [comment]
Agreed, this is a good candidate for a new configuration logic being discussed in #570 
Marking as enhancement, we should take a look at it...

**Comment by natanrolnik** [comment]
Awesome! Indeed, #570 is needed as many additions and improvements are added to the framework.

**Comment by richardjrossiii** [comment]
@natanrolnik I just updated #570 with the ability to disable/adjust the retry attempts used in the SDK. Let me know what your thoughts on the APIs that have been proposed.

**Comment by natanrolnik** [comment]
Hey @richardjrossiii it's looking good!
From what I see, it will work as a per-request count correct?

This is coming in 1.11.0 or more probably in 1.12.0?

**Comment by richardjrossiii** [comment]
@natanrolnik This is still preliminary. We're looking to roll out new configuration APIs across all platforms already (.NET exists, Java still in progress). Hopefully 1.11, but more likely 1.12.

And yes, the retry count is on a per-request basis.

**Comment by nlutsenko** [comment]
This was released in #570.
