### ISSUE TITLE
`Could not build Objective-C module 'Parse'` when integrated as dependency in Cocoapods

### ISSUE THREAD

**Issue by honghaoz** [ParsePlatform/Parse-SDK-iOS-OSX#613]
I want to use `Parse` as a dependency in one of my Pod project.
Say my pod is named `ParseUtility`, it has some handy extensions I created based on Parse SDK.
```
  s.subspec "ParseUtility" do |ss|
    
    ss.summary     = "Utilities for Parse"
    ss.source_files = 'Source/iOS/Parse/*.*'
    ss.dependency 'Parse'
    
  end
```

However, after `pod install`. I got errors: `Include of non-modular header inside framework module 'Parse.Parse'` and `Could not build Objective-C module 'Parse'`

![screen shot 2015-12-01 at 15 42 16](https://cloud.githubusercontent.com/assets/3926785/11513604/1fe5ca00-9842-11e5-904e-28c59e867d0d.png)

Is there a way to integrated Parse as a dependency for other Pods?

**Comment by nlutsenko** [comment]
@honghaoz This looks like the same issue as in https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/466
Both of them being fixed either by one of the workarounds or by using the master of CocoaPods.
