### ISSUE TITLE
Question: how to get NSURLSessionConfiguration used by Parse

### ISSUE THREAD

**Issue by oferRounds** [ParsePlatform/Parse-SDK-iOS-OSX#614]
I would like set it protcolClasses, so I could monitor the netwrok request using this library here:

https://github.com/kasketis/netfox

by following this suggestion:
https://github.com/kasketis/netfox/blob/master/Workarounds.md#99

**Comment by richardjrossiii** [comment]
If you're using CocoaPods (which you probably should be), you can modify `-[PFURLSessionCommandRunner`'s _urlSessionConfigurationForApplicationId:clientKey:]` to add any additional configuration you'd like.

Allowing an easier public method to configure the URL session would be interesting, and probably falls under the scope of #570.

**Comment by oferRounds** [comment]
Thanks!
I actully saw this method, and I am using CocoaPods. The thing is that I'm not sure how can I modify it, as my other 3rd party libaray is not embeded via Cocoa Pods. So I can't import it there...

Any thoughts?

And yes, that would be great if could add a public method to get it.

**Comment by richardjrossiii** [comment]
You could go the classic method swizzling route, though that does feel very hacky at that point. You could also fork Parse, and use your own fork of parse as your 'source of truth' for all of our dependencies (e.g. `pod Parse :git => "https://github.com/oferRounds/Parse-SDK-iOS-OSX.git"`).

It definitely doesn't help that you're trying to tightly couple the network intercepting of a separate library to that of an unrelated library...

We do have `PFNetworkWillSendURLRequestNotification` and `PFNetworkDidReceiveURLResponseNotification` as events sent through `NSNotificationCenter` that you could observe as well.

**Comment by richardjrossiii** [comment]
@oferRounds, I just added some preliminary APIs for configuring URL sessions & retry attempts that we use in the SDK, in #570. Let me know what you think, and if you have any thoughts please don't hesitate to share!

**Comment by oferRounds** [comment]
Hi @richardjrossiii 

I just updated my project to use 1.12.0 release. 

Maybe I miss it, but I still don't see any available option to update the NSURLSessionConfiguration's protocolClasses.
Am I missing it, or is it still not available?

Thanks a lot again!

**Comment by richardjrossiii** [comment]
@oferRounds We have removed this feature for the time being, as we decided that this sort of thing would be better configured by forking the SDK. I forgot to get back to you with this decision, and I apologize.

(Another option would be to swizzle NSURLSessionConfiguration and add those protocols to all NSURLSessions created by the system).

**Comment by oferRounds** [comment]
@richardjrossiii - thanks! No problem :)
