### ISSUE TITLE
Automatic login hook?

### ISSUE THREAD

**Issue by huguesbr** [ParsePlatform/Parse-SDK-iOS-OSX#620]
Automatic login is awesome, but I wish there was some hook to plug to.

My user object have a pointer (to the current survey they're suppose to answer). When user launch the app I would like to know when is the last time the current user have been fetch and add an includeKey to the user query to also fetch the pointer object, or at least receive a notification that user have been fetch in order to fetch the pointed object.

Hope it make sense and that you can point me in any direction.r

**Comment by hhanesand** [comment]
(This is similar to a question I asked here)[https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/463] and I still haven't figured out an applicable solution to this, so I definitely support here.

Maybe the parse sdk could guarantee that the '+object' or '+user' method is called on the furthest descendant of the user class when an automatic user is created?

**Comment by huguesbr** [comment]
@hhanesand fairly similar. But I also got surprise by the fact that Parse doesn't update the user object on app start. It basically restore the session but doesn't refresh the user. So if you store any data on the user, you're out of luck :(... I guess the easiest solution would be to deactivate auto login... Hope there is a better flow.

**Comment by nlutsenko** [comment]
Hey everyone, we are discussing some APIs/features that might help improve this, but at current time - there is no public API to track when the object was fetched/saved/updated from the server.
I've just opened a separate issue to track this feature request - #775.

**Comment by huguesbr** [comment]
@nlutsenko ok, cool, that would be awesome ^^
