### ISSUE TITLE
Dynamic implementation of NSNumber properties doesn't seem to work as expected

### ISSUE THREAD

**Issue by huguesbr** [ParsePlatform/Parse-SDK-iOS-OSX#621]
Any idea why in subclassing (`PFUser` not sure if it's the reason why), dynamic properties using `NSNumber` don't seem to be saved? But they work if I implement it manually.

If 

`HBRUser.h` (subclass of `PFUser`)

    @property (strong, nonatomic) NSNumber *number

`HBRUser.m`

this doesn't work

    @dynamic number;

this work

```
- (void)setNumber:(NSNumber *)aNumber {
    [self setObject: aNumber forKey:@"number"];
}

-(NSNumber *)number {
    return [self objectForKey:@"number"];
}
```

If I use the dynamic implementation then this doesn't update the `number`:
```
aUser.number = @(3);
[aUser save];
```

**Comment by richardjrossiii** [comment]
I just tested locally and I am unable to reproduce. Would you care to share what version of the SDK you're using? The latest is 1.10.0.

**Comment by huguesbr** [comment]
I'm using 1.8.5, updating now. and testing

**Comment by huguesbr** [comment]
@richardjrossiii could it be related to the fact it's a subclass of `PFUser`. It seem to work on other subclass...

**Comment by huguesbr** [comment]
Updated and not able to reproduce anymore...

**Comment by huguesbr** [comment]
thx!
