### ISSUE TITLE
Building an identical PFQuery always returns false for hasCachedResult, even though a cached result is supplied if it exists

### ISSUE THREAD

**Issue by gadu** [ParsePlatform/Parse-SDK-iOS-OSX#623]
Hopefully this is a problem with usage but I'm having an issue getting `hasCachedResult` to return an accurate result.

The query is to fill in a value for a `UITableViewCell`. I set it up to cache (using the policy and only clearing cached results when explicitly pulling down to refresh), and the behavior seems to corroborate that I am doing it correctly (the first time it loads in async, any other time it loads in instantly).

Is there a special way you are supposed to be using `hasCachedResults`?

Here's what my code looks like:

```objective-c
        PFObject *obj = [PFObject objectWithoutDataWithClassName:...];
        PFRelation *relation = [obj relationForKey:...];
        PFQuery *q = [relation query];
        [q whereKey:...];
        
    // CHECKING TO SEE IF CACHED
        if ([q hasCachedResult]) {
            NSLog(@"1");
        }
        
        q.cachePolicy = kPFCachePolicyCacheElseNetwork; // to prevent network calls every time cell is re-used.

    // CHECKING TO SEE IF CACHED        
        if ([q hasCachedResult]) {
            NSLog(@"2");
        }

        
        [q countObjectsInBackgroundWithBlock:^(int number, NSError * _Nullable error) {

    // CHECKING TO SEE IF CACHED            
            if ([q hasCachedResult]) {
                NSLog(@"3");
            }
        }
```

Neither 1, 2, or 3 get printed. 

From my experimentation I've noticed that `hasCachedResults` only returns true if called after a query completes (did a contrived example): 

```objective-c
        PFQuery *query1 = [PFQuery queryWithClassName:];
        [query1 whereKey:@"objectId" equalTo:...];
        if ([query1 hasCachedResult]) {
            NSLog(@"A");
        }
        query1.cachePolicy = kPFCachePolicyCacheElseNetwork;
        if ([query1 hasCachedResult]) {
            NSLog(@"B");
        }
        PFObject *top = [query1 getFirstObject];
        if ([query1 hasCachedResult]) {
           NSLog(@"C");
        }
```

and only C printed. And it gets printed every time, even after the first that came from a network call.

I replaced my `getObjectWithoutData` above with this so I can also confirm this has nothing to do with that method, or that its a relationship query, since the above query was not a relationship query.

Again all these methods run inside of - `(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath. `

It seems if I recreate a `PFQuery`, even if I give it the same exact perimeters, `hasCachedResult` will return false, even though there are no UI hiccups or other delays after its been called the first time, suggesting it really does get the result from the cache...

If this is expected behavior I really suggest adding something to the documentation. Just from googling it seems that "hasCachedQuery always returning false" is a somewhat common problem.

**Comment by nlutsenko** [comment]
Sounds like a bug to me, will investigate and get back to you on this.

**Comment by nlutsenko** [comment]
Hey @gadu, I've ran a couple of tests as well as looked into our test coverage on query caching - it actually looks fine and I can't reproduce the issue you are having.

Here is the detailed explanation of what might have gone wrong when you are in your tests:

- First part aka `PFQuery` from a `PFRelation`:
Relational queries are very dependent on the state of the parent object, as well as the target class that you have. [Here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/blob/master/Parse/PFRelation.m#L139) is the implementation of query creation from `PFRelation`, and as you can see - it very much depends on what is the initial state of the object for which you are getting a relation and creating a query.

- Second part aka `getFirstObject`:
As specified in the method documentation - `getFirstObject*` and `getObjectWithId*` method families mutate the original query when you invoke those methods. In your example - the query won't have any cached result, unless you specify `query.limit = 1;`, which will mutate it the same way as `getFirstObject*` would.

Let me know if there is anything that I've missed here.
And if you still can repro the issue - could you include a precise code snippet or repro project that has this problem.

**Comment by gadu** [comment]
I've been a bit busy but I will look into it sometime this week and see if I can provide you with more information
