### ISSUE TITLE
Unity + Parse + iOS NSURLErrorDomain error -1012

### ISSUE THREAD

**Issue by Bestlis** [ParsePlatform/Parse-SDK-iOS-OSX#624]
Hello!
I try to integrate parse into my iOS game.

When I try get info from DB I get exception

Exception: {"error":"The operation couldn’t be completed. (NSURLErrorDomain error -1012.)"}

Here is my code:

var query = ParseObject.GetQuery(ParseTableName).WhereEqualTo("DeviceId", SystemInfo.deviceUniqueIdentifier);
var res = query.FindAsync();

while (!res.IsCompleted)
yield return null;

if (res.IsFaulted)
{
print("Parse exception: " + res.Exception.Message);

foreach (var excep in res.Exception.InnerExceptions)
print("Exception: " + excep.Message);

yield break;
}

Does anybody know what is my problem?
Thanks!

**Comment by richardjrossiii** [comment]
Thanks for the report! Unfortunately you seem to have posted this to the wrong repository. Our Unity SDK is located over at https://github.com/ParsePlatform/Parse-SDK-dotNET/, and so if you'd be kind enough to re-create this issue on that repository, I'll be glad to help.
