### ISSUE TITLE
Memory Leak in iOS Parse SDK v1.10.0

### ISSUE THREAD

**Issue by adonoho** [ParsePlatform/Parse-SDK-iOS-OSX#626]
Gentlefolk,

I was using Instruments to check a prototype app for memory leaks. It is linked against the released Parse iOS SDK v1.10.0. Here is a screenshot of Instruments fingering a retain cycle deep in the core of the Parse SDK.

![screen shot 2015-12-05 at 08 58 31](https://cloud.githubusercontent.com/assets/179204/11608423/6e3089ae-9b2e-11e5-92ee-5f3e456fedb1.png)

As this is a simple app, I'm happy to instrument it however you guys wish to help find what is likely a problem.

Anon,
Andrew

**Comment by nlutsenko** [comment]
Awesome find! Could you attach a saved instruments file with this cycle to the
Is issue? It would help tremendously, since we'll be able to analyze it deeper.

**Comment by adonoho** [comment]
This trace is too big for GitHub. Please let me know when you've downloaded it so I can delete it out of Dropbox.
https://dl.dropboxusercontent.com/u/2124207/20151205%20Parse%20Memory%20Leak.trace.zip

**Comment by nlutsenko** [comment]
Downloaded. Many thanks! Will dig deep into it.

**Comment by nlutsenko** [comment]
Found the cause, fixing it in a bit.
