### ISSUE TITLE
Parse crash 

### ISSUE THREAD

**Issue by chlebta** [ParsePlatform/Parse-SDK-iOS-OSX#628]
When I run my app it crash and I get this error : 
```
dyld: Library not loaded: @rpath/Parse.framework/Parse
  Referenced from: /var/mobile/Containers/Bundle/Application/C69EBCFE-40C1-410B-BE92-100FAFAA8CA0/Daam.app/Daam
  Reason: image not found
```

And if I try to download Parse library then integrate it I get thiss error : 
>Parse/Parse.h file not found

at  `#import <Parse/Parse.h>` line

**Comment by nlutsenko** [comment]
This looks like due to the fact that it fails to load a dynamic framework.
Can you make sure you installed it correctly and that it shows Parse.framework in the embedded binaries section of your target configuration?

**Comment by chlebta** [comment]
@nlutsenko yes I'm sure it have been added : 
<img width="735" alt="screen shot 2015-12-08 at 08 40 43" src="https://cloud.githubusercontent.com/assets/1204608/11650352/a1685c32-9d88-11e5-9783-25c6d1e56afc.png">

**Comment by wojtekdmyszewicz** [comment]
Same problem... maybe I need to rollback parse or pod, I will let you guys know.

**Comment by chlebta** [comment]
@wojtekdmyszewicz I tried many way but nothing worked please if you succeeded let me know

**Comment by wojtekdmyszewicz** [comment]
@chlebta maybe this can help us https://github.com/CocoaPods/CocoaPods/issues/4336

**Comment by wojtekdmyszewicz** [comment]
@chlebta for me the following fixed the problem: Project > Targets > Build Phases > Link Binary With Libaries > Pods_{app_name}.framework > Set <b>required</b> to <b>optional</b>
