### ISSUE TITLE
Parse pod for both app & extension

### ISSUE THREAD

**Issue by yaalaa** [ParsePlatform/Parse-SDK-iOS-OSX#637]
xcode 7.2
cocoapods 0.39.0
parse 1.10.0

I've got app & share extension as targets of the same project.
I'm trying to use
`pod 'Parse'`
for both targets.

Actual result:
Build fails with `'showAlertWithTitle:message:cancelButtonTitle:otherButtonTitles:completion:' is unavailable: not available on iOS (App Extension)"`

Expected result:
it should compile and work

_It seems the same parse target is shared between app & extension targets._
_BTW some pods use subspecs to resolve such issues._

**Comment by nlutsenko** [comment]
Yup, just found this.
Looks like a valid issue, sending a Pull Request with a fix in few minutes.
