### ISSUE TITLE
Third-party authentication

### ISSUE THREAD

**Issue by OlivierVoyer** [ParsePlatform/Parse-SDK-iOS-OSX#638]
Hi all,

First, thanks for having open-sourced this awesome library to show us how good is your API.
However, I have a question about some PFUser authentication methods that you publicly provided.
I am trying to code a new third-party service authentication provider (such as LinkedIn, Instagram, etc) and based on the API comments and the examples of ParseFacebookUtils and ParseTwitterUtils, I did the following steps:

- [PFUser registerAuthenticationDelegate:provider forAuthType:"MyCustomAuthType"];
- [PFUser logInWithAuthTypeInBackground:"MyCustomAuthType" authData:@{ @"id": @"<uuid>" }];
-> the Parse SDK creates a POST request to /users/ with parameters { authData = { MyCustomAuthType = { id = "<uuid>" } } }

Issue: I am receiving the following error:

[Error]: custom credential verification for auth service MyCustomAuthType failed (Code: 251, Version: 1.10.0)

Is there any kind of Parse platform limitation that is only allowing Facebook, Twitter and Anonymous as authentication service type?

**Comment by OlivierVoyer** [comment]
Hi all,

Is my issue report missing some useful informations? Please let me know what I can add.
I am surprised about not having any answer or comment about it.

Regards

**Comment by nlutsenko** [comment]
Hey @OlivierVoyer, sorry, this issue slipped through untouched.
Third-party authentication APIs are available publicly in the SDK, but currently, we indeed have a server-side limitation allowing only Facebook, Twitter and Anonymous authentication types.

We are working on something exciting that these APIs would power, and it's coming very soon.
In the meantime - I would recommend using Cloud Code / webhooks to build your own custom authentication and not rely on these APIs (even though they won't change).

**Comment by OlivierVoyer** [comment]
Hi @nlutsenko , thanks for your answer.
My guessing was right about the server-side limitation.
I thought that registering an authentication provider was enough to take care of the API and writing/reading the PFUser authData.
Anyway, I will keep playing with Cloud Code and looking forward to your new exciting features.

Regards
