### ISSUE TITLE
Parse `saveEventually` fails to save array of pointers after the record on the backend has been edited

### ISSUE THREAD

**Issue by fatuhoku** [ParsePlatform/Parse-SDK-iOS-OSX#639]
1. Save a row with a field `arrayOfPointers` on iOS, with empty array of pointers.
2. Update another field on the row.
3. Try to update the `arrayOfPointers` with an actual pointer (let's call it `somePointer`)
4. Observe that `arrayOfPointers` does not contain `somePointer`, as expected

**Comment by richardjrossiii** [comment]
When parse gets passed an array, we make a *copy* of that array, and store it, since #102. The behavior you were relying on was inconsistent and relied upon the implementation detail that parse wouldn't make copies of mutable arrays like most sane Cocoa/CocoaTouch APIs did.

**Comment by fatuhoku** [comment]
@richardjrossiii So what do you suggest that I do?

**Comment by richardjrossiii** [comment]
Your logic should now look something like this:

```
NSMutableArray<PFObject *> *arrayOfPointers = [myObject.arrayOfPointers mutableCopy];
[arrayOfPointers addObject:myNewPointer];

myObject.arrayOfPointers = arrayOfPointers;
```
