### ISSUE TITLE
Cannot Export data

### ISSUE THREAD

**Issue by SleepSchool** [ParsePlatform/Parse-SDK-iOS-OSX#640]
I cannot export my data from Sleep To Perform App.

I have been told to contact your support.

Please help.

aid@thesleepschool.org

![parse - export data](https://cloud.githubusercontent.com/assets/7021672/11694290/2badef4c-9ea1-11e5-96e4-6dd6dd0b0002.jpg)

**Comment by nlutsenko** [comment]
Hey @SleepSchool, could you file an issue via [FB Bug Tool](https://parse.com/help), since we are using that one for tracking backend issues. Someone should get back to you shortly there.
