### ISSUE TITLE
A Push increments the badge number even though I select "NO" in the beta dashboard

### ISSUE THREAD

**Issue by DaveKoz** [ParsePlatform/Parse-SDK-iOS-OSX#646]
The SDK or new dashboard is incrementing the badge number on the app icon even thought I selected no for this option. now the apps are all stuck with an incrementing badge number with no way to remove

**Comment by nlutsenko** [comment]
Hey @DaveKoz, since it looks like a dashboard issue - could you file an issue on https://parse.com/help, since this repo is purely for client-side issues related to SDKs.
