### ISSUE TITLE
Objects are no longer being saved or loaded to/from parse

### ISSUE THREAD

**Issue by johnstephenson39** [ParsePlatform/Parse-SDK-iOS-OSX#650]
I haven't changed the code for saving and loading objects from/to parse but noticed after the last update that parse is no longer saving and loading my objects, and the for-loops for both don't even get called. This code worked as recently as last night so I'm not sure what the problem is. My parse objects are still in the database unchanged from how they were last night despite trying to update them since then. Here is my code:

        query.findObjectsInBackgroundWithBlock { (objects:[PFObject]?, error:NSError?) -> Void in
        if error == nil{
        
                    print("about to mess up")
        
                    for object in objects! {
        
                        print("looping")
    
                self.ageField.text = object["age"] as? String
        }
      }
    }

        

           

And here is the console log:

Optional("Profile")

query successful

stage 1

stage 2

about to mess up

So "looping" never gets printed, and my objects aren't being saved or loaded. This example was just from when I'm trying to load objects.

**Comment by nlutsenko** [comment]
Hey @johnstephenson39, thanks for the report, and sorry for a delayed answer.
Any chance you can try the latest version of Parse SDK (1.12.0)?

Also, since you have a condition on `error == nil`, could you try placing a print/log statement just before to see if there are any errors reported?
