### ISSUE TITLE
Upgrade SDK to v1.11.0 for Watch OS 2 .

### ISSUE THREAD

**Issue by powhu** [ParsePlatform/Parse-SDK-iOS-OSX#655]
Thanks for hard work for Watch OS 2.

I download 1.11.0 SDK and replace old SDK.Upgrade target to Watch OS2.

When I build I got

```
ld: file is universal (5 slices) but does not contain a(n) armv7k slice: /Users/yang/Documents/Xcode/Circle/OpenSource/Bolts.framework/Bolts file '/Users/yang/Documents/Xcode/Circle/OpenSource/Bolts.framework/Bolts' for architecture armv7k
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is there any doc for Watch OS 2?

**Comment by nlutsenko** [comment]
Hey @powhu,

It looks like you are trying to integrate iOS version of Bolts.framework into a watchOS app.
To fix this - I would recommend trying out a watchOS starter project from the releases page [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/tag/1.11.0).
Or using CocoaPods with `pod 'Parse'` for your watchOS 2 target.

Please note that binaries from iOS/watchOS/tvOS/OSX are not compatible with each other, and you need a framework that is built specifically for each platform.
All of these are available on the releases page of this repository or [Bolts-ObjC](https://github.com/boltsframework/bolts-ios/releases/latest)

Let me know if you run into any issues or need help with the setup of something explicit.

**Comment by powhu** [comment]
@nlutsenko

Thanks a lot.
Using CocoaPods solved my problem.
