### ISSUE TITLE
Array of pointers is no longer being saved.

### ISSUE THREAD

**Issue by juggleware** [ParsePlatform/Parse-SDK-iOS-OSX#662]
Without having changed any code, the part of my project that makes 2 groups of objects (one is Room, and one is Child), saves them separately in the background, and upon success, connects them via an array of pointers within Room — in other words, it stores references of Child in a property on Room called children which is an array of pointers.

I am using subclassing. Both classes are setup to use PFSubclassing and inherit from PFObject.

This was working perfectly before, and I haven't changed any code — but now isn't, so I am wondering if something changed with the last iOS update of Parse? Or something on the backend? Maybe because I am using subclassing?

I am checking the array before and after the save in the debugger and everything looks good.... the arrays are referenced as they should be. When I go to look at the Room objects in the browser, or download them from the server again, the arrays are empty (not nil), just as when I first initialized them.... I am using NSMutableArray.

**Comment by juggleware** [comment]
OK, I figured this out. Before I was able to use this code:
```[firstRoom.children addObject: kid];```

But now it seems, I must do this:
```[firstRoom addObject:kid forKey:@"children"]```

As I said before, I am using `PFObject<PFSubclassing>`, and the `@dynamic` keyword on my `NSMutableArray` property.

**Comment by nlutsenko** [comment]
Hey @juggleware, you are correct, this looks like related to change in version 1.10.0 of the SDK and #97.
The most important piece of change here is the fact that we are no longer tracking the changes to any mutable object container that you set as a key on `PFObject` - which is aligned with Cocoa conventions.
To make it work the same way as before - you either need to use `addObject:forKey:` (as you did in the example above) or after adding an object to the array simply `firstRoom[@"children"] = children;` aka use the `setObject:forKey:` API on `PFObject`.

Let me know if it helps.

**Comment by digicub** [comment]
Wow, this has been causing me no end of trouble - I couldn't work out why my PFObject's mutable array was not updating. I thought I was going crazy, and missing some fundamental understanding of Parse! This should be made far more apparent!
