### ISSUE TITLE
PFObject doesn't allow NSNull values

### ISSUE THREAD

**Issue by emkman** [ParsePlatform/Parse-SDK-iOS-OSX#667]
Contrary to documentation and the provided error message, PFObject (and PFUser) doesn't allow explicit NSNull values when set from an NSDictionary.

example code:
```
-(void)codeToTest {
    PFObject *testObject = [PFObject objectWithClassName:@"Foo"];
    [testObject setValuesForKeysWithDictionary:@{@"a": @"b",
                                               @"foo": [NSNull null]}];
    [testObject save];
}
```

Exception:
```*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Can't use nil for keys or values on PFObject. Use NSNull for values.'```

**Comment by nlutsenko** [comment]
This is quite interesting - it should indeed work, but what I think happens is that Foundation implementation converts the dictionary to a bunch of invocations to setValue:forKey: and uses 'nil' value.

Thanks for reporting this! Indeed looks like a valid bug, which means that fix is coming soon.

**Comment by nlutsenko** [comment]
And huh - I was right, according to the documentation.
> The default implementation invokes setValue:forKey: for each key-value pair, substituting nil for NSNull values in keyedValues.

Sending a fix in a bit so this is fixed.

**Comment by emkman** [comment]
Great, thank you! This is a big help for me safely setting objects based on variable remote data without having to write a million if statements. I appreciate it.

**Comment by nlutsenko** [comment]
In the meantime, until the new version is released, there are few ways you can achieve this:
- `-removeObjectForKey:` instead of using `NSNull`
- `+objectWithClassName:dictionary:` which should work great
- Iterate over the array and simply invoke `setObject:forKey:` or use literal syntax to set the objects for keys.
