### ISSUE TITLE
PFUser.currentUser() is never nil

### ISSUE THREAD

**Issue by frgmt** [ParsePlatform/Parse-SDK-iOS-OSX#679]
SDK version: 1.11.0
Xcode version: 7.2 (Swift 2 compiler)
Platform: iOS

Issue: 
When checking a user is logged in with PFUser.currentUser() the return of this method is never nil. Instead it is an PFUser Object with empty email and username. So either the guide is wrong or the function is not working correctly as provided for.

My workaround right now is just checking the username and email field to be nil. 

Regards
Lennart

**Comment by nlutsenko** [comment]
Hey @frgmt, thanks for the report.

Do you by any chance have `PFUser.enableAutomaticUser()` in your code?
After calling that method, `+currentUser` will always have a value. The user will only be created on the server once the user has been saved, or once an object with a relation to that user or an ACL that refers to the user has been saved.
