### ISSUE TITLE
PFTwitterUtils crash

### ISSUE THREAD

**Issue by maxbryan** [ParsePlatform/Parse-SDK-iOS-OSX#68]
While testing my app I ran across this crash. It looks like it has to do with the PF_Twitter interface. The link with twitter was successful but right after the dialogue screen went away this crash happened. 

Is this a known issue with the PF_Twitter/PFTwitterUtils class? Also, did the PFTwitterUtils get open sourced as well? I'm not finding it here. 

Thanks.

![pftwittercrash](https://cloud.githubusercontent.com/assets/3952680/9376930/1ef81b76-46d9-11e5-95d7-3fc029a2e902.png)

**Comment by nlutsenko** [comment]
PFTwitterUtils, as well as PFFacebookUtils are coming very soon.
In the meantime - let me try to investigate what happened here.
Can you share a code sample or failing unit test that this fails again?

**Comment by nlutsenko** [comment]
Hey @maxbryan, I think I just got the repro for this.
Apparently - you are specifying the wrong consumerKey and/or consumerSecret for your twitter authentication. I used a generic sample available in [ParseUI Demo app](https://github.com/ParsePlatform/ParseUI-iOS).

Please double check those keys and let me know if it was that or not. (feel free to reopen this issue)
In the meantime - I am going to make it not crash, but rather fail with an error specifying that the authentication failed.

**Comment by maxbryan** [comment]
Hey thanks @nlutsenko for your quick reply. I know that I have the right consumerKey and consumerSecret because it has worked many times before and continues to do so. It was just this one time that it crashed. I may have had a bad connection at the time... But I don't know much more of what could have caused it.

Will your fix solve the crash problem if it's not the keys that were wrong? Let me know how else I can help. Thanks again.

            PFTwitterUtils.linkUser(currentUser, block: {
                (linked, error) -> Void in
                
                if let error = error {
                    
                    completion(success: false, error: error, displayErrorAlert: true)
                    
                } else {
                    
                    completion(success: linked, error: nil, displayErrorAlert: false)
                }
                
            })

**Comment by nlutsenko** [comment]
Yup, the crash is going to be solved in the next version of the SDK and it will simply fail gracefully with an  error.
