### ISSUE TITLE
BigObjecet Error : cannot check stored bigObject data in dashboard

### ISSUE THREAD

**Issue by comeonyoh** [ParsePlatform/Parse-SDK-iOS-OSX#680]
Thanks to your platform and effort! 

I have practiced something about iOS SDK with your guide document.

In Object part and Data Type section, there are big object example.

and I just follow it.

I know data stored in my cloud but cannot check with dashboard like picture I attached.

what is the problem ?! 

thanks in advance

![2015-12-22 11 51 47](https://cloud.githubusercontent.com/assets/4162456/11957884/c7265962-a907-11e5-8b28-8e00d9531d82.png)

**Comment by nlutsenko** [comment]
Hey @comeonyoh, looks like your issue is about the dashboard.
Since we are using FB Bug Tool to track those, could you file a report on https://parse.com/help

Let me know if there is anything I missed here.

**Comment by comeonyoh** [comment]
@nlutsenko  @parse-github-bot  

Thank your for reply and sorry for uploaded it in this page.

I will register this bus in help site
