### ISSUE TITLE
Deadlocking esp. around isDataAvailable/dataAvailable

### ISSUE THREAD

**Issue by christianpbrink** [ParsePlatform/Parse-SDK-iOS-OSX#685]
As I mentioned in #11 I'm seeing this in 1.11.0. 

Having downgraded to 1.9.1 to escape it, I've realized that it sometimes crops up there too.  Not nearly as easily/often, but it can.

If I do end up writing a repro, I'll post it here.  Prob not though.

**Comment by nlutsenko** [comment]
Perfect, I'll mark this as needs more info in the meantime.
Looking forward to get a repro/more information that could help us here.
