### ISSUE TITLE
Becoming a user on Watch failing

### ISSUE THREAD

**Issue by danhopwood** [ParsePlatform/Parse-SDK-iOS-OSX#690]
Calling [becomeInBackground:block:](https://parse.com/docs/ios/api/Classes/PFUser.html#/c:objc(cs)PFUser(cm)becomeInBackground:block:) on watchOS 2 extension (v1.11.0 of Parse iOS SDK) results in `[Error]: invalid session token (Code: 209, Version: 1.11.0)`

Running the same code (using the same `sessionToken`) on the iPhone app succeeds so this is isolated to the Watch.

Same error whether request is synchronous or asynchronous.

In addition, calling the REST API also succeeds in retrieving the user:

    curl -X GET \
      -H "X-Parse-Application-Id: <app-id>" \
      -H "X-Parse-REST-API-Key: <key>" \
      -H "X-Parse-Session-Token: <same token here>" \
      https://api.parse.com/1/users/me

Background: in my app there is no way for the user to log in on the Watch so the Watch app relies on there being a logged in user already. A request is therefore made to retrieve the `sessionToken` from the main iPhone app, hence needing to 'become' that user.

**Comment by nlutsenko** [comment]
Hey @danhopwood, thanks for the report. Am going to test this further...
One thing that I might suggest for this, if you are using [revocable session tokens](https://parse.com/docs/ios/guide#sessions) - create an empty `PFSession` object and save it - which will give you a revocable session token that you can pass to your watch.

This approach is slightly more secure, as well as lets you create independent sessions between watch and the phone.

**Comment by danhopwood** [comment]
Thanks @nlutsenko 

I've switched to creating a restricted session for use on the Watch as suggested, which seems to be created and its token passed back to the Watch ok.

On the Watch side, presumably that remains the same (i.e. calls `become`), which I can confirm is still failing :)

**Comment by nlutsenko** [comment]
@danhopwood, I assume you are using the same app across watchOS and iOS, right?
Any chance you can try authenticating with any different method other than session token?
Say, does the authentication via login/password work?

Here is the sample code I used for the iOS app:
```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        Parse.enableLocalDatastore()
        Parse.setApplicationId("phfHef5qZe2rHyHniyiEGiITNgwDMFdRANdYKdwE", clientKey: "hKl13kaQ0B8sfDs8FQNYzxX7UI5BCNRhQKJDJqvD")

        try! PFUser.become("N3pTUFehu1sd14p7R3j1EjxWw")
        print(PFUser.currentUser()!.sessionToken)

        return true
    }
}
```

And this is the piece inside the watch extension:
```swift
class ExtensionDelegate: NSObject, WKExtensionDelegate {
    func applicationDidFinishLaunching() {
        Parse.enableLocalDatastore()
        Parse.setApplicationId("phfHef5qZe2rHyHniyiEGiITNgwDMFdRANdYKdwE", clientKey: "hKl13kaQ0B8sfDs8FQNYzxX7UI5BCNRhQKJDJqvD")

        try! PFUser.become("N3pTUFehu1sd14p7R3j1EjxWw")
        print(PFUser.currentUser()!.sessionToken)
    }
}
```

**Comment by danhopwood** [comment]
@nlutsenko do apologise, I copied a #if DEBUG #else construct from the main iPhone app and forgot to set the compiler flag in the Watch app. So it was was hitting the #else statements and initialising the production app..

Works great now

Sorry to waste your time :(

**Comment by nlutsenko** [comment]
No problem, glad you got to the source of the problem.
