### ISSUE TITLE
Allow In App Purchase receipt validation for purchases without content/file associated

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/Parse-SDK-iOS-OSX#696]
Reading the docs and digging into the `PFPurchase` class (and associated classes), I noticed that the receipt validation for In App Purchases is only valid when it satisfies the following conditions:
- the purchase is defined in the `_Product` table
- the product must have an associated `PFFile`

If my assumptions are correct, why can't we use Parse to validate any purchase? I can by myself implement the validation logic in the server. But as Terry Crews said, there is a better way :)

Also, I couldn't understand if the completionBlock on `buyProduct:` and the `addObserverForProduct` are both called, or not; if not, what's the point of the first?

**Comment by nlutsenko** [comment]
That's a good call, receipt validation is indeed helpful for anything, not only downloadable products.
The logic on the server explicitly requires receipt validation only via `_Product` table, with a file, but I agree we should expand this further. (marking it as enhancement)

The completion blocks should be called for both - `buyProduct:` and `addObserverForProduct:` - the difference is that the latter gives you an ability to observe transactions and trigger receipt validation (via `downloadAssetForTransaction:`, whilst the former only gives you an `error` or `nil`.
This approach lets you use the former method in your UI, and disconnect that from actual logic for downloading assets/validation receipts. Also, you can trigger the former method with `PFPurchase.+restore` which will attempt restoring all your purchases from App Store and send you transactions for every one of them.

P.S. You can use the receipt validation right now for anything, by simply adding, say, an empty text file for every product.

**Comment by natanrolnik** [comment]
Perfect response, @nlutsenko !

Currently implementing the receipt validation in a Cloud Code function, as a simple POST. 
Cheers!

**Comment by nlutsenko** [comment]
After some thought and team discussions, there is not really a value we can provide here outside of using specifically attached to `PFProduct`+`PFFile`. Any other solution would involve custom code that you would want to run, which brings us to `Cloud Code` being the perfect solution for that.

And taking into account that you are already making a custom function - receipt validation with Apple via Cloud Code is actually very easy to implement, or use, say via `npm`/`gem` if you use Webhooks for you functions.

I am going to close out this issue for now. 
Feel free to comment/reopen if there is something on your mind that you think we could build that would be valuable.

**Comment by natanrolnik** [comment]
Well, I believe this is a bit subjective. I can technically setup my own function in Cloud Code, setup the HTTP Post to Apple servers, or find a good snippet and use in Cloud Code. I also can use a `gem` or `npm` and link it with Cloud Code via Webhooks. I can also setup my own server to do that. I personally believe that's exactly what Parse can do to save time for lots and lots of developers :) And it should be no difference if my purchase allows the user to download some content, or to use some feature, right?

My own Cloud Code solution is what I did. **Not that complicated but a matter of time**

**Comment by nlutsenko** [comment]
There are few gotchas about this, let me expand:
- receipt validation flow could happen on the client, but is quite complicated (requires openssl)
- server-side receipt validation is more secure, but only if you can prevent man-in-the-middle attacks (which is the case with `PFProduct+PFFile`, since you can't get a file only with a receipt)
- building a generic server-side receipt validation, that also is safe from these attacks would require some secret key that is passed to the client and validated, which is quite hard to implement in a generic way
- rolling out your own receipt validation is quite easy and gives you all the benefits above, whilst doesn't constrain us to supporting this feature in future.

Cloud Code still remains the best solution here, and I would gladly contribute to a wrapper/helper that is open source and could be used with Parse.

**Comment by natanrolnik** [comment]
Nikita WINS 👏🏻
(Although I remember I've read somewhere that apple recommends against the flow happening on the client as you mentioned)
