### ISSUE TITLE
Email address cannot be verified

### ISSUE THREAD

**Issue by SergeyK-Wind** [ParsePlatform/Parse-SDK-iOS-OSX#703]
We have encountered a problem: there are email addresses which don’t receive a verify link. An example of such address is saruman_001@mail.ru. Is there a way to resolve this issue?

**Comment by nlutsenko** [comment]
Hey @SergeyK-Wind, I would recommend filing an issue on https://parse.com/help since we are using FB Bug Tool to track backend/non-client issues.

Will look into the logs, but I would recommend taking a look at say "spam" folder, maybe the email got there.
