### ISSUE TITLE
currentUser() is nil after calling enableAutomaticUser()

### ISSUE THREAD

**Issue by mbachrach** [ParsePlatform/Parse-SDK-iOS-OSX#709]
I'm working in Swift 2.1, running iOS 9.2 on an iPhone, and compiling with Parse 1.11.  I created an app specifically to test this (as it's not working in my current project).  That test project is attached.

[Test.zip](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/files/74941/Test.zip)

**Comment by nlutsenko** [comment]
Hey @mbachrach, looks like you are not configuring the SDK with an `applicationId` and `clientKey`, which is very much required step to use any API and the behavior without this is undefined as of right now, and will throw an exception in future.

After adding `Parse.setApplicationId("a", clientKey:"b")` everything works like a charm.
Here is the updated code snippet from your project:
```swift
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    Parse.enableLocalDatastore()
    Parse.setApplicationId("a", clientKey:"b")
    PFUser.enableAutomaticUser()

    let acl = PFACL()
    acl.publicReadAccess = true
    PFACL.setDefaultACL(acl, withAccessForCurrentUser: true)
    
    let usr = PFUser.currentUser()
    assert(usr != nil)
    print(usr);
    
    return true
}
```

**Comment by mbachrach** [comment]
I have been doing that, although perhaps not in the same order you have in your code:  I just left it out of what I sent you.  I’ll check it out.

thanks
-Max
