### ISSUE TITLE
PFTwitterUtils silently fails when trying to log in and user has multiple accounts

### ISSUE THREAD

**Issue by samiq** [ParsePlatform/Parse-SDK-iOS-OSX#71]
This is an issue introduced with 1.8.0 when trying to log in user to twitter and the user has more than 1 twitter account setup.

This specific issue happens when trying to log into twitter from a uiviewcontroller that is been presented as modal. 

This is/was working ok up until 1.7.3.5, where the selection of the account is done as a dialog and not as an action sheet.

For now the only way to make it work is forcing the 1.7.3.5 pod 

In the console you can see printed

Warning: Attempt to present <UIAlertController: 0x127685e70> on <LFTabBarController: 0x12763c990> whose view is not in the window hierarchy!

Where LFTabBarController is just a sub class of UITabBarController

**Comment by acegreen** [comment]
Seeing the same error: 

<StockSwipe.LogInViewController: 0x15e6508f0> which is already presenting <PFLogInViewController: 0x15e533b60>

**Comment by nlutsenko** [comment]
This sounds strange, looking into it.

**Comment by nlutsenko** [comment]
Valid bug indeed, working on fixing it...

**Comment by nlutsenko** [comment]
Bug is going to happen only on iOS 8.0+, and is going to be fixed whenever the attached PR is landed.
Feel free to start using `master` after this issue is closed.

**Comment by nlutsenko** [comment]
Hey guys, the fix for this is checked in and I've just tested locally - it totally works with the latest master and ParseTwitterUtils 1.8.1.
Let me know if there is anything else I can help you with.

**Comment by acegreen** [comment]
1.8.1? SDK on Parse.com shows the problem still there

**Comment by nlutsenko** [comment]
@acegreen `README.md` has a guide on how to use the latest code from master from this repo, since everything is opensource. We don't rebuild the SDKs every time a new commit is checked in into master, as it would require about 10-15 builds of the SDK every day.

I would suggest using CocoaPods for this actually, since it's the easiest way to install this.

**Comment by acegreen** [comment]
@nlutsenko I did consider adding Parse as a pod but i like .frameworks, just easier to import
