### ISSUE TITLE
Twitter LoginwithBlock Crashed if twitter account not added

### ISSUE THREAD

**Issue by venky145** [ParsePlatform/Parse-SDK-iOS-OSX#714]
I am getting below exception after 
[PFTwitterUtils logInWithBlock:^(PFUser *user, NSError *error) {}

i am getting below error

LaunchServices: invalidationHandler called
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x21f3a49f 0x2f734c8b 0x21e5a873 0x21e5a657 0xd92d5 0xdabeb 0x5119db 0x5119c7 0x5153ed 0x21f003b1 0x21efeab1 0x21e4c3c1 0x21e4c1d3 0x2924a0a9 0x2545a7b1 0x9d8f5 0x2fcb4aaf)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by nlutsenko** [comment]
Hey @venky145, please verify that `callback url` is set in your Twitter app settings at https://dev.twitter.com/apps.

If it still fails after this - please open an issue in the [ParseTwitterUtils repo](https://github.com/parseplatform/parsetwitterutils-ios).
