### ISSUE TITLE
Parse Analytics: tvOS custom events show up as Android

### ISSUE THREAD

**Issue by pbonneville** [ParsePlatform/Parse-SDK-iOS-OSX#715]
When posting a custom event to Parse Analytics in a tvOS app, the event shows up with a "Parse SDK" of Android in the Analytics Explorer > Table view

![screenshot 2016-01-04 10 08 44](https://cloud.githubusercontent.com/assets/1179637/12095414/a52f3f9a-b2cb-11e5-9304-faa90db54cd2.png)

**Comment by nlutsenko** [comment]
Hey @pbonneville, we noticed this issue earlier and it should be fixed as of this morning.
(the old data might still be recognized as `Android`, but the new data should definitely be visible as coming from tvOS).
If you still can see wrong values there - could you file a request on https://www.parse.com/help, as we are still using FB Bug Tool to track dashboard/backend issues.

**Comment by pbonneville** [comment]
The correct value is showing up now. Thanks!
