### ISSUE TITLE
Not able to update object from iOS on PARSE

### ISSUE THREAD

**Issue by akshayaher** [ParsePlatform/Parse-SDK-iOS-OSX#723]
I have tried to update Parse object from Parse CloudCode function. I want to update status_id for one particular entry whose objectId is "vZveFx3KcP”. Whenever i call following function no entry gets updated. but whenever i added manual entry or entry from Android device it gets updated without any issue. For iOS i am using latest Parse version "1.11.0". I got this issue only to those entries who gets added by iOS platfrom.

Can any one Please explain where i am going wrong. I am new to javascript programming so let me know if you need additional information from me. You can check my code below. I have tried calling cloud function from Parse API console.

Parse.Cloud.define("freshFunction", function(request, response) {

               var GameScore = Parse.Object.extend("Booking");
               var query = new Parse.Query(GameScore);
               query.equalTo("objectId", "vZveFx3KcP");
               query.first({
                          success: function(results) {

                          alert("Successfully retrieved " + results.length + "user_id");

                          results.set("status_id", 2);
                          results.save();
                          response.success();
                          },
                          error: function(error) {
                          alert("Error: " + error.code + " " + error.message);
                           response.error();
                          }
                          });

               });

	
I am updating these entries from cloud code. I am able to fetch and update those entries from iOS platform. But those entries are not updating when we call them from cloud code. In cloud code i am getting success message but in reality its not at all updated. This happens to entries who are added from iOS platform. For android and manual entry function works fine.
 Can anyone face the same issue ? Let me know if you need additional info from me.

Thanks in Advance,
Akshay Aher.

**Comment by nlutsenko** [comment]
Hey @akshayaher, this looks to be more related to Cloud Code/JS SDK. I can help you validate the iOS code that you are using, but the JS function looks fine, since it also works on Android.

Another thing I would recommend is to fit an issue on our [JS SDK](https://github.com/parseplatform/parse-sdk-js) repo.

**Comment by akshayaher** [comment]
For adding object i am using following code on iOS platform. 

PFObject *gameScore = [PFObject objectWithClassName:@"Booking"];
    gameScore[@"book_fromtime"]=[NSNumber numberWithFloat:[[[arrStartTimeUTC objectAtIndex:1] stringByReplacingOccurrencesOfString:@":" withString:@"."] floatValue]]; 
    gameScore[@"book_totime"] = [NSNumber numberWithFloat:[[[arrEndTimeUTC objectAtIndex:1] stringByReplacingOccurrencesOfString:@":" withString:@"."] floatValue]];
    gameScore[@"book_date"]=[arrStartTimeUTC objectAtIndex:0];
    gameScore[@"room_mac_id"]=objRoomData.roomMacId;
    gameScore[@"user_id"]=[[NSUserDefaults standardUserDefaults] objectForKey:USER_ID];
    gameScore[@"title"]=txtSubject.text;
    gameScore[@"description"]=txtViewDescription.text;
    gameScore[@"status_id"]=@1;
    
    [gameScore saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
            if (succeeded) {
                // The object has been saved.
                [self hideBusyActivityView];
                [self.navigationController popViewControllerAnimated:YES];
            } else {
                // There was a problem, check error.description
                [self hideBusyActivityView];
                [self showAlertWithMessage:error.localizedDescription];
            }
        }];


With above code object saved successfully. however when i updated that object from cloud code it fail to update.
