### ISSUE TITLE
[Error]: temporary error. Code: 159

### ISSUE THREAD

**Issue by halvini** [ParsePlatform/Parse-SDK-iOS-OSX#725]
5 minutes ago I wrote that I cant access my app because of error code 2, which happens every day at about 4 p.m. UTC.

Now I cant even access my Dashboard.
![2016-01-05 19 09 07](https://cloud.githubusercontent.com/assets/16026223/12121801/e7020014-b3df-11e5-940d-e23afa08a3c1.png)

It shows that I have NO logs. And in the lower left corner of the Dashboard says "temporary error".

**Comment by nlutsenko** [comment]
Hey @halvini, please submit a ticket at https://parse.com/help, as we are using it for tracking backend issues. It also gives us an ability to see which app is this affecting.
