### ISSUE TITLE
Swift compiler warning

### ISSUE THREAD

**Issue by kamoljan** [ParsePlatform/Parse-SDK-iOS-OSX#73]
Hi guys

I am getting Swift compiler warning:
`Umbrella header for module 'Parse' does not include header 'PF_Twitter.h'`

Podfile with Xcode 6.4

    pod 'Parse', '1.8.1'
    pod 'ParseFacebookUtils', '1.8.1'
    pod 'ParseCrashReporting', '1.8.1'
    pod 'FBSDKCoreKit', '4.5.1'
    pod 'FBSDKLoginKit', '4.5.1'
    pod 'FBSDKShareKit', '4.5.1'
    pod 'Bolts', '1.2.0'

**Comment by nlutsenko** [comment]
Hmm... @kamoljan, this sounds very strange, as `PF_Twitter` is not even available in the codebase anymore - it was moved to ParseTwitterUtils with `1.8.0`.

Can you please clear Xcode DerivedData and try recompiling?

**Comment by kamoljan** [comment]
@nlutsenko yeah, it is wierd. I will check tonight and update you.
Thank you.

**Comment by famAlex** [comment]
I'm in the same situation too.
My pod file is:

pod 'Bolts'
pod 'Crashlytics'
pod 'DLImageLoader', '~> 2.1.0'
pod 'DOFavoriteButton'
pod 'DZNEmptyDataSet'
pod 'Fabric'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Parse'
pod 'ParseUI'
pod "PhotoSlider"
pod "XCDYouTubeKit", "~> 2.2.0"
pod 'TwitterCore'
pod 'TwitterKit'

and I get the two errors when I run my app on iPad only:
Umbrella header for module 'Parse' does not include header 'PF_Twitter.h'
Umbrella header for module 'Parse' does not include header 'PFTwitterUtils.h'

Before updating Parse with pods to last version available, I hadn't any issue.

**Comment by nlutsenko** [comment]
Hey @famAlex, since `1.8.0` of Parse pod - ParseTwitterUtils are a separate framework, 
contained in `ParseTwitterUtils` pod. Cleaning Xcode derived data aka Product -> Clean is generally a very good practice and something that I personally multiple times a day just to make sure everything still works in a clean environment.
