### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'Key "title" has no data.  Call fetchIfNeeded before getting its value.'

### ISSUE THREAD

**Issue by duraiganesh0** [ParsePlatform/Parse-SDK-iOS-OSX#740]
SDK throws this error while accessing data from parse. 'NSInternalInconsistencyException', reason: 'Key "title" has no data.  Call fetchIfNeeded before getting its value.' . Can anyone help me to solve this issue?

**Comment by nlutsenko** [comment]
Hey @duraiganesh0, this is a valid error - if trying to read data for a given key that was never set from an object that was never fetched - it will throw this exception.
To fix it, per suggestion of the exception message - add `fetchIfNeeded()` call on this object before reading any values.
