### ISSUE TITLE
Erratic push notification delivery

### ISSUE THREAD

**Issue by nishrit** [ParsePlatform/Parse-SDK-iOS-OSX#748]
We are noticing an error, where when sending push notifications from the parse backend, it is not being delivered to all devices. This number varies on every push. In push analytics it reports a few error that dont give much information with the error "Other" (30%) being the most common, followed by  APN's(No certificate). What could be causing these issues. We have also noticed some devices get a push one day, not the other, then get it again the day after.

**Comment by nlutsenko** [comment]
Hey @nishrit, looks like this is purely backend issue. Could you file a report at https://parse.com/help, since we are using FB Bug Tool to track backend related issues.
