### ISSUE TITLE
PFInstallation doesn't update or fetch current data while app is in foreground

### ISSUE THREAD

**Issue by DaylnM** [ParsePlatform/Parse-SDK-iOS-OSX#749]
It seams that when app is in foreground the PFInstallation object doesn't update or fetch correct data unless a notification is received while in background.
Link to stackoverflow issue:

http://stackoverflow.com/questions/34441126/pfinstallation-not-up-to-date-when-receiving-notifications-in-app

**Comment by nlutsenko** [comment]
This is quite strange, as the received notification even in foreground should trigger the update of the notification badge icon number. Is there any chance you can verify that the badge icon number via `UIApplication.sharedApplication().applicationBadgeIconNumber` is also wrong?
