### ISSUE TITLE
Appcrash issue

### ISSUE THREAD

**Issue by dushmantha** [ParsePlatform/Parse-SDK-iOS-OSX#752]
When I execute this objective c file(PFSQLiteDatabase) in my mobile application, app was crashed.please help me.

PFSQLiteDatabase.m line 176 
-[PFSQLiteDatabase_executeQueryAsync:withArgumentsInArray:cachingEnabled:]

**Comment by nlutsenko** [comment]
Hey @dushmantha, unfortunately just based on method and line number it's very hard to find the source of the problem. Can you attach a stack trace for all threads for your app at the moment it crashed?
