### ISSUE TITLE
Unable to create a Pointer with a String ID

### ISSUE THREAD

**Issue by Helmikku** [ParsePlatform/Parse-SDK-iOS-OSX#753]
Hi,

I want to create and save a message object with a pointer to its conversation. I already have the conversation object ID but I don't have the whole conversation object.

I used to create a pointer with the method PFObject(withoutDataWithClassName:, objectId:) but it is not working anymore. Is it a bug or is it  a normal behaviour? How would you create a pointer with the object ID from the iOS SDK then?

Here is a sample of code (iOS - Swift - SDK 1.12.0):

let conversationId = "MyConversationID"
let message = PFObject(className: "Message")
message["conversation"] = PFObject(withoutDataWithClassName: "Conversation", objectId: conversationId)
message["user"] = PFUser.currentUser()!
message["body"] = "Hello world"
message.saveInBackground()

And the error:
[Error]: object not found for update (Code: 101, Version: 1.12.0)

If I comment the line message["conversation"]... the message is saved without any issue. I've also checked that the ID is the right one.

**Comment by nlutsenko** [comment]
After some testing - I can't reproduce the issue at all, as long as `conversationId` is a valid objectId that exists in the database.
Here is the code that I've used.
```swift
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    Parse.enableLocalDatastore()
    Parse.setApplicationId("hSXnrrMHMSoR9GbanivAkTCup7Cw2vxCOoZ9I5C9", clientKey: "IubXJ3kxXOnOS5c7QFyPhlr4AOu1VDJ86mXOMN4m")

    let conversationId = "8dKKLiUERJ"
    let message = PFObject(className: "Message")
    message["conversation"] = PFObject(withoutDataWithClassName: "Conversation", objectId: conversationId)
    message["body"] = "Hello world"
    do {
        try message.save()
    } catch let error {
        print(error)
    }
    print(message)

    return true
}
```

Any chance you can verify that the objectId is valid?

**Comment by Helmikku** [comment]
Thanks for your feedback.

I've checked several times the ID but it is correct. In fact, I create the conversation pointer and use it twice. In the first case, I use it to load every messages of the conversation, and it works.

Code:
dataSource = PFObject(withoutDataWithClassName: "Conversation", objectId: conversationId)
let query = PFQuery(className: "Message")
query.includeKey("conversation")
query.includeKey("user")
query.whereKey("conversation", equalTo: dataSource)
query.findObjectsInBackgroundWithBlock()...

I got all the messages of the conversation without any issue.

But when creating a new message, with the same PFObject (dataSource), it fails.

I've tried in Android and got the same issue. When I print/log the PFObject at the different calls, I got the same ID, the same object reference. I don't have any log in the server side.

My last hint would be : since I'm using LocalDataStore, and I'm getting messages including the conversation object, could the pointer and the real object be in conflict?

**Comment by Helmikku** [comment]
Well I finally found what was wrong.

I was setting one field of my pointer (conversation default name). It was thus locally modified and not synced with its datasource anymore.

That was causing the database to refuse this pointer, as not "up to date". (I thought that the message "up to date" was about the message but it was about the conversation pointer)

Thank you anyway!

**Comment by nlutsenko** [comment]
Glad you found it. Let me know if there is anything else.
