### ISSUE TITLE
App start -  objectId - unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by yaalaa** [ParsePlatform/Parse-SDK-iOS-OSX#755]
iOS 9.2
Parse 1.12
Bolts 1.6.0
App uses parse data sharing.

On particular devices app crashes on start, likely before didFinishLaunchingWithOptions, i.e. before any explicit Parse call.
Console shows something like this:
```
App[NNN] <Error>: [/BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreUI/CoreUI-371.4/Bom/Storage/BOMStorage.c:522] <memory> is not a BOMStorage file
App[NNN] <Error>: -[__NSDictionaryM objectId]: unrecognized selector sent to instance 0x14d6c3e60
```
I saw such issues months ago, several times.
Now it's time again.
Re-install doesn't help.
Other device works good.

Any ideas?

**Comment by nlutsenko** [comment]
Is there any chance you can get a stack trace from the thread that is crashing?
It's really hard to bisect this down to a specific place, as we call `objectId` like this in a lot of places.

**Comment by yaalaa** [comment]
Device is remote, I couldn't debug it but I figure out the real issue looks differently. I'm going to file it as separate one.

**Comment by nlutsenko** [comment]
@yaalaa, I think you are right #762 would be the root issue for this.
I am going to close this one out, let me know if there is anything other than the issue described in #762 that is causing this.

**Comment by josh7** [comment]
almost in all cases, this is harmless unless your url is wrong.to make the BOMStorage file more serious, you can add this: **urlString = [urlString stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]]; **
**Besides,you can choose other method to replace:[image stretchableImageWithLeftCapWidth:0 topCapHeight:0] forState:UIControlStateNormal];**
