### ISSUE TITLE
Parse version 1.12.0, freeze UI

### ISSUE THREAD

**Issue by kirank-canwill** [ParsePlatform/Parse-SDK-iOS-OSX#757]
I have update latest Parse version 1.12.0, but it freeze UI while using Live and Local query. 

I've display the query result on tableview and tableview scrolling i will call parse live and local query. while query is running that time tableview view scrolling stuck.

Thanks

**Comment by kirank-canwill** [comment]
I observed that application stuck while below method execute.
[PFObject pinAllInBackground: resultArray block:^(BOOL succeeded, NSError *error) {
           }];

I have also tried [PFObject pinAllInBackground:resultArray]; but issue still remains. 

thanks
Kiran

**Comment by nlutsenko** [comment]
Hey @kirank-canwill, that sounds very strange.
Any chance you can post a stack trace here (or in a gist) for all threads, that would help us tremendously to uncover the underlying issue.

**Comment by kirank-canwill** [comment]
Hi Thanks for your response...

I have used below code. I have  four Tap on TableView and every Tap action and TableView Scrolling I'm calling this query according to tap request. Other three query are similar to this just table name changed.

If I comment the " [PFObject pinAllInBackground: objects];" this line every thing is working fine and smoothly.. O.W tableview scrolling stuck because of above line.

 PFQuery *query = [PFQuery queryWithClassName:@"Invitation"];
     [query whereKey:@"recipients" equalTo:[LUUser currentUser]];
     [query includeKey:@"recipients"];
     [query includeKey:@"sender"];
     [query orderByDescending:@"createdAt"]; 
     [query setLimit:startPoint]; 
     [query setSkip:endPoint];
    if([ConnectionModel checkInternetConnection]) { //If connection appear get result from Live server
      NSLog(@“Connection connected”)
     }else{
    [query fromLocalDatastore]; // Take result from Local Server...
     NSLog(@“Connection failed”)
     }
    [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error)      {
    completionBlock(objects);
 [PFObject pinAllInBackground: objects];

}];

Please suggest me,  if need more information.

Thanks
Kiran

**Comment by nlutsenko** [comment]
Hey @kirank-canwill, since the code looks correct and we have tests around this piece - is there any chance you can include a stack trace (pause in the debugger and paste here the output of `bt all`).
That would help identify where the lock is coming from and investigate this further.

**Comment by kirank-canwill** [comment]
Hey, i have already told If I comment the below line everything is working fine.
 [PFObject pinAllInBackground: objects];

Thanks
Kiran

**Comment by hhanesand** [comment]
I don't see how that provides the information @nlutsenko needs @kirank-canwill .

The only way he will be able to diagnose this issue for you is if you provide a stack trace.

The next  time you observe your UI freezing, press the pause button in Xcode and type into the debugger `bt all`, and post the result here or link to it.
