### ISSUE TITLE
Setting Cache Policy on PFQuery has no effect

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/Parse-SDK-iOS-OSX#758]
```swift
let postQuery: PFQuery = PFQuery(className: "Posts")
postQuery.addDescendingOrder("day")
postQuery.whereKey("live", equalTo: true)
postQuery.cachePolicy = PFCachePolicy.CacheElseNetwork
print("Has posts cache: \(postQuery.hasCachedResult())")
```
This always returns as false, and my query always queries from network.

**Comment by talkaboutdesign** [comment]
Also I get this error sometimes: 
```swift
Optional(Error Domain=Parse Code=120 "Cache miss." UserInfo={error=Cache miss., NSLocalizedDescription=Cache miss., code=120})
```

**Comment by nlutsenko** [comment]
Hey @talkaboutdesign, that is strange.
Which method do you use to actually perform the query?
Please note, that `CacheElseNetwork` will try to get a cached value and then if there is no cache - fetch from network and save the result of the query to the cache.

**Comment by artooras** [comment]
Hi. I have the same issue with Parse not saving cache. Here's my sample code:

    PFQuery *query = [PFQuery queryWithClassName:GROUP];
    [query whereKey:GROUP_OWNER equalTo:[PFUser currentUser]];
    [query includeKey:GROUP_CONTACTS];
    [query orderByAscending:GROUP_TITLE];
    [query setCachePolicy:kPFCachePolicyCacheElseNetwork];

If I run this once and then the second time after the network callback had completed, cache is still empty.

**Comment by artooras** [comment]
Any progress on this issue? I've had it for a while now, here's a link to the question I raised 3 months ago to give some more context http://stackoverflow.com/questions/33317312/pfquery-never-has-cached-results

**Comment by nlutsenko** [comment]
No progress yet, but I am marking this for investigation, and will keep you updated.

**Comment by artooras** [comment]
Thanks. Does your last statement change though with the news about deprecation of the Parse platform out and public?

**Comment by nlutsenko** [comment]
Nope. I am going to stick around for a while to support the open source community.

**Comment by artooras** [comment]
Thanks

**Comment by nlutsenko** [comment]
And I don't think I can reproduce it at all.
No matter how hard I try - it always succeeds and properly returns true for `hasCachedResult` after cache the first network fetch. Any chance you guys can attach a repro case here or send it over email to nlutsenko(at)fb.com?

The test that I've used:
```objc
[Parse setApplicationId:@"phfHef5qZe2rHyHniyiEGiITNgwDMFdRANdYKdwE" clientKey:@"hKl13kaQ0B8sfDs8FQNYzxX7UI5BCNRhQKJDJqvD"];

PFQuery *query = [PFQuery queryWithClassName:@"Agenda"];
[query orderByAscending:@"updatedAt"];
[query whereKey:@"title" equalTo:@"1"];
query.cachePolicy = kPFCachePolicyCacheElseNetwork;
NSLog(@"%d", [query hasCachedResult]);
[[query findObjectsInBackground] continueWithBlock:^id _Nullable(BFTask * _Nonnull task) {
    NSLog(@"%d", [query hasCachedResult]);
    return nil;
}];
```
It properly reports false for the first log statement and from there on - always returns `true`.

**Comment by artooras** [comment]
Hi Nikita. I can't reproduce this anymore either. It seems it has been fixed somewhere. Thanks.

**Comment by nlutsenko** [comment]
Perfect, glad it works for you.
Let me know if anything comes up.
