### ISSUE TITLE
PFObjects created with objectWithoutDataWithClassName: doesn't pin

### ISSUE THREAD

**Issue by Dalein** [ParsePlatform/Parse-SDK-iOS-OSX#759]
I'm using CoreData as main DB for app and Parse local DB (pin) only for the objects that I can't send to Parse: create new or update old, because of Internet problem. My object has a property "id" that can has "local" format (it's not synced with Parse) and "synced" form (equals parse objectId). I have a method to get PFObject from NSManagedObject:

```objectivec
      - (nonnull PFObject *)getParseObjFromManagObj:(nonnull NSManagedObject *)managObj {

        PFObject *parseObj = nil;

        if ([self isLocalID:[managObj valueForKey:@"id"]]) {
            parseObj = [PFObject objectWithClassName:@"MyClass"];
        }
        else {
            // Create a pointer to an object
            parseObj = [PFObject  objectWithoutDataWithClassName:@"MyClass" objectId:[managObj valueForKey:@"id"]];
        }

         parseObj.ACL = [PFACL ACLWithUser:[PFUser currentUser]];
         parseObj[@"Foo"] = @"Bar";

       return parseObj;
}
```
I form array of PFObjects and send it like this:
```objectivec
- (void)saveAllInParse:(nonnull NSArray *)arrPFObj WithEntityName:(nonnull NSString *)entityName {

    [PFObject saveAllInBackground:arrPFObj block:^(BOOL succeeded, NSError * _Nullable error) {
        if (succeeded) {
            // Update CoreData objects
        }
        else {
            NSLog(@"Error saveAllInParse. %@", error);
            NSLog(@"______ arrPFObj = %@", arrPFObj);
            NSError *error = nil;
            [PFObject pinAll:arrPFObj error:&error];
            NSLog(@"pinAll error = %@", error.localizedDescription);
        }
    }]; 
}
```

If I do it when device has Internet - all OK, but if not it looks like arrPFObj didn't pinned, I can't then saw something in local datastore (I see log output "```objectivec ______ arrPFObj = ... ```" well, and error = nil). I tried this approach in getParseObjFromManagObj:
```objectivec
PFObject *parseObj = [PFObject objectWithClassName:@"MyClass"];

 if ([self isLocalID:[managObj valueForKey:@"id"]]) {
         parseObj.objectId = [managObj valueForKey:@"id"];
 }
```

And it's works well (online or offline it sending to Parse or pinned), but time to time I got this error: ```objectivec Attempted to change an objectId to one that's already known to the OfflineStore. ``` on row ```objectivec parseObj.objectId = [managObj valueForKey:@"id"]; ``` I assumed that reason for this error - that Parse local datastore already has an object with objectId that I trying to set, but before creating new PFObject I synchronously query from local datastore:
```objectivec
PFQuery *query = [PFQuery queryWithClassName:updateObj.entity.name];
        [query fromLocalDatastore];
        [query whereKey:@"localID" containedIn:arrObjsLocalIDs];

        NSArray *objects =  [query findObjects];
        if (objects.count > 0) {
           // Send this array to Parse
        }
        else {
          // Created PFObjects
        }
```
I'm struggling with this for couple of days, what I'm doing wrong?

**Comment by Dalein** [comment]
I think I found a problem. I saved a reference to PFObject before sending to Parse (in case if app got killed I pinned it), and didn't nil it after.

**Comment by nlutsenko** [comment]
Great, glad you found the problem.
Let me know if there is anything else here.

**Comment by christianpbrink** [comment]
@Dalein I'm seeing the same exception and don't quite understand your explanation of what the problem is / how to fix it. Can you elaborate a little? What were you doing wrong exactly?

**Comment by Dalein** [comment]
@christianpbrink this exception arise when you have more that one PFObject with the same objectID

**Comment by christianpbrink** [comment]
Thanks Daleijn. What I don't understand is the significance of whether or
not we save a reference to a PFObject (i.e. pin it, right?) before sending
it to Parse. Can you say more about this? I have routinely pinned objects
before saving them to Parse, and it has not caused a problem for me.
