### ISSUE TITLE
Network connection failed. Parse SDK 1.12.0

### ISSUE THREAD

**Issue by kirank-canwill** [ParsePlatform/Parse-SDK-iOS-OSX#764]
Hi 

We have face below issue in Parse SDK 1.12.0.

[Error]: The request timed out. (Code: 100, Version: 1.12.0)
[Error]: Network connection failed. Making attempt 1 after sleeping for 1.823224 seconds.
 [Error]: A server with the specified hostname could not be found. (Code: 100, Version: 1.12.0)

we used  Xcode Version is 7.0.
This error occurred very frequently. We have good internet connectivity but still we face this issued.

Thanks
Kiran

**Comment by nlutsenko** [comment]
Hey @kirank-canwill, this sounds very strange.
An error type - `A server with the specified hostname could not be found.` sounds like the device is failing to resolve DNS for our server - `api.parse.com`.
Is there any chance you can try hitting that URL directly say via Safari on the phone when you see this error happening... Since we don't have more reports on this issue, I am skeptical that this is caused by client and might be related to the DNS propagation or your local ISP.

Does this reproduce for you on the previous version of the SDK as well (1.11.0)?
Any more info on this would be super helpful.

**Comment by kirank-canwill** [comment]
Hey nlutsenko,

Thanks for response, Yes I got same error on previous versions. But this version we received very frequently this issued.

we have also added below setting in info plist, which are required for Https request in iOS9. 

<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>api.parse.com</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>


Thanks
Kiran

**Comment by nlutsenko** [comment]
These are not required for api.parse.com, as we fully conform to App Transport Security on api.parse.com. :wink: 
I would suggest filing an issue on https://parse.com/help for backend team to take a look at possible network issues in this case, since this looks like an isolated issue.

**Comment by kirank-canwill** [comment]
Thanks,
 I will put my issue over https://www.parse.com/help

Can you Please reply on below issues.
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/757


Thanks
Kiran

**Comment by miladmahdian** [comment]
Hi,

I have a similar problem. Did you find out how to fix it?

Thanks,
Milad

**Comment by kukkadapukarhtik** [comment]
hi,
i had a problem when i run the application on xcode using aws server.

Error]: The request timed out. (Code: 100, Version: 1.12.0)

**Comment by AshishKapoor** [comment]
check your response.error(error) and response.success("success"); Cheers

**Comment by parulgarg004** [comment]
@kirank-canwill can you please tell me how you solved this issue? I'm having the same problem.

**Comment by kukkadapukarhtik** [comment]
The network connection was lost. (Code: 100, Version: 1.12.0)
Network connection failed. Making attempt 1 after sleeping for 1.568368 seconds.

please help me out.

**Comment by Jesterix** [comment]
I had the same issue. The solution was that the name of the server in AppDelegate must start with "http://". May be this will be helpful to somebody.

**Comment by philosopherdog** [comment]
Make sure you're not denying the connection with a proxy like little snitch!
