### ISSUE TITLE
PFSubclassing with NSDate property returning different types when cache and not cached

### ISSUE THREAD

**Issue by steve0hh** [ParsePlatform/Parse-SDK-iOS-OSX#767]
So I've written this application that does the following:
```swift
let queryy = Week.query()
queryy?.orderByDescending("createdAt")
```

So my week subclass properties is as follows:
```swift
    @NSManaged var duration: String
    @NSManaged var to: NSDate
    @NSManaged var from: NSDate
    @NSManaged var name: String
    @NSManaged var remarks: String
    @NSManaged var semester: String
```
So I did some dates comparisons for the `to` and `from` properties and it works.

After adding the following `.CacheElseNetwork`, it is not working.. 
```diff
let queryy = Week.query()
queryy?.orderByDescending("createdAt")
+ queryy?.cachePolicy = .CacheElseNetwork // look for cache first, then network
```
and upon inspection on setting some breakpoints and printing out the types the result is as follows:

```swift
// without caching
(lldb) po week.to
2015-08-07 00:00:00 +0000

(lldb) po week.to.dynamicType
__NSTaggedDate


// this is with caching
(lldb) po week.to
2015-08-07T00:00:00.000Z

(lldb) po week.to.dynamicType
__NSCFString
```

Is it supposed to be like this or is this a bug? 

Thanks! :smile:

**Comment by nlutsenko** [comment]
Hey @steve0hh, thanks for the report, this sounds indeed like a bug.
Will investigate and let you know.

**Comment by steve0hh** [comment]
Ahh. Alright. Thanks! 

Anyway, I am using the following versions:
  - Bolts/Tasks (1.5.1)
  - Parse (1.11.0):
    - Bolts/Tasks (~> 1.5)

**Comment by nlutsenko** [comment]
If you could upgrade to `1.12.0` and comment if you still experience the issue - it would be extremely helpful.

**Comment by steve0hh** [comment]
Updated to the following:
  - Bolts/Tasks (1.6.0)
  - Parse (1.12.0):
    - Bolts/Tasks (~> 1.5)

But I am still having the same error. :smile:

**Comment by nlutsenko** [comment]
Perfect, that helps a whole lot, since we have a confirmation that we will likely be able to reproduce an issue locally.

**Comment by nlutsenko** [comment]
And I don't seem to be able to reproduce this with SDK 1.13.0 and Swift 2.2.
@steve0hh, could you confirm that this works for you?
I am using this code snippet right now:
```swift
    class Agenda: PFObject, PFSubclassing {
        @NSManaged var date: NSDate

        static func parseClassName() -> String {
            return "Agenda"
        }
    }

    func applicationDidFinishLaunching(aNotification: NSNotification) {
        Parse.setApplicationId("phfHef5qZe2rHyHniyiEGiITNgwDMFdRANdYKdwE", clientKey: "hKl13kaQ0B8sfDs8FQNYzxX7UI5BCNRhQKJDJqvD")
        Agenda.registerSubclass()

        let query = Agenda.query()
        query?.orderByDescending("createdAt")
        query?.limit = 1
        query?.cachePolicy = .CacheElseNetwork
        query?.findObjectsInBackgroundWithBlock({ (results, error) in
            print(results)
            if let agenda = results?.first as? Agenda {
                print(agenda.date)
                print(agenda.date.dynamicType)
            }
        })
    }
```
