### ISSUE TITLE
pin and save should be separated completely

### ISSUE THREAD

**Issue by acegreen** [ParsePlatform/Parse-SDK-iOS-OSX#77]
This maybe my specific implementation but I have a scenario where I would like to saveEventually and still pin the object, regardless of the outcome of the saveEventually. 

This matters to me because I can then manipulate the object locally without fetching it again, then saveEventually again when I'm done. 

saveEventually can pin the object or do whatever but if I purposely pin an object using the pinInBackgroundWithBlock I expect it to stay pinned regardless.

**Comment by nlutsenko** [comment]
Hey @acegreen, sorry it took a while to get back to you on this one.
You can still pin any object to Local Datastore, regardless of whether you are saving it eventually or not.
And it will still stay pinned, regardless if saveEventually succeeds or fails.

Since PFObject is guaranteed to be a single instance in-memory if you have Local Datastore enabled - all the changes that you make to this object, or anything that updates that object (like querying for it) - will propagate to the object and will be available to you.

**Comment by acegreen** [comment]
Thanks for getting back to me on this, i have been struggling to get localDataStore working for a while now. What you said above is exactly what I was hoping for but something doesn't seem right

Here is what I'm doing to saveEventually and pin my object

            currentObject.pinInBackgroundWithBlock({ (success, error) -> Void in
                
                if success {
                    
                    print("pinned successfully")
                }
                
            })
            
            currentObject.saveEventually()


Then to retrieve my objects i do:

		var parseLocalQuery = PFQuery(className:"Stocks")
//        parseLocalQuery.fromLocalDatastore()
        parseLocalQuery.whereKey("Symbol", containedIn: symbolStringArray)
        parseLocalQuery.findObjectsInBackgroundWithBlock({ (objects, error) -> Void in
            
            if error == nil {
                
                if let objects = objects as? [PFObject] {
                    
                    // The find succeeded.
                    print("Successfully retrieved \(objects.count) object")
                    
                }
                
            } else {
                
                // Log details of the failure
                print("Error: \(error) \(error!.userInfo)")
                
            }
        })

if i comment out .fromLocalDatastore() it retrieves the object. But with it, the query comes back empty (count = 0). 

Notes:
- Pinning seems to be successful as the print message appears
- tried to move saveEventually() before pinning didn't make a difference ( I thought saveEventually() only holds onto the object until it can save it then deletes it. 
- tried to remove saveEventually() completely and just leave pinInBackgroundWithBlock and still no results

**Comment by nlutsenko** [comment]
> tried to remove saveEventually() completely and just leave pinInBackgroundWithBlock and still no results

If this code doesn't work even without `saveEventually()` - it's quite possible that `saveEventually()` piece is completely unrelated to this.
Is it possible that there is no object `Stocks` that have `Symbol` inside symbolStringArray in Local Datastore?

**Comment by acegreen** [comment]
I only tried to remove saveEventually() after posting this. Might not be but I thought saveEventually() only pins until it can save then removes the object from localDatastore.

i tried to remove the .whereKey predicate but still empty. I did notice though that VERY rarely it actually retrieves something. can be that it requires a REALLY long time to pin? Even though, it shows pin successful right after i pin it?

**Comment by acegreen** [comment]
The object should have Symbol inside it as it is the same object I fetched from the cloud easier. 

Here is the workflow:

1. Fetch objects from data
2. When button is pressed, pin object
3. when deleting object, fetch object fromLocalDatastore 
4. do something to object and delete it

The struggle is with step 3. If I do step 3 from the cloud using the whereKey of symbolStringArray it works. Doing it from local WITH or WITHOUT whereKey, query is empty

**Comment by nlutsenko** [comment]
This sounds very strange.
Do you have query fetching being done after the pinning happened?

A repro project or code snippet would be the best help here, since the code above is quite generic.

**Comment by acegreen** [comment]
@nlutsenko apologize for the delayed reply, didn't have access to my computer.

The query is DEFINITELY being executed after the pin. 

Sample code is above, but I'll need to figure out who to setup a repro project because the project is a little sensitive. Can we setup a short chat outside to show you the issue first hand

**Comment by Raesu** [comment]
I would like to hear any conclusions from this topic. I have noticed some unusual behavior when pinning and using saveEventually.

**Comment by acegreen** [comment]
@nlutsenko i would like to address this as well. A short skype session would be very efficient to show you what I'm talking about

**Comment by acegreen** [comment]
@nlutsenko Anyone there? I know you are busy, but I would really appreciate if we can sit down and discuss this

**Comment by acegreen** [comment]
Hello? Anyone there?

**Comment by nlutsenko** [comment]
Hey @acegreen, sorry - got tangled in other things.
Can you share the piece of code that you use for pinning the object, the object schema and query here?

This sounds like a general use case of Local Datastore (pin an object, query for it), as we previously discussed looks like not related to `saveEventually`.

Feel free to share the project with me privately (nlutsenko@fb.com) or in any way you want to.

**Comment by acegreen** [comment]
@nlutsenko Its hard to show you my specific case using a demo or snippet code. I would just schedule a 5 minute session to show you the code in action. If it turns out to be an actual problem, we will document it here for everyone to follow

**Comment by nlutsenko** [comment]
@acegreen, the best way to help you would be to look at the sample project that reproduces the issue, or a snippet of code that includes information I referenced above.
If you explicitly need to share it privately, feel free to reach out via email or Facebook Messenger.

**Comment by acegreen** [comment]
@nlutsenko I can't share my project, nor am I interested to replicate the whole process is another issue. I don't see how 10 minutes of showing you on Skype is not a better way or more efficient. Anyways I'm done trying with this. You don't seem interested to resolve this. Lets wait until enough people complain

**Comment by acegreen** [comment]
I don't think this should be closed. I would suggest you have a short Skype chat with me and I can demonstrate the issue at hand.

**Comment by acegreen** [comment]
@nlutsenko 

So I'm taking another jab at this issue. Suddenly with 1.10.0, fetching from fromLocalDatastore returns stuff. Literally the exact same code. 

But then I try to do:
                    for object in objects {
                        
                        guard (PFUser.currentUser() != nil) else { break }
                        
                        object.removeObject(PFUser.currentUser()!, forKey: "Shorted_By")
                        object.removeObject(PFUser.currentUser()!, forKey: "Longed_By")
                        
                        object.saveEventually()
                        
                        print("User removed from object: \(object)")
                    }
And it just doesn't go further, no crash but the rest of my code doesn't run further. Also the currentUser is not removed from those objects online.

**Comment by acegreen** [comment]
Just two notes:

1. Issue still there on 1.11.0

2. If I comment out the removeObject lines, the code executes as expected. but that means I can't remove stuff from a pinned object?
                        object.removeObject(PFUser.currentUser()!, forKey: "Shorted_By")
                        object.removeObject(PFUser.currentUser()!, forKey: "Longed_By")

**Comment by acegreen** [comment]
@nlutsenko see notes above, if I try to do the above with fromLocalDatastore() it just jumps the rest of my code. If I comment these removeObject out, it runs. 

I pinned the objects to my local datastore so I can later retrieve them and manipulate them and do saveEventually.

**Comment by gstream** [comment]
I am facing same issue. After pinned object, I can't retrieve from local database.
[[query findObjectsInBackground] continueWithBlock:^id(BFTask *task) {
            if (task.error) {
                NSLog(@"Error: %@", task.error);
                return task;
            }
            
            NSLog(@"Retrieved %@", task.result);
            return task;
        }]

Fetching object from local database always returns 0 elements array.

**Comment by gstream** [comment]
But can retrieve objects without this line.
[query fromLocalDatastore];
