### ISSUE TITLE
Any reason why OCMock is included through Carthage?

### ISSUE THREAD

**Issue by AndrewSB** [ParsePlatform/Parse-SDK-iOS-OSX#771]
In my opinion it doesn't make sense to include the `OCMock.framework` when installing through Carthage. Would love your input on this/ get it removed.

**Comment by nlutsenko** [comment]
Hey @AndrewSB, thanks for the report.
`OCMock` is not included into public `Cartfile` (only the private one aka `Cartfile.private`), as a result it won't be installed when you use Carthage for dependency management.
Are you compiling the project from scratch using `carthage build` and a local checkout of the repo, or using your own Cartfile to manage dependencies?

**Comment by AndrewSB** [comment]
I'm compiling using `carthage update --no-use-binaries --platform iOS`

my Cartfile is 
```
# Helper
github "AndrewSB/Library" "master"
github "AndrewSB/Curly" "master" 
github "Haneke/HanekeSwift"
github "hackiftekhar/IQKeyboardManager"
github "thii/SwiftHEXColors"
github "malcommac/SwiftDate"
github "duemunk/Async"

# Custom UI
github "AndrewSB/HMSegmentedControl" "master"
github "AndrewSB/KLCPopup" "master"

# Reactive
github "ReactiveX/RxSwift" ~> 2.0 
github "AndrewSB/Parse-RxSwift" "master"
github "robrix/Box"

# Parse
github "ParsePlatform/Parse-SDK-iOS-OSX" "master"
github "flovilmart/ParseKit" "master"    
```

and the relevant line in the update output is `*** Building scheme "OCMock iOS" in Parse.xcworkspace`

**Comment by nlutsenko** [comment]
@AndrewSB, try removing `"master"` from your Cartfile, this might help very much.

**Comment by nlutsenko** [comment]
Also, looks like you are using `flovilmart/ParseKit`, which might collide with official Parse support for Carthage. cc @flovilmart

**Comment by AndrewSB** [comment]
@nlutsenko trying without `master` right now. Didn't notice that you had published a release with full Carthage support :smile: 

ParseKit doesn't get built if I use the `--no-use-binaries` flag, so I'm 100% sure it's not affecting the build when I update as I am right now

**Comment by AndrewSB** [comment]
Not targeting `"master"` seems to have done the trick!

**Comment by nlutsenko** [comment]
Perfect! Glad it helped!
