### ISSUE TITLE
PFQuery fromLocalDatastore() returns [Error]: The Internet connection appears to be offline

### ISSUE THREAD

**Issue by andrew8712** [ParsePlatform/Parse-SDK-iOS-OSX#776]
Please consider this code:

    if !Reachability.isConnectedToNetwork() {
        query.fromLocalDatastore()
    }
    query.findObjectsInBackgroundWithBlock { (objects, error) -> Void in
       
    }

I'm expecting the objects to be received from the local datastore when the device is completely offline, but I'm getting this error instead of desired objects:

    [Error]: The Internet connection appears to be offline. (Code: 100, Version: 1.11.0)

Does local datastore requires the Internet connection?

PS: I have called `Parse.enableLocalDatastore()`

**Comment by nlutsenko** [comment]
Local Datastore queries indeed never touch the network and this error shouldn't happen, unless you performing a query against Parse.
Any chance you can expand here on the steps to repro the issue? That would be super helpful to investigate further!

**Comment by andrew8712** [comment]
I checked `findObjectsInBackgroundWithBlock:` method in PFQuery.m and this condition:

    (!self.state.queriesLocalDatastore && self.state.cachePolicy == kPFCachePolicyCacheThenNetwork)

evaluates to false. I have `self.state.cachePolicy == kPFCachePolicyIgnoreCache` for some reasons.

When I'm trying to set `cachePolicy` manually, I get "Method not allowed when Pinning is enabled." errror

**Comment by andrew8712** [comment]
Sorry, this seems to be my code issue: there was another query without `fromLocalDatastore()` call
