### ISSUE TITLE
The issue was closed, but not resolved

### ISSUE THREAD

**Issue by halvini** [ParsePlatform/Parse-SDK-iOS-OSX#777]
Dear Nikita,

Thank you for your time and your answer!

Please have a look at my last comment. I think we haven't found the right solution yet:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/769

**Comment by nlutsenko** [comment]
You can always reopen the issues that you've created, reopening - let's have further discussion there.
