### ISSUE TITLE
Keychain access request

### ISSUE THREAD

**Issue by Naoto-Ida** [ParsePlatform/Parse-SDK-iOS-OSX#779]
I'm not that well aware of keychains,
but I've gotten a report from a non-dev colleague that ever since the bundle name change in our app,
he has been getting requests for Keychain access (it isn't the bundle identifier, which I presume is very important for Keychain).

Is it normal for Parse to ask for keychain access?
There was nothing about it written in the documents, so I'm kind of worried that maybe it's the way I implemented it.

This is all that I'm doing with Parse:
```
Parse.setApplicationId(self.parseApplicationId, clientKey: self.parseClientKey)
PFAnalytics.trackAppOpenedWithLaunchOptions(nil)

if !isRegisteredWithParse() {
    registerWithParse()
}

func isRegisteredWithParse() -> Bool {
    if PFUser.currentUser() != nil {
        print("Already registered with Parse")
        return true
    }
    return false
}

func registerWithParse() {
    print("Registering with Parse")
    PFAnonymousUtils.logInWithBlock() {
        user, error in
        if error != nil {
            print(error)
        } else {
            print("Login complete!")
            PFUser.currentUser()!.setObject(self.isUnlocked(), forKey: "isCustomer")
            PFUser.currentUser()!.saveEventually()
        }
    }
}
       
```

**Comment by nlutsenko** [comment]
Hey @Naoto-Ida, we are using system Keychain on iOS/OSX/tvOS/watchOS to store user sensitive information, like session token or Facebook authentication data.
Don't be worried about a way you implemented it - this is an intended behavior.
To remove the keychain permission request on every app launch on OS X - I would recommend looking at the entitlements/permissions of your application - it should list keychain as one of the capabilities.
Feel free to reopen this issue if there is anything else here I could help you with.

**Comment by Naoto-Ida** [comment]
@nlutsenko Thank you! Really enjoying the statistics we are getting.
