### ISSUE TITLE
Error possibly due to adding localeIdentifier

### ISSUE THREAD

**Issue by CraigSiemens** [ParsePlatform/Parse-SDK-iOS-OSX#78]
After updating to 1.8.1, I was getting the following message in the debugger.

```
[Error]: This user is not allowed to add a field to _Installation. You can change this setting in the Data Browser. (Code: 119, Version: 1.8.1)
```

I checked the `Installation` table and it already had the new `localeIdentifier` column so that shouldn't be the cause.

I temporarily turned on the `Add Field` permission, ran my app again, then turned off `Add Field` and I've stopped getting the error.

My guess is that something private needed to be added to `Installation` since nothing I can see has changed on `Installation`. Is this the case? Any way to prevent this in the future?

**Comment by nlutsenko** [comment]
This sounds like a backend issue, since the error and the solution that you've used is not related to the client implementation of this property.
As we continue to use FB bug reporting tool for those - can you file a bug report on https://parse.com/help
