### ISSUE TITLE
Error 209 invalid session token after Facebook linking of the current anonymous user

### ISSUE THREAD

**Issue by Seishin** [ParsePlatform/Parse-SDK-iOS-OSX#781]
Hello pals! 

I'm experiencing this problem with my parse app after the current anonymous user is linked with his/her Facebook profile.

The implementation is the same in my Android app as well, but the iOS app gives me this error... 

In the AppDelegate class I've this code:
```Swift
if (PFUser.currentUser() == nil) {
    PFAnonymousUtils.logInInBackground()
} else if (PFUser.currentUser() != nil && PFFacebookUtils.isLinkedWithUser(PFUser.currentUser()!)) {
    PFFacebookUtils.logInInBackgroundWithAccessToken(FBSDKAccessToken.currentAccessToken())
}
```

When the user wants to link with his/her Facebook profile:
```Swift
if PFFacebookUtils.isLinkedWithUser(PFUser.currentUser()!)  {
    PFFacebookUtils.linkUserInBackground(PFUser.currentUser()!, withReadPermissions: permissions, block: { (success: Bool, error: NSError?) -> Void in
        if success.boolValue {
            PFFacebookUtils.linkUserInBackground(PFUser.currentUser()!, withAccessToken: FBSDKAccessToken.currentAccessToken())
             self.obtainFacebookProfile()
         }
     })
} else {
    PFFacebookUtils.logInInBackgroundWithReadPermissions(permissions, block: { (user: PFUser?, error: NSError?) -> Void in
        if error != nil {
            return
         }
                
         if user != nil {
             PFFacebookUtils.linkUserInBackground(user!, withAccessToken: FBSDKAccessToken.currentAccessToken())
              self.obtainFacebookProfile()
          }
    })
}
```

What I can do to get rid of this error? 
I want to have persistent anonymous users and after their linking with FB, the FB parse user to persist.

Thanks!

**Comment by nlutsenko** [comment]
Hey @Seishin, thanks for the report.
From the code above: You don't need to link Facebook with currentUser if you already logged in with Facebook. Logging in will do it for you. That might help resolve the issue here, but overall - if you can get a piece of code that I can use to reproduce the issue - I will be able to assist further.

**Comment by Seishin** [comment]
Thank you for your fast reply @nlutsenko! 

I made what you suggested. It works except that on the first app start after the linking/login with Facebook I still receive the error. On any further start of the app, the user is logged in with Facebook.

You could reproduce it with the referencing code I wrote above. Just comment the
```
self.obtainFacebookProfile()
```

**Comment by Seishin** [comment]
I think I solved this problem by getting rid of Facebook login in the AppDelegate class. Since the current user is already linked with the Facebook profile, there is no need to do it again on app start because it generates a new session token. The problem is that maybe Parse isn't able to update the session token in the database before the next data request is made.

Thanks for the help! :)
