### ISSUE TITLE
Cannot build Parse-SDK-iOS-OSX

### ISSUE THREAD

**Issue by PeaceKeeperOrg** [ParsePlatform/Parse-SDK-iOS-OSX#782]
MacBook Pro 17"/2011, core-i5, 8GB/256GB
Xcode-7.2

My Cartfile contains only:

---Cartfile---
github "ParsePlatform/Parse-SDK-iOS-OSX"
---

Note that I tried building without the --platform option first, but it failed with watchOS and something about BITCODE - so I tried narrowing the build to just iOS, which is all I'm interested in.

I initiate the build as such:
Bollo:Parse rowland$ carthage update --platform iOS

*** Fetching Parse-SDK-iOS-OSX
*** Fetching Bolts-iOS
*** Checking out Bolts-iOS at "1.6.0"
*** Downloading Parse-SDK-iOS-OSX.framework binary at "1.12.0"
*** Checking out Parse-SDK-iOS-OSX at "1.12.0"
*** xcodebuild output can be found in /var/folders/mq/0f_f80lx14143cb2b6cnyqg40000gn/T/carthage-xcodebuild.W9nsxe.log
*** Building scheme "Bolts-iOS" in Bolts.xcodeproj
A shell task failed with exit code 1:
error: cannot parse the debug map for "/Users/rowland/Development/iOS/Parse/Carthage/Checkouts/Bolts-iOS/Carthage/Build/iOS/Bolts.framework/Bolts": The file was not recognized as a valid object file

I've included a zip of the build log in case it will help.
Thanks,
Rowland

**Comment by nlutsenko** [comment]
Hey @PeaceKeeperOrg, that looks very strange.
Any chance yo pare using an old version of Carthage?

We are testing carthage builds with the latest version as part of CI on every commit/pull request.
