### ISSUE TITLE
iOS data not being sent or received

### ISSUE THREAD

**Issue by bryanchoi** [ParsePlatform/Parse-SDK-iOS-OSX#783]
The Parse team asked me to log this bug under the iOS SDK. I found an issue where custom data is not sent or received using the Parse push notifications. The code I'm sending from one iOS device to another iOS or android device results only in a result where the Alert message can be viewed. No data is passed along. Please fix this SDK bug asap. Thanks.

NSDictionary *data = @{

                           @"email" : @"john.doe@acme.com"

                           };

    PFPush *push = [[PFPush alloc] init];
    PFQuery *pushQuery = [PFInstallation query];
    [pushQuery whereKey:@"device_id" equalTo:@"1234567890"];
[push setQuery:pushQuery]; // Set our Installation query
            [push setData:data];
            [push setMessage:[NSString stringWithFormat:@"John Doe requests to connect with you."]];
            [push sendPushInBackground];

**Comment by nlutsenko** [comment]
Hey @bryanchoi, are you referencing `setData:` portion of the code above?
If yes - then it looks like it works according to the documentation on the method: `@warning This will overwrite any data specified in setData.`.

I recommend rewriting your code into something like this, this should send both alert and email and is close to what you would send via REST API or Parse Dashboard.
```objc
NSDictionary *data = @{
                       @"alert" : [NSString stringWithFormat:@"John Doe requests to connect with you."],
                       @"email" : @"john.doe@acme.com"
};

PFPush *push = [[PFPush alloc] init];
PFQuery *pushQuery = [PFInstallation query];
[pushQuery whereKey:@"device_id" equalTo:@"1234567890"];
[push setQuery:pushQuery]; // Set our Installation query
[push setData:data];
[push sendPushInBackground];
```

Let me know if it helps, or feel free to reopen this issue if there is anything I might have missed.

**Comment by bryanchoi** [comment]
Nikita, thank you very much for that clarification. This helped resolve
this issue and now I'm able to see the custom data including the alert
message. Much appreciated!

**Comment by bryanchoi** [comment]
Hi Nikita,

I'm seeing issues where some push notifications in my beta test build which
test users are using are not being sent. All the devices I own and in my
testing work fine, but then sporadically pushes are not getting
sent/received on test users' devices. When I click into it, it says, APNS -
invalid token. The curious thing is if the other user running the beta test
build has the app open it handles the notification. It's only when the app
is minimized, he sometimes gets the message or not. Please advise as
getting this running consistently is critical to the functionality of my
app.

Bryan

[image: Inline image 1]
