### ISSUE TITLE
Can't schedule a push - Parse Dashboard

### ISSUE THREAD

**Issue by barfoon** [ParsePlatform/Parse-SDK-iOS-OSX#788]
Currently trying to send a push notification on an established Parse setup (been working for months up until now).

When configuring a push in the new dashboard, we get a 'Save Failed', please select devices, despite 'Everyone' selected as the audience:

![image](https://cloud.githubusercontent.com/assets/1120510/12559983/1fda50ae-c366-11e5-9c62-d61a6c7edeee.png)

![image](https://cloud.githubusercontent.com/assets/1120510/12559993/2be729b2-c366-11e5-8b09-70de84ad162a.png)

![image](https://cloud.githubusercontent.com/assets/1120510/12560044/710badf6-c366-11e5-90ca-e1feaade09a6.png)

In the old dashboard, under our production account, we do not see any devices (despite their being 340k in the new dashboard), and cannot schedule a push.

![image](https://cloud.githubusercontent.com/assets/1120510/12560079/b1b68be6-c366-11e5-9db6-79de6faef999.png)

My apologies if this is not the right channel, it's been very challenging trying to find a support email address and all other avenues point to here. Also, the contact us form on the website gives a 500:

![image](https://cloud.githubusercontent.com/assets/1120510/12560109/e005c3d6-c366-11e5-819d-7cf9924983cf.png)

**Comment by hramos** [comment]
Closing as this has already been submitted through the official bug reporting channel for Dashboard issues (see https://developers.facebook.com/bugs/551553698343157/).
