### ISSUE TITLE
Wondering how fetchIfNeeded was used

### ISSUE THREAD

**Issue by AndrewSB** [ParsePlatform/Parse-SDK-iOS-OSX#789]
On my `PFUser`s I have a `facebookID` that I want to switch on in my `AppDelegate`. Was wondering if the `facebookID` was guaranteed to be fetched and on the user or if I should call fetchIfNeeded?

How does that work? How does the PFUser decide which fields to fetch prior to a fetchIfNeeded call?

**Comment by nlutsenko** [comment]
Hey @AndrewSB, that's a great question!

It depends on how the `PFUser` was fetched from the server:

- On `query`/`login`/`signup`/`become`/`loginWithAuthData` - you get the entire user object from `Parse`. And that data also would any info you mutated in before/after save hooks.

- If the user is fetched a non-expanded pointer from another object (no `includeKey:` used when performing a query for other class) - it will be marked as non-fetched.
Any call to `objectForKey:`/`objectForKeyedSubscript:` on these objects will throw an exception, indicating that you should call `fetchIfNeeded`. 

Side note: You can check whether the object was fetched fully by getting the value of `dataAvailable` property on any instance of `PFObject`. This properly also correlates with whether `fetchIfNeeded` is a no-op or it actually performs network request.

Let me know whether this helps at all or you have more questions on this.

**Comment by AndrewSB** [comment]
@nlutsenko that makes sense, let me present my use case so you can give me some directed advice.

My users have a `signedUp` field, a boolean indicating whether or not they've been approved + finished on boarding.
It's possible that the `signedUp` flag has been changed on the backend using cloud code (or in some way that the client has no idea it's changed).

In my `AppDelegate`, I switch on the `signedUp` flag, changing the `initialViewController` based on whether it's true or false.
The issue I'm facing is `fetchIfNeeded:` doesn't seem to know whether or not the `signedUp` property has been changed on the server, I need to instead do a `fetch:` before I can set the `initialViewController`, which means the app won't be able to be used without internet?

Any more reliable way to find out if the `signedUp` property has changed? Or should I make some educated guesses and then reload the `currentUser` after I've presented my educated-guess-view, then double checking to make sure my educated guess is correct?

Let me know if anything doesn't make sense @nlutsenko, I think I rambled on a bit

**Comment by nlutsenko** [comment]
I would recommend optimistically presenting them with the context that you think is the most appropriate.
Since the process likely to be once per use - you can present them with a loading screen, and say something like "Fetching your approval status...".

I wouldn't recommend relying on the fact that the user is fetched or not when you are about to start the app in either case.
