### ISSUE TITLE
Twitter login crashes my app

### ISSUE THREAD

**Issue by orkhanalizade** [ParsePlatform/Parse-SDK-iOS-OSX#792]
I'm trying the standard code from your website and get the next crash:

    Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

I read carefully previous issues and still cannot solve it. I checked twice my consumer key and secret in my AppDelegate.

Can you help me to solve this crash, please?

**Comment by ashish-naik** [comment]
Hi @orkhanalizade 

Does this happen when you cancel twitter login? if yes then did you find solution?
