### ISSUE TITLE
How to get the PFUser.currentUser() on watchOS 2 

### ISSUE THREAD

**Issue by chavez-md** [ParsePlatform/Parse-SDK-iOS-OSX#793]
There seems to be old documentation that discusses how PFUser is shared across the phone and watch which can be seen here using local data sharing for extensions:
http://blog.parse.com/announcements/introducing-local-data-sharing-for-apple-watch-and-app-extensions/

But, since support has now been updated for watchOS 2 SDK there is no information on how to access the logged in currentUser() from the base app on the watch. 

How can the PFUser.currentUser() on the watch become the one that is logged in on the base app?

Thanks

**Comment by nlutsenko** [comment]
Hey @chavez-md, you are absolutely correct - that approach isn't going to work for watchOS 2.
The general suggestion to use the same user on watch and phone - pass the restricted session token from the phone to the watch via WatchConnectivity.framework.

I have a rough sample app that can do this, but it needs to be cleaned up before it is public.
Would that be something very valuable for you? 
Or something like https://github.com/NatashaTheRobot/WatchConnectivityApplicationContextDemo would work better?

**Comment by chavez-md** [comment]
Hello @nlutsenko,

Access to your sample app would definitely be very valuable to me, and the users who have commented on issue #760. Please let me know when it will be published.

Also thanks for the example on the WatchConnectivity.framework.

Thanks
