### ISSUE TITLE
Parse Retirement

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/Parse-SDK-iOS-OSX#795]
Will this SDK continue to perfectly work to connect to the Parse Server after the Parse Platform is retired? I have spent years creating apps with Parse so naturally this announcement comes as a huge shock/blow to me, but I'm hoping the transition will be as smooth as possible. 

Thank you for the ongoing support of the Parse team, as I know they are doing everything they can to help out developers.

**Comment by nlutsenko** [comment]
Yes, absolutely!
The current version of the SDK is perfectly fit to work with the opensource version of Parse Server. 
In addition to this, I am, personally, as well everyone here at Parse is committed to continue maintaining and updating all of the open source repositories we have.
