### ISSUE TITLE
Good job, team.

### ISSUE THREAD

**Issue by FreudGit** [ParsePlatform/Parse-SDK-iOS-OSX#796]
re: http://blog.parse.com/announcements/moving-on/

Still an issues.

We will lose something very soon.  We will lost a very good product, going stronger and stronger.
We will lost a super new way to communicate and innovate (open source).

We will lose a great team, motivated and clearly proud of their products.

I'm surprised by the Facebook approach.  This cie say that they want to be more involved with the developer, but they will close probably billions of dev accounts.  Sad.

@nlutsenko and all Parse team, be proud of you, we are.

**Comment by nlutsenko** [comment]
Thank you @FreudGit, for the kind words.
All of our open source repos are going to stay around, and I am personally committed to supporting this for quite a while.
