### ISSUE TITLE
Parse database migration issue, now can't do anything 

### ISSUE THREAD

**Issue by hafizapp** [ParsePlatform/Parse-SDK-iOS-OSX#798]
<img width="1127" alt="screen shot 2016-01-30 at 2 07 33 am" src="https://cloud.githubusercontent.com/assets/1691606/12686845/5913a7f6-c6f6-11e5-9c55-9bcbab998aee.png">

Today morning I am trying to migrate my database to mongoDB, and it goes to second step. And instead of clicking "Finalize" I clicked on "Stop"

now dashboard of this App doesn't allow me to do re-initiate the migration process. Can any one please help regarding this matter.

@daaku @tmc @kashif @jamesyu @Palleas

**Comment by nlutsenko** [comment]
Hey @hafizapp, sorry it took a while to get back to you on this.
I hope you managed to solve the issue.
Though, if not - please report this on https://parse.com/help, since we are using this repo only for tracking iOS SDK issues.
