### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by MarvinNazari** [ParsePlatform/Parse-SDK-iOS-OSX#8]
Would be awesome to have Carthage support.

**Comment by nlutsenko** [comment]
Hey @MarvinNazari,
Thanks! Definetly, would be great, we'll get there shortly.

**Comment by KyleLeneau** [comment]
:100:  :+1:

**Comment by KyleLeneau** [comment]
So I just tried this and it seems to be working... What else is needed to be done?

**Comment by dgrekov** [comment]
works for me as well

**Comment by bojanstef** [comment]
I wrote this in my Cartfile and it didn't work...
```
github "ParsePlatform/Parse-SDK-iOS-OSX" ~> 1.8.1 # FB Parse compatible with version 1.8.1
```
The error message was: https://gist.github.com/bojanstef/2544b0f7b5273121ca42

Any suggestions?

**Comment by kyledecot** [comment]
Doesn't work for me. I'm getting the following when doing a `carthage update`

```
*** Building scheme "Parse-OSX" in Parse.xcworkspace
** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution BoltsSDK-OSX
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution BoltsSDK-OSX
(1 failure)
```

**Comment by schwa** [comment]
:+1:

Looks like Bolts framework is a _fake static_ framework.

Carthage only works with dynamic frameworks.

**Comment by dgrekov** [comment]
While the main branch is not yet fully compatible with Carthage or iOS9 Bitcode, you can use my branch for Carthage

github "dgrekov/Parse-SDK-iOS-OSX"

**Comment by nlutsenko** [comment]
That's great! Would love to see a PR for this!
master branch is fully compatible with bitcode, though.

**Comment by dgrekov** [comment]
Yes, the changes that I have made center mainly around project configuration and making a bitcode compatible Bolts build. Let me look to see how I can make it a clean pull request and make it happen.

For reference, bolts is at: github "dgrekov/Bolts-iOS"

**Comment by exalted** [comment]
@dgrekov I added following lines in `Cartfile`:

```ruby
github "dgrekov/Bolts-iOS" "358dd4ee49b9befb76c3005327ea417c4197bfa8"
github "dgrekov/Parse-SDK-iOS-OSX" "b532ee86b83bf865ad9386aead3e4aeba06e3ee0”
```

… and still get:

```
*** Building scheme "Parse-OSX" in Parse.xcworkspace
** BUILD FAILED **


The following build commands failed:
	ExternalBuildToolExecution BoltsSDK-OSX
(1 failure)
```

How am I supposed to try this instead?

Thanks.

**Comment by danstepanov** [comment]
@dgrekov @nlutsenko where did things land with this pull request https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/281

I'm trying to get my cartfile to work with
```
github "ParsePlatform/Parse-SDK-iOS-OSX" == 1.8.3
```
Dimitry's fork only goes up to 1.8.1.7. Does this mean that there is currently no Swift 2.0, Xcode 7, Carthage compatible version of the Parse iOS SDK?

**Comment by nlutsenko** [comment]
@danstepanov There is no Carthage compatible version for iOS indeed.
There is some work being done in #600 by @flovilmart to make this happen though.

**Comment by nlutsenko** [comment]
Though we are fully compatible with Swift 2.0/2.1, Xcode 7 and friends...

**Comment by dgrekov** [comment]
Currently, there is no way to build the framework using Carthage. I am exploring the use of the framework zip file and will update the thread as I know more.

**Comment by flovilmart** [comment]
I'm working on it as we speak, with a clean rake build script that would build both Bolts and Parse as dylibs and compatible with Carthage

**Comment by lolagin** [comment]
So at present, if I want to use the parse framework in a project actively using carthage, do I just need to manually import it? Can carthage work with cocoapods and those xcworkspaces?

**Comment by istx25** [comment]
Any updates on Carthage support?

**Comment by flovilmart** [comment]
You Can get it from here, https://github.com/flovilmart/ParseKit the supported versions are detailed in the readme. PR are welcome for updating to the latest versions of submodules.

This repo essentially builds all the dependencies, including FBSDK, as proper modules through custom configurations at build time.

**Comment by nlutsenko** [comment]
Official update: it's coming very soon, targeting next or one after release (before end of year or in first week of new year).
Since I want to rollout the compatibility for every platform (iOS/OSX/watchOS/tvOS), there are some changes required in Bolts.framework to make it happen (pending review right now).

**Comment by brennanMKE** [comment]
I've added support to use the new dynamic build targets in Bolts but I am currently stuck on a build error which I cannot explain yet. My forked branch can be found below. I'd like to know what needs to be done to make it work.

I have a local copy of the script updated in the PR for Bolts which should be building the Mach-O dynamic framework but maybe something else is happening elsewhere that I do not know about.

PR
https://github.com/BoltsFramework/Bolts-iOS/pull/210

Forked Branch
https://github.com/brennanMKE/Parse-SDK-iOS-OSX/tree/carthage-ios-support

cc @nlutsenko

**Comment by fbartho** [comment]
@nlutsenko: So this was closed because #717 added Dynamic Framework Support. But -- how do I use Carthage to install Parse?

**Comment by nlutsenko** [comment]
Add the following to your Cartfile:
`github "ParsePlatform/Parse-SDK-iOS-OSX" "master"`

P.S. I would recommend waiting until the release of `1.12.0`, since both the PR and this issue is attributed with such.

**Comment by fbartho** [comment]
Thanks @nlutsenko. I'm actually just starting a brand new project -- first from scratch-scratch in a while. I didn't want to use Cocoa Pods, but am totally new to looking at Carthage.

My timeline is such that I'm certain 1.12.0 will be released way before my project is. :)

**Comment by exalted** [comment]
I think some basic setup instructions in README would be nice to have for Carthage at this point. 

What do you think?

**Comment by istx25** [comment]
^ :+1:

**Comment by nlutsenko** [comment]
Agreed, will update the README with release of 1.12.0, since we didn't release the new version yet.

**Comment by AndrewSB** [comment]
@nlutsenko @flovilmart: I'm transitioning over from @flovilmart branch to this master repo, any idea on how to integrate everything else @flovilmart was offering?

- FBSDKCoreKit.framework : 4.8.0
- FBSDKLoginKit.framework : 4.8.0
- FBSDKShareKit.framework : 4.8.0
- ParseFacebookUtilsV4.framework : 1.9.0
- ParseTwitterUtils.framework : 1.9.1

Any ideas? Hoping that over time ParsePlatform will modularize all of the repos (relevant https://github.com/ParsePlatform/ParseFacebookUtils-iOS/issues/21 & https://github.com/ParsePlatform/ParseTwitterUtils-iOS/issues/18), and then maybe, a while later, the FBSDK can come around too

**Comment by nlutsenko** [comment]
ParseTwitterUtils - on it.
ParseFacebookUtils - outside of rolling out your own support for this, unless FBSDK***Kit supports it, we can't quite make it work.

**Comment by flovilmart** [comment]
@AndrewSB you could still use the other kits without Parse, now that Parse is offering the Carthage support, I can remove it from the repo to only build the FB dependencies,  including ParseFacebookUtilsV4.framewok

**Comment by AndrewSB** [comment]
@nlutsenko awesome! what do you think are the odds that Facebook will decide to support Carthage? Slim to none? 

@flovilmart that would be awesome. Thank you for maintaining that :smile:

**Comment by nlutsenko** [comment]
@AndrewSB, as I work at FB :grin:, let me try to get it done, so there is a good chance it will happen, though I don't have a timeline for it.

**Comment by AndrewSB** [comment]
Wasn't sure how much pull you had there 😛
Unfamiliar with how close the parse team is with the rest of Facebook/Facebook mobile teams.

That would be super cool, keep us updated!

**Comment by danstepanov** [comment]
Thank you young based @nlutsenko

**Comment by Bogidon** [comment]
When I build Parse with Carthage I only get an OSX framework and no iOS one. Am I doing something wrong?

**Comment by nlutsenko** [comment]
@Bogidon, use the `master` branch since it's already merged or the next release, since there is still no tag that supports Carthage (the release is coming tomorrow).

**Comment by Bogidon** [comment]
@nlutsenko How can I tell Carthage to use the `master` branch? (does it not do this by default?)

**Comment by nlutsenko** [comment]
@Bogidon Nope, it should use the latest tag avaiable.
Add the following to your Cartfile to use master branch:
```
github "ParsePlatform/Parse-SDK-iOS-OSX" "master"
```

**Comment by Bogidon** [comment]
@nlutsenko sorry for the trouble but now I'm getting this error:
`Scheme Bolts-tvOS is not currently configured for the build action.`

I'm up-to-date with Carthage, Xcode and OS X.

**Comment by Bogidon** [comment]
I deleted my `Carthage` folder and ran `carthage update` again and now it works. Thanks for the help @nlutsenko, looking forward to the release tomorrow :smile:

**Comment by kirank-canwill** [comment]
I have update latest Parse version 1.12.0, but it freeze UI while using Live and Local query. can you please help me.

**Comment by istx25** [comment]
@kirank-canwill Unrelated to Carthage. Can you file another issue for this problem? We'll also need more details to provide any assistance.
