### ISSUE TITLE
when using local parse-server Cloud Calls have no session token

### ISSUE THREAD

**Issue by nncary** [ParsePlatform/Parse-SDK-iOS-OSX#804]
Guys,

When using the new constructor, and passing in a local server. All my cloud code calls, via PFCloud do not include the sessionToken, even though I see it being created in _Session, and PFUser.currentUser().sessionToken. 

Any ideas what I may be doing wrong? Everything else seems to be working as advertised.

**Comment by nncary** [comment]
actually its sending the token correctly, I guess my question is for the parse-server team then because the parse cloud code dosen't see the logged in user in the cloud code function

**Comment by nlutsenko** [comment]
@nncary Yup, that sounds about right. I also verified that we are sending the token correctly.
Could you open an issue on https://github.com/parseplatform/parse-server for this?
