### ISSUE TITLE
PFTwitterUtils not returning any values

### ISSUE THREAD

**Issue by mrsenorhill** [ParsePlatform/Parse-SDK-iOS-OSX#805]
This began since last evening at around 10pm eastern. 

We have twitter auth through PFTwitterUtils. Currently, users are unable to log-in/sign-up. 

The reason seems to be that the query is not returning any values when it hits Parse's endpoint. We've never had this problem before.

Here's the error we're getting: 

2016-02-02 11:14:31.371 Huckle Prod[69518:1346267] Error: Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}

**Comment by mrsenorhill** [comment]
![](https://files.slack.com/files-pri/T02AACVAW-F0L3J7DDM/pasted_image_at_2016_02_02_09_27_am.png)

**Comment by mrsenorhill** [comment]
Update: We're getting a 504 timeout on api.parse.com/1/users
![pasted_image_at_2016_02_02_09_27_am_720](https://cloud.githubusercontent.com/assets/2974149/12758093/804e806e-c9a0-11e5-8f1a-02fdb58dfc3d.png)

**Comment by ale0xB** [comment]
Same error here. Glad to know someone else is experiencing it. It was driving me crazy

**Comment by mrsenorhill** [comment]
@ale0xB Definitely seems to be on the APi side. Have you been able to make any headway?

**Comment by nlutsenko** [comment]
Hey guys, since this is a backend issue - could you please file a request at https://parse.com/help
We are using FB Bug Tool to track backend/api issues, where this repo is used purely for tracking client-side issues.
