### ISSUE TITLE
Swift v2.2: Awkward conversion of ObjC header to Swift ...

### ISSUE THREAD

**Issue by adonoho** [ParsePlatform/Parse-SDK-iOS-OSX#806]
From PFObject:

    + (instancetype)objectWithoutDataWithClassName:(NSString *)className objectId:(nullable NSString *)objectId;

Automatically converts to:
Swift v2.1:

    public convenience init(withoutDataWithClassName className: String, objectId: String?)

Swift v2.2:

    public convenience init(outDataWithClassName className: String, objectId: String?)

From PFSubclassing:

    + (instancetype)objectWithoutDataWithObjectId:(nullable NSString *)objectId;

Automatically converts to in both versions but is different than what the PFObject conversion with similar naming:

    optional public static func objectWithoutDataWithObjectId(objectId: String?) -> Self

The different conversions are probably not what was intended. 

Anon,
Andrew

**Comment by nlutsenko** [comment]
Yeah, this is not intentional. Thanks for reporting. We can definitely make it better.

**Comment by adonoho** [comment]
It's nice to see you're still around after the Parse shutdown announcement. I hope Facebook is helping Parse folks have a future in the company.

**Comment by nlutsenko** [comment]
Hey @adonoho, looks like problem is Swift 2.2+, but the PR attached here shoudl help.
Please note that ObjC->Swift conversion doesn't quite support protocol initializers, which probably makes a lot of sense, so we are literally just fixing the naming convention on the method where it broke.

**Comment by adonoho** [comment]
That is a fine solution. Thank you for updating the headers.
