### ISSUE TITLE
PFTwitterUtils.logInWithBlock returns incorrect data format error

### ISSUE THREAD

**Issue by blwinters** [ParsePlatform/Parse-SDK-iOS-OSX#807]
I have the following code, which matches the Parse docs, and today this started failing for all users:

        PFTwitterUtils.logInWithBlock { (user: PFUser?, error: NSError?) -> Void in
            self.actInd.stopAnimating()
            
            print(error?.localizedDescription)
            print(error?.code)

            if let user = user as? User { //User is my subclass of PFUser
                
                if user.isNew {
                    print("User signed up and logged in with Twitter")
                                        
                } else {
                    print("Existing user logged in with Twitter")
                    
                }
                
                self.dismissViewControllerAnimated(true, completion: nil)
                
            } else {
                print("Uh oh. The user cancelled the Twitter login.")
            }
        }

The request runs for about 60 seconds before returning a nil user and the following error: "The data couldn’t be read because it isn’t in the correct format." The error code is 3840, which relates to an error parsing JSON data.

This code was previously working for a couple months until today. I don't see any status changes in my Parse account. Any idea what could be causing this?

**Comment by ativslife** [comment]
I'm confused as to why this isn't being addressed **urgently**. Almost every dev working on Parse is experiencing this...

This issue was previously brought up and not addressed: https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/805

Is there no other way to contact you? If there is, please let us know because many of us have put in a request hoping for an update. Please advise.

**Comment by cragworks** [comment]
My client is having this issue with twitter login too.

**Comment by nlutsenko** [comment]
I already raised this with our backend team and we are working on it.
If you have extra details - please file an issue on https://parse.com/help, also doing that will guarantee that you'll get status updates as soon as they are available.

**Comment by ativslife** [comment]
Thank you - much appreciated. Wish parse didn't have to go :(

**Comment by nlutsenko** [comment]
Going to close this one out, as this is backend as well as #805.

**Comment by MuhammadArqamOwais** [comment]
Has this issue been fixed? I am still getting this error

`Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}`

```
    [PFTwitterUtils logInWithBlock:^(PFUser *user, NSError *error) {
        if ( !user ) {
            NSLog(@"Uh oh. The user cancelled the Twitter login.");
            return;
        } else {
            NSString *twitterUsername = [PFTwitterUtils twitter].screenName;
            if (user.isNew) {
                NSLog(@"User signed up and logged in with Twitter");
            } else {
                NSLog(@"User logged in with Twitter!");
            }
        }
    }];
```

**Comment by MuhammadArqamOwais** [comment]
Also what is the alternative for **screenName** in the line
`[PFTwitterUtils twitter].screenName;`

**Comment by riksof-abdulrauf** [comment]
Any update on @MuhammadArqamOwais  question ?

**Comment by flovilmart** [comment]
Can you provide the server logs when running with VERBOSE=1?

**Comment by riksof-abdulrauf** [comment]
@flovilmart Where can I found it ?

is it meaning full for you
![screen shot 2017-02-27 at 6 26 04 pm](https://cloud.githubusercontent.com/assets/5626513/23363012/4aed7a02-fd1a-11e6-9119-23a3e0edc3c5.png)

**Comment by flovilmart** [comment]
I meant the parse-server logs

**Comment by riksof-abdulrauf** [comment]
nothing else found in logs
receiving error
Error Domain=NSCocoaErrorDomain Code=3840

**Comment by flovilmart** [comment]
there should be at least a call to /users/login otherwise that may mean pour parse-server URL is improperly configured.

Can you double check the network calls that are made with: https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool

**Comment by riksof-abdulrauf** [comment]
simple login and login with Facebook via parse working fine
PFFacebookUtils
[PFUser logInWithUsername:
Ok let me check this tool

**Comment by riksof-abdulrauf** [comment]
@flovilmart please check logs
![screen shot 2017-02-27 at 8 05 31 pm](https://cloud.githubusercontent.com/assets/5626513/23366564/fa836464-fd28-11e6-968d-2f89c60d5790.png)

**Comment by flovilmart** [comment]
And the server logs? do you have access to them?

**Comment by riksof-abdulrauf** [comment]
haven't access of server logs

**Comment by flovilmart** [comment]
That would be required to debug that issue, otherwise you should  report that to buddy.com

**Comment by henrydeclety** [comment]
I am getting 'Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." ' when trying to login with PFFacebookUtils.logInInBackground, where/how can I get the server logs?
Thanks
Henry
