### ISSUE TITLE
Push notifications from my iOS app sporadically not getting sent. None get received

### ISSUE THREAD

**Issue by bryanchoi** [ParsePlatform/Parse-SDK-iOS-OSX#809]
Hi,

I have tested push notifications from an development iPhone to another iPhone and they work fine. When I submit my app to beta test via TestFlight, I get sporadic failure of pushes. When I check the dashboard, I get an invalid token message: the user might have uninstalled the app when in fact i know the user hasn't done so. Please help me troubleshoot this as my app depends on users receiving and responded to parse pushes. Thanks 

<img width="570" alt="screen shot 2016-02-03 at 6 37 27 pm" src="https://cloud.githubusercontent.com/assets/7385138/12800742/65b89770-caa5-11e5-92cb-24ba3554cd7a.png">

**Comment by nlutsenko** [comment]
That sounds pretty strange and definitely not expected.
I believe this is purely the server-side issue, and since we are using this repo for tracking client-side issues - any chance you can report this at https://parse.com/help, since we are using FB Bug Tool to track server-side/push-related issues.

**Comment by bryanchoi** [comment]
I didn't see where to file the bug in  https://www.parse.com/help. In any
case, I'll provide all the info possible.

Here is one push that it states is not sent. My app name is called
GrabCoffee. The odd thing is there are instances in the dashboard where it
says 2 pushes are sent, but the majority of pushes are stating not being
sent in the testflight beta build. Let me know if I can provide more info.
Thanks.

PUSH ID

eEfyTTHjJv
TARGETING

device_id is "6463373383"
SENDING TIME

February 2nd, 2016 at 9:52 PM
EXPIRATION

None
FULL TARGET

{
  "device_id": "6463373383"
}

FULL DATA

{
  "alert": "Bryan Choi requests to connect with you.",
  "email": "bryanchoi@gmail.com",
  "name": "Bryan Choi"
}

**Comment by bryanchoi** [comment]
One more detail is in my app, I have client push enabled and all the pushes
are being sent from the ios device using the ios sdk code. It works totally
fine on all my test devices (I have 2 ios test devices and 1 android). It's
just when I deploy the test build, the majority of notifications are not
being received or sent according to the dashboard.

**Comment by bryanchoi** [comment]
Has there been any progress on the info I sent earlier? Anything I can try
out?
