### ISSUE TITLE
How do I reset authData?

### ISSUE THREAD

**Issue by fatuhoku** [ParsePlatform/Parse-SDK-iOS-OSX#814]
A user no longer uses their Facebook account but would still like to access our app through e-mail login.
Simple, I thought. I just set a username and password for that user account. Sure enough, they can log in.

However, when they do log in, they're presented with an ugly alert, saying that they should re-login to connect with Facebook again. Clearly this is dumb because they don't want to use Facebook to log in again.

So, I tried to

 - delete their `authData` from Parse Dashboard. Didn't work.
 - wrote a NodeJS script to `unlink` the user with `FacebookUtils`. Didn't work, because `parse/node` doesn't recognize the Node version of the Facebook JS SDK. It assumes that unlink has to be done from the browser
 - wrote a small iOS function that `unlinks` the user and run it once

Here's the code I wrote for the latter approach:

```objc
    [[[[PFUser logOutInBackground] continueWithSuccessBlock:^id(BFTask *task) {
        return [PFUser logInWithUsernameInBackground:@"user@email.com" password:@"abc123"];
    }] continueWithSuccessBlock:^id(BFTask *task) { 
        return [PFFacebookUtils unlinkUserInBackground:[PFUser currentUser]];
    }] continueWithBlock:^id(BFTask *task) {
        if (task.error) {
            NSLog(@"ERROR: %@", [task.error localizedDescription]);
        } else {
            NSLog(@"result: %@", task.result);    // succeeds!
        }
        return nil;
    }];
```

I thought that would have worked. The `BFTask` reports completion, but `authData` is still present for that user. I've also tried the non-`BFTask` version of the the `unlinkUserInBackground:` function. Same result: the call succeeds but `authData` sticks around.

This is really frustrating. What's so hard about removing the value in this field?

Does unlinking do anything at all on Parse?!

**Comment by nlutsenko** [comment]
Hey @fatuhoku, thanks for the report.
This is strange and should definitely remove `facebook` from `authData` of that user.
Any chance you can confirm that it still persists in that user, by logging it?

I'll try to reproduce locally as well, but am curious on whether this reproduces for you, since there might be something else going on.

**Comment by fatuhoku** [comment]
@nlutsenko not sure what you mean. The field looks populated (i.e. the value persists) for that user, yes.

The only way that I found in the end of unlinking is probably the best way — using the REST API. The client API's aren't quite as close to the data I guess.

**Comment by nlutsenko** [comment]
Can you breakpoint and inspect the authData that is stored inside PFUser after unlink?
Does it still have `facebook` inside of it?

**Comment by fatuhoku** [comment]
@nlutsenko I haven't really set a breakpoint no; I've resolved my problem with the REST endpoint and am no longer interested in doing it through the iOS SDK. Closing.

**Comment by dorjeozer** [comment]
I'm facing exactly the issue as @fatuhoku did - PFFacebookUtils.unlinkUserInBackground(user) doesn't do anything for the authData field and I can't set it to null manually either.

The code works with a project that is hosted in parse.com and SDK v1.12.0, but on my own server which is running v2.2.15 and SDK v1.13.0 it absolutely does nothing.

**Comment by dorjeozer** [comment]
This is the only feedback I'm receiving:

> [Bolts] Warning: `BFTask` caught an exception in the continuation block. This behavior is discouraged and will be removed in a future release. Caught Exception: Key "authData" has no data.  Call fetchIfNeeded before getting its value.
