### ISSUE TITLE
Strange behaviour with [query includeKey] on array of pointers after migrating database, (OS X only)

### ISSUE THREAD

**Issue by shaynos** [ParsePlatform/Parse-SDK-iOS-OSX#816]
Hi there I have just migrated my parse database to digital ocean and I am getting some strange behaviour when querying the new database from my OSX project.

This is what my query looks like:

```
    PFQuery *query = [PFQuery queryWithClassName:@"XXX"];
    [query includeKey:@"employeesInvolved"];
    [query includeKey:@"faultsRectified"];
    [query includeKey:@"WorkSite"];
    [query orderByDescending:@"startDate"];
    [query findObjectsInBackgroundWithBlock:^(NSArray * _Nullable objects, NSError * _Nullable error) {
        for (int i = 0; i<objects.count; i++) {
            PFObject *obj = [objects objectAtIndex:i];
            NSLog(@"Employees = %@", [obj objectForKey:@"employeesInvolved"]);
        }
    }];

```

If I query the new database on digital ocean this is the log:

> Employees = (
>     "<PFUser: 0x6000000f0800, objectId: TMOw3G7qti, localId: (null)> {\n}",
>     "<PFUser: 0x6000000ec180, objectId: iZFZPzq1bU, localId: (null)> {\n}",
>     "<PFUser: 0x6000000ec080, objectId: 0fE4tsp7WM, localId: (null)> {\n}"

But if I query the old Parse database then the Employees array, returns the list of PFUsers including all of their fields.

This project also has an iOS application which queries and displays this exact same data, using the exact same query. When I query the new database from the iOS application the query works as intended.

Thanks, hope you can help.

**Comment by nlutsenko** [comment]
Hey @shaynos, any chance you have different setup in any place between iOS and OS X projects?
Looks like `employeesInvolved` are actually parsed as empty JSON objects, meaning that for some reason the server doesn't send back the proper data...

Any repro case here would help tremendously, or say whether the same issue reproduces if you do a REST API request against your server.
