### ISSUE TITLE
PFOfflineStore _getPointerAsyncWithUUID:database

### ISSUE THREAD

**Issue by ahmad-ishfaq** [ParsePlatform/Parse-SDK-iOS-OSX#819]
Sometimes the sdk throughs an exception with this in logs.

**Comment by ahmad-ishfaq** [comment]
Backtrace of logs:
Thread : Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x24f862eb __exceptionPreprocess
1  libobjc.A.dylib                0x24752dff objc_exception_throw
2  CoreFoundation                 0x24f86231 -[NSException initWithCoder:]
3  Parse                          0x16da55d __52-[PFOfflineStore _getPointerAsyncWithUUID:database:]_block_invoke (PFOfflineStore.m:912)
4  Parse                          0x16fa62f __65-[PFSQLiteDatabase executeQueryAsync:withArgumentsInArray:block:]_block_invoke_2 (PFSQLiteDatabase.m:233)
5  Bolts                          0x1025caf __62-[BFTask continueWithExecutor:successBlock:cancellationToken:]_block_invoke (BFTask.m:410)
6  Bolts                          0x1025679 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 (BFTask.m:336)
7  Bolts                          0x10238b1 -[BFExecutor execute:] (BFExecutor.m:129)
8  Bolts                          0x10255cb __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke (BFTask.m:328)
9  Bolts                          0x1025439 -[BFTask continueWithExecutor:block:cancellationToken:] (BFTask.m:379)
10 Bolts                          0x1025c21 -[BFTask continueWithExecutor:successBlock:cancellationToken:] (BFTask.m:406)
11 Bolts                          0x1025b55 -[BFTask continueWithExecutor:withSuccessBlock:] (BFTask.m:396)
12 Parse                          0x167cab9 -[BFTask(Private) continueImmediatelyWithSuccessBlock:] (BFTask+Private.m:45)
13 Parse                          0x16fa589 __65-[PFSQLiteDatabase executeQueryAsync:withArgumentsInArray:block:]_block_invoke (PFSQLiteDatabase.m:232)
14 Bolts                          0x1025679 __55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2 (BFTask.m:336)
15 libdispatch.dylib              0x24b2ce2f _dispatch_barrier_sync_f_slow
16 Parse                          0x16fd6f7 PFThreadsafetySafeDispatchSync (PFThreadsafety.m:31)
17 libdispatch.dylib              0x24b23dd7 _dispatch_call_block_and_release
18 libdispatch.dylib              0x24b2f7b9 _dispatch_root_queue_drain
19 libdispatch.dylib              0x24b2f193 _dispatch_worker_thread3
20 libsystem_pthread.dylib        0x24cbce0d _pthread_wqthread
21 libsystem_pthread.dylib        0x24cbc9fc start_wqthread

**Comment by nlutsenko** [comment]
Hey @ahmad-ishfaq, this exception basically means that you got into very inconsistent state with Local Datastore, so instead of continuing - we decide that it's better to crash here, since everything can go wrong from this point.

Any chance you have an idea on where this might be coming from or what triggers this behavior?
Would love to investigate more together.
