### ISSUE TITLE
PFFileMaxFileSize

### ISSUE THREAD

**Issue by sbauch** [ParsePlatform/Parse-SDK-iOS-OSX#820]
There was a PR on parse-server that was merged for raising the (server side) limit of PFFiles to 20mb.

https://github.com/ParsePlatform/parse-server/pull/54

Is there a reason on the iOS side that it should remain 10mb, outside of general network request performance concerns?

**Comment by nlutsenko** [comment]
Hey @sbauch, you are right - we should remove this limitation on the iOS client.
Marking it for the next version.

**Comment by sbauch** [comment]
@nlutsenko awesome, yeah, always one of my hangups with parse - space is so cheap, why such a low limit? Anyways, I'd have been happy to do this work, but looks like you went ahead and submitted a PR. I guess I wasn't sure whether it should be upped to 20MB to match the default on the server project, or removed entirely. I'm happy to see it gone entirely!!
