### ISSUE TITLE
Parse migration to heroku/aws regarding the images

### ISSUE THREAD

**Issue by kumargagan4** [ParsePlatform/Parse-SDK-iOS-OSX#821]
I have successfully migrated my parse db to aws but the urls of image files still like 'http://files.parsetfss.com/77447afb-f681-4b55-afad-6bceeb2e155a/tfss-79297c86-bd48-4d7f-87ab-c43e02d1a8f3-photo.png'

it means files are still on parse s3 cloud or something their own storage so what will happen to those files after parse shutdown.
what is the way to migrate the images to new database/storage on my own AWS. I am worried because I have apprx 14.5 k images on parse.

Please provide you valuable guidance on this.

**Comment by nlutsenko** [comment]
We have a plan best described [here](https://github.com/ParsePlatform/parse-server/wiki/Files-Migration)
I would start with a simplest solution for now: Open-source Parse Server will understand old non-migrated Parse Files and you can actually write a small script that will query all your data and re-upload the contents to your own storage.
Another important piece is that we are working on a set of tooling to help you migrate all existing files referenced by your application to your own backing store, so stay tuned for updates either on [https://github.com/ParsePlatform/parse-server](Parse Server repo) or [https://blog.parse.com](our blog).
