### ISSUE TITLE
Retrieving arrays from Local Datastore

### ISSUE THREAD

**Issue by hhanesand** [ParsePlatform/Parse-SDK-iOS-OSX#824]
I'm having issues retrieving an object that has an array of pointers to parse objects that has been saved to the LDS.

This object (and its children) has never been saved to the server, so it does not have an object id.

When trying to query for the object on app restart, all the objects exist, but their non-pointer attributes have been lost. I will post code in a bit, but does anyone have any tips?

**Comment by nlutsenko** [comment]
Hey @hhanesand, you might be running into one of the limitations of Local Datastore here, which is as follows
"all data in pointers to other objects that automatically get pinned when you pin the root object will be converted to shallow pointers, if you add a new object to the pin without querying for all of the data from that pin first". This limitation basically means that you need to fetch all of the data using `includeKey:` on your queries for any pointer that you have in objects that you pin before pinning a new object to the same pin.

Let me know if this helps.

**Comment by hhanesand** [comment]
Huh, ok thanks. The issue seems to have resolved itself anyways after I changed some things...
