### ISSUE TITLE
Web Admin after Migration 

### ISSUE THREAD

**Issue by JoseVigil** [ParsePlatform/Parse-SDK-iOS-OSX#825]
Hi guys,

Is the parse web admin tool available after running on another server and migrating?

I cannot hide to express my disappointment on the bad news parse is shutting down. However, moving on I reviewed the migration document and there is no information about the Web Admin. I understand the web admin is going to work as exact means correct?

What I did verified is that push notification is not supported and looking for an alternative like https://www.kumulos.com/2016/02/04/best-alternative-for-parse-push-notification/.

Please let me know if someone migrated already and what are the side effect of doing so. 

Thanks lot
Jose

**Comment by nlutsenko** [comment]
Hey, @JoseVigil, we are working on it and is currently being tracked here - https://github.com/ParsePlatform/parse-server/issues/3

**Comment by JoseVigil** [comment]
It would have been a pain to handle without web admin. 

Great news! Thanks for the answer.
