### ISSUE TITLE
[Parse Server] clientKey is optional if using Parse Server

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/Parse-SDK-iOS-OSX#826]
A client key does not need to be configured in order to deploy a Parse Server. The Parse iOS SDK does not currently support connecting to a clientKey-less Parse Server.

To resolve this, a new initialization method is required: 

`+ (void)setApplicationId:(NSString *)applicationId;`

We will also need to remove the assertion that checks for a client key when the SDK is initialized.

**Comment by nlutsenko** [comment]
Will do, but only through a new configuration API.

**Comment by hramos** [comment]
Looks like we can already do this via the Configuration API:

```objc
[Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
   ...
   
   configuration.applicationId = @"YOUR_APP_ID";
   configuration.server = @"http://localhost:1337/parse";
   
   ...
   
}]];
```

I think we only need to remove the assert?

**Comment by nlutsenko** [comment]
Yup, you are correct. Remove the validation on client-key and make all the code paths that require the client key to be safe - be able to accept `nil`.
