### ISSUE TITLE
Object points to same memory address even if created twice

### ISSUE THREAD

**Issue by akki7017** [ParsePlatform/Parse-SDK-iOS-OSX#829]
Let's say for example, i have an objectId = wMxPq6icAV. and i want to have 2 objects with the same id.

i have tried creating new object only with the ID and then NSLog it. seems that they all have the same memory address. They are referencing to the same memory address, so technically i have only 1 object to refer to. However i want to have 2 different objects with different memory allocations, is there any way to achieve this?

Please let me know if you need any more information on this issue.

Thanks and regards, 
Akshit Zaveri

**Comment by nlutsenko** [comment]
Hey @akki7017, yes there is!
With Local Datastore - we have an explicit guarantee that you are going to have only a single object in memory at any given point in time for a given className+objectId pair.
Meaning, if you disable Local Datastore - this is no longer guaranteed and every time you query an object - you actually get the different address back.
I hope this addresses your needs here.

**Comment by akki7017** [comment]
Many thanks for the prompt response.
But i need to use LocalDataStore. It's mandatory for the app. any workarounds without disabling LDS?

Thanks and regards,
Akshit Zaveri

**Comment by nlutsenko** [comment]
Not really, no. The whole Local Datastore designed in this way and wouldn't work otherwise.
I wish we had a workaround that easy to implement, but the only thing that comes to my mind is to either have same addresses or not to use Local Datastore.

Let's try from a different angle: How can I help you solve the original issue where you needed 2 distinct instances of the same object?

**Comment by akki7017** [comment]
I am showing the list of events, initially for a specific date only, User should be able to see the events for whole month too. Events can be repeating also. But, in the LDS i am storing only one instance of the event with the repeating information attached. 

Now, i am able to show repeating events in the list for whole month but when i try to change any details of the event, it changes for both of them.

this sounds complex, but to simplify consider the iOS calendar app. it's same as the calendar events.

I have a solution in mind that i need to create a wrapper class to show the list, havent finalised on it yet. Your inputs would be great. 

Thanks and regards,
Akshit Zaveri

**Comment by akki7017** [comment]
I have implemented the solution as i mentioned previously. 

My custom PFSubclassed object name is **Goal** so i subclassed NSObject **GoalWrapper** and moved custom properties to new class. **Goal** class now only represents properties inherited from Parse class. and i was able to achieve what i needed.

Thanks for the support @nlutsenko. Really appreciate it.

Best regards,
Akshit Zaveri

**Comment by nlutsenko** [comment]
Yup, that solution will work great. Glad I could help.
