### ISSUE TITLE
Comparison between pointer and [PFUser currentUser]

### ISSUE THREAD

**Issue by refre5h** [ParsePlatform/Parse-SDK-iOS-OSX#831]
This was originally reported in [parse-server/issues/521](https://github.com/ParsePlatform/parse-server/issues/521). Moved here as requested. 

`user`, a pointer, and `[PFUser currentUser]` are referring to the same user. With hosted parse, `[user isEqualTo:[PFUser currentUser]]` returns `true`, but with parse-server it returns `false`.

A workaround is `[user.objectId isEqualToString:[PFUser currentUser].objectId]`, but that requires a huge amount of changes in our client code as we did most comparisons like `[user isEqualTo:[PFUser currentUser]]`.

Also may be related: when the client is connected with hosted parse, `user`, the pointer, and `[PFUser currentUser]` seem to be regarded the same and data inside are always available. But when connected with parse-server, those two are different, so I can not get any data from the pointer object.

Is this a bug? If not, any advice please?

**Comment by refre5h** [comment]
@nlutsenko To answer your questions in [parse-server/issues/521](https://github.com/ParsePlatform/parse-server/issues/521):

We are not using Local Datastore, but if you can shed some light on comparing by identity, it'd be really helpful.

Also, as I mentioned, we used to be able to get user data from the `user` pointer in hosted parse, but not anymore when connected to parse-server. Any idea?

**Comment by nlutsenko** [comment]
> We are not using Local Datastore, but if you can shed some light on comparing by identity, it'd be really helpful.

With LDS enabled - you have a guarantee that the className+objectId will always resolve the same instance of an object in memory, so simply comparing identity here would work (pointer comparison).

I think the most important question now is `isEqualTo:` on a PFUser - what does the implementation of it look like?

> Also, as I mentioned, we used to be able to get user data from the user pointer in hosted parse, but not anymore when connected to parse-server. Any idea?

Can you expand here a little more on how you are fetching data for the user?

**Comment by hansimmmi** [comment]
I was also using `isEqualTo:` to compare PFUser. I believe `[PFUser currentUser]` is always available, so whenever I got objects which might has a pointer to  `[PFUser currentUser]` is used `isEqualTo:` to compare if the pointer is equal to  `[PFUser currentUser]`. Here, you can see, one is `[PFUser currentUser]` object and the other one is `[PFUser currentUser]` pointer. This comparison used to work 100%, but according to your explanation, I was just lucky, and now the comparison doesn't work any more. So should we change all comparison to string match of objectIds?

**Comment by nlutsenko** [comment]
I would very much recommend doing so, since the data in a pointer and object can be different, and it looks like what you are looking for is checking whether it's the same user, not necessarily the same data in that user. 

Feel free to reopen this issue if you run into any more troubles or if this solution doesn't quite work for you.
