### ISSUE TITLE
User Signup wrong API method call

### ISSUE THREAD

**Issue by adadgio** [ParsePlatform/Parse-SDK-iOS-OSX#836]
The SDK makes the following requests to the parse server on user signup

`/parse/users -x POST
`
it should be

`/parse/classes/_Users -x POST `

(im refering the REST documentation). Its not the only non-conventional method in the SDK mess buts its the most disrupting i think. FYI the Android SDK makes the correct request.

See also... https://github.com/ParsePlatform/Parse-SDK-Android/issues/408

**Comment by nlutsenko** [comment]
Actually, it's absolutely fine to do this.
Both methods work fine and are resolved to the same functionality. 

Turns out that going through /users is even the preferred one according to the official REST docs [here](https://parse.com/docs/rest/guide).

**Comment by adadgio** [comment]
True true true, so its the Android SDK that makes a query to _Users.. hm. Thats were the inconsistency is then. Tks !
