### ISSUE TITLE
Facebook Login Issue with Latest iOS SDK (1.12.0)

### ISSUE THREAD

**Issue by sprabs** [ParsePlatform/Parse-SDK-iOS-OSX#837]
I was previously running the 1.9.0 Parse SDK. When I updated to 1.12.0 and tested, I noticed that users who were already authenticated by Facebook or who tried to connect to Facebook through my app were crashing. We are using ParseFacebookUtils.

---
This is the error I am seeing: 

 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSProxy doesNotRecognizeSelector:openWithBehavior:fromViewController:completionHandler:] called!'
*** First throw call stack:
(0x187572530 0x1985480e4 0x187572470 0x188459abc 0x1875763ac 0x18747ac4c 0x1003fcc0c 0x1003fa624 0x1003fa7b4 0x1001fe584 0x1002ea9ac 0x1000dddf8 0x18c14cebc 0x18c14d4d0 0x18c07c2e0 0x18c07e86c 0x18bea2988 0x18bdb7d84 0x18bdb78ec 0x18bdb77f4 0x18b6d8d78 0x100b5cf94 0x100b61c28 0x18752a2ec 0x187528394 0x1874551f4 0x1908776fc 0x18bde610c 0x10011cd7c 0x198bc6a08)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by nlutsenko** [comment]
Hm, that sounds super strange, but looks like you are running an old version of FBSDK that doesn't have the required methods in? I would actually recommend using `ParseFacebookUtilsV4`, and migrating to FBSDKv4, as it looks like you are running an old version.

Any chance you can provide explicitly the version of both `ParseFacebookUtils` and `FBSDK` that you are using?
