### ISSUE TITLE
PFRelation not working I think

### ISSUE THREAD

**Issue by alexrmacleod** [ParsePlatform/Parse-SDK-iOS-OSX#838]
I just updated from 1.6.2 to 1.12.0 besides my collection views loosing performance, it looks like the relations aren't being created.  

error response:
2016-03-01 15:24:29.415 Fashun[3408:883978] [Error]: PFKeychainStore failed to get object for key 'currentUser', with error: -34018
2016-03-01 15:24:29.421 Fashun[3408:883978] [Error]: PFKeychainStore failed to set object for key 'currentUser', with error: -34018
like obejct saved for Optional("bubbles")

Code:
        let like = Like(photo: photo, user: user)

        like.saveInBackgroundWithBlock({ (success:Bool, error:NSError?) -> Void in
            if error == nil {
                let likeCreatedAtRelation = user.relationForKey("like_createdat")
                likeCreatedAtRelation.addObject(like)
                user.saveInBackgroundWithBlock({ (success:Bool, error:NSError?) -> Void in
                    self.photo.saveInBackgroundWithBlock({ (success:Bool, error:NSError?) -> Void in
                        self.transitionInProgress = false
                        print("like obejct saved for \(user.firstName)")
                    })
                })
            } else {
                print("error.userInfo: \(error!.userInfo)")
            }
        })

Any ideas?

**Comment by nlutsenko** [comment]
Hey @alexrmacleod, let's debug this together!
Few questions that would be help uncover the truth:
- Are you using Local Datastore?
- How does the fact that relations are not being created surface? Is it Local Datastore query or query caching or it doesn't show up on the dashboard?
- Since you are saving objects directly - this should convert into a network request, meaning that we can debug it together! Whee! Any chance you can instrument your app with client-side Network Debug Tool and paste the output of these network requests into this issue. The process is described on this repo wiki [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool).

Let me know how it goes, I am confident we'll uncover what is going on.

**Comment by alexrmacleod** [comment]
A response from @nlutsenko I feel blessed! After more digging I found #437 could be the same problem. 

I have a feeling that PFKeychainStore isn't working as it should, so when I try to use PFRelation to save a objects to a PFUser account it can't find the user I am trying to save to. but sometimes the error message: " [Error]: PFKeychainStore failed to set object for key 'currentUser', with error: -34018" doesn't even show up. but every time the object doesn't save. 

**Are you using Local Datastore?**
- no not using enableLocalDatastore
**How does the fact that relations are not being created surface? Is it Local Datastore query or query caching or it doesn't show up on the dashboard?**
- I press a like button on a viewcontroller which runs the "like.saveInBackgroundWithBlock", then when I move to the users profile viewcontroller to perform a relation query of all their likes, the like that should have been saved doesn't show up.  
**Since you are saving objects directly - this should convert into a network request, meaning that we can debug it together! Whee! Any chance you can instrument your app with client-side Network Debug Tool and paste the output of these network requests into this issue. The process is described on this repo wiki here.
**
- when a users presses a like button
`URL : https://api.parse.com/1/batch
Method : Optional("POST")
Headers : Optional(["X-Parse-Installation-Id": "d8521f2b-6adb-40bf-aed6-0d54b146d9e1", "X-Parse-Session-Token": "g36UP66cvvbKfk8cZ5ZMaOvHe", "Content-Type": "application/json; charset=utf-8"])
Request Body : Optional({"requests":[{"path":"\/1\/classes\/Photo\/GKJv3IYTWj","method":"PUT","body":{"app_likes_count":{"amount":1,"__op":"Increment"},"lovedBy":{"objects":[{"__type":"Pointer","className":"_User","objectId":"UffHHSeUzH"}],"__op":"AddRelation"}}}]})
URL : https://api.parse.com/1/batch
Status Code : 200
Headers : [Access-Control-Allow-Methods: *, Content-Type: application/json; charset=utf-8, Server: nginx/1.6.0, X-Parse-Platform: G1, Connection: keep-alive, Date: Tue, 01 Mar 2016 11:30:35 GMT, X-Runtime: 1.217524, Content-Length: 75, Access-Control-Allow-Origin: *]
Response Body : Optional([{"success":{"app_likes_count":2,"updatedAt":"2016-03-01T11:30:34.735Z"}}]
)
URL : https://api.parse.com/1/classes/Like
Method : Optional("POST")
Headers : Optional(["X-Parse-Installation-Id": "d8521f2b-6adb-40bf-aed6-0d54b146d9e1", "X-Parse-Session-Token": "g36UP66cvvbKfk8cZ5ZMaOvHe", "Content-Type": "application/json; charset=utf-8"])
Request Body : Optional({"photo":{"__type":"Pointer","className":"Photo","objectId":"GKJv3IYTWj"},"user":{"__type":"Pointer","className":"_User","objectId":"UffHHSeUzH"}})
URL : https://api.parse.com/1/classes/Like
Status Code : 201
Headers : [Server: nginx/1.6.0, Content-Type: application/json; charset=utf-8, Access-Control-Allow-Methods: *, Location: https://api.parse.com/1/classes/Like/MOJgcs6jq2, X-Parse-Platform: G1, Connection: keep-alive, Date: Tue, 01 Mar 2016 11:30:35 GMT, X-Runtime: 0.012480, Content-Length: 65, Access-Control-Allow-Origin: *]
Response Body : Optional({"createdAt":"2016-03-01T11:30:35.773Z","objectId":"MOJgcs6jq2"}
)
URL : https://api.parse.com/1/classes/_User/UffHHSeUzH
Method : Optional("PUT")
Headers : Optional(["X-Parse-Installation-Id": "d8521f2b-6adb-40bf-aed6-0d54b146d9e1", "X-Parse-Session-Token": "g36UP66cvvbKfk8cZ5ZMaOvHe", "Content-Type": "application/json; charset=utf-8"])
Request Body : Optional({"like_createdat":{"objects":[{"__type":"Pointer","className":"Like","objectId":"MOJgcs6jq2"}],"__op":"AddRelation"},"authData":{"facebook":{"id":"10152639114171574","access_token":"CAAUCSRZCIXqUBAGov4IXKTFv7L5UUSQZALgoxNdIirh66ZAR4wCctRXuN8JZAZBQU6Jk6Rx8dUoykeRDcqYMXJy9rZC0SMDOQSdHfXqBF1hZAUwTr3ZAwKKj0hQD8nJVOZB6ZC0yzdUsvqdRobOlJ38cEEZBMRcyjn9Rc3E0wHDmfy3hYNiJoL7X5Hc20e1b0FgYu2MIQPsfJb7rGTXG1fKRgDOtbv5lWRuZBiuBgDUFiOIfZBQZDZD","expiration_date":"2016-04-30T07:20:58.863Z"}}})
URL : https://api.parse.com/1/classes/_User/UffHHSeUzH
Status Code : 200
Headers : [Access-Control-Allow-Methods: *, Content-Type: application/json; charset=utf-8, Server: nginx/1.6.0, X-Parse-Platform: G1, Connection: keep-alive, Date: Tue, 01 Mar 2016 11:30:36 GMT, X-Runtime: 0.025931, Content-Length: 403, Access-Control-Allow-Origin: *]
Response Body : Optional({"authData":{"facebook":{"access_token":"CAAUCSRZCIXqUBAGov4IXKTFv7L5UUSQZALgoxNdIirh66ZAR4wCctRXuN8JZAZBQU6Jk6Rx8dUoykeRDcqYMXJy9rZC0SMDOQSdHfXqBF1hZAUwTr3ZAwKKj0hQD8nJVOZB6ZC0yzdUsvqdRobOlJ38cEEZBMRcyjn9Rc3E0wHDmfy3hYNiJoL7X5Hc20e1b0FgYu2MIQPsfJb7rGTXG1fKRgDOtbv5lWRuZBiuBgDUFiOIfZBQZDZD","expiration_date":"2016-04-30T07:20:58.863Z","id":"10152639114171574"}},"updatedAt":"2016-03-01T11:30:36.099Z"}
)
like obejct saved for Optional("peony")
`

I couldn't figure out how to convert this 
- NSLog(@"Status Code : %ld", (long)response.statusCode);
to swift: the (long) part I just did
-  print("Status Code : \(response!.statusCode)")

**Put this on the Network debug tool wiki page for all the swift coders:**

`    Parse.setLogLevel(PFLogLevel.Debug)
    NSNotificationCenter.defaultCenter().addObserver(self, selector: "receiveWillSendURLRequestNotification:", name: PFNetworkWillSendURLRequestNotification, object: nil)
    NSNotificationCenter.defaultCenter().addObserver(self, selector: "receiveDidReceiveURLResponseNotification:", name: PFNetworkDidReceiveURLResponseNotification, object: nil)
`

`    func receiveWillSendURLRequestNotification(notification:NSNotification) {
        let request = notification.userInfo![PFNetworkNotificationURLRequestUserInfoKey];
        print("URL : \(request!.URL!!.absoluteString)")
        print("Method : \(request!.HTTPMethod)")
        print("Headers : \(request!.allHTTPHeaderFields)")
        print("Request Body : \(NSString(data: request!.HTTPBody!!, encoding: NSUTF8StringEncoding))")
    }

    func receiveDidReceiveURLResponseNotification(notification:NSNotification) {
        let request = notification.userInfo![PFNetworkNotificationURLRequestUserInfoKey];
        let response = notification.userInfo![PFNetworkNotificationURLResponseUserInfoKey];
        let responseBody = notification.userInfo![PFNetworkNotificationURLResponseBodyUserInfoKey];
        print("URL : \(request!.URL!!.absoluteString)")
        print("Status Code : \(response!.statusCode)")
        print("Headers : \(response!.allHeaderFields)")
        print("Response Body : \(responseBody)")
    }
`

**Comment by nlutsenko** [comment]
Thanks for the Swift code snippet - will update.

The Request/Response actually looks absolutely correct as you can see there are `__op: AddRelation` in the body which add the objects to the relation of `like_createdat`.

Any chance you can log the request/response that you perform via relation query?
Since data is properly getting saved, I think there might be a problem in this space.

**Comment by alexrmacleod** [comment]
After some query investigation I realised the
`query.cachePolicy = PFCachePolicy.CacheElseNetwork`
should be:
`query.cachePolicy = PFCachePolicy.NetworkElseCache`
That was the reason why the newly saved relations weren't showing up on the users profile viewcontroller

So relations are working fine sorry for the confusion, thanks for the help, please check out this though #842

**Comment by nlutsenko** [comment]
Great!
Glad you found the solution!
