### ISSUE TITLE
Parse not sending Push Notification, After I revoked My APNS certificate and uploaded a new .p12 file 

### ISSUE THREAD

**Issue by GeetCD** [ParsePlatform/Parse-SDK-iOS-OSX#84]
I revoked my push notification certificate. i.e. APNS certificate and created a new .p12 file however, after uploading this to parse dashboard, and trying to send the new notification, they are not getting sent..It keeps showing pending in the dashboard. what could be the issue???

**Comment by nlutsenko** [comment]
Hey @GeetCD, this sounds like a backend issue.
We are continuing to use Facebook Bug Tool for those, could you file a bug on https://parse.com/help
