### ISSUE TITLE
whereKeyExists not working accurately for PFFile

### ISSUE THREAD

**Issue by cshah3** [ParsePlatform/Parse-SDK-iOS-OSX#840]
I am performing a query on the User class that checks to see if the user's picture, which is a PFFile, exists: `query.whereKeyExists("picture")`.

This is removing some users without pictures from the results but not all.

**Comment by nlutsenko** [comment]
Hey @cshah3, let's find the solution for this together...
Few questions:
- Are you using parse.com or self hosted Parse Server?
- Could your app with network debug tool from [this wiki page](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool) and paste the output here? (don't need the direct urls, but do need to see the network traffic)
- Was there something specific that changed or happened when this stopped working or it was like this from the start?

**Comment by cshah3** [comment]
- We are using parse.com.
- Here is the output from the network debug tool:

`[PFNetworkNotificationURLRequestUserInfoKey: <NSMutableURLRequest: 0x14fc2cd0> { URL: https://api.parse.com/1/classes/_User }]
[PFNetworkNotificationURLResponseUserInfoKey: <NSHTTPURLResponse: 0x1609a520> { URL: https://api.parse.com/1/classes/_User } { status code: 200, headers {
    "Access-Control-Allow-Methods" = "*";
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 20790;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 07 Mar 2016 03:35:30 GMT";
    Server = "nginx/1.6.0";
    "X-Parse-Platform" = G1;
    "X-Runtime" = "0.102742";
} }, PFNetworkNotificationURLRequestUserInfoKey: <NSMutableURLRequest: 0x14fc2cd0> { URL: https://api.parse.com/1/classes/_User }, PFNetworkNotificationURLResponseBodyUserInfoKey: {"results":[`
- We haven't changed anything for this query or the SDK version. I think it was working properly a few weeks ago - we just noticed this issue in the last week.

**Comment by nlutsenko** [comment]
Any chance you can expand the body of the request and the results that are sent back?

**Comment by cshah3** [comment]
`2016-03-07 16:39:13.700 Reach[68930:9515103] URL : https://api.parse.com/1/classes/_User
2016-03-07 16:39:13.700 Reach[68930:9515103] Method : POST
2016-03-07 16:39:13.701 Reach[68930:9515103] Headers : {
    "Content-Type" = "application/json; charset=utf-8";
    "X-Parse-Installation-Id" = "___";
    "X-Parse-Session-Token" = ___;
}
2016-03-07 16:39:13.701 Reach[68930:9515103] Request Body : {"limit":"25","where":{"picture":{"$exists":true},"location":{"$nearSphere":{"__type":"GeoPoint","longitude":-79.3911270660543,"latitude":43.64133881156735},"$maxDistance":3.924030764401193}},"_method":"GET"}
2016-03-07 16:39:13.980 Reach[68930:9515106] URL : https://api.parse.com/1/classes/_User
2016-03-07 16:39:13.983 Reach[68930:9515106] Status Code : 200
2016-03-07 16:39:13.984 Reach[68930:9515106] Headers : {
    "Access-Control-Allow-Methods" = "*";
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 27856;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Mon, 07 Mar 2016 21:39:06 GMT";
    Server = "nginx/1.6.0";
    "X-Parse-Platform" = G1;
    "X-Runtime" = "0.138685";
}
2016-03-07 16:39:13.985 Reach[68930:9515106] Response Body : {"results":[`

**Comment by nlutsenko** [comment]
@cshah3, the query and responses look absolutely fine, meaning that this is likely a backend issue...
Any chance you can try using cURL (hopefully the debugged request helps) to check if the issue reproduces outside of iOS SDK?

**Comment by cshah3** [comment]
The issue also exists on the Android SDK. The constraint works perfectly for all non-PFFile fields.

**Comment by nlutsenko** [comment]
This is actually very weird.
Any chance you are using both Parse server and parse.com at the same time for Files?
From what it feels like there is something specific about those files that limit them from being queryable and returned to you on the client.
Any chance you can query for all of them and look at the network debug tool (post here would be great) to see if there is something specific that distinguishes them?
