### ISSUE TITLE
Parse pod 1.12.0 not including latest source code?

### ISSUE THREAD

**Issue by thphuc** [ParsePlatform/Parse-SDK-iOS-OSX#841]
In recently update, the issue [#827](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/827) was fixed. But when I get final version of Parse (1.12.0) by using pod 'Parse', the old source code is still there.
I also checked [Parse on CocoaPods ](https://cocoapods.org/pods/Parse), the last release	date is Jan 2016. 
So my question is Parse pod 1.12.0 not including latest source code and the issue [#827](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/827) is still there?

**Comment by nlutsenko** [comment]
827 wasn't released yet and is coming in 1.13.0 according to the milestone on it.
Should be out this or early next week.

**Comment by thphuc** [comment]
Great! Thanks @nlutsenko
