### ISSUE TITLE
There are always unsaved changes of PFObject

### ISSUE THREAD

**Issue by kenkuan** [ParsePlatform/Parse-SDK-iOS-OSX#852]
My cloud code depend on `PFObject.dirtyKeys()` in before save hook. Recently I found `dirtyKeys()` always return values even when I saved unmodified object.
After digging, I found that the issue is that `[PFObject unsavedChanges]` always returned field I modified before. 

For example: I have an object 
```
{
   "name": "Ken",
    "age": 18,
    "gender": "M"
}
```

If I modified `name` and saved, then `dirtyKeys()` return `["name"]`
Then I modified `age` and saved, then `dirtyKeys()` return `["name", "age"]`

My saving code is like this:
```
object.pinInBackground().continueWithSucessBlock { task in
    return object.saveInBackground()
}
```

**Comment by nlutsenko** [comment]
Hey @kenkuan, this sounds very strange...
Are you checking for whether keys are dirty or not directly after calling these methods or after the completion of `saveInBackground()`.

Keep in mind that unless the object is fully saved to Parse.com, meaning that until the moment completion of `saveInBackground()` is called - the keys will remain dirty.

If you could expand your code snippet - that would help tremendously.

**Comment by kenkuan** [comment]
Hi @nlutsenko 
I checked dirty keys by `Parse.Object.dirtyKeys()` from cloud code, so I thought it's already be saved.
I tried to kill the app and restart it, the object still has dirty keys. 

Is it possible that dirty keys had been saved in pin?

**Comment by nlutsenko** [comment]
`dirtyKeys()` in a beforeSave or afterSave hook?

**Comment by nlutsenko** [comment]
All changes in that are made to the object are going to be observed in a `beforeSave` hook, since it is being called before actual save, meaning that you can actually change the actual values and override what the client wants to save.
If it's `afterSave` - then it's slightly more concerning.
Awaiting your reply to investigate more.

**Comment by kenkuan** [comment]
It's in a beforeSave hook.
After some digging, I found that iOS SDK will pin operation in local and keep it.
Originally I save my object by pinning it first like 
```
object.pinInBackground { (success, e) -> 
    if success {
        return object.saveEventually()
    }
    return nil
}

I remove the pin calling by just use `object.saveEventually()` and everything gonna fine.
