### ISSUE TITLE
Swift - importing Parse result in error in compilation : Parse/ParseClientConfiguration.h file not found

### ISSUE THREAD

**Issue by rosarionakkocom** [ParsePlatform/Parse-SDK-iOS-OSX#853]
I'm using Swift and pods  (Parse 1.12.0)
I
Import Parse
and I get the following errors on compilation

 1) Could not build Objective-C module 'Parse' because of
 2) result in error in compilation  Parse/ParseClientConfiguration.h file not found

The file is there for sure and can be accessed. 

 What I'm trying to do is simple this (which worked fine before doing a pod update... ) :

 Parse.initializeWithConfiguration(ParseClientConfiguration.init(block: { (ParseMutableClientConfiguration) -> Void in ... etc

Any idea that is missing from the build ?

**Comment by nlutsenko** [comment]
I would suggest clearing your Xcode DerivedData, that might have the old version of these headers.
Make sure you also quite and relaunch Xcode after it, also clearing the Trash might help.

**Comment by rosarionakkocom** [comment]
As suggested clearing the Xcode DerivedData fix the problem.

**Comment by sarbogast** [comment]
I have cleaned derived data, upgraded to the latest Parse pod (1.13.0), cleaned the product and restarted Xcode in all directions and I still have the same issue. And when I CMD+click the Parse/ParseClientConfiguration.h I can get to it. I'm using the latest version of XCode 7.3.1
Any other suggestion?

**Comment by rosarionakkocom** [comment]
HI Sebastian, so you still can't see that file after closing xcode, cleanderived data, upgrading the pod  ?

**Comment by sarbogast** [comment]
Indeed. The latest version of the pod is 1.13.0 right?

**Comment by rosarionakkocom** [comment]
Yeah, that’s what I’m using it.
 And did you try to build also with the error ? If so can I ask you to try this, just create a clean project and set only the parse pod add that to the delegate and build see if is something related to the project itself or something with Xcode.
