### ISSUE TITLE
PFQuery whereKey:nearGeoPoint returning incorrect results

### ISSUE THREAD

**Issue by tahoecoop** [ParsePlatform/Parse-SDK-iOS-OSX#855]
Hello, below is my query to find tag objects where a specific key exists `"T\(tagObjectIDs[0])"`. I am limiting the search to within 2 kilometers. When I include the geopoint constraint, parse returns all results, not just the one where that key exists. But if I remove the geopoint constraint, I only get results where the key exists. I'm a little perplexed, it seems like the geopoint query constraint is my issue, just not sure if it's something on my end. Thank you very much!

EDIT: I did check to make sure the user location is there, as well as the proper key where I'm plugging it into whereKeyExists.

```
 let userGeo:PFGeoPoint = PFGeoPoint(location: userCurrentLocation)

            let singleQuery = PFQuery(className: "tags")
            singleQuery.whereKeyExists("T\(tagObjectIDs[0])")
            singleQuery.whereKey("geoPoint", nearGeoPoint: userGeo, withinKilometers: 2)

            singleQuery.findObjectsInBackgroundWithBlock({ (objects, error) -> Void in

             ...
            })


```

**Comment by gateway** [comment]
@tahoecoop I seem to also be having this issue.  Any parse dev's know what the issue might be?

**Comment by nlutsenko** [comment]
Hey guys, sorry for a delayed reply, let me ask few questions so we can debug this together:
- Are you using parse.com or Open Source Parse Server?
- Is this attached to a specific application or doesn't work for all apps?
- Does the problem reproduce outside of iOS SDK, for example, via curl?

One thing that might help debugging this is to instrument your application with Network Debug Tool from [this guide](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool), so you are able to see requests/responses. Most importantly - I believe this would be an issue outside of the SDK and should be reported on the server repo, but let's debug this together here first.

**Comment by tahoecoop** [comment]
Thanks very much for the response. To answer your questions above:
-I'm currently using parse.com
-This is attached to one specific app
-Haven't seen results via curl, but I installed the network debug tool. This gives me the same results as in the app, i.e. returning extra results where the key doesn't exist.

What are the next steps to solve this issue? My partner already opened up a ticket on the parse server on this issue as well (https://github.com/ParsePlatform/parse-server/issues/1080). Thanks again for the assistance!

**Comment by nlutsenko** [comment]
Taking into account that you can see the same results in the network debug tool - this is clearly a backend issue. Since we are using this repo for tracking client-side issues only - could you file a bug report on http://parse.com/help in addition to what you already have on parse-server, since the issue is on parse.com.
Let me know if there is anything else I can help you with.

**Comment by gateway** [comment]
Done, hopefully someone can look at it, this seems like a genuine bug.
