### ISSUE TITLE
Cant upload VOIP Service Push Certificate 

### ISSUE THREAD

**Issue by simplysanthakumar** [ParsePlatform/Parse-SDK-iOS-OSX#856]
Got following error on uploading Apple Push Certificates in Settings > Push

_Unsupported certificate type. Common Name (CN) must contain one of: Apple Production IOS Push Services, Apple Push Services, Apple Development IOS Push Services, Pass Type ID, Apple Development Mac Push Services, Apple Production Mac Push Services._

**Comment by nlutsenko** [comment]
Hey @simplysanthakumar, unfortunately we don't support VOIP Push on parse.com and never had.
I would suggest opening a feature request issue on Open Source Parse Server [here](https://github.com/parseplatform/parse-server)
