### ISSUE TITLE
Parse Log In Problem

### ISSUE THREAD

**Issue by techsd-repo** [ParsePlatform/Parse-SDK-iOS-OSX#866]
When I go to log a user in, I get the error message: `[Error]: Invalid username/password. (Code: 101, Version: 1.12.0)`. The user exists, is shown in Parse Dashboard, and I can sign up just fine. It does not work on a real device and the simulator.

Xcode: 7.3
iOS: 9.3

My code is below:

  

      PFUser.logInWithUsernameInBackground((usernameField?.text)!, password: (passwordField?.text)!) { (user: PFUser?, error: NSError?) -> Void in
                if error == nil {
                    //Segue to account
                    self.defaults.data.setValue(self.usernameField?.text, forKey: "currentUser")
                    
                   self.presentViewController(AccountInterface(), animated: true, completion: {
                    
                   })
                } else {
                    print(error?.description)
                }
            }

**Comment by nlutsenko** [comment]
@techsd-repo, any chance you can get us a repro?
This clearly and definitely works (you are the only person reporting this), but I would love to help you debug this and investigate if necessary.

**Comment by nlutsenko** [comment]
Few follow-up questions here:
- Are you using parse.com or Open Source Parse Server?
- Can you signup a new account and paste it here so we can test it?
- Does the issue reproduce outside of this specific application?
- Are you using a combination or any of Anonymous Users/Facebook Users/Twitter Users/ Custom Auth Provider Users?

All of these will help us debug a lot and identify the root cause, so let's work together to get this going.

**Comment by techsd-repo** [comment]
1. I am using Parse Server
2. Server URL: http://parseserver-quizical.herokuapp.com Username: test01 Password: test01
3. No
4. I am not using any Twitter/Facebook users

**Comment by nlutsenko** [comment]
You can send it over FB Messenger or to nlutsenko(at)fb.com

**Comment by techsd-repo** [comment]
I sent the keys over FB Messenger, I just wanted to make sure you got them.
:)

**Comment by techsd-repo** [comment]
I don't know how but I can now log in with users.. Thanks for the help :)

**Comment by nlutsenko** [comment]
Glad you found the solution. Let me know if there is anything else that comes up.
