### ISSUE TITLE
Who handles Pull-Requests/Issues on the Parse-Android-UI Github page?

### ISSUE THREAD

**Issue by ofuwape** [ParsePlatform/Parse-SDK-iOS-OSX#868]
Who handles Pull-Requests/Issues on the Parse-Android-UI Github page? There has been no response to questions and bug reports in weeks/months. What's going on here?
https://github.com/ParsePlatform/ParseUI-Android/issues

**Comment by nlutsenko** [comment]
Not sure it's worth opening an issue here, to be honest.
@wangmengyan95 and @grantland  should be able to help you.
