### ISSUE TITLE
Parse iOS builds page being updated?

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/Parse-SDK-iOS-OSX#869]
Anyone updating the builds page for the iOS sdk, or are we now stuck to using cocoapods or building this ourselves?  It was nice to have the package build for download because it included other utils and the fb framework.

**Comment by nlutsenko** [comment]
It's also available on the releases page on this repo [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases). Since we are moving to more and more open source - we would love to actually cross-link the releases page and the downloads page on parse.com
