### ISSUE TITLE
Saving a PFObject is not returning, the execution is stoked in [BFTask waitUntilFinished]

### ISSUE THREAD

**Issue by jonathanff** [ParsePlatform/Parse-SDK-iOS-OSX#870]
In `[self.projectData save:&err]` this method never returns and get paused in the method   [BFTask waitUntilFinished]

` (void)saveToParseWithEmployeeLockStatus:(BOOL)lock andDoThisAfterwards:(void (^)(NSError *error))completionBlock;
{
    //First, save locally.
    if (![self saveLocally]) {
        return;
    }
    
    //Add an edition entry. For now, we only worry if whoever is editing is an employee.
    PFObject *newEditionEntry = [PFObject objectWithClassName:EditionEntryClassKey];
    [newEditionEntry setObjectOrNil:_project forKey:ProjectClassKey];
    [newEditionEntry setObjectOrNil:[[SanMiguelDataManager sharedManager] loggedWorkerSource] forKey:WorkerClassKey];
    
    //If we need to lock, add it to our edition entry.
    if(lock){
        [newEditionEntry setObjectOrNil:[self.projectData objectOrNilForKey:ProjectDataNameKey]
                                 forKey:EditionEntryEmployeeLockProjectNameKey];
        [newEditionEntry setObjectOrNil:[NSNumber numberWithBool:YES]
                                 forKey:EditionEntryEmployeeLock];
    }
    
    //Save it.
    [newEditionEntry saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
        //Could we save the edition entry?
        if(error){
            completionBlock(error);
            return;
        }
        
        //We saved the edition entry. Save it to our project.
        PFRelation *editionEntriesRelation = [_project objectOrNilForKey:ProjectEditionEntriesRelationKey];
        [editionEntriesRelation addObject:newEditionEntry];
        
        NSError *err = [[NSError alloc] init];

        if (![self.client save:&err]) {
            if (completionBlock) {
                NSLog(@"%@", err);
                completionBlock(err);
            }
        }
        
        if (![self.project save:&err]) {
            if (completionBlock) {
                NSLog(@"%@", err);
                completionBlock(err);
            }
        }
        
        if (![self.projectData save:&err]) {
            if (completionBlock) {
                NSLog(@"%@", err);
                completionBlock(err);
            }
        }
        
        [self.client fetchInBackgroundWithBlock:nil];
        completionBlock(error);
    }];
}`

**Comment by nlutsenko** [comment]
Any chance `newEditionEntry` have pointers back to `client`/`project` or `projectData`?
Whenever you save an object if it has any pointers to other objects that are not saved - those are going to be saved before you save an object, meaning that you probably can avoid doing that save.

Also, any chance you can add the stack trace for all threads when it locks up?
To do that - just put `bt all` in the debugger console and paste the output here.
