### ISSUE TITLE
PFUser(withoutDataWithObjectId:) error in Swift 2.2

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/Parse-SDK-iOS-OSX#871]
After update to Swift 2.2 Xcode shows an error for `PFUser(withoutDataWithObjectId:)`:
`Incorrect argument label in call (have 'withoutDataWithObjectId:', expected 'className:')`

This still happens after updating to Parse iOS SDK 1.13.0.

Environment:
Xcode 7.3 (7D175)
Swift 2.2

**Update**
There seems to be a typo in the Parse SDK as Swift is auto-suggesting the function `PFUser(outDataWithObjectId:)`.

**Comment by nlutsenko** [comment]
Thanks for the report.
Turns out, that we already have fixed this in #859, it will be released with the next version of the SDK.
In the meantime - you can simply replace the method in the header with 
```
+ (instancetype)objectWithoutDataWithObjectId:(nullable NSString *)objectId NS_SWIFT_NAME(init(withoutDataWithObjectId:));
```
Which properly imports the method in Swift 2.2.

**Comment by spencerfornaciari** [comment]
Which header are you saying you need to replace this in? PFObject+Subclass.h?

**Comment by mtrezza** [comment]
Another easy solution would be subclassing the PFObject:

```
extension PFObject {
    convenience init(withoutDataWithObjectId objectId: String?) {
        self.init(outDataWithObjectId: objectId)
    }
}
```
