### ISSUE TITLE
[Swift - 1.13.0] Subclass with subclassed PFObject as property give exception

### ISSUE THREAD

**Issue by iStopped** [ParsePlatform/Parse-SDK-iOS-OSX#873]
In my Swift codebase I've something like this:
```
class A : PFObject, PFSubclassing {
    
    @NSManaged var propertyA: B?
    
    override class func initialize() {
        struct Static {
            static var onceToken : dispatch_once_t = 0;
        }
        dispatch_once(&Static.onceToken) {
            self.registerSubclass()
        }
    }
    
    static func parseClassName() -> String {
        return "A"
    }
}

class B : PFObject, PFSubclassing {
    
    @NSManaged var name: String?
    
    override class func initialize() {
        struct Static {
            static var onceToken : dispatch_once_t = 0;
        }
        dispatch_once(&Static.onceToken) {
            self.registerSubclass()
        }
    }
    
    static func parseClassName() -> String {
        return "B"
    }
}
```

When I try to fetch, via dataLocalStore and using includeKey, the property of B I always get _-[PFObject name]: unrecognized selector sent to instance 0x162450130_. I'm using the latest ParseSDK, via carthage.

EDIT: No problem accessing objectId.
EDIT 2: In my test I found out that even if I register the PFObject subclass I cannot cast any PFObject to any subclass. Printing that object, or inspecting it with the debugger, show me the correct subclass but casting produces nil.
EDIT 3: I've done some very basic test and actually initialize is called AFTER didFinishLaunchingWithOptions and the initialization of ParseSDK

**Comment by nlutsenko** [comment]
Sounds very strange, we don't seem to have any changes in the 1.13.0 that would affect this.
Did anything else change affecting this? Does the same work fine with SDK 1.12.0?

**Comment by iStopped** [comment]
I'll test that, by the way I'm using the latest version of Xcode, iOS SDK and Swift. Maybe something changed and broke something else. 
 
As side note, since +load is not implemented in Swift and initialization in not called on class-load you should edit the wiki.
