### ISSUE TITLE
PFGoogleUtils or generic login utils?

### ISSUE THREAD

**Issue by gilthonweapps** [ParsePlatform/Parse-SDK-iOS-OSX#876]
Hi,

Since the release of parse-server to the open-source community, we can use several providers for user authentication (facebook, twitter, google, linked, instagram, etc.). For Twitter and Facebook, there are 2 useful libs available: PFTwitterUtils and PFFacebookUtils.

I would like to use Google to authenticate my users. However, as there is no "PFGoogleUtils", I haven't been able to figure out how I can authenticate my users with Google.
Would it be possible to have a PFGoogleUtils or maybe something more generic that would allow more authentication options (and replace PFTwitterUtils and PFFacebookUtils)? I am glad to help if I can.

I have seen there is a method called `+ (BFTask<__kindof PFUser *> *)logInWithAuthTypeInBackground:(NSString *)authType authData:(NSDictionary<NSString *, NSString *> *)authData` but I cannot call it directly as it asks me to register a specific delegate.

**Comment by nlutsenko** [comment]
Hey @gilthonweapps, that sounds like an amazing idea!
You can actually build your own PFGoogleUtils and I would gladly contribute to it and cross-link from our documentation.

I would recommend taking a look at the PFFacebookUtils and how it interacts with the Parse framework as an inspiration.
Roughly the flow looks like this:
- Register an instance that confirms to a `PFUserAuthenticationDelegate` protocol via `PFUser +registerAuthenticationDelegate:forAuthType:` 
- Implement `restoreAuthenticationWithAuthData:` on the provider that will be invoked when a user logs in or `currentUser` is loaded
- Call into `logInWithAuthTypeInBackground:authData:` with Google authentication data

You can also take a look at how validation works on the server side [here](https://github.com/ParsePlatform/parse-server/blob/master/src/authDataManager/google.js). It already supports Google Authentication, the only missing piece is a client integration.

Let me know if you have any questions or are blocked at any point on this issue and feel free to reopen it.

**Comment by gilthonweapps** [comment]
Hi,

I have already managed to create my own ParseFacebookUtils in swift. It is just a single class for authentication. It doesn't have all the features PFFacebookUtils has, but it is enough for my needs.
I will try to make the same for Google.
