### ISSUE TITLE
Facebook login failure

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/Parse-SDK-iOS-OSX#878]
My objective-c code:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    [Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"myAppId";
        configuration.clientKey = @"clientKey";
        configuration.server = @"http://localhost:1337/parse";
    }]];
    
    return YES;
}

- (IBAction)onLogin:(id)sender {
    [PFUser registerAuthenticationDelegate:self forAuthType:@"facebook"];
    [PFUser logInWithAuthTypeInBackground:@"facebook" authData:@{ @"id": @"884739xxxxxxxxx" }];    
}

- (BOOL)restoreAuthenticationWithAuthData:(NSDictionary<NSString *, NSString *> *)authData;
{
    return YES;
}

```

But I got the following error message:

> Facebook auth is invalid for this user. (Code: 101, Version: 1.13.0)

What's wrong with it? What's should be inside **authData**?

**Comment by zhouhao27** [comment]
Any idea? Thanks

**Comment by nlutsenko** [comment]
@zhouhao27, thanks for the report, sorry it took a while to get back to you.
Looks like you are using Facebook Auth via your own authentication provider.
I would recommend taking a look at the Facebook integration portion of our guide [here](https://parse.com/docs/ios/guide#users-facebook-users).

You would need an extra framework - ParseFacebookUtils or ParseFacebookUtilsV4 (based on the major version of the FBSDK that you want to use) and the amount of code integration there is fairly minimal.

Let me know if you get blocked on any portion of it or if you have any other questions on this issue and please feel free to reopen it.
