### ISSUE TITLE
PFQuery using includeKey: returns null objects 

### ISSUE THREAD

**Issue by andreassylvester** [ParsePlatform/Parse-SDK-iOS-OSX#879]
Recently I've been experiencing when querying a class with an array of objectPointers included with a call to includeKey that some of them inexplicably return as null. Removing the includeKey calls from the query makes the findObjects-call return all object ID:s properly, so that every object might be fetched manually and indeed none of them are null when using this approach.

This is not on a self-hosted Parse installation as we've yet to migrate and the SDK version is 1.13.0 should that matter.

for clarity: returned object when calling includeKey
```
(
  "<Collection: 0x7fdf6a4cf1a0, objectId: 2YET5ibgKi, localId: (null)> {
        shows =         (
                <Show: 0x7fdf6a76cf30, objectId: 6VFYUhFoox, localId: (null)>,
                <null>,
                <Show: 0x7fdf6a74ee00, objectId: rWwIZDnXNh, localId: (null)>,
                <null>,
                <Show: 0x7fdf6c8236e0, objectId: TKSdZgNv3C, localId: (null)>,
                <Show: 0x7fdf6c825db0, objectId: VMXmzsWl6h, localId: (null)>,
                <Show: 0x7fdf6c829fc0, objectId: m7MWr9ku56, localId: (null)>,
                <Show: 0x7fdf6a58ac30, objectId: 4KDzWWyE3L, localId: (null)>,
                <Show: 0x7fdf6a58e0a0, objectId: YSFGTeK5DY, localId: (null)>
        );
        title = #Skoj!;
}",
  "<Collection: 0x7fdf6a58e2b0, objectId: 47fdRfVCXi, localId: (null)> {
        shows =         (
                <Show: 0x7fdf6a7853c0, objectId: ZIDucXEcgo, localId: (null)>,
                <null>,
                <Show: 0x7fdf6a769a60, objectId: Lp55HJpWch, localId: (null)>,
                <Show: 0x7fdf6a59ffe0, objectId: ZC4zSaiu7U, localId: (null)>,
                <Show: 0x7fdf6a5a11f0, objectId: 8Dq6p26bsK, localId: (null)>,
                <null>,
                <Show: 0x7fdf6a5a1c70, objectId: YGycm345yI, localId: (null)>,
                <null>,
                <null>,
                <Show: 0x7fdf6a5adaf0, objectId: MFujAmbC8H, localId: (null)>,
                <null>,
                <Show: 0x7fdf6c9a2390, objectId: smFvuekfnO, localId: (null)>,
                <Show: 0x7fdf6c834ff0, objectId: SBirS0djUi, localId: (null)>,
                <null>,
                <null>,
                <Show: 0x7fdf6a5b3ef0, objectId: 2jffTGz1iD, localId: (null)>,
                <Show: 0x7fdf6a5b7b60, objectId: AJWyqVxmOq, localId: (null)>,
                <Show: 0x7fdf6a5bbaf0, objectId: tydXIMcIl5, localId: (null)>,
                <null>
        );
        title = #Veckotipset;
}"
)
```
And returned object for the same PFQuery but without the includeKey call:

```
(
  "<Collection: 0x7fcacb4a9fb0, objectId: 2YET5ibgKi, localId: (null)> {
    shows =     (
        <Show: 0x7fcacb4beeb0, objectId: 6VFYUhFoox, localId: (null)>,
        <Show: 0x7fcacb4895d0, objectId: xGlECRUNNJ, localId: (null)>,
        <Show: 0x7fcacd91ce70, objectId: rWwIZDnXNh, localId: (null)>,
        <Show: 0x7fcacd91d630, objectId: uxatUR5xzd, localId: (null)>,
        <Show: 0x7fcacd91b210, objectId: TKSdZgNv3C, localId: (null)>,
        <Show: 0x7fcacd91af60, objectId: VMXmzsWl6h, localId: (null)>,
        <Show: 0x7fcacb4bfa00, objectId: m7MWr9ku56, localId: (null)>,
        <Show: 0x7fcacb4cc480, objectId: 4KDzWWyE3L, localId: (null)>,
        <Show: 0x7fcacd913500, objectId: YSFGTeK5DY, localId: (null)>
    );
    title = #Skoj!;
}",
  "<Collection: 0x7fcacb55ad10, objectId: 47fdRfVCXi, localId: (null)> {
    shows =     (
        <Show: 0x7fcacb576c20, objectId: ZIDucXEcgo, localId: (null)>,
        <Show: 0x7fcacb570170, objectId: ZGWEViMONj, localId: (null)>,
        <Show: 0x7fcacd91d240, objectId: Lp55HJpWch, localId: (null)>,
        <Show: 0x7fcacb4bc690, objectId: ZC4zSaiu7U, localId: (null)>,
        <Show: 0x7fcacb4081c0, objectId: 8Dq6p26bsK, localId: (null)>,
        <Show: 0x7fcacb4f6950, objectId: kTaGoee6nx, localId: (null)>,
        <Show: 0x7fcacb4cbb40, objectId: YGycm345yI, localId: (null)>,
        <Show: 0x7fcacd91a450, objectId: P5lrSQt1K0, localId: (null)>,
        <Show: 0x7fcacb4f35b0, objectId: khZjnh6Yx6, localId: (null)>,
        <Show: 0x7fcacb4391d0, objectId: MFujAmbC8H, localId: (null)>,
        <Show: 0x7fcacb4ef8d0, objectId: 7pzJ934yuZ, localId: (null)>,
        <Show: 0x7fcacd912e00, objectId: smFvuekfnO, localId: (null)>,
        <Show: 0x7fcacd919f00, objectId: SBirS0djUi, localId: (null)>,
        <Show: 0x7fcacb4bf410, objectId: ONiphqp3wT, localId: (null)>,
        <Show: 0x7fcacb4bf6b0, objectId: hLqX42DDcM, localId: (null)>,
        <Show: 0x7fcacd91df40, objectId: 2jffTGz1iD, localId: (null)>,
        <Show: 0x7fcacd91e1d0, objectId: AJWyqVxmOq, localId: (null)>,
        <Show: 0x7fcacd91e540, objectId: tydXIMcIl5, localId: (null)>,
        <Show: 0x7fcacd91e7e0, objectId: p6sXRHMZAt, localId: (null)>
    );
    title = #Veckotipset;
}"
)
```

**Comment by nlutsenko** [comment]
Sounds very strange, let's try debugging this together to identify whether it's a client-side or a server-side issue.
- Does the issue reproduce via curl request or on any other platform?
- If making curl request or using other platform is not an option - you could instrument your app with our Network Debug Tool from [this guide](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool).

Looking forward to hear from you with the results.

**Comment by andreassylvester** [comment]
thanks for your answer and sorry for the late follow-up. I can't seem to reproduce the problem via curl and when checking the JSON returned via the parse SDK (using the network debug tool), it's (sometimes) missing the field with the pointer data.

Creating a query and calling
```
[query includeKey:@"user"];
[query includeKey:@"targetShow"];
```
produces the result for a specific class object
```
{
	"createdAt": "2016-04-06T10:54:19.547Z",
	"objectId": "IjRBiRJ5gx",
	"type": "showLike",
	"updatedAt": "2016-04-06T10:54:19.547Z",
	"user": { ...* }
}
```
and the response for the same call but without calling `includeKey`:
```
{
	"createdAt": "2016-04-06T10:54:19.547Z",
	"objectId": "IjRBiRJ5gx",
	"targetShow": {
		"__type": "Pointer",
		"className": "Show",
		"objectId": "jZuiahJtJV"
	},
	"type": "showLike",
	"updatedAt": "2016-04-06T10:54:19.547Z",
	"user": {
		"__type": "Pointer",
		"className": "_User",
		"objectId": "j27fKKzlQv"
	}
}
```

whereas the curl call for this object returns it completely as expected
```
curl -X GET \
-H "X-Parse-Application-Id: xxx" \
-H "X-Parse-REST-API-Key: xxx" \
-G \
--data-urlencode 'include=targetShow,user' \
https://api.parse.com/1/classes/Activity/IjRBiRJ5gx
```
```
{
	"createdAt": "2016-04-06T10:54:19.547Z",
	"objectId": "IjRBiRJ5gx",
	<pre><b>"targetShow": { ...* }</b></pre>,
	"type": "showLike",
	"updatedAt": "2016-04-06T10:54:19.547Z",
	"user": { ...* }
}
```

\* complete object

**Comment by nlutsenko** [comment]
Hey @andreassylvester, are you using Parse Server or parse.com?
If the former - I would recommend reporting this on the Parse Server [repo](https://github.com/ParsePlatform/parse-server), since this looks to be a server-side issue, probably related to caching.

Since this is flaky and raw network data sometimes is missing the data, I don't think this is caused by the client. The only thing that comes to my mind is concurrent call into `includeKey:` but I highly doubt that's the case here.

This is highly likely to be caused by something inconsistent being saved into `targetShow` where that fails to unwrap into the full object...

**Comment by andreassylvester** [comment]
Hey,
This is on parse.com, but we plan on migrating shortly. 
Yes, I've tried to check the data for inconsistencies, with no luck, any sort of suggestions on where to start would be greatly appreciated as it's very time consuming and difficult to know what to look for other than the obvious pointers to null objects and the like. 

Another thing I've forgotten to mention is the fact that which objects return as null is not consistent but varies depending on which pointers are contained in the `shows` array. So for instance, Show X can return properly when `shows` contain just the one pointer, but when Show Y is added, Show X starts returning as null.

**Comment by andreassylvester** [comment]
Ok after doing some more digging it seems the villain in this particular drama is a String field which, when exceeding roughly 950 characters make the surrounding object return as null. I tried to find some more info on this and couldn't discern any length limit to the String type, but I did see a reference to Parse objects being limited to 128 k, something I should be well below even when taking in to account all the referenced objects sizes combined?  

Do you know if this limit is something that still applies to the self hosted parse installation or if not, maybe this problem will solve itself on migration?

**Comment by nlutsenko** [comment]
Yup, sounds like you found the source of the problem - the size could be a bottleneck here.
Good news, we don't have this limit on Parse Server and this will be solved by migrating to it.

Also, if you run into the similar problem or any problem at all, the turnaround resolution time on Parse Server is way faster, since we can ship the new versions without going through big platform deploy.

Let me know if you find anything else as a source of the problem or if you have any questions.
(and please feel free to reopen this issue)
