### ISSUE TITLE
PFFile problem

### ISSUE THREAD

**Issue by yoshiboarder** [ParsePlatform/Parse-SDK-iOS-OSX#883]
I'm trying to upload image via singup function.

userName/userPassword/userPasswordRepeat is works fine.

but PFFile have a problem.

[Error]: The request timed out. (Code: 100, Version: 1.13.0)

My Parse Server environment is...AWS with MonggoDB(https://mlab.com/)

Anyone Helping me?

Here is my code.

`@IBAction func signUpButtonTapped(sender: AnyObject) {
        
        let userName=userEmailAddressTextField.text!
        let userPassword=userPasswordTextField.text!
        let userPasswordRepeat=userPasswordRepeatTextField.text!
        
        
        if(userName.isEmpty || userPassword.isEmpty || userPasswordRepeat.isEmpty)
        {
            var myAlert=UIAlertController(title:"Alert", message: "All fields are required to fill in",preferredStyle: UIAlertControllerStyle.Alert)
            let okAction=UIAlertAction(title:"Ok", style: UIAlertActionStyle.Default, handler: nil)
            myAlert.addAction(okAction)
            
            self.presentViewController(myAlert, animated:true, completion:nil)
            
            return
        }
        
        if(userPassword != userPasswordRepeat)
        {
            var myAlert=UIAlertController(title:"Alert", message: "Passwords do not match. Please try again",preferredStyle: UIAlertControllerStyle.Alert)
            
            let okAction=UIAlertAction(title:"Ok", style: UIAlertActionStyle.Default, handler: nil)
            myAlert.addAction(okAction)
            
            self.presentViewController(myAlert, animated:true, completion:nil)

            
            
            return
        }
        
        
        let myUser:PFUser=PFUser()
        myUser.username=userName
        myUser.password=userPassword
        myUser.email=userName
        
        let profileImageData=UIImageJPEGRepresentation(profilePhotoImageView.image!,1)
        
        if(profileImageData != nil)
        {
            //Create PFFile object to be sent to Parse cloud service
            let profileImageFile=PFFile(data: profileImageData!)
            myUser.setObject(profileImageFile!, forKey: "profile_picture")
            
        }
        
        myUser.signUpInBackgroundWithBlock{(success:Bool, error:NSError?)->Void in
        
            
            var userMessage="Registration is successful. Thank you!"
        
            if(!success)
            {
//                userMessage="Could not register at this time please try again later."
                userMessage=error!.localizedDescription
                
            }
            var myAlert=UIAlertController(title:"Alert", message: userMessage,
                preferredStyle: UIAlertControllerStyle.Alert)
            
            let okAction=UIAlertAction(title:"Ok", style: UIAlertActionStyle.Default){ action in
                
                if(success){
                    self.dismissViewControllerAnimated(true, completion: nil)
                    
                }
                
            }
            myAlert.addAction(okAction)
            
            self.presentViewController(myAlert, animated:true, completion:nil)
            
            
        
        }
        
        
        
    }
`

**Comment by nlutsenko** [comment]
The code looks fine. I would recommend trying to save a file via curl request.
For example:
```
curl -X POST \
  -H "X-Parse-Application-Id: %APP_ID%" \
  -H "Content-Type: text/plain" \
  -d 'Hello, World!' \
  http://%SERVER_URL%/parse/files/hello.txt
```

If this doesn't work and times out as well - then, could you open the issue on the Parse Server repo [here](https://github.com/parseplatform/parse-server).

Let us know here how it goes for you.

**Comment by iStopped** [comment]
I get the same error, but not always with PFUser (or subclass). If I define a new class with one or more PFFile I can't save the file(s); I always get timeout errors.
