### ISSUE TITLE
Errors with building Parse SDK through cocoapods

### ISSUE THREAD

**Issue by anoopnimkar** [ParsePlatform/Parse-SDK-iOS-OSX#884]
Getting errors related with Bolts framework when using latest Parse and Facebook SDKs through cocoapods,
**PFObject.h:295:4: Type arguments cannot be applied to non-parameterized class 'BFTask'**

My podfile,
pod 'Parse'
pod 'ParseCrashReporting'
pod 'ParseFacebookUtilsV4'
pod 'ParseTwitterUtils'

**Comment by nlutsenko** [comment]
Looks like you have an old version of `Bolts`.
Try running `pod update` and pasting the output here...

**Comment by anoopnimkar** [comment]
I just created this new project,
Using Bolts (1.7.0)
Using FBSDKCoreKit (4.10.1)
Using FBSDKLoginKit (4.10.1)
Using Parse (1.13.0)
Using ParseCrashReporting (1.9.2)
Using ParseFacebookUtilsV4 (1.11.1)
Using ParseTwitterUtils (1.10.0)

**Comment by anoopnimkar** [comment]
Output for `pod update`
Update all pods
Updating local specs repositories

CocoaPods 1.0.0.beta.6 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using Bolts (1.7.0)
Using FBSDKCoreKit (4.10.1)
Using FBSDKLoginKit (4.10.1)
Using Parse (1.13.0)
Using ParseCrashReporting (1.9.2)
Using ParseFacebookUtilsV4 (1.11.1)
Using ParseTwitterUtils (1.10.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 7 total pods installed.

**Comment by nlutsenko** [comment]
Hmm. Seems absolutely fine. 
Any chance you have an old version of FBSDK in ~/Documents/FacebookSDK ?
Also, if you could paste the screenshot of the error that would be helpful. 
As another thing - I would double check that Xcode DerivedData is clean.

**Comment by skimgosu** [comment]
Are you using the latest XCode and Swift? If so, try deleting the Pods/Header folder.

**Comment by anoopnimkar** [comment]
It was with latest Xcode. I deleted the old project file, recreated new one and it started working. 
No issues while building and running. Thanks!

**Comment by anoopnimkar** [comment]
My suspicion is that somehow LD_LIBRARY_PATH was getting over-ridden

**Comment by nlutsenko** [comment]
Glad you found the solution! Xcode is not helpful sometimes...
