### ISSUE TITLE
How do you check local datastore?  localId always shows null

### ISSUE THREAD

**Issue by mikepaggi** [ParsePlatform/Parse-SDK-iOS-OSX#894]
I can't tell if something is pinned or not...localId always shows null but i know some things are pinning though...

is there a way to check the local datastore to see if things are actually saving?

**Comment by nlutsenko** [comment]
Unfortunately, there is no way to check if something is available in the local datastore or not directly.
The only way we have right now - query for it and check if the returned count is non-zero.

Something like this would work:
```objc
PFObject *object = ...;
PFQuery *query = [[PFQuery queryWithClassName:object.parseClassName] fromLocalDatastore];
[query whereKey:@"objectId" equalTo:object.objectId];
[query countObjectsInBackgroundWithBlock:^(int number, NSError * _Nullable error) {
    if (number != 0) {
        // Object is in Local Datastore
    } else {
        // Object is not in Local Datastore
    }
}];
```

Let me know if this helps, if not - please feel free to reopen the issue.

**Comment by mikepaggi** [comment]
So when I print the object and see that localId reference...that doesn't mean really anything, right?

**Comment by nlutsenko** [comment]
Not if you are using Local Datastore, no. :)

**Comment by mikepaggi** [comment]
Ok good to know....it would be nice in the future to be able to see what is in local data store just to really verify things.  By the way....is local datastore using sqlite or something on the lines of that?

**Comment by nlutsenko** [comment]
It does indeed use sqlite and our custom layer on top on both iOS and Android.
