### ISSUE TITLE
PFPurchase.buyProduct() not working with Swift

### ISSUE THREAD

**Issue by mkral** [ParsePlatform/Parse-SDK-iOS-OSX#9]
It seems like somethings getting hung up and the block is never fired. 

I'm working on a project in Swift and using Cocoapods to add Parse to my project

I'm testing in Sandbox Environment on iPhone 6 (8.4.1) with Parse 1.8.0

The user is never prompted to purchase the IAP either.

**Comment by nlutsenko** [comment]
Hey @mkral, thanks for the report.
I've just tested IAP locally with the SDK and it works great both in Swift and ObjC.
Any chance you can attach a unit test that fails or have a repro project?
Also, have you seen the integration guide for IAP at https://parse.com/docs/ios/guide , it has some useful info on how to set it up.

**Comment by mkral** [comment]
Sorry, it appears to be working now. I think I had too many non-finished transactions in the queue (before I switched to Parse) but it's working now. you can close this.

**Comment by richardjrossiii** [comment]
Just an FYI, you should be able to close your own issues. I've got this one for now though :)
