### ISSUE TITLE
Swift: Parse query where relation contains all objects from array

### ISSUE THREAD

**Issue by nsekhon** [ParsePlatform/Parse-SDK-iOS-OSX#904]
Currently I am trying to get an AND query instead of an OR query, but this method only works for arrays, not relations:

> query.whereKey("relationKey", containsAllObjectsInArray: pfObjects)

Is there any way to do this or is it not possible yet?
Thanks, Neil

**Comment by nlutsenko** [comment]
You can do it, but would need to do through a relation query.
For example:
```swift
let object = PFObject(withoutDataWithObjectId: "")
let objects: [PFObject] = []
let relation = object.relationForKey("relationKey")
let relationQuery = relation.query()
relationQuery.whereKey("objectId", containedIn: objects.map({ $0.objectId! }))
```

Let me know if this helps.

**Comment by nsekhon** [comment]
Unfortunately this did not work because I believe that this query fetches the actual objects of "relationKey" rather than objects that contain all of the "relationKey" objects in its relation. I am trying to fetch a list of objects that contain all of the given pfObjects in its relation. So for example I am given an array of "ClassB" objects and need to fetch all the "ClassA" objects that contain all of the given "ClassB" objects in the "ClassA" objects' relation "relationKey".

**Comment by nlutsenko** [comment]
Hey @nsekhon, gotcha,
Unfortunately, `$all` is not supported for relation fields, though you can do `containedIn` aka `$in` operator, which will query all the objects that have your objects contained in the relation field, then you can query individual relation queries on the client and simply count the objects that you are looking for.
If that count doesn't match - then the object should be filtered.

This is the updated code snippet for your use case:
```swift
let objects = [ PFObject(withoutDataWithClassName: "ClassB", objectId: "...") ]
let query = PFQuery(className: "Class")
relationQuery.whereKey("relationKey", containedIn: objects)
```

Then for filtering you can do something like this
```swift
nonFilteredObjects.forEach { object in
    let query = object.relationForKey("relationKey").query()
    let count = query.countObjects
    if count == objects.count {
        filteredObjects.addObject(object)
    }
}
```

Let me know if this flow helps.
