### ISSUE TITLE
PFFacebookUtils.logInInBackgroundWithReadPermissions not working with FB SDK 4.11

### ISSUE THREAD

**Issue by rmasoor** [ParsePlatform/Parse-SDK-iOS-OSX#905]
Hi

I am using the following method with FB SDK4.11 and IoS9.3 to integrate with FB in viewController()

override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let permissions = ["public_profile"]
        
      **PFFacebookUtils.logInInBackgroundWithReadPermissions(permissions, block)**
}
However, the following function in appDelegate() is not being called to generate the URL:

    **func application(application: UIApplication,
                     openURL url: NSURL,
                             sourceApplication: String?,
                             annotation: AnyObject) -> Bool {
        
        return FBSDKApplicationDelegate.sharedInstance().application(application, openURL: url, sourceApplication: sourceApplication, annotation: nil)
    }**

I have followed the instructions as per FB and Parse but it appears the PFFacebookUtils.logInInBackgroundWithReadPermissions is not called at all.

Appreciate your response.

Thanks

Ramesh

**Comment by nlutsenko** [comment]
Hey @rmasoor, just tested this with the latest FBSDK and Parse and it seems to work like a charm, meaning that there might be something specific about your SDK setup here.

Any chance you can share you SDK setup code snippet? (feel free to omit keys).
The part that I am interested in is the order of the setup.
It should be something like this: 
- Initialize Parse (set appId/server/key)
- Initialize FBSDK
- Initialize ParseFacebookUtils

**Comment by rmasoor** [comment]
Hi Nikita,

Thanks for checking into this.

Here is the code for appDelegate and viewController

mport UIKit


import Bolts

import Parse


// If you want to use any of the UI components, uncomment this line

// import ParseUI


// If you want to use Crash Reporting - uncomment this line

// import ParseCrashReporting


@UIApplicationMain

class AppDelegate: UIResponder, UIApplicationDelegate {


    var window: UIWindow?


    //--------------------------------------

    // MARK: - UIApplicationDelegate

    //--------------------------------------


    func application(application: UIApplication,
didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool
{

        // Enable storing and querying data from Local Datastore.

        // Remove this line if you don't want to use Local Datastore
features or want to use cachePolicy.

        Parse.enableLocalDatastore()


        Parse.setApplicationId("BuJz6kwDxhGGWapcRwlxB2mnWKjBd1m1NmdaCXxq",

            clientKey: "t7K9aKsoAM6Sb72FZfyMcsOs4C2eUI826AN2G0uR")





        PFFacebookUtils.initializeFacebookWithApplicationLaunchOptions
(launchOptions)



        PFUser.enableAutomaticUser()


        let defaultACL = PFACL();


        // If you would like all objects to be private by default, remove
this line.

        defaultACL.setPublicReadAccess(true)


        PFACL.setDefaultACL(defaultACL, withAccessForCurrentUser:true)


        if application.applicationState != UIApplicationState.Background {

            // Track an app open here if we launch with a push, unless

            // "content_available" was used to trigger a background push
(introduced in iOS 7).

            // In that case, we skip tracking here to avoid double counting
the app-open.


            let preBackgroundPush = !application.respondsToSelector(
"backgroundRefreshStatus")

            let oldPushHandlerOnly = !self.respondsToSelector(
"application:didReceiveRemoteNotification:fetchCompletionHandler:")

            var noPushPayload = false;

            if let options = launchOptions {

                noPushPayload = options[
UIApplicationLaunchOptionsRemoteNotificationKey] != nil;

            }

            if (preBackgroundPush || oldPushHandlerOnly || noPushPayload) {

                PFAnalytics.trackAppOpenedWithLaunchOptions(launchOptions)

            }

        }

        if application.respondsToSelector(
"registerUserNotificationSettings:") {

            let userNotificationTypes: UIUserNotificationType = [
UIUserNotificationType.Alert, UIUserNotificationType.Badge,
UIUserNotificationType.Sound]

            let settings = UIUserNotificationSettings(forTypes:
userNotificationTypes, categories: nil)

            application.registerUserNotificationSettings(settings)

            application.registerForRemoteNotifications()

        } else {

            let types: UIRemoteNotificationType =
[UIRemoteNotificationType.Badge,
UIRemoteNotificationType.Alert, UIRemoteNotificationType.Sound]

            application.registerForRemoteNotificationTypes(types)

        }


        return FBSDKApplicationDelegate.sharedInstance().application(application,
didFinishLaunchingWithOptions: launchOptions)

    }


    //--------------------------------------

    // MARK: Push Notifications

    //--------------------------------------


    func application(application: UIApplication,
didRegisterForRemoteNotificationsWithDeviceToken deviceToken: NSData) {

        let installation = PFInstallation.currentInstallation()

        installation.setDeviceTokenFromData(deviceToken)

        installation.saveInBackground()



//        PFPush.subscribeToChannelInBackground("") { (succeeded: Bool,
error: NSError?) in

//            if succeeded {

//                print("ParseStarterProject successfully subscribed to
push notifications on the broadcast channel.");

//            } else {

//                print("ParseStarterProject failed to subscribe to push
notifications on the broadcast channel with error = %@.", error)

//            }

//        }

    }


    func application(application: UIApplication,
didFailToRegisterForRemoteNotificationsWithError error: NSError) {

        if error.code == 3010 {

            print("Push notifications are not supported in the iOS
Simulator.")

        } else {

            print("application:didFailToRegisterForRemoteNotificationsWithError:
%@", error)

        }

    }


    func application(application: UIApplication,
didReceiveRemoteNotification userInfo: [NSObject : AnyObject]) {

        PFPush.handlePush(userInfo)

        if application.applicationState == UIApplicationState.Inactive {

            PFAnalytics.trackAppOpenedWithRemoteNotificationPayload
(userInfo)

        }

    }


    ///////////////////////////////////////////////////////////

    // Uncomment this method if you want to use Push Notifications with
Background App Refresh

    ///////////////////////////////////////////////////////////

    // func application(application: UIApplication,
didReceiveRemoteNotification userInfo: [NSObject : AnyObject],
fetchCompletionHandler completionHandler: (UIBackgroundFetchResult) ->
Void) {

    //     if application.applicationState == UIApplicationState.Inactive {

    //
PFAnalytics.trackAppOpenedWithRemoteNotificationPayload(userInfo)

    //     }

    // }


    func application(application: UIApplication,

        openURL url: NSURL,

        sourceApplication: String?,

        annotation: AnyObject) -> Bool {

            return
FBSDKApplicationDelegate.sharedInstance().application(application,
openURL: url, sourceApplication: sourceApplication, annotation: annotation)

    }



    func applicationDidBecomeActive(application: UIApplication) {

        FBSDKAppEvents.activateApp()

    }

 ================================

viewController


import UIKit

import Parse

import FBSDKCoreKit


class ViewController: UIViewController {



    override func viewDidLoad() {

        super.viewDidLoad()

        // Do any additional setup after loading the view, typically from a
nib.



        let permissions = ["public_profile"]





        PFFacebookUtils.logInInBackgroundWithReadPermissions(permissions) {



            (user: PFUser?, error: NSError?) -> Void in



            if let error = error {



                print(error)



            } else {



                if let user = user {



                    print(user)





                }







            }







        }





    }



    override func didReceiveMemoryWarning() {

        super.didReceiveMemoryWarning()

        // Dispose of any resources that can be recreated.

    }

}

Here is the info.plist

--------------------------

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "
http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">

<dict>

<key>CFBundleDevelopmentRegion</key>

<string>en</string>

<key>CFBundleExecutable</key>

<string>$(EXECUTABLE_NAME)</string>

<key>CFBundleIdentifier</key>

<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>

<key>CFBundleInfoDictionaryVersion</key>

<string>6.0</string>

<key>CFBundleName</key>

<string>$(PRODUCT_NAME)</string>

<key>CFBundlePackageType</key>

<string>APPL</string>

<key>CFBundleShortVersionString</key>

<string>1.7.5</string>

<key>CFBundleSignature</key>

<string>????</string>

<key>CFBundleURLTypes</key>

<array>

<dict>

<key>CFBundleURLSchemes</key>

<array>

<string>fb1723152657963987</string>

</array>

</dict>

</array>

<key>CFBundleVersion</key>

<string>1.7.5</string>

<key>FacebookAppID</key>

<string>1723152657963987</string>

<key>FacebookDisplayName</key>

<string>MyTinder</string>

<key>LSApplicationQueriesSchemes</key>

<array>

<string>fbauth2</string>

</array>

<key>LSRequiresIPhoneOS</key>

<true/>

<key>NSAppTransportSecurity</key>

<dict>

<key>NSAllowsArbitraryLoads</key>

<true/>

</dict>

<key>UIMainStoryboardFile</key>

<string>Main</string>

<key>UIRequiredDeviceCapabilities</key>

<array>

<string>armv7</string>

</array>

<key>UISupportedInterfaceOrientations</key>

<array>

<string>UIInterfaceOrientationPortrait</string>

<string>UIInterfaceOrientationLandscapeLeft</string>

<string>UIInterfaceOrientationLandscapeRight</string>

</array>

<key>UISupportedInterfaceOrientations~ipad</key>

<array>

<string>UIInterfaceOrientationPortrait</string>

<string>UIInterfaceOrientationPortraitUpsideDown</string>

<string>UIInterfaceOrientationLandscapeLeft</string>

<string>UIInterfaceOrientationLandscapeRight</string>

</array>

</dict>

</plist>

**Comment by highthem** [comment]
issue is not fixed :(
