### ISSUE TITLE
PFGeoPoint - Latitude out of range [-90.0, 90.0] 

### ISSUE THREAD

**Issue by ryderjack** [ParsePlatform/Parse-SDK-iOS-OSX#906]
Certain locations fall outside of the latitude range within PFGeoPoint such as North Dakota with a latitude of -100.445038.

Is there a reason for the range figures only going up to +/-90?

Cheers

**Comment by nlutsenko** [comment]
Hey @ryderjack,

Are you sure you are referring to `latitude` and not `longitude`?
According to [Google Maps](https://www.google.com/maps/place/North+Dakota/@47.4496322,-102.5498487,7z/data=!3m1!4b1!4m2!3m1!1s0x52d7831257d8e963:0xd849a39835ecfc9), North Dakota has a negative (-101) `longitude`, which has a range of `[-180...180]`, but 47 as a latitude.

**Comment by ryderjack** [comment]
Yes I'm sure, here's a screenshot of the error which occurs on this line:

`self.geopoint = [PFGeoPoint geoPointWithLatitude:item2 longitude:item1];`

<img width="1280" alt="screen shot 2016-04-25 at 20 07 30" src="https://cloud.githubusercontent.com/assets/10326229/14795688/83678a3a-0b21-11e6-8194-de527d3b5416.png">
