### ISSUE TITLE
email verification is broken

### ISSUE THREAD

**Issue by dashboardstory** [ParsePlatform/Parse-SDK-iOS-OSX#907]
I can't seem to get the email verification function working for the iOS app on Parse. I tried both new signup and existing account. Any idea?

**Comment by nlutsenko** [comment]
Hey @dashboardstory, 

Unfortunately, without more info this issue is not quite actionable.
Let's try to figure this out together:
- Are you using parse.com or Parse Server?
- If the former - we expect it to work out-of-the-box
- If the latter - how does your email provider setup look like?
