### ISSUE TITLE
Uploading 40MB File to database

### ISSUE THREAD

**Issue by mocode808** [ParsePlatform/Parse-SDK-iOS-OSX#910]
Does PFFIle still have a max file limit of 10MB? If so how can I bypass this or what is the best method for uploading larger files to a database?

**Comment by nlutsenko** [comment]
Hey @mocode808,

Limit was removed in the current latest version of iOS SDK (1.13.0).
Meaning that you don't actually have to do anything special on the client to upload files larger than 10MB.

On the backend you have few options:
- Parse.com has a generous file upload limit, though I recommend avoiding using it for anything new and recommend migrating from it.
- Parse Server has a built-in 20MB set, but it could be removed simply by using a `maxUploadSize` configuration option. You can find the code for it [here](https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/FilesRouter.js#L21).
Also, specifically for Parse Server - we have many solutions for files, like custom S3, Google Cloud Storage or simple on-disk files. All of this is documented [here](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters).

Let me know if this doesn't help or you are still running into issues.
