### ISSUE TITLE
Cocoapods not updated to the latest Parse library

### ISSUE THREAD

**Issue by oberoi1** [ParsePlatform/Parse-SDK-iOS-OSX#914]
Trying to use this method post parse server migration as suggested in the guide : 
    [Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"YOUR_APP_ID";
        configuration.clientKey = @"YOUR_APP_CLIENT_KEY";
        configuration.server = @"http://localhost:1337/parse/";
    }]];
This gives a compile error Use of undeclared identifier "ParseClientConfiguration" (See attached screenshot).
![screenshot 2016-05-02 12 54 08](https://cloud.githubusercontent.com/assets/16607300/14949132/01321924-1065-11e6-81e5-31bad3b408fd.png)

My pod file is this -
source 'https://github.com/CocoaPods/Specs.git'
workspace 'SwipingTest'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseCrashReporting'
pod 'ParseUI'

**Comment by manishnath** [comment]
I am getting the same issue. Can someone clarify this. I have migrated my parse app to self hosted servers. Need to migrate the iOS app ASAP.

**Comment by nlutsenko** [comment]
Hey guys,

Thus should be resolved by updating to the latest version of the SDK. Looks like there is something potentially blocking the update. 
Can you post your 'pod update' output here?

Also, side note: ParseCrashReporting is deprecated and is no longer supported.

**Comment by manishnath** [comment]
@nlutsenko Not using ParseCrashReporting anymore ,  Here is my pod update output :
Manish:SwipingTest Manish$ pod update
Update all pods
Analyzing dependencies
/Users/Manish/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/source.rb:42: warning: Insecure world writable dir /usr/local/git/bin in PATH, mode 040777
2016-05-03 09:46:37.828 xcodebuild[2386:8047] [MT] PluginLoading: Required plug-in compatibility UUID F41BD31E-2683-44B8-AE7F-5F09E919790E for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/App.io Xcode Plugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs

CocoaPods 1.0.0.rc.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Using AMSmoothAlert (1.1)
Using AppsFlyer-SDK (2.5.3.19)
Using Bolts (1.7.0)
Using Branch (0.12.1)
Using CLImageEditor (0.1.4)
Using CleverTap-iOS-SDK (2.0.10)
Using Crashlytics (3.7.0)
Using FBSDKCoreKit (4.11.0)
Using FBSDKShareKit (4.11.0)
Using Fabric (1.6.7)
Using Facebook-iOS-SDK (3.24.4)
Using FormatterKit (1.8.1)
Using GPUImage (0.1.7)
Using Google (2.0.4)
Using GoogleAnalytics (3.14.0)
Using GoogleAppIndexing (2.0.3)
Using GoogleIDFASupport (3.14.0)
Using GoogleInterchangeUtilities (1.2.0)
Using GoogleNetworkingUtilities (1.2.0)
Using GoogleSymbolUtilities (1.1.0)
Using GoogleUtilities (1.3.0)
Using MBProgressHUD (0.9.2)
Using MZTimerLabel (0.5.4)
Using Parse (1.13.0)
Using ParseFacebookUtils (1.10.0)
Using ParseUI (1.2.0)
Using Reachability (3.2)
Using STTwitter (0.2.3)
Using UIImageEffects (0.0.1)
Generating Pods project
Integrating client project

Now I am getting only one linker error while I try to run the project ld: library not found for -lParseCrashReporting
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
![screenshot 2016-05-03 09 51 09](https://cloud.githubusercontent.com/assets/907546/14974618/9f44c44a-1114-11e6-8f35-20042334d2c9.png)

**Comment by nlutsenko** [comment]
This looks better now, perfect.
Now the last issue that you need to resolve - look for `ParseCrashReporting` in `Other Linker Flags` or in `Linked Libraries & Binaries` for your target.
After ParseCrashReporting is gone from those places - it should compile no problem.

**Comment by manishnath** [comment]
Ok I had to remove PFFacebookUtils also. But there was a -l pods PFFacebookUtils and one -l PFFacebookUtils. So I think its resolved now.

**Comment by nlutsenko** [comment]
Perfect! Glad you were able to find the issue and resolve it. 
Let me know if anything comes up further.

**Comment by sidan5** [comment]
Just happened to me. Seems that first time using `pod install` installed version 1.2.30 but `pod update` fixed that.

**Comment by sidan5** [comment]
Found the solution. Apparently I was using iOS 6.0 as deployment target (and it's not compatible so it install the latest update the runs on iOS 6). I found that issue only by using `pod 'Parse', '~> 1.13.0'`

I suggest using that method as example so other won't have same stupid issue.

**Comment by karthisiva** [comment]
here i am getting Library not found for ~lPods after updating to the new Parse SDK POD file.
clang: error:linker command failed.
here is the screen shot
![screen shot 2016-11-18 at 6 39 46 pm](https://cloud.githubusercontent.com/assets/6926979/20439196/8a58e836-ade0-11e6-9771-1c4037233720.png)

**Comment by qasimsqm** [comment]
I am still getting this issue. I tried all the ways to install uninstall and a lot of other things but i am still getting this error. Following is my pod update output.
Update all pods
Updating local specs repositories

CocoaPods 1.2.0.rc.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.rc.1

Analyzing dependencies
Downloading dependencies
Using Bolts (1.8.4)
Using Cloudinary (1.0.15)
Using FBAudienceNetwork (4.10.1)
Installing FBSDKCoreKit 4.10.1 (was 4.18.0)
Using FBSDKLoginKit (4.10.1)
Using FBSDKMessengerShareKit (1.3.2)
Using FBSDKShareKit (4.10.1)
Using MKSHorizontalLineProgressView (0.1.1)
Installing Parse (1.14.2)
Installing ParseFacebookUtilsV4 (1.11.1)
Using SDWebImage (3.8.2)
Using TOCropViewController (2.0.11)
Using TWMessageBarManager (1.8.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 11 dependencies from the Podfile and 13 total pods installed.

**Comment by qasimsqm** [comment]
I got it fixed. There was an old parse framework in my project folder that was not hard deleted it was just deleted by reference. Now i deleted that and it worked for me.
