### ISSUE TITLE
CocoaPods and Parse Issues

### ISSUE THREAD

**Issue by rvishal1991** [ParsePlatform/Parse-SDK-iOS-OSX#918]
Ruby - 
 gems/ruby-2.3.1/gems/cocoapods-1.0.0.rc.2/lib/cocoapods.rb

Parse - 
Using Parse (1.13.0)

![screen shot 2016-05-09 at 11 10 57 pm](https://cloud.githubusercontent.com/assets/16077139/15122159/5ea856e6-163b-11e6-824d-ab48481b7b41.png)

**Comment by nlutsenko** [comment]
Hey @rvishal1991, looks like you either have a stale Parse.framework somewhere in the search paths that Xcode can find, or maybe a caching issue?
Try clearing Xcode DerivedData as well as make sure you don't have stale version of framework somewhere in the search paths.

If that doesn't help, could you post your Podfile and log of `pod update` here?
I am confident we will get to the bottom of this together.

**Comment by batkov** [comment]
I had same issue after updating through new Cocoapods Mac App.
Deleting derived data solved the problem. I believe this issue can be closed
