### ISSUE TITLE
'Parse/Parse.h' file not found when using cocoapods1.0.0

### ISSUE THREAD

**Issue by skyhacker2** [ParsePlatform/Parse-SDK-iOS-OSX#923]
It's ok when I using cocoapods 0.x, but yesterday I update to 1.0.0, 'Parse/Parse.h' file not found.

My Podfile is:
platform :ios, '8.0'
use_frameworks!
target 'MyApp' do
   pod 'Parse'
end

![2016-05-23 3 42 23](https://cloud.githubusercontent.com/assets/1547841/15463554/c8855fb6-20fc-11e6-960e-53f94cf531b8.png)

**Comment by skyhacker2** [comment]
Build success when select simulator, but wrong when select devcie.

**Comment by 5amfung** [comment]
I have the same error even with simulator.

**Comment by DeepLight** [comment]
I have the same issue - if I comment out use_frameworks! it works again - however this is not an option for me as I need to include for IBdesignables. Only happened after updating cocoapods to 1.0.0

**Comment by DeepLight** [comment]
@skyhacker2 Did you manage to resolve this? I was unable to build for device and simulator - until I remove _use_frameworks_ from my podfile and update.

**Comment by DeepLight** [comment]
I've rolled back to cocoapods 0.39.0, hit update pods - and all good again... hmmm

**Comment by 5amfung** [comment]
There's bug fix in cocoapod 1.0 that I need.  Too bad I can't really rollback to 0.39.0.  I hope there's quick fix.  Removing use_frameworks doesn't work for me neither as most of my pods are swift.

**Comment by skyhacker2** [comment]
@DeepLight No, Now I just temporarily removed use_frameworks! .

**Comment by nlutsenko** [comment]
Hey everyone, this seems to work now as of `1.14.1`.
Please reopen/comment here or open a new issue if you guys still experience this issue.
