### ISSUE TITLE
Update starter projects to use the new initialization API that exposes changing the server URL.

### ISSUE THREAD

**Issue by ihomecall** [ParsePlatform/Parse-SDK-iOS-OSX#929]

**Comment by bre7** [comment]
Check  the docs.

>If you haven't installed the SDK yet, please head over to the QuickStart guide to get our SDK up and running in Xcode.
https://www.parse.com/apps/quickstart#parse_data/mobile/ios/native/new

```swift
let configuration = ParseClientConfiguration {
    $0.applicationId = "AAAAAA"
    $0.clientKey     = "BBBBBB"
    $0.server        = "https://some.url/parse"
}
Parse.initializeWithConfiguration(configuration)
```

**Comment by nlutsenko** [comment]
That should do the trick! Thanks for bringing this up!
We also would love to update the starter projects to use the new API for setting the server up.
I am going to track this using this issue, so we can act on it.
