### ISSUE TITLE
Issues with the iOS Simulator and Parse CoreLocation Wrapper

### ISSUE THREAD

**Issue by istx25** [ParsePlatform/Parse-SDK-iOS-OSX#93]
We (@damonjones and I) are building an iOS application that extensively uses Parse and your CoreLocation wrapper. Our user's location is vital to the application's UX, as we exchange information for where they are in relation to restaurants and bars in their city/area.

We use this `PFGeoPoint` method to fetch our user's location data:

```swift
/*!
@abstract Fetches the current device location and executes a block with a new `PFGeoPoint` object.
    
@param geoPointHandler A block which takes the newly created `PFGeoPoint` as an argument.
It should have the following argument signature: `^(PFGeoPoint *geoPoint, NSError *error)`
*/
class func geoPointForCurrentLocationInBackground(geoPointHandler: PFGeoPointResultBlock?)
```

The API works perfectly on real iOS hardware, but is rather unreliable in the iOS Simulator. We always receive the requested data on real iOS hardware, but only three times out of five in the simulator. We are not entirely sure if this *problem* is related to Parse or CoreLocation. We're looking to find out who the culprit is - to either contribute in having it fixed or file a radar with Apple.

What do you think?

**Comment by nlutsenko** [comment]
Just looked at the code, and tested in the Simulator.
What I think is happening is that iOS Simulator doesn't actually have real location, but rather simulates it and the results are flaky.
I would suggest trying getting the location with our wrapper and comparing the results, it would really help in identifying the problem here and fixing it fast.

**Comment by istx25** [comment]
Oh okay, @nlutsenko! It makes sense that the location is simulated, but I thought that Apple's simulation would be better! I'll write an API comparison application utilising both stock CoreLocation APIs and Parse's wrapper. I'll try to put this together in a few days as we're just finishing up a release at work! :+1:


I'll write a comparison application using both APIs in a few days. Just finishing up a release at work.

**Comment by istx25** [comment]
Oh okay, @nlutsenko! It makes sense that the location is simulated, but I thought that Apple's simulation would be better! I'll write an API comparison application utilising both stock CoreLocation APIs and Parse's wrapper. I'll try to put this together in a few days as we're just finishing up a release at work! :+1:

**Comment by gonzalonunez** [comment]
CoreLocation is known to be a little shaky on the simulator. Most of the times, setting the simulated location to None and then back to whatever you had it at gets it working again. I highly highly doubt this is a Parse issue, especially if you're only experiencing problems on the simulator.

**Comment by nlutsenko** [comment]
Oh, iOS Simulator, you know we love you, but you are sometimes a pain to deal with.
@istx25, I am going to close out this issue for now, feel free to reopen if you see anything weird happening.
