### ISSUE TITLE
Framework not found Parse for architecture x86_64

### ISSUE THREAD

**Issue by ChrisBeeson** [ParsePlatform/Parse-SDK-iOS-OSX#934]
I'm having a problem with parse 1.13.0 linking to an OS X application.

` framework not found Parse for architecture x86_64`

This is my podfile

```
use_frameworks!

def shared_pods
    pod 'DateTools', '~> 1.7'
    pod 'ObjectMapper', '~> 1.2'
    pod 'SwiftyStoreKit'
    pod 'Parse'
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'ActionsKit-OSX' do
    platform :osx, '10.11'
    shared_pods
end

target 'ActionsKit-iOS' do
    platform :ios, '8.0'
     shared_pods
end
```

Any help would be much greatly received.

**Comment by nlutsenko** [comment]
Hey @ChrisBeeson, thanks for the report.
This should work just as fine as of `1.14.1`.
Please reopen/comment or open a new issue if you still experience problems.

I would also suggest removing `Pods` folder completely and running `pod update` to make sure everything is properly downloaded and installed.
