### ISSUE TITLE
Push not sent using parse client code IOS

### ISSUE THREAD

**Issue by sourcebit** [ParsePlatform/Parse-SDK-iOS-OSX#94]
Hi,
Im not receiving the push on my device using the push client code below on other IOS device.
PFPush *push = [[PFPush alloc] init];

            NSString *to = [[[AppDelegate appDelegate].sendTo componentsSeparatedByString:@"@"] firstObject];

            [push setChannel:[NSString stringWithFormat:@"z%@",to]];

            [push setMessage:@"dscxvx"];

            [push sendPushInBackgroundWithBlock:^(BOOL succeeded, NSError * __nullable error) {

                if (succeeded) {

                    NSLog(@"succeeded");

                }

                NSLog(@"error==%@",error.localizedDescription);

            }];

Below are some observations that i feel are correct so that i should receive a push but unfortunately it doesnt.

1) I have enabled the client key in parse website(settings push).

2) The channels are set in core for both the IOS device along with the device tokens

3) I have cross checked the channel name set in my IOS code with the one set in parse website core section.

4) When check the push section in parse web site it shows the push as sent to 0 devices.

5) Also The push works when i send it from parse website to all devices and by rest api too using postman extension for chrome.

6) In the above code "succeeded" is printed in console and error is Null.That shows push is sent but was never delivered to any device.

Only sending the push through client code doesn't work for me.

My Email id registered with parse is evince5@yahoo.com.In case you need to check the above information i cited.

Please help.

Thanks,

AD

**Comment by richardjrossiii** [comment]
Thanks for the report! We'll definitely look into it. Have you verified that your channels are correct? It would appear your `stringWithFormat:` has a 'z' preceding it, I assume that is intentional?

Also if you could create a small reproducing project here on github, it would greatly help us track down this bug.

**Comment by sourcebit** [comment]
Hi Richard,

I have figured out the problem as the channel name used had alp lower case
letters and I was sending the push to a channel with capital letters.

Thanks for help.
