### ISSUE TITLE
NSError from query is returning Parse code 100

### ISSUE THREAD

**Issue by ChrisWi** [ParsePlatform/Parse-SDK-iOS-OSX#95]
Since last night my queries have not been returning successfully.  I have been using a breakpoint and getting:

    domain: @"Parse" code - 100

So I can't connect to the Parse server via my app.  The server side the system is up tho.

Thanks.

**Comment by richardjrossiii** [comment]
It would appear that this is a server-side issue. If this is reproducible using the REST API, please direct the bug report to https://parse.com/help.

If not, can I get a small repro use-case?

**Comment by ChrisWi** [comment]
Thanks for the help. It was a iphone device issue. I ran it fine in my
simulator and it worked in wifi on the device.  Somehow the cell network
had issues. I restarted the app and phone and all is well. Thanks!

**Comment by nlutsenko** [comment]
Glad the reboot helped.
