### ISSUE TITLE
saveInBackground method causes error: The data couldn’t be read because it isn’t in the correct format.

### ISSUE THREAD

**Issue by andrew8712** [ParsePlatform/Parse-SDK-iOS-OSX#952]
### Issue Description

I have a class called `Image`, which has `image` property of `PFFile` type. When I'm trying to create a new object by calling `saveInBackground` method, the server returns this error:

```
Error Domain=NSCocoaErrorDomain Code=3840 
"JSON text did not start with array or object and option to allow fragments not set." 
UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
```

`error.localizedDescription`:

```
The data couldn’t be read because it isn’t in the correct format.
```

Save operations on other classes work fine. The server log doesn't even show that there is POST request to `Image` class.

Any ideas what's wrong?

### Environment Setup

Parse SDK version: 1.13.0
Bolts: 1.7.0

- **Server**
  - parse-server version: 2.2.14.
  - parse-dashboard version: 1.0.14
  - Operating System:     Ubuntu 10.14

**Comment by andrew8712** [comment]
Also this cloud code doesn't work as well:

    var query = new Parse.Query("UserProfile");
    query.equalTo("objectId", userProfileId);
    query.first().then(function(userProfile) {
        ///...
    },
    function(error) {
      response.error("code=" + error.code + ": " + error.message);
    });

Returns this error:

    code=107: Received an error with invalid JSON from Parse: Cannot POST /parse/classes/UserProfile

**Comment by andrew8712** [comment]
Seems like the issue was related to wrong `serverURL` variable at server configuration file.

**Comment by omarojo** [comment]
How come you were successfully saving other Classes, but that one was failing. And it turned out to be the serverURL ? 
I have the same issue, but my URLs are fine.
