### ISSUE TITLE
PFUser Subclass currentUser() not returning subclass

### ISSUE THREAD

**Issue by Vortec4800** [ParsePlatform/Parse-SDK-iOS-OSX#963]
Say we have a custom user subclass:

```swift
class TUser: PFUser {
	override class func initialize() {
		struct Static {
			static var onceToken : dispatch_once_t = 0;
		}
		dispatch_once(&Static.onceToken) {
			self.registerSubclass()
		}
	}
	
	// MARK: Parse Properties
	@NSManaged var mySpecialObject: PFObject?
}
```

The expectation is that TUser.currentUser() will return the currently authenticated user as a TUser object. Unfortunately, we often get a PFUser object back instead, and the method ignores our subclass altogether.

When trying to access a property like `TUser.currentUser()?.mySpecialObject` this causes a bad access crash, because PFObject does not have a mySpecialObject property.

I tried to do a little digging and got all the way to the `PFObjectFilePersistenceController` and the `PFObjectFileCoder` where it appears to write the current user info to Core Data, and it stores the Parse class name (_User in our case) but doesn't seem to do anything for subclassing. Following the call tree up, I don't see anywhere that a subclass would get instantiated instead and returned.

How is this supposed to work? Is the issue stemming from creating these subclasses using Swift? Is the Parse SDK expecting something dynamic that Swift isn't providing?

**Comment by Vortec4800** [comment]
Some more info. It seems like the Parse initialize method pre-loads "current" objects from disk. This seems to happen before the custom `TUser` subclass is registered. The current user controller then caches the current user, which is a `PFUser` object, and that's what gets vended from there on out.

Running the `TUser.registerSubclass()` before calling Parse.init should solve this problem. Going to keep looking to see if there is another solution that doesn't require moving the register subclass method.

**Comment by Vortec4800** [comment]
Created a PR which will fix the issue without any code changes. This should result in safer code (doesn't matter if some developers are unaware of this bug or that they may need to move their subclass reg methods, if they update their code will just work as expected.

**Comment by nlutsenko** [comment]
@Vortec4800, good job on identifying the root cause of this.
Since currently it's required to register subclasses before Parse is initialized - I am not sure if the temporary workaround is required at all and I would rather pursue #5 (as you said) instead of adding a temporary patch around something that will go away.

Let me know your thoughts on this, so we can discuss and make the best decision together.

**Comment by Vortec4800** [comment]
I had a few thoughts about that.

When trying to figure out what was happening (started as just a bad access crash on the currentUser line, which didn't give me a lot to work with at first) I found a few other people with similar issues. I did find someone who said to register the subclass before running the Parse init, but I wanted to better understand what was happening.

I've been working on this project for a while and never even noticed this issue happening until recently, because of the weird race condition I described it only happens in certain circumstances. This leads me to believe that there are more than likely other devs running into this issue and not even realizing it. Putting together a fix like this would just automatically fix all those projects once they update.

I do think #5 is a much more elegant solution and would much prefer it to my change. I wasn't sure why that had been sitting for so long, and why it hasn't been merged yet. I figured a patch like this is so small and won't affect projects that don't need it, and when #5 is actually ready to go this would probably get refactored away anyway, given it references the singleton user controller.

**Comment by nlutsenko** [comment]
This sounds great!
Let me ping @richardjrossiii today to see if we can update and ship #5 with the next upcoming release.
If not - I am all in for the change. If yes - it'll just get better for everyone at once. 😁 
Thank you for clarification, it's awesome to have you!

**Comment by Vortec4800** [comment]
👍 👍 👍
