### ISSUE TITLE
Link Twitter after migrating to Parse server

### ISSUE THREAD

**Issue by anoopnimkar** [ParsePlatform/Parse-SDK-iOS-OSX#969]
Hello,
We are trying to test twitter link and facebook link after migrating to Parse server and hitting issues with Twitter link. We see following error on console log,
**Twitter auth is invalid for this user. (Code: 101, Version: 1.13.0)**

We have all config set on index.js with Twitter secret and client key and using latest SDKs

Facebook link works fine.

Any suggestions on how to debug the issue?

**Comment by nlutsenko** [comment]
Probably more relevant place for reporting this, so let's move overall discussion on this to ParsePlatform/ParseTwitterUtils-iOS#35
