### ISSUE TITLE
Remove `mutable container` functionality.

### ISSUE THREAD

**Issue by nlutsenko** [ParsePlatform/Parse-SDK-iOS-OSX#97]
Mutable containers right now power the ability to mutate NSArray, NSDictionary, PFGeoPoint after setting them on PFObject.
Here is an example:
```objc
NSMutableArray *array = [NSMutableArray array];

PFObject *object = [PFObject objectWithClassName:@"Example"];
object[@"array"] = array;
[object save];
// This will save an object with empty `array` field.

[array addObject:@"test1"];
[object save];
// This will save an object with `array: [ test1 ]` field
```

This issue is for tracking proposal to remove this functionality from our SDKs. Here are just a few reasons:
- Inconsistency with Cocoa(iOS/OSX) conventions, where you always pass an object by copy, specifically where related to closest thing to Parse - Core Data.
- Inconsistency when fetching an object, where it will remove the mutable containers tracking, as the data will be overwritten by new data from the server.
- Slower Local Datastore performance - a lot of time spent on pinning objects to LDS is spent in checkpointing all mutable containers.

cc @grantland, @hallucinogen, @richardjrossiii

**Comment by richardjrossiii** [comment]
+1

**Comment by nlutsenko** [comment]
This is potentially breaking, if someone relies on the flow discussed above.
Please raise questions/issues here, so we are more aware of the public impact.

**Comment by gonzalonunez** [comment]
+1

**Comment by gavinbunney** [comment]
:+1: would be great to removed (as per #102) - would be more consistent with how you imagine it would work since they are `NSArray` objects, not `NSMutableArray`.

Typically we've handed this through helper methods on the parent objects such as (add a new `Note` object):

```
- (Note *)addNote:(Note*)note {
    [self willChangeValueForKey:@"notes"];

    NSMutableArray *mutableArray = self.notes.mutableCopy;
    if (!mutableArray) {
        mutableArray = [NSMutableArray array];
    }

    [mutableArray addObject:note];
    self.notes = mutableArray;
    [self didChangeValueForKey:@"notes"];

    return note;
}
```

**Comment by FreudGit** [comment]
+1

**Comment by alex-vasenin** [comment]
Guys, I agree you've had a good reasons to remove mutability. But the bad thing the following code which worked well in 1.9.1 *silently* fails under 1.10.1 without any compile or runtime errors/warnings: `[myPfObjectSubclass[@"someArrayKey"] addObject:someObject]`.

**Comment by UberJason** [comment]
I agree with alex-vasenin. I had that exact thing happen to me - my saves stopped working and I didn't know why, and the save calls were coming back with BOOL success = YES and nil errors. Only after coming to check the Parse 1.10 release notes did I realize that this mutable container change was made which was affecting my app. There should definitely be some compile-time or runtime warning, at the least.
