### ISSUE TITLE
Facebook Authentication with Parse Server and iOS

### ISSUE THREAD

**Issue by istx25** [ParsePlatform/Parse-SDK-iOS-OSX#971]
**Long and short of it: When I call `logInInBackgroundWithReadPermissions(permissions: block:)` in my view controller, the `PFUser` and `NSError` objects are both returned as `nil` .**

I am an iOS developer so I'm new to the server-side of things. Anyways, I am trying to setup Facebook login with an iOS app and Parse Server. Some extra details:
- Parse (1.13.0)
- ParseFacebookUtilsV4 (1.11.1)
- Parse Server (_How do I check the version?_)
  - Running on Digital Ocean with Docker and Mongo.

However, I ran into an issue that I can't seem to resolve. When I call `logInInBackgroundWithReadPermissions(permissions: block:)` in my view controller, the `PFUser` and `NSError` objects are both returned as `nil`.

Here's some code:
- `AppDelegate.swift`
- Omitted all code that was not related to Parse

``` swift
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

    let configuration = ParseClientConfiguration {
        $0.applicationId = APIKeys.getParseApplicationId()
        $0.clientKey = APIKeys.getParseClientKey()
        $0.server = APIKeys.getParseServerURL()
    }

    Parse.initializeWithConfiguration(configuration)
    FBSDKSettings.setAppID(APIKeys.getFacebookApplicationId())
    PFFacebookUtils.initializeFacebookWithApplicationLaunchOptions(launchOptions)
    PFUser.enableRevocableSessionInBackground()

    return true
}

func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
    return FBSDKApplicationDelegate.sharedInstance().application(application, openURL: url, sourceApplication: sourceApplication, annotation: annotation)
}
```
- `Facebook.swift`
- Function is inside of a struct named "Facebook"

``` swift
static func loginInBackground(with permissions: [String], handler: PFUserResultBlock) {
    PFFacebookUtils.logInInBackgroundWithReadPermissions(permissions, block: handler)
}
```
- `LoginViewController.swift`
- Called inside of `func loginButtonPressed(sender: UIButton)`

``` swift
Facebook.loginInBackground(with: LoginViewController.ReadPermissions) { user, error in
    guard let user = user as? User else {
        print(error)
        return
    }

    user.attachFacebookProfile()
    let authenticatedViewController = AuthenticatedViewController()
    self.navigationController?.pushViewController(authenticatedViewController, animated: true)
}
```

Resources used so forth:
- Issue https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/556
- https://medium.com/@dmathewwws/guide-to-building-your-own-parse-server-aad6568b743d
- http://stackoverflow.com/questions/35096737/error-using-facebook-login-with-parse-server

Any leads would be greatly appreciated.

Edit: The Xcode Project is also open-source on [this repository](https://github.com/istx25/Facebook-Login-Parse/tree/add/facebook-integration) in branch `add/facebook-integration`. My API keys aren't included there. Email me at [willow.alex@bellemore.ca](mailto:willow.alex@bellemore.ca) if you would like to test with my API keys or help in a more direct/private manner.

**Comment by istx25** [comment]
Any ideas, @nlutsenko?

**Comment by istx25** [comment]
You came across this problem as well, @demosten (https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/556#issuecomment-214388248). How do you recommend I proceed? Did you ever find a solution yourself?

**Comment by dnadri** [comment]
@istx25 I experienced a similar issue as explained in my [Stackoverflow answer](http://stackoverflow.com/questions/35096737/error-using-facebook-login-with-parse-server).

You seem to have already done so but this resolved the issue for me:
In AppDelegate.swift, the 'ParseClientConfiguration' must be initialized **BEFORE** the Parse Facebook Utils initialization in 'didFinishLaunchingWithOptions'.

Also, make sure you have all the following in your App Delegate:
```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    let configuration = ParseClientConfiguration {
        $0.applicationId = APIKeys.getParseApplicationId()
        $0.clientKey = APIKeys.getParseClientKey()
        $0.server = APIKeys.getParseServerURL()
    }

    Parse.initializeWithConfiguration(configuration)
    FBSDKSettings.setAppID(APIKeys.getFacebookApplicationId())
    PFFacebookUtils.initializeFacebookWithApplicationLaunchOptions(launchOptions)
    PFUser.enableRevocableSessionInBackground()

    return FBSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)

}

//Make sure it isn't already declared in the app delegate (possible redefinition of func error)
func applicationDidBecomeActive(application: UIApplication) {
  FBSDKAppEvents.activateApp()
}

func application(application: UIApplication,
                 openURL url: NSURL,
                 sourceApplication: String?,
                 annotation: AnyObject?) -> Bool {
  return FBSDKApplicationDelegate.sharedInstance().application(application,
                                                             openURL: url,
                                                             sourceApplication: sourceApplication,
                                                             annotation: annotation)
}
```
Hope this helps!

**Comment by ZacharyKhan** [comment]
@istx25 did the solution provided by @dnadri solve your issue?

**Comment by istx25** [comment]
Don't remember. That's almost a year ago.
