### ISSUE TITLE
PFUser subclass fails on 1.14.0

### ISSUE THREAD

**Issue by batkov** [ParsePlatform/Parse-SDK-iOS-OSX#975]
Hi,

After update to 1.14.0 I'm experiencing constant crash when trying to work with subclass of PFUser.

Actually there is no subclass:
[MyUser currentUser] returns PFUser instance

After I rolled back to 1.13.0 everything works as is.

**Comment by batkov** [comment]
I do following after didFinishLaunching  
```
[MyUser registerSubclass];
[Parse initializeWithConfiguration:]
```

**Comment by nlutsenko** [comment]
@batkov, does your `MyUser` class conform to `PFSubclassing`?
There is a requirement on this, where the classes are not registered automatically, unless they expose the fact that they conform to `PFSubclassing`, which is a required step for making subclasses of `PFObject`/`PFUser`/`PFInstallation`.

**Comment by iStopped** [comment]
Confirmed broken, I've subclassed PFUser as User and I get this error:
`-[PFUser isComplete]: unrecognized selector sent to instance 0x7faf08c8a4e0`
isComplete is a custom field in my subclass.

**Comment by iStopped** [comment]
@nlutsenko If MyUser subclass PFUser, you can't redefine the PFSubclassing implementation.

**Comment by nlutsenko** [comment]
@iStopped, you can't redefine the implementation, but you can declare the fact that you conform to `PFSubclassing`, which is a requirement for `PFObject`/`PFUser`/`PFInstallation` subclasses.
I've just tested the following MyUser implementation and it works like a charm:
```objc
MyUser.h

#import <Parse/Parse.h>

@interface MyUser : PFUser <PFSubclassing>

@property (nonatomic, assign) BOOL isComplete;

@end
```

```objc
MyUser.m

#import "MyUser.h"

@implementation MyUser

@dynamic isComplete;

@end
```

```objc
AppDelegate.m

NSLog(@"%@", [MyUser currentUser]);
NSLog(@"%@", [[MyUser currentUser] class]);
NSLog(@"%d", [[MyUser currentUser] isComplete]);
```

**Comment by nlutsenko** [comment]
The whole thing here is that you shouldn't be required to, you are right.
I am going to send a patch in few minutes that fixes this altogether without a need for workaround.

**Comment by iStopped** [comment]
@nlutsenko I'm talking about swift, you can't do that in swift. Sorry for the misunderstanding

**Comment by nlutsenko** [comment]
`1.14.1` is live now (you might want to run `pod repo update` if you are using CocoaPods for dependency management).
Would be great if you guys could validate that all of this works now.

**Comment by iStopped** [comment]
It is working, thanks. 👍

**Comment by acegreen** [comment]
@nlutsenko Crashalytics says 800+ crashes on my beta build yet I never experienced any. Are these hard crashes? Also I never subclass anything, does PFUser use this class?

<img width="1573" alt="screen shot 2016-07-18 at 9 17 12 am" src="https://cloud.githubusercontent.com/assets/10794609/16915966/7c623616-4cc8-11e6-8d78-0c66440e540e.png">

**Comment by acegreen** [comment]
@nlutsenko Even after updating to 1.14.1 the issue resurfaces

**Comment by acegreen** [comment]
It seems to happen multiple times in an instance because only Apple bots have this beta under review and the crash report. Crashes now at 943

**Comment by acegreen** [comment]
Well over a 1k now and this is just from Apple bots and myself. Whats going on here

![Uploading Screen Shot 2016-07-18 at 12.29.19 PM.png…]()

**Comment by acegreen** [comment]
Just one last note: the version on my device with the same 1.14.1 doesn't experience any crash reports. Only the bots seem to cause issues
