### ISSUE TITLE
Code signing doesn't work on Mac OS with latest XCode version

### ISSUE THREAD

**Issue by markmcminn** [ParsePlatform/Parse-SDK-iOS-OSX#98]
I'm using XCode 6.4 with the latest Parse MacOS SDK. I get a code signing error whether I'm using my own project or the blank new project you provide. I'm attaching the screenshots of both. The error has something to do with the Code Signing Resources Rules option being deprecated in OS 10.10.
![screen shot 2015-08-24 at 1 04 12 pm](https://cloud.githubusercontent.com/assets/13951027/9450994/e081c942-4a60-11e5-9c95-d883c5009e87.png)
![screen shot 2015-08-24 at 1 04 35 pm](https://cloud.githubusercontent.com/assets/13951027/9450996/e3b087ca-4a60-11e5-9065-37a80091deea.png)

**Comment by nlutsenko** [comment]
Hey @markmcminn, thanks for report.
Do you have `code sign when copying` enabled for Parse.framework by any chance?

**Comment by markmcminn** [comment]
How would I check that?

**Comment by nlutsenko** [comment]
It should be in `Copy Files` or `Copy Frameworks` phase of your target.
Something like this
![screen shot 2015-08-24 at 1 15 30 pm](https://cloud.githubusercontent.com/assets/606991/9451235/5042afd4-4a62-11e5-8d89-b238c0f35caf.png)

**Comment by markmcminn** [comment]
Yes, I do have it on, both on my project and the parse starter project. Same problem with both. Here’s my settings…

Mark

**Comment by nlutsenko** [comment]
This error generally suggests that you don't have a valid signing identity (certificate and private key pair) in your keychain.
![screen shot 2015-08-24 at 1 18 20 pm](https://cloud.githubusercontent.com/assets/606991/9451289/9e5523be-4a62-11e5-85f7-dc9735bf1fbe.png)

**Comment by markmcminn** [comment]
The starter project works fine until I code sign it. Then I get the error I posted.

**Comment by markmcminn** [comment]
Ah, that could be. I just changed computers.

**Comment by markmcminn** [comment]
Thanks.

**Comment by nlutsenko** [comment]
Glad I helped. In general use case `Fix Issue` on that screen should resolve the problem.

**Comment by markmcminn** [comment]
Yeah, I tried that, but it didn’t help. Maybe I’ll just have to delete and reinstall certificates…

**Comment by markmcminn** [comment]
Nikita,

I don’t think this issue was related to having a new computer. I can run my apps that don’t have the Parse framework fine on the new Mac. All the code signing works just as it should. Also, I can run all my iOS apps with the Parse framework fine and the code signing works just as it should. It’s only Mac OS apps with Parse that won’t run. Shall I reopen the issue?

Mark McMinn

**Comment by nlutsenko** [comment]
Yup, I just reproduced it in the meantime.
Working on the fix, it should be out very soon.

**Comment by markmcminn** [comment]
Thanks.

**Comment by nlutsenko** [comment]
Found the issue, fix with PR is coming.

**Comment by nlutsenko** [comment]
Workaround - force code sign the binary first in a build script as a separate build phase.
Or precompile the framework for yourself when PR is merged.
Both of these are unrequired with the next version, but only in case you want it faster.. :grin:

**Comment by markmcminn** [comment]
Thanks. I don’t think I know how to do either of those so I’ll just wait. Any idea when the fixed version will be released?

**Comment by nlutsenko** [comment]
We don't have the specific time for 1.8.2 release yet, but having this bug definitely raises the priority of releasing it sooner.

**Comment by markmcminn** [comment]
Ok, I may try to figure out the workaround. What does PR stand for in your earlier email?

Mark

**Comment by nlutsenko** [comment]
`PR` stands for Pull Request. [This one.](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/103)
