### ISSUE TITLE
Getting weird crashes PFObjectSubclassingController.m

### ISSUE THREAD

**Issue by patpawasantanon** [ParsePlatform/Parse-SDK-iOS-OSX#980]
1644 crashes with only 5 users

PFObjectSubclassingController.m line 355

http://crashes.to/s/d1678763779

anyone know how to solve this?

**Comment by pawelkata** [comment]
Same here. My app was sent to a beta review a few hours ago:

http://crashes.to/s/dc1ff26327c

I'm rocking iOS SDK v1.14.1.

**Comment by fluidsonic** [comment]
Same here. Crash when starting the app in the debugger.

**PFObjectSubclassingController.m:**
```objc
char potentialPaths[2][PATH_MAX] = { };

strncpy(potentialPaths[0], bundle.executablePath.UTF8String, PATH_MAX); // crash
realpath(potentialPaths[0], potentialPaths[1]);
```

`bundle.executablePath` is `nil` and thus causing the crash.

The offending bundle is `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib`.

**Comment by fluidsonic** [comment]
Why not just use the `NSLoadedClasses` notification key for a list of all classes instead of examining the executable image? Seems unnecessarily complicated.

**Comment by natanrolnik** [comment]
I submitted recently an the app to review with 1.14.1, and I got 361 crashes in one device 😨 (apparently they are running the app in some devices before it enters in review):
http://crashes.to/s/e334c371112

**Comment by fluidsonic** [comment]
We've fixed the issue for us in https://github.com/Widgetlabs/Parse-SDK-iOS-OSX/commit/aaa0632235b0896f5738a234e89a4a377d7eb68c.

You can use it in your `Podfile` like so:

```ruby
# https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/980
pod 'Parse', :git => 'https://github.com/Widgetlabs/Parse-SDK-iOS-OSX.git', :branch => 'patch-1'
```

But I'd recommend to either fork our fix or use Parse SDK `1.13.0` which is not affected by this bug.

**Comment by patpawasantanon** [comment]
Thank you! @fluidsonic

**Comment by ProximalPod** [comment]
@fluidsonic This worked for me. My code was crashing anytime I initialized an object in the AVFoundation framework, e.g. `[[AVSpeechSynthesizer alloc] init]`. I traced it back to this code but was wary of changing it. Thanks!

**Comment by nlutsenko** [comment]
This is getting merged in a few moments and release is coming soon.
Thank you everyone for the input and thank you @fluidsonic for a fast fix!

**Comment by acegreen** [comment]
@nlutsenko thats what I was talking about in https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/975
