### ISSUE TITLE
Use of unresolved identifier 'BFURL' 

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/Parse-SDK-iOS-OSX#983]
Using the Pod file for Parse it seems like bolts is having an issue.. 

Error Below..
![image](https://cloud.githubusercontent.com/assets/519563/16969524/4aeff9bc-4dca-11e6-9159-821e7eb354ff.png)

![image](https://cloud.githubusercontent.com/assets/519563/16969567/8440ee1a-4dca-11e6-8697-bd1cff51b147.png)

any ideas?

**Comment by gateway** [comment]
Any ideas, this is blocking us from debugging some code.

**Comment by gateway** [comment]
Seems like something is messed up with the parse pod file, I added in pod file for bolts and its now working.

**Comment by nlutsenko** [comment]
Parse only depends `Tasks` portion of `Bolts`.
So, in order to get `BFURL` and other parts of `Bolts` - you would need to explicitly add it to your Podfile.
