### ISSUE TITLE
findObjectsInBackgroundWithBlock returning empty array

### ISSUE THREAD

**Issue by naresh-wal** [ParsePlatform/Parse-SDK-iOS-OSX#985]
We had same issue year ago(12th July 2015), we filed this issue in Facebook. at that time it was resolved. But now the same issue is surfacing again. Unfortunately that Facebook bug info is not available at this time, but we have all conversion in the from of pdf. I can not reveal all those info here.
Any help?

**Comment by shiva-wal** [comment]
Please find more info at https://developers.facebook.com/bugs/1239018396132432

**Comment by nlutsenko** [comment]
Looks like your issue is related to Parse.com and not a client SDK.
Closing this issue, as the conversation is more relevant on the linked FB bug.

**Comment by naresh-wal** [comment]
We have already posted in Facebook they said its not Facebook issue and asked us to post in SDK repositories in Github.

Here is the problem:

Please see the attached screenshot of the parse table. It shows that there exists user with the email "naresh@westagilelabs.com". However, the following query is not returning any result although there exists a row for that user in parse. So it seems to be a bug on parse. Can you please look into this? It's affecting all of our app users, I would really appreciate if you can look into this. Thanks in advance. 

PFQuery *query = [PFQuery queryWithClassName:@"LoginTable"];
    [query whereKey:@"Email" equalTo:@"naresh@westagilelabs.com"];
    [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
        if (!error) {
        } else {
        }
    }];

![screen shot 2016-07-22 at 5 45 43 pm](https://cloud.githubusercontent.com/assets/11420125/17058656/275dec12-503f-11e6-9ae7-30feb7f28de0.png)

**Comment by acegreen** [comment]
try query.whereKey("Email", containsString: "naresh@westagilelabs.com")
Also check that your db entry doesn't include a space at the end.

**Comment by naresh-wal** [comment]
Thanks @acegreen its working.

**Comment by acegreen** [comment]
Just for educational proposals, what ended up working?
