### ISSUE TITLE
fetchAllIfNeededInBackground error "Object not found on the server."

### ISSUE THREAD

**Issue by acegreen** [ParsePlatform/Parse-SDK-iOS-OSX#986]
I'm running into an issue where I present a view and try to execute fetchAllIfNeededInBackground on a few objects. The first time the function is called, I get the mentioned error. Subsequent calls yields results. 

Important note to make. This pointers in the "recentSearches" array can be from two classes.

```
    func getUserRecentSearches() {
        
        guard let currentUser = PFUser.currentUser() else { return }

        if let currentUserRecentSearches = currentUser["recentSearches"] as? [PFObject] {
            
            PFObject.fetchAllIfNeededInBackground(currentUserRecentSearches) { (currentUserRecentSearches, error) in
                
                if let currentUserRecentSearches = currentUserRecentSearches as? [PFObject] {
                    self.recentSearches = currentUserRecentSearches
                    self.tableView.reloadData()
                }
            }
        }
    }
```

**Comment by acegreen** [comment]
note: it doesn't trigger the assertion below so objectId != nil 
```
            PFParameterAssert(object.objectId != nil,
                              @"All objects must exist on the server.");
```

**Comment by acegreen** [comment]
Another note: 
fetchAllInBackground() also causes the same error **AND** it doesn't show results the second time around.

**Comment by acegreen** [comment]
@nlutsenko I would appreciate your input on this. This maybe tied to #984 where I removed the insertion to be able to fetch from multiple classes at the same time.

**Comment by acegreen** [comment]
It seems as though when there are a mixture of classes, some code runs ahead instead of waiting for an async and returns that error.

**Comment by acegreen** [comment]
My two guess:
1. Either by the second call, the first call is complete and it just brings up the cached results from the first call
2. Since there are two classes in my case, the first call queried the objects for the first class and the second call for the second class and with that all the objects were found

**Comment by shiva-wal** [comment]
seems like this is similar to my [issue](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/985)

**Comment by acegreen** [comment]
@shiva-wal don't do that, dont try to hijack this thread
1. Your issue is poorly written with no code samples or explanation to what you are trying to do
2. findObjectsInBackgroundWithBlock() is different than fetchAllIfNeededInBackground() 
3. I'm not returning an empty array but an error and I explained in detail why that seems to happen. So unless you are fetching from two classes, it isn't similar. 

Please remove your comment.

**Comment by burf2000** [comment]
I think my issue is related to yours, hopefully we come up with a fix, spent all day trying to work out whats wrong, mine seems to be with relationships and fetchIfNeededInBackgroundWithBlock

**Comment by acegreen** [comment]
@burf2000 yea its definitely related.

**Comment by nlutsenko** [comment]
Hey everyone,

What seems to be happening is that you are trying to fetch 6 objects, where only 5 have were found on the server. We explicitly fail with an error on that one and the entire task is treated as faulted (even though the 5 objects were successfully refreshed).

The first thing I would suggest checking is whether you can reproduce the same weird behavior with a simple `curl` request to isolate whether the issue is on the client or on the server (my gut says it's on the server). Also, enabling logging on the server could help observe whether a client makes the proper request.

Let me know what you find from the step above ^.

**Comment by acegreen** [comment]
@nlutsenko Thanks for the response. Regarding your points, 

1. All objects are on the server but 
2. There is at least one object that is of a different class than the rest, that may explain why the 
fetch seems to only find 5. 
3. The error only happens on first call, subsequent calls bring up the items just fine (all 6)

**Comment by acegreen** [comment]
@nlutsenko can this issue be related? https://github.com/ParsePlatform/parse-server/issues/1417

**Comment by acegreen** [comment]
@nancychowmein  just to point out, if I do the following on first call, the results appear from the get-go. Thats obviously because my call includes itself. So the first call is actually 2 calls in one. 

```
    func getUserRecentSearches() {
        
        guard let currentUser = PFUser.currentUser() else { return }

        if let currentUserRecentSearches = currentUser["recentSearches"] as? [PFObject] {
            
            PFObject.fetchAllIfNeededInBackground(currentUserRecentSearches) { (currentUserRecentSearches, error) in
                
                if let currentUserRecentSearches = currentUserRecentSearches as? [PFObject] {
                    self.recentSearches = currentUserRecentSearches
                    dispatch_async(dispatch_get_main_queue(), { () -> Void in
                        self.tableView.reloadData()
                    })
                }
                
                self.getUserRecentSearches()
            }
        }
    }
```

**Comment by flovilmart** [comment]
> There is at least one object that is of a different class (PFUser) than the rest, that may explain why the fetch seems to only find 5.

Yes and the code snipped you provided will run the query against the className of the first object, therefore marking the whole task as failed.
