### ISSUE TITLE
[PFPush handlePush:] should not play vibration when not sound is specified.

### ISSUE THREAD

**Issue by dev-mush** [ParsePlatform/Parse-SDK-iOS-OSX#99]
Currently, sending the userInfo to `[PFPush handlePush:] ` will cause the device to vibrate even if no "sound" parameter is specified in the notification payload, as listed in `PFPush.h #416-422` : 

```
    NSString *soundName = aps[@"sound"];

    if ((id)soundName == [NSNull null] || soundName.length == 0 || [soundName isEqualToString:@"default"]) {
        [[self pushInternalUtilClass] playVibrate];
    } else {
        [[self pushInternalUtilClass] playAudioWithName:soundName];
    }
```

Since is written in the documentation that handlePush: would mimic the behaviour of the notification as if handled by the OS when the app is in background, it would be preferable to not play anything at all if no "sound" parameter is specified.
The drawback would be that it's not possible to play the default notification sound when the parameter is `"sound" : "default"` since there is no way to determine the default system notification sound id (or at least not in a clean-ish way), but at least the developer is not forced to trigger a vibration also for a silent notification with a custom payload.
The code would be something like:

```
   NSString *soundName = aps[@"sound"];     
   if(soundName){
       [[self pushInternalUtilClass] playAudioWithName:soundName];
  }
```

alternatively, default could go to a vibration:

```
    NSString *soundName = aps[@"sound"];
  
       if(soundName){
            if ([soundName isEqualToString:@"default"]) {
                      [[self pushInternalUtilClass] playVibrate];
            } 
           else{
                    [[self pushInternalUtilClass] playAudioWithName:soundName];
           }
  }
```

For further reading:
* http://stackoverflow.com/questions/11776737/how-can-i-access-default-ios-sound-to-set-it-as-notification-sound
* http://stackoverflow.com/questions/9841600/ios-push-notifications-how-to-specify-alert-and-badge-with-no-sound

Hope this has been somehow useful.
Thank you for your great framework :+1:  , best regards

Marco

**Comment by nlutsenko** [comment]
That's a great suggestion.
The workaround for this would be to check if `aps[@"sound"]` has anything and not to call into `handlePush:`.

I think not vibrating if the sound isn't specified, thus playing vibration only if `default` is specified is the way to go.
@grantland @stanleyw What do you guys think?

**Comment by grantland** [comment]
I don't really have a strong preference here. In Android we use defaults for sounds/vibrate and vibrate requires a permission. In addition, developers can override `ParseBroadcastReceiver.getNotification()` to set their own sounds/vibrate.
