### ISSUE TITLE
Crash in Parse 1.14.1

### ISSUE THREAD

**Issue by DarkInsight85** [ParsePlatform/Parse-SDK-iOS-OSX#993]
Background: Push out an update of my app yesterday, the update passed through every QA test but users who installed the update are now reporting that they couldn't launch the app. I have checked my crash logs and found the following issue.

Line that cause the crash is in: PFObjectSubclassingController.m line 355
Specifically this line: strncpy(potentialPaths[0], bundle.executablePath.UTF8String, PATH_MAX);

Error is: 
Crashed: com.parse.object.subclassing
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

At the moment, I have no idea why there is an memory address error when trying to access the item.

Attached is the stack trace.

[stack trace.txt](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/files/380832/stack.trace.txt)

**Comment by zvonicek** [comment]
Hi there, I report the exact same issue. Definitely introduced in 14.14 as it never happened before 14.4.0. It occasionally occurs on my testing device and in iOS simulator, today it crashed while trying to log in shortly after opening the app. I'm using CocoaPods so Parse is in dynamically linked framework.

Please see my screenshot showing the crash in Xcode debugger.

![Crash while in debugging session](https://cloud.githubusercontent.com/assets/1540564/17096892/bd2a55c8-525b-11e6-8c31-90ff0b448e46.png)

**Comment by zvonicek** [comment]
It looks this issue was solved in #981 so please try to upgrade the SDK.

**Comment by nlutsenko** [comment]
1.14.2 should fix exactly this problem.
Please update and open new issues if you run into any problems.
